// frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
<template>
  <div class="flex-1 flex items-stretch overflow-hidden">
    <div class="flex-1 overflow-y-hidden overflow-x-auto" :class="contentClass">
      <slot v-if="!viewState || viewState.view === 'CODE'" name="code-panel" />

      <template v-if="viewState && viewState.view !== 'CODE'">
        <div class="h-full flex flex-col">
          <div
            class="py-2 px-2 w-full flex flex-row gap-x-2 justify-between items-center"
          >
            <div class="flex items-center justify-start gap-2">
              <DatabaseChooser :disabled="true" />
              <SchemaSelectToolbar simple />
            </div>
          </div>
          <div class="flex-1">
            <InfoPanel v-if="viewState.view === 'INFO'" :key="tab?.id" />
            <TablesPanel v-if="viewState.view === 'TABLES'" :key="tab?.id" />
            <ViewsPanel v-if="viewState.view === 'VIEWS'" :key="tab?.id" />
            <FunctionsPanel
              v-if="viewState.view === 'FUNCTIONS'"
              :key="tab?.id"
            />
            <ProceduresPanel
              v-if="viewState.view === 'PROCEDURES'"
              :key="tab?.id"
            />
            <SequencesPanel
              v-if="viewState.view === 'SEQUENCES'"
              :key="tab?.id"
            />
            <PackagesPanel
              v-if="viewState.view === 'PACKAGES'"
              :key="tab?.id"
            />
            <TriggersPanel
              v-if="viewState.view === 'TRIGGERS'"
              :key="tab?.id"
            />
            <ExternalTablesPanel
              v-if="viewState.view === 'EXTERNAL_TABLES'"
              :key="tab?.id"
            />
            <DiagramPanel v-if="viewState.view === 'DIAGRAM'" :key="tab?.id" />
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computedAsync } from "@vueuse/core";
import { first } from "lodash-es";
import { storeToRefs } from "pinia";
import { watch } from "vue";
import { useEmitteryEventListener } from "@/composables/useEmitteryEventListener";
import { useExecuteSQL } from "@/composables/useExecuteSQL";
import { useAIContext } from "@/plugins/ai/logic";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDatabaseV1Store,
  useDBSchemaV1Store,
  useSQLEditorTabStore,
} from "@/store";
import { isValidDatabaseName } from "@/types";
import type { DatabaseMetadata } from "@/types/proto-es/v1/database_service_pb";
import {
  extractDatabaseResourceName,
  getInstanceResource,
  nextAnimationFrame,
  type VueClass,
} from "@/utils";
import DatabaseChooser from "@/views/sql-editor/EditorCommon/DatabaseChooser.vue";
import { useCurrentTabViewStateContext } from "../context/viewState.tsx";
import { SchemaSelectToolbar } from "./common";
import DiagramPanel from "./DiagramPanel";
import ExternalTablesPanel from "./ExternalTablesPanel";
import FunctionsPanel from "./FunctionsPanel";
import InfoPanel from "./InfoPanel";
import PackagesPanel from "./PackagesPanel";
import ProceduresPanel from "./ProceduresPanel";
import SequencesPanel from "./SequencesPanel";
import TablesPanel from "./TablesPanel";
import TriggersPanel from "./TriggersPanel/TriggersPanel.vue";
import ViewsPanel from "./ViewsPanel";

defineProps<{
  contentClass?: VueClass;
}>();

const { currentTab: tab } = storeToRefs(useSQLEditorTabStore());
const { viewState, selectedSchemaName, updateViewState } =
  useCurrentTabViewStateContext();
const { database } = useConnectionOfCurrentSQLEditorTab();
const { execute } = useExecuteSQL();
const { events: AIEvents } = useAIContext();
const databaseMetadata = computedAsync(() => {
  if (!isValidDatabaseName(database.value.name)) {
    return undefined;
  }
  return useDBSchemaV1Store().getOrFetchDatabaseMetadata({
    database: database.value.name,
    silent: true,
  });
});

watch(
  [() => tab.value?.id, databaseMetadata, selectedSchemaName],
  ([id, database, schema]: [
    string | undefined,
    DatabaseMetadata | undefined,
    string | undefined,
  ]) => {
    if (!id) return;
    if (!database) return;
    if (
      !isValidDatabaseName(extractDatabaseResourceName(database.name).database)
    ) {
      return;
    }
    if (!schema || database.schemas.findIndex((s) => s.name === schema) < 0) {
      selectedSchemaName.value = first(database.schemas)?.name;
    }
  },
  { immediate: true, flush: "post" }
);

useEmitteryEventListener(AIEvents, "run-statement", async ({ statement }) => {
  if (!tab.value) {
    return;
  }
  updateViewState({
    view: "CODE",
  });
  await nextAnimationFrame();
  const connection = tab.value.connection;
  const database = await useDatabaseV1Store().getOrFetchDatabaseByName(
    connection.database
  );
  execute({
    connection,
    statement,
    engine: getInstanceResource(database).engine,
    explain: false,
    selection: tab.value.editorState.selection,
  });
});
</script>

// frontend/src/modules/sql-editor/components/Panels/Panels.tsx
import { Loader2, ShieldAlert } from "lucide-react";
import { Suspense, useEffect, useMemo } from "react";
import { useTranslation } from "react-i18next";
import {
  Panel,
  Group as PanelGroup,
  Separator as PanelResizeHandle,
} from "react-resizable-panels";
import { useShallow } from "zustand/react/shallow";
import { Alert } from "@/components/ui/alert";
import { useAppDatabaseMetadata } from "@/hooks/useAppDatabaseMetadata";
import { useExecuteSQL } from "@/hooks/useExecuteSQL";
import { AIChatToSQL, AIContextProvider } from "@/modules/ai/components";
import { aiContextEvents } from "@/modules/ai/logic";
import { resizeHandleClass } from "@/modules/schema-editor/resize";
import { DatabaseChooser } from "@/modules/sql-editor/components/DatabaseChooser";
import { DataExplorerPanel } from "@/modules/sql-editor/components/DataExplorer/DataExplorerPanel";
import { DiagramPanel } from "@/modules/sql-editor/components/DiagramPanel";
import { ExternalTablesPanel } from "@/modules/sql-editor/components/ExternalTablesPanel";
import { FunctionsPanel } from "@/modules/sql-editor/components/FunctionsPanel";
import { InfoPanel } from "@/modules/sql-editor/components/InfoPanel";
import { PackagesPanel } from "@/modules/sql-editor/components/PackagesPanel";
import { ProceduresPanel } from "@/modules/sql-editor/components/ProceduresPanel";
import { SchemaSelectToolbar } from "@/modules/sql-editor/components/SchemaSelectToolbar";
import { SequencesPanel } from "@/modules/sql-editor/components/SequencesPanel";
import { StandardPanel } from "@/modules/sql-editor/components/StandardPanel/StandardPanel";
import { TablesPanel } from "@/modules/sql-editor/components/TablesPanel";
import { TerminalPanel } from "@/modules/sql-editor/components/TerminalPanel/TerminalPanel";
import { TriggersPanel } from "@/modules/sql-editor/components/TriggersPanel";
import { ViewsPanel } from "@/modules/sql-editor/components/ViewsPanel";
import { useConnectionOfCurrentSQLEditorTab } from "@/modules/sql-editor/hooks/useSQLEditorState";
import {
  selectEditorPanelSize,
  useSQLEditorStore,
} from "@/modules/sql-editor/store";
import {
  getSQLEditorTabsState,
  useCurrentSQLEditorTab,
  useSQLEditorTabState,
} from "@/modules/sql-editor/store/tab";
import { useAppStore } from "@/stores/app";
import { isValidDatabaseName } from "@/types";
import {
  extractDatabaseResourceName,
  getInstanceResource,
  nextAnimationFrame,
} from "@/utils";
import { useViewStateNav } from "./common/useViewStateNav";

const AIPaneFallback = () => (
  <div className="w-full h-full grow flex flex-col items-center justify-center">
    <Loader2 className="size-6 animate-spin text-control-light" />
  </div>
);

/**
 * The host shell beneath the `<TabList>` in `SQLEditorHomePage`'s main
 * column. Two render modes:
 * - `viewState.view === "CODE"` (or no viewState) — shows the saved query
 *   editor (`<StandardPanel>`) or terminal (`<TerminalPanel>`) based on
 *   the active tab's mode.
 * - any other `viewState.view` — shows a metadata browser surface
 *   (info / tables / views / functions / etc.) with the schema-select
 *   toolbar above. The AI pane mounts to the right via a horizontal
 *   resizable split when the user has both the AI panel and a
 *   "code-viewer" surface open (`isShowingCode`).
 */
export function Panels() {
  const { t } = useTranslation();
  const handleEditorPanelResize = useSQLEditorStore(
    (s) => s.handleEditorPanelResize
  );
  const { database } = useConnectionOfCurrentSQLEditorTab();

  const tab = useCurrentSQLEditorTab();
  const tabMode = useSQLEditorTabState(
    (s) => s.tabsById.get(s.currentTabId)?.mode
  );
  const databaseName = database.name;
  const view = useSQLEditorTabState(
    (s) => s.tabsById.get(s.currentTabId)?.viewState?.view
  );
  const showAIPanel = useSQLEditorStore((s) => s.showAIPanel);
  const isShowingCode = useSQLEditorStore((s) => s.isShowingCode);
  const editorPanelSize = useSQLEditorStore(useShallow(selectEditorPanelSize));

  const showAIPaneAlongsidePanel = showAIPanel && isShowingCode;
  const effectiveView = tabMode === "DATA_EXPLORER" ? "CODE" : view;
  const { setSchema, updateViewState } = useViewStateNav();
  const { execute } = useExecuteSQL();

  // Run statements the AI chat sends via the "run-statement" event.
  useEffect(() => {
    const off = aiContextEvents.on(
      "run-statement",
      async ({ data: { statement } }) => {
        const tabsState = getSQLEditorTabsState();
        const t = tabsState.tabsById.get(tabsState.currentTabId);
        if (!t) return;
        updateViewState({ view: "CODE" });
        await nextAnimationFrame();
        const connection = t.connection;
        const database = await useAppStore
          .getState()
          .getOrFetchDatabaseByName(connection.database);
        void execute({
          connection,
          statement,
          engine: getInstanceResource(database).engine,
          explain: false,
          selection: t.editorState.selection,
        });
      }
    );
    return () => {
      off();
    };
  }, [updateViewState, execute]);

  // Parent drives the metadata fetch for the whole Panels subtree;
  // children call `useAppDatabaseMetadata(..., { autoFetch: false })`.
  const databaseMetadata = useAppDatabaseMetadata(databaseName ?? "", {
    silent: true,
  });

  // Pin the active schema to a sensible default whenever the tab,
  // database metadata, or current schema changes.
  const tabId = tab?.id;
  const currentSchema = tab?.viewState?.schema;
  useEffect(() => {
    if (!tabId) return;
    if (
      !isValidDatabaseName(
        extractDatabaseResourceName(databaseMetadata.name).database
      )
    ) {
      return;
    }
    if (
      !currentSchema ||
      databaseMetadata.schemas.findIndex((s) => s.name === currentSchema) < 0
    ) {
      const next = databaseMetadata.schemas[0]?.name;
      if (next !== undefined) setSchema(next);
    }
  }, [tabId, databaseMetadata, currentSchema, setSchema]);

  const codePanel = useMemo(() => {
    if (!tab || tabMode === "SAVED_QUERY") {
      return <StandardPanel key={`standard-${tab?.id ?? "default"}`} />;
    }
    if (tabMode === "ADMIN") {
      return <TerminalPanel key={`terminal-${tab.id}`} />;
    }
    if (tabMode === "DATA_EXPLORER") {
      return <DataExplorerPanel key={`data-explorer-${tab.id}`} />;
    }
    return (
      <Alert variant="error" className="m-2" key={`no-permission-${tab.id}`}>
        <ShieldAlert className="size-5 shrink-0 mt-0.5" />
        <div>{t("database.access-denied")}</div>
      </Alert>
    );
  }, [tab, tabMode, t]);

  const subPanel = effectiveView
    ? renderSubPanel(effectiveView, tab?.id)
    : null;

  const handleAiResize = (sizePct: number) => {
    if (!Number.isFinite(sizePct)) return;
    handleEditorPanelResize(sizePct / 100);
  };

  return (
    <div className="flex-1 flex items-stretch overflow-hidden">
      <div className="flex-1 overflow-y-hidden overflow-x-auto">
        {(!effectiveView || effectiveView === "CODE") && codePanel}
        {effectiveView && effectiveView !== "CODE" && (
          <div className="h-full flex flex-col">
            <div className="py-2 px-2 w-full flex flex-row gap-x-2 justify-between items-center">
              <div className="flex items-center justify-start gap-2">
                {/*
                  Wrap the chooser so it's the lone child of its own
                  flex container. The chooser uses
                  `[&:not(:last-child)]:border-r-0` /
                  `first:rounded-l-xs last:rounded-r-xs` to share borders
                  with adjacent buttons in a button-group context. Here
                  the next sibling is a separate Select primitive (not
                  part of the group), so without this wrapper the chooser
                  loses its right border and only gets left-rounded
                  corners.
                */}
                <div className="inline-flex">
                  <DatabaseChooser disabled />
                </div>
                <SchemaSelectToolbar />
              </div>
            </div>
            {showAIPaneAlongsidePanel ? (
              <PanelGroup orientation="horizontal" className="flex-1">
                <Panel
                  defaultSize={`${editorPanelSize.size * 100}%`}
                  minSize={`${editorPanelSize.min * 100}%`}
                  maxSize={`${editorPanelSize.max * 100}%`}
                  onResize={(size) => handleAiResize(size.asPercentage)}
                >
                  {subPanel}
                </Panel>
                <PanelResizeHandle
                  className={resizeHandleClass("vertical", "w-0.5")}
                />
                <Panel
                  defaultSize={`${(1 - editorPanelSize.size) * 100}%`}
                  minSize="10%"
                >
                  <div className="h-full overflow-hidden flex flex-col">
                    <Suspense fallback={<AIPaneFallback />}>
                      <AIContextProvider>
                        <AIChatToSQL />
                      </AIContextProvider>
                    </Suspense>
                  </div>
                </Panel>
              </PanelGroup>
            ) : (
              <div className="flex-1 min-h-0">{subPanel}</div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function renderSubPanel(view: string, tabId: string | undefined) {
  const k = (suffix: string) => `${suffix}-${tabId ?? "default"}`;
  switch (view) {
    case "INFO":
      return <InfoPanel key={k("info")} />;
    case "TABLES":
      return <TablesPanel key={k("tables")} />;
    case "VIEWS":
      return <ViewsPanel key={k("views")} />;
    case "FUNCTIONS":
      return <FunctionsPanel key={k("functions")} />;
    case "PROCEDURES":
      return <ProceduresPanel key={k("procedures")} />;
    case "SEQUENCES":
      return <SequencesPanel key={k("sequences")} />;
    case "PACKAGES":
      return <PackagesPanel key={k("packages")} />;
    case "TRIGGERS":
      return <TriggersPanel key={k("triggers")} />;
    case "EXTERNAL_TABLES":
      return <ExternalTablesPanel key={k("external-tables")} />;
    case "DIAGRAM":
      return <DiagramPanel key={k("diagram")} />;
    default:
      return null;
  }
}
