// frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/TableCell.vue
<!-- eslint-disable vue/no-v-html -->
<template>
  <div
    class="relative px-2 py-1 text-sm dark:text-gray-100 leading-5 whitespace-nowrap break-all"
    :class="classes"
    @click="handleClick"
  >
    <div
      ref="wrapperRef"
      class="whitespace-nowrap font-mono text-start line-clamp-1"
      v-html="html"
    ></div>
    <div v-if="clickable" class="absolute right-1 top-1/2 translate-y-[-45%]">
      <NButton
        size="tiny"
        circle
        class="dark:!bg-dark-bg"
        @click.stop="showDetail"
      >
        <template #icon>
          <heroicons:arrows-pointing-out class="w-3 h-3" />
        </template>
      </NButton>
    </div>
  </div>
</template>

<script setup lang="ts">
import { type Table } from "@tanstack/vue-table";
import { escape, uniq } from "lodash-es";
import { NButton } from "naive-ui";
import stringWidth from "string-width";
import { computed, ref } from "vue";
import { useConnectionOfCurrentSQLEditorTab } from "@/store";
import { Engine } from "@/types/proto/v1/common";
import type { QueryRow, RowValue } from "@/types/proto/v1/sql_service";
import { extractSQLRowValue, getHighlightHTMLByRegExp } from "@/utils";
import { useSQLResultViewContext } from "../../context";
import { useSelectionContext } from "../common/selection-logic";

const props = defineProps<{
  table: Table<QueryRow>;
  value: RowValue;
  width: number;
  setIndex: number;
  rowIndex: number;
  colIndex: number;
}>();

const {
  state: selectionState,
  disabled: selectionDisabled,
  selectRow,
} = useSelectionContext();
const { dark, disallowCopyingData, detail, keyword } =
  useSQLResultViewContext();
const wrapperRef = ref<HTMLDivElement>();
const plainValue = computed(() => {
  return extractSQLRowValue(props.value).plain;
});
const truncated = computed(() => {
  // not that accurate
  const content = String(plainValue.value);
  const em = 8;
  const padding = 8;
  const guessedContentWidth = stringWidth(content) * em + padding * 2;

  return guessedContentWidth > props.width;
});

const { database } = useConnectionOfCurrentSQLEditorTab();

const clickable = computed(() => {
  if (truncated.value) return true;
  if (database.value.instanceResource.engine === Engine.MONGODB) {
    // A cheap way to check JSON string without paying the parsing cost.
    const maybeJSON = String(props.value).trim();
    return (
      (maybeJSON.startsWith("{") && maybeJSON.endsWith("}")) ||
      (maybeJSON.startsWith("[") && maybeJSON.endsWith("]"))
    );
  }
  return false;
});

const classes = computed(() => {
  const classes: string[] = [];
  if (disallowCopyingData.value) {
    classes.push("select-none");
  }
  if (!selectionDisabled.value) {
    if (props.colIndex === 0) {
      classes.push("cursor-pointer");
      classes.push("hover:bg-accent/10");
    }
    if (
      selectionState.value.columns.includes(props.colIndex) ||
      selectionState.value.rows.includes(props.rowIndex)
    ) {
      classes.push("bg-accent/10");
    }
  }
  if (clickable.value) {
    classes.push("cursor-pointer");
    classes.push(dark.value ? "hover:!bg-white/20" : "hover:!bg-black/5");
  }
  return uniq(classes);
});

const html = computed(() => {
  const value = plainValue.value;
  if (value === undefined) {
    return `<span class="text-gray-400 italic">UNSET</span>`;
  }
  if (value === null) {
    return `<span class="text-gray-400 italic">NULL</span>`;
  }
  const str = String(value);
  if (str.length === 0) {
    return `<br style="min-width: 1rem; display: inline-flex;" />`;
  }

  const kw = keyword.value.trim();
  if (!kw) {
    return escape(str);
  }

  return getHighlightHTMLByRegExp(
    escape(str),
    escape(kw),
    false /* !caseSensitive */
  );
});

const handleClick = (e: MouseEvent) => {
  if (props.colIndex === 0 && !selectionDisabled.value) {
    selectRow(props.rowIndex);
    e.stopPropagation();
  }

  if (!clickable.value) return;
  showDetail();
};

const showDetail = () => {
  detail.value = {
    show: true,
    set: props.setIndex,
    row: props.rowIndex,
    col: props.colIndex,
    table: props.table,
  };
};
</script>

// frontend/src/modules/sql-editor/components/ResultView/TableCell.tsx
import { ExpandIcon } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { HighlightLabelText } from "@/components/HighlightLabelText";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { Engine } from "@/types/proto-es/v1/common_pb";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import type { RowValue } from "@/types/proto-es/v1/sql_service_pb";
import type { SearchScope } from "@/utils/v1/advanced-search/common";
import { getInstanceResource } from "@/utils/v1/database";
import { BinaryFormatButton } from "./BinaryFormatButton";
import type { BinaryFormat } from "./binary-format";
import { getPlainValue } from "./cell-value";
import {
  useBinaryFormatContext,
  useSelectionContext,
  useSQLResultViewContext,
} from "./context";

interface TableCellProps {
  value: RowValue;
  rowIndex: number;
  colIndex: number;
  allowSelect?: boolean;
  columnType: string;
  database: Database;
  scope?: SearchScope;
  keyword: string;
}

export function TableCell({
  value,
  rowIndex,
  colIndex,
  allowSelect: allowSelectProp,
  columnType,
  database,
  scope,
  keyword,
}: TableCellProps) {
  const { setDetail } = useSQLResultViewContext();
  const { getBinaryFormat, setBinaryFormat } = useBinaryFormatContext();
  const {
    state: selectionState,
    disabled: selectionDisabled,
    toggleSelectCell,
    toggleSelectRow,
  } = useSelectionContext();

  const cellRef = useRef<HTMLDivElement>(null);
  const wrapperRef = useRef<HTMLDivElement>(null);
  const [truncated, setTruncated] = useState(false);

  const allowSelect = !!allowSelectProp && !selectionDisabled;
  const hasByteData = value.kind?.case === "bytesValue";

  const binaryFormat = getBinaryFormat({ rowIndex, colIndex });

  // ResizeObserver replaces Vue's `useResizeObserver(cellRef, ...)`.
  useEffect(() => {
    const cell = cellRef.current;
    const wrapper = wrapperRef.current;
    if (!cell || !wrapper) return;
    const measure = () => {
      const verticalTruncated = wrapper.scrollHeight > wrapper.offsetHeight + 2;
      const availableWidth = Math.min(cell.offsetWidth, wrapper.offsetWidth);
      const horizontalTruncated = wrapper.scrollWidth > availableWidth + 2;
      setTruncated(verticalTruncated || horizontalTruncated);
    };
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(cell);
    return () => observer.disconnect();
  }, []);

  const clickable = useMemo(() => {
    if (truncated) return true;
    const eng = getInstanceResource(database).engine;
    if (eng === Engine.MONGODB || eng === Engine.ELASTICSEARCH) {
      const maybeJSON = String(value).trim();
      return (
        (maybeJSON.startsWith("{") && maybeJSON.endsWith("}")) ||
        (maybeJSON.startsWith("[") && maybeJSON.endsWith("]"))
      );
    }
    return false;
  }, [truncated, database, value]);

  const selected = useMemo(() => {
    if (!allowSelect) return false;
    const { columns, rows } = selectionState;
    if (columns.length === 1 && rows.length === 1) {
      return columns[0] === colIndex && rows[0] === rowIndex;
    }
    return columns.includes(colIndex) || rows.includes(rowIndex);
  }, [allowSelect, selectionState, colIndex, rowIndex]);

  const plainValue = useMemo(
    () => getPlainValue(value, columnType, binaryFormat),
    [value, columnType, binaryFormat]
  );

  const showDetail = () => {
    setDetail({ row: rowIndex, col: colIndex });
  };

  const handleClick = (e: React.MouseEvent) => {
    if (!allowSelect) return;
    if (window.getSelection()?.toString()) return;
    if (e.ctrlKey || e.metaKey) {
      toggleSelectRow(rowIndex);
    } else {
      toggleSelectCell(rowIndex, colIndex);
    }
    e.stopPropagation();
  };

  const activeKeyword = (scope?.value || keyword).trim();

  let inner: React.ReactNode;
  if (plainValue === undefined) {
    inner = <span className="text-control-placeholder italic">UNSET</span>;
  } else if (plainValue === null) {
    inner = <span className="text-control-placeholder italic">NULL</span>;
  } else if (plainValue.length === 0) {
    inner = <br style={{ minWidth: "1rem", display: "inline-flex" }} />;
  } else {
    inner = <HighlightLabelText text={plainValue} keyword={activeKeyword} />;
  }

  return (
    <div
      ref={cellRef}
      onClick={handleClick}
      onDoubleClick={showDetail}
      className={cn(
        "relative w-full h-full px-2 py-1 flex items-center",
        allowSelect ? "cursor-pointer hover:bg-accent/10" : "select-none",
        selected && "bg-accent/20!"
      )}
    >
      <div
        ref={wrapperRef}
        className={cn(
          "font-mono text-start wrap-break-word whitespace-pre-wrap line-clamp-3",
          (hasByteData || clickable) && "max-w-[calc(100%-1.5rem)]",
          hasByteData && clickable && "max-w-[calc(100%-3.25rem)]"
        )}
      >
        {inner}
      </div>
      <div className="absolute right-1 top-1/2 -translate-y-[45%] flex items-center gap-1">
        {hasByteData && (
          <BinaryFormatButton
            format={binaryFormat}
            onFormatChange={(format: BinaryFormat) =>
              setBinaryFormat({ colIndex, rowIndex, format })
            }
          />
        )}
        {clickable && (
          <Button
            size="sm"
            appearance="outline"
            className="size-6 p-0 rounded-full shadow opacity-90 hover:opacity-100"
            onClick={(e) => {
              e.stopPropagation();
              showDetail();
            }}
          >
            <ExpandIcon className="size-3" />
          </Button>
        )}
      </div>
    </div>
  );
}
