// frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/VirtualDataTable.vue
<template>
  <div
    ref="containerRef"
    class="relative w-full flex-1 overflow-auto flex flex-col rounded-sm border dark:border-zinc-500"
  >
    <div class="inline-block shrink-0">
      <table
        ref="tableRef"
        class="relative border-collapse -mx-px"
        v-bind="tableResize.getTableProps()"
      >
      <thead
        class="bg-gray-50 dark:bg-gray-700 sticky top-0 z-1 drop-shadow-xs"
      >
        <tr>
          <!-- header for the index -->
          <th
            :key="`0-index`"
            class="group relative py-2 shrink-0 tracking-wider border-x border-block-border dark:border-zinc-500 w-px whitespace-nowrap"
            v-bind="tableResize.getColumnProps(0)"
          >
            <!-- Use the max index to calculate the cell width -->
            <div
              :class="[
                'textinfolabel pr-1 opacity-0',
                selectionDisabled
                  ? 'pl-1'
                  : 'pl-4',
              ]"
            >{{ rows.length }}</div>
            <div
              class="absolute w-2 right-0 top-0 bottom-0 cursor-col-resize"
              @pointerdown="tableResize.startResizing(0)"
              @click.stop.prevent
            />
          </th>
          <!-- header for columns -->
          <th
            v-for="(header, columnIndex) of columns"
            :key="`${columnIndex + 1}-${header.id}`"
            class="group relative px-3 py-2 min-w-8 text-left text-xs font-medium text-gray-500 dark:text-gray-300 tracking-wider border-block-border dark:border-zinc-500"
            :class="{
              'border-r': columnIndex < (columns.length - 1),
              'cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800':
                !selectionDisabled,
              'bg-accent/10! dark:bg-accent/40!':
                selectionState.rows.length === 0 &&
                selectionState.columns.includes(columnIndex),
            }"
            v-bind="tableResize.getColumnProps(columnIndex + 1)"
            @click="e => handleSelectColumn(e, columnIndex)"
          >
            <div class="flex items-center overflow-hidden gap-x-1">
              <span class="flex flex-row items-center select-none">
                <template
                  v-if="String(header.name).length > 0"
                >
                  {{ header.name }}
                </template>
                <br v-else class="min-h-4 inline-flex" />
              </span>

              <MaskingReasonPopover
                v-if="getMaskingReason && getMaskingReason(columnIndex)"
                :reason="getMaskingReason(columnIndex)!"
                :statement="statement"
                :database="database.name"
                class="shrink-0"
              />

              <ColumnSortedIcon
                :is-sorted="getColumnSortDirection(columnIndex)"
                @click.stop.prevent="handleHeaderClick(columnIndex)"
              />

              <!-- Add binary format button if this column has binary data -->
              <BinaryFormatButton
                v-if="existBinaryValue(columnIndex)"
                :format="
                  getBinaryFormat({
                    colIndex: columnIndex,
                  })
                "
                @update:format="
                  (format: BinaryFormat) =>
                    setBinaryFormat({
                      colIndex: columnIndex,
                      format,
                    })
                "
                @click.stop
              />
            </div>

            <!-- The drag-to-resize handler -->
            <div
              class="absolute w-2 right-0 top-0 bottom-0 cursor-col-resize"
              @pointerdown="tableResize.startResizing(columnIndex + 1)"
              @click.stop.prevent
            />
          </th>
        </tr>
      </thead>
      </table>
    </div>
    <NVirtualList
      ref="virtualListRef"
      :items="rows"
      :item-size="ROW_HEIGHT"
      :style="{
        minWidth: `${tableResize.effectiveWidth.value}px`,
      }"
    >
      <template #default="{ item: row, index: rowIndex }: { item: { key: number; item: QueryRow; }; index: number; }">
        <div
          :key="rowIndex"
          class="flex group"
          :data-row-index="rowIndex"
          :style="{
            height: `${ROW_HEIGHT}px`,
            minWidth: `${tableResize.effectiveWidth.value}px`,
          }"
        >
          <!-- the index cell  -->
          <div
            :key="`${rowIndex}-0`"
            class="relative flex items-center shrink-0 text-sm dark:text-gray-100 leading-5 whitespace-nowrap break-all border-block-border dark:border-zinc-500 group-even:bg-gray-100/50 dark:group-even:bg-gray-700/50"
            :class="{
              'border-r': true,
              'border-b': true,
              'bg-accent/10! dark:bg-accent/40!': activeRowIndex === rowIndex,
              'bg-accent/20! dark:bg-accent/40!': selectionState.columns.length === 0 && selectionState.rows.includes(rowIndex)
            }"
            :data-col-index="0"
            :style="{
              height: `${ROW_HEIGHT}px`,
              width: `${tableResize.getColumnWidth(0)}px`,
            }"
          >
            <NPerformantEllipsis
              :class="[
                'textinfolabel pr-1',
                selectionDisabled
                  ? 'pl-1'
                  : 'pl-4',
              ]"
            >
              {{ rowIndex + 1 }}
            </NPerformantEllipsis>

            <div
              v-if="!selectionDisabled"
              class="absolute inset-y-0 left-0 w-3 cursor-pointer bg-accent/5 dark:bg-white/10 hover:bg-accent/10 dark:hover:bg-accent/40"
              :class="{
                'bg-accent/20! dark:bg-accent/40!':
                  selectionState.columns.length === 0 &&
                  selectionState.rows.includes(
                    rowIndex
                  ),
              }"
              @click="e => handleSelectRow(e, rowIndex)"
            ></div>
          </div>

          <!-- other cells -->
          <div
            v-for="(cell, columnIndex) of row.item.values"
            :key="`${rowIndex}-${columnIndex + 1}`"
            class="relative shrink-0 text-sm dark:text-gray-100 leading-5 whitespace-nowrap break-all border-block-border dark:border-zinc-500 group-even:bg-gray-100/50 dark:group-even:bg-gray-700/50"
            :class="{
              'border-r': columnIndex < (row.item.values.length - 1),
              'border-b': true,
            }"
            :data-col-index="columnIndex + 1"
            :style="{
              height: `${ROW_HEIGHT}px`,
              width: `${tableResize.getColumnWidth(columnIndex + 1)}px`,
            }"
          >
            <div
              class="h-full flex items-center overflow-hidden"
            >
              <TableCell
                :value="cell"
                :keyword="search.query"
                :scope="search.scopes.find(scope => scope.id === columns[columnIndex]?.id)"
                :row-index="rowIndex"
                :col-index="columnIndex"
                :allow-select="true"
                :column-type="getColumnTypeByIndex(columnIndex)"
                :database="database"
                :class="{
                  'h-full w-full truncate': true,
                  'bg-accent/10! dark:bg-accent/40!': activeRowIndex === rowIndex
                }"
              />
            </div>
          </div>
        </div>
      </template>
    </NVirtualList>
  </div>
</template>

<script lang="ts" setup>
import { useWindowSize, watchDebounced } from "@vueuse/core";
import { head, last } from "lodash-es";
import { NPerformantEllipsis, NVirtualList } from "naive-ui";
import { computed, nextTick, onMounted, onUnmounted, ref } from "vue";
import { DEBOUNCE_SEARCH_DELAY } from "@/types";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import type { MaskingReason } from "@/types/proto-es/v1/sql_service_pb";
import { type QueryRow } from "@/types/proto-es/v1/sql_service_pb";
import { type SearchParams } from "@/utils";
import BinaryFormatButton from "./common/BinaryFormatButton.vue";
import {
  type BinaryFormat,
  getBinaryFormatByColumnType,
  useBinaryFormatContext,
} from "./common/binary-format-store";
import ColumnSortedIcon from "./common/ColumnSortedIcon.vue";
import MaskingReasonPopover from "./common/MaskingReasonPopover.vue";
import { useSelectionContext } from "./common/selection-logic";
import type {
  ResultTableColumn,
  ResultTableRow,
  SortDirection,
  SortState,
} from "./common/types";
import { getPlainValue } from "./common/utils";
import TableCell from "./TableCell.vue";
import useTableColumnWidthLogic from "./useTableResize";

const props = defineProps<{
  rows: ResultTableRow[];
  columns: ResultTableColumn[];
  activeRowIndex: number;
  isSensitiveColumn: (index: number) => boolean;
  getMaskingReason?: (index: number) => MaskingReason | undefined;
  database: Database;
  statement?: string;
  sortState?: SortState;
  search: SearchParams;
}>();

const emit = defineEmits<{
  (event: "toggle-sort", columnIndex: number): void;
}>();

const ROW_HEIGHT = 35; // 35px height for every row
const { width: windowWidth } = useWindowSize();

const getColumnSortDirection = (columnIndex: number): SortDirection => {
  if (!props.sortState || props.sortState.columnIndex !== columnIndex) {
    return false;
  }
  return props.sortState.direction;
};

const handleHeaderClick = (columnIndex: number) => {
  emit("toggle-sort", columnIndex);
};

const {
  state: selectionState,
  disabled: selectionDisabled,
  toggleSelectColumn,
  toggleSelectRow,
  deselect,
} = useSelectionContext();
const containerRef = ref<HTMLDivElement>();
const tableRef = ref<HTMLTableElement>();
const virtualListRef = ref<InstanceType<typeof NVirtualList>>();

// Get row cell content for column width calculation
const getRowCellContent = (columnIndex: number): string | undefined => {
  // check at most 3 rows
  for (let i = 0; i < Math.min(3, props.rows.length); i++) {
    const firstRow = props.rows[i];
    if (!firstRow) {
      continue;
    }
    const cell = firstRow.item.values[columnIndex];
    if (!cell) {
      continue;
    }
    const columnType = props.columns[columnIndex]?.columnType ?? "";
    const plainValue = getPlainValue(cell, columnType, "DEFAULT");
    if (plainValue) {
      return plainValue;
    }
  }
  return undefined;
};

const hasRowSelect = computed(() => {
  return (
    selectionState.value.columns.length === 0 &&
    selectionState.value.rows.length > 0
  );
});

const handleSelectRow = (e: MouseEvent, index: number) => {
  e.stopPropagation();

  if ((e.metaKey || e.ctrlKey) && hasRowSelect.value) {
    const firstRowIndex = head(selectionState.value.rows);
    const lastRowIndex = last(selectionState.value.rows);
    if (lastRowIndex !== undefined && index > lastRowIndex) {
      for (let i = lastRowIndex + 1; i <= index; i++) {
        toggleSelectRow(i);
      }
    } else if (firstRowIndex !== undefined && index < firstRowIndex) {
      deselect();
      for (let i = index; i <= firstRowIndex; i++) {
        toggleSelectRow(i);
      }
    }
    return;
  }

  toggleSelectRow(index);
};

const hasColumnSelect = computed(() => {
  return (
    selectionState.value.columns.length > 0 &&
    selectionState.value.rows.length === 0
  );
});

const handleSelectColumn = (e: MouseEvent, index: number) => {
  e.stopPropagation();

  if ((e.metaKey || e.ctrlKey) && hasColumnSelect.value) {
    const firstColumnIndex = head(selectionState.value.columns);
    const lastColumnIndex = last(selectionState.value.columns);
    if (lastColumnIndex !== undefined && index > lastColumnIndex) {
      for (let i = lastColumnIndex + 1; i <= index; i++) {
        toggleSelectColumn(i);
      }
    } else if (firstColumnIndex !== undefined && index < firstColumnIndex) {
      deselect();
      for (let i = index; i <= firstColumnIndex; i++) {
        toggleSelectColumn(i);
      }
    }
    return;
  }

  toggleSelectColumn(index);
};

const tableResize = useTableColumnWidthLogic({
  tableRef,
  containerRef,
  minWidth: 64, // 4rem
  maxWidth: 640, // 40rem
  getRowCellContent,
});

const { getBinaryFormat, setBinaryFormat } = useBinaryFormatContext();

const getColumnTypeByIndex = (columnIndex: number) => {
  return props.columns[columnIndex].columnType;
};

const existBinaryValue = (columnIndex: number) => {
  if (!getBinaryFormatByColumnType(getColumnTypeByIndex(columnIndex))) {
    return false;
  }

  // Check each row in the column for binary data (proto-es oneof pattern)
  for (const row of props.rows) {
    const cell = row.item.values[columnIndex];
    if (!cell) continue;

    if (cell.kind?.case === "bytesValue") {
      return true;
    }
  }

  return false;
};

// Re-initialize column widths when data changes
watchDebounced(
  () => props.columns,
  () => {
    nextTick(() => {
      tableResize.reset();
    });
  },
  { immediate: true, deep: true, debounce: DEBOUNCE_SEARCH_DELAY }
);

watchDebounced(
  () => windowWidth.value,
  () => {
    nextTick(() => {
      tableResize.reset();
    });
  },
  { debounce: DEBOUNCE_SEARCH_DELAY }
);

// Handle horizontal scrolling for both:
// 1. Shift+wheel for mouse users
// 2. Native horizontal swipe (deltaX) for trackpad users
// Use capture phase to intercept before NVirtualList handles it
const handleWheel = (event: WheelEvent) => {
  const container = containerRef.value;
  if (!container) return;

  const hasHorizontalOverflow = container.scrollWidth > container.clientWidth;
  if (!hasHorizontalOverflow) return;

  // Handle shift+wheel (mouse with vertical scroll wheel)
  if (event.shiftKey) {
    event.preventDefault();
    event.stopPropagation();
    container.scrollLeft += event.deltaY || event.deltaX;
    return;
  }

  // Handle trackpad horizontal swipe (deltaX is dominant)
  // When |deltaX| > |deltaY|, it's a horizontal swipe gesture
  if (Math.abs(event.deltaX) > Math.abs(event.deltaY)) {
    event.preventDefault();
    event.stopPropagation();
    container.scrollLeft += event.deltaX;
  }
};

onMounted(() => {
  // Use capture phase to intercept before NVirtualList
  containerRef.value?.addEventListener("wheel", handleWheel, {
    passive: false,
    capture: true,
  });
});

onUnmounted(() => {
  containerRef.value?.removeEventListener("wheel", handleWheel, {
    capture: true,
  });
});

defineExpose({
  scrollTo: (index: number) =>
    virtualListRef.value?.scrollTo({
      top: Math.max(0, (index - 1) * ROW_HEIGHT),
      debounce: true,
      behavior: "smooth",
    }),
});
</script>

// frontend/src/modules/sql-editor/components/ResultView/VirtualDataTable.tsx
import { useVirtualizer } from "@tanstack/react-virtual";
import { head, last } from "lodash-es";
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from "react";
import { cn } from "@/lib/utils";
import { MaskingReasonPopover } from "@/modules/sql-editor/components/MaskingReasonPopover";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import type { MaskingReason } from "@/types/proto-es/v1/sql_service_pb";
import type { SearchParams } from "@/utils/v1/advanced-search/common";
import { BinaryFormatButton } from "./BinaryFormatButton";
import {
  type BinaryFormat,
  getBinaryFormatByColumnType,
} from "./binary-format";
import { ColumnSortedIcon } from "./ColumnSortedIcon";
import { getPlainValue } from "./cell-value";
import { useBinaryFormatContext, useSelectionContext } from "./context";
import { ResultCopyContextMenu } from "./ResultCopyContextMenu";
import { TableCell } from "./TableCell";
import type {
  ResultTableColumn,
  ResultTableRow,
  SortDirection,
  SortState,
} from "./types";
import { useTableResize } from "./useTableResize";

const ROW_HEIGHT = 35;
const MIN_COL_WIDTH = 64;
const MAX_COL_WIDTH = 640;

export interface VirtualDataTableHandle {
  scrollTo(index: number): void;
}

export interface VirtualDataTableProps {
  rows: ResultTableRow[];
  columns: ResultTableColumn[];
  activeRowIndex: number;
  isSensitiveColumn: (index: number) => boolean;
  getMaskingReason?: (index: number) => MaskingReason | undefined;
  database: Database;
  statement?: string;
  sortState?: SortState;
  search: SearchParams;
  onToggleSort: (columnIndex: number) => void;
}

/**
 * Virtualized result-table grid. Replaces the Naive UI `NVirtualList` host
 * with `@tanstack/react-virtual`'s `useVirtualizer`. The header is a
 * separate sticky row outside the virtual scroller so it can stay fixed
 * during vertical scroll without fighting the virtualizer's internal
 * positioning.
 */
export const VirtualDataTable = forwardRef<
  VirtualDataTableHandle,
  VirtualDataTableProps
>(function VirtualDataTable(
  {
    rows,
    columns,
    activeRowIndex,
    getMaskingReason,
    database,
    statement,
    sortState,
    search,
    onToggleSort,
  },
  ref
) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [containerWidth, setContainerWidth] = useState(0);

  // Track container width for last-column extra-space distribution.
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const update = () => setContainerWidth(el.clientWidth);
    update();
    const observer = new ResizeObserver(update);
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  const {
    state: selectionState,
    disabled: selectionDisabled,
    toggleSelectColumn,
    toggleSelectRow,
    deselect,
  } = useSelectionContext();

  const { getBinaryFormat, setBinaryFormat } = useBinaryFormatContext();

  const getColumnTypeByIndex = useCallback(
    (columnIndex: number) => columns[columnIndex]?.columnType ?? "",
    [columns]
  );

  const getRowCellContent = useCallback(
    (columnIndex: number): string | undefined => {
      // Sample up to 3 rows for column-width estimation.
      for (let i = 0; i < Math.min(3, rows.length); i++) {
        const sampleRow = rows[i];
        if (!sampleRow) continue;
        const cell = sampleRow.item.values[columnIndex];
        if (!cell) continue;
        const plain = getPlainValue(
          cell,
          getColumnTypeByIndex(columnIndex),
          "DEFAULT"
        );
        if (plain) return plain;
      }
      return undefined;
    },
    [rows, getColumnTypeByIndex]
  );

  const tableResize = useTableResize({
    columns,
    rows,
    containerWidth,
    minWidth: MIN_COL_WIDTH,
    maxWidth: MAX_COL_WIDTH,
    getRowCellContent,
  });

  const virtualizer = useVirtualizer({
    count: rows.length,
    getScrollElement: () => containerRef.current,
    estimateSize: () => ROW_HEIGHT,
    overscan: 8,
  });

  useImperativeHandle(
    ref,
    () => ({
      scrollTo(index: number) {
        virtualizer.scrollToIndex(Math.max(0, index - 1), {
          align: "start",
          behavior: "smooth",
        });
      },
    }),
    [virtualizer]
  );

  const getColumnSortDirection = (columnIndex: number): SortDirection => {
    if (!sortState || sortState.columnIndex !== columnIndex) return false;
    return sortState.direction;
  };

  const hasRowSelect =
    selectionState.columns.length === 0 && selectionState.rows.length > 0;
  const hasColumnSelect =
    selectionState.columns.length > 0 && selectionState.rows.length === 0;

  const handleSelectRow = (e: React.MouseEvent, index: number) => {
    e.stopPropagation();
    if ((e.metaKey || e.ctrlKey) && hasRowSelect) {
      const firstRowIndex = head(selectionState.rows);
      const lastRowIndex = last(selectionState.rows);
      if (lastRowIndex !== undefined && index > lastRowIndex) {
        for (let i = lastRowIndex + 1; i <= index; i++) toggleSelectRow(i);
      } else if (firstRowIndex !== undefined && index < firstRowIndex) {
        deselect();
        for (let i = index; i <= firstRowIndex; i++) toggleSelectRow(i);
      }
      return;
    }
    toggleSelectRow(index);
  };

  const handleSelectColumn = (e: React.MouseEvent, index: number) => {
    e.stopPropagation();
    if ((e.metaKey || e.ctrlKey) && hasColumnSelect) {
      const firstCol = head(selectionState.columns);
      const lastCol = last(selectionState.columns);
      if (lastCol !== undefined && index > lastCol) {
        for (let i = lastCol + 1; i <= index; i++) toggleSelectColumn(i);
      } else if (firstCol !== undefined && index < firstCol) {
        deselect();
        for (let i = index; i <= firstCol; i++) toggleSelectColumn(i);
      }
      return;
    }
    toggleSelectColumn(index);
  };

  // Precompute the set of column indices that hold any binary cell value.
  // Done once per `rows` / `columns` change instead of per-header-render —
  // the per-header form was O(rows × columns) on every VirtualDataTable
  // render and stalled the main thread on large result sets.
  const binaryColumnSet = useMemo(() => {
    const candidates: number[] = [];
    for (let i = 0; i < columns.length; i++) {
      if (getBinaryFormatByColumnType(columns[i]?.columnType)) {
        candidates.push(i);
      }
    }
    if (candidates.length === 0) return new Set<number>();
    const out = new Set<number>();
    const remaining = new Set(candidates);
    for (const row of rows) {
      if (remaining.size === 0) break;
      for (const colIdx of [...remaining]) {
        const cell = row.item.values[colIdx];
        if (cell?.kind?.case === "bytesValue") {
          out.add(colIdx);
          remaining.delete(colIdx);
        }
      }
    }
    return out;
  }, [columns, rows]);

  // Shift+wheel for mouse + trackpad horizontal swipes.
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    const handleWheel = (event: WheelEvent) => {
      const hasHorizontalOverflow =
        container.scrollWidth > container.clientWidth;
      if (!hasHorizontalOverflow) return;
      if (event.shiftKey) {
        event.preventDefault();
        event.stopPropagation();
        container.scrollLeft += event.deltaY || event.deltaX;
        return;
      }
      if (Math.abs(event.deltaX) > Math.abs(event.deltaY)) {
        event.preventDefault();
        event.stopPropagation();
        container.scrollLeft += event.deltaX;
      }
    };
    container.addEventListener("wheel", handleWheel, {
      passive: false,
      capture: true,
    });
    return () => {
      container.removeEventListener("wheel", handleWheel, { capture: true });
    };
  }, []);

  const totalRows = rows.length;
  const indexColWidth = tableResize.getColumnWidth(0);

  // The header row sits outside the virtualizer so it stays sticky during
  // vertical scroll. Same min-width as body rows so horizontal scroll
  // syncs visually.
  const minRowWidth = useMemo(
    () => `${tableResize.effectiveWidth}px`,
    [tableResize.effectiveWidth]
  );

  return (
    <ResultCopyContextMenu>
      <div
        ref={containerRef}
        className="relative w-full flex-1 min-h-0 overflow-auto rounded-sm border border-block-border"
      >
        {/* Header */}
        <div
          className="sticky top-0 z-1 bg-control-bg flex shadow-sm"
          style={{ minWidth: minRowWidth }}
        >
          {/* Index header */}
          <HeaderCell
            width={indexColWidth}
            borderRight
            onResizeStart={(e) => tableResize.onResizeStart(0, e)}
          >
            <div
              className={cn(
                "textinfolabel pr-1 opacity-0",
                selectionDisabled ? "pl-1" : "pl-4"
              )}
            >
              {totalRows}
            </div>
          </HeaderCell>

          {/* Data column headers */}
          {columns.map((header, columnIndex) => {
            const slotWidth = tableResize.getColumnWidth(columnIndex + 1);
            const isLast = columnIndex === columns.length - 1;
            const isSelected =
              selectionState.rows.length === 0 &&
              selectionState.columns.includes(columnIndex);
            const reason = getMaskingReason?.(columnIndex);
            return (
              <HeaderCell
                key={`${columnIndex}-${header.id}`}
                width={slotWidth}
                borderRight={!isLast}
                onResizeStart={(e) =>
                  tableResize.onResizeStart(columnIndex + 1, e)
                }
                onClick={(e) => handleSelectColumn(e, columnIndex)}
                className={cn(
                  "px-3 py-1.5 min-w-8 text-left text-xs font-medium text-control-light tracking-wider",
                  !selectionDisabled &&
                    "cursor-pointer hover:bg-control-bg-hover",
                  // NOTE: opacity may need visual tuning on dark themes
                  isSelected && "bg-accent/10!"
                )}
              >
                <div className="flex items-center min-w-0 gap-x-1">
                  <span className="min-w-0 truncate select-none">
                    {String(header.name).length > 0 ? (
                      header.name
                    ) : (
                      <br className="min-h-4 inline-flex" />
                    )}
                  </span>
                  {reason && (
                    <span className="shrink-0">
                      <MaskingReasonPopover
                        reason={reason}
                        statement={statement}
                        database={database.name}
                      />
                    </span>
                  )}
                  <span
                    onClick={(e) => {
                      e.stopPropagation();
                      onToggleSort(columnIndex);
                    }}
                    role="button"
                    tabIndex={-1}
                    className="shrink-0 inline-flex"
                  >
                    <ColumnSortedIcon
                      isSorted={getColumnSortDirection(columnIndex)}
                    />
                  </span>
                  {binaryColumnSet.has(columnIndex) && (
                    <span
                      onClick={(e) => e.stopPropagation()}
                      className="shrink-0"
                    >
                      <BinaryFormatButton
                        format={getBinaryFormat({ colIndex: columnIndex })}
                        onFormatChange={(format: BinaryFormat) =>
                          setBinaryFormat({ colIndex: columnIndex, format })
                        }
                      />
                    </span>
                  )}
                </div>
              </HeaderCell>
            );
          })}
        </div>

        {/* Virtualized body */}
        <div
          style={{
            height: `${virtualizer.getTotalSize()}px`,
            minWidth: minRowWidth,
            position: "relative",
          }}
        >
          {virtualizer.getVirtualItems().map((virtualRow) => {
            const rowIndex = virtualRow.index;
            const row = rows[rowIndex];
            if (!row) return null;
            const isActive = activeRowIndex === rowIndex;
            const rowSelected =
              selectionState.columns.length === 0 &&
              selectionState.rows.includes(rowIndex);
            return (
              <div
                key={virtualRow.key}
                data-row-index={rowIndex}
                className="flex absolute inset-x-0 group"
                style={{
                  top: 0,
                  transform: `translateY(${virtualRow.start}px)`,
                  height: `${ROW_HEIGHT}px`,
                  minWidth: minRowWidth,
                }}
              >
                {/* Index cell */}
                <div
                  className={cn(
                    "relative flex items-center shrink-0 text-sm text-control leading-5 whitespace-nowrap break-all border-block-border border-r border-b group-even:bg-control-bg/40",
                    // NOTE: opacity may need visual tuning on dark themes
                    isActive && "bg-accent/10!",
                    rowSelected && "bg-accent/20!"
                  )}
                  data-col-index={0}
                  style={{
                    height: `${ROW_HEIGHT}px`,
                    width: `${indexColWidth}px`,
                  }}
                >
                  <span
                    className={cn(
                      "textinfolabel pr-1 truncate",
                      selectionDisabled ? "pl-1" : "pl-4"
                    )}
                  >
                    {rowIndex + 1}
                  </span>
                  {!selectionDisabled && (
                    <button
                      type="button"
                      aria-label={`Select row ${rowIndex + 1}`}
                      onClick={(e) => handleSelectRow(e, rowIndex)}
                      className={cn(
                        "absolute inset-y-0 left-0 w-3 cursor-pointer bg-accent/5 hover:bg-accent/10",
                        // NOTE: opacity may need visual tuning on dark themes
                        rowSelected && "bg-accent/20!"
                      )}
                    />
                  )}
                </div>

                {/* Data cells */}
                {row.item.values.map((cell, columnIndex) => {
                  const cellWidth = tableResize.getColumnWidth(columnIndex + 1);
                  const isLastCol = columnIndex === row.item.values.length - 1;
                  return (
                    <div
                      key={`${rowIndex}-${columnIndex + 1}`}
                      className={cn(
                        "relative shrink-0 text-sm text-control leading-5 whitespace-nowrap break-all border-block-border border-b group-even:bg-control-bg/40",
                        !isLastCol && "border-r",
                        // Match the Vue version: an active (search-matched) row
                        // highlights every cell in that row, not just the index
                        // column.
                        // NOTE: opacity may need visual tuning on dark themes
                        isActive && "bg-accent/10!"
                      )}
                      data-col-index={columnIndex + 1}
                      style={{
                        height: `${ROW_HEIGHT}px`,
                        width: `${cellWidth}px`,
                      }}
                    >
                      <div className="h-full flex items-center overflow-hidden">
                        <TableCell
                          value={cell}
                          keyword={search.query}
                          scope={search.scopes.find(
                            (s) => s.id === columns[columnIndex]?.id
                          )}
                          rowIndex={rowIndex}
                          colIndex={columnIndex}
                          allowSelect
                          columnType={getColumnTypeByIndex(columnIndex)}
                          database={database}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            );
          })}
        </div>
      </div>
    </ResultCopyContextMenu>
  );
});

interface HeaderCellProps {
  width: number;
  borderRight?: boolean;
  onResizeStart: (e: React.PointerEvent) => void;
  onClick?: (e: React.MouseEvent) => void;
  className?: string;
  children?: React.ReactNode;
}

function HeaderCell({
  width,
  borderRight,
  onResizeStart,
  onClick,
  className,
  children,
}: HeaderCellProps) {
  return (
    <div
      onClick={onClick}
      className={cn(
        "group relative shrink-0 border-block-border",
        borderRight && "border-r",
        className
      )}
      style={{ width: `${width}px` }}
    >
      {children}
      <span
        role="separator"
        aria-orientation="vertical"
        onPointerDown={onResizeStart}
        onClick={(e) => {
          e.stopPropagation();
          e.preventDefault();
        }}
        className="absolute w-2 right-0 top-0 bottom-0 cursor-col-resize"
      />
    </div>
  );
}
