// frontend/src/views/sql-editor/EditorPanel/Panels/ProceduresPanel/ProceduresPanel.vue
<template>
  <div v-if="metadata?.schema" class="h-full overflow-hidden flex flex-col">
    <div
      v-show="!metadata.procedure"
      class="w-full h-[44px] py-2 px-2 border-b flex flex-row gap-x-2 justify-end items-center"
    >
      <SearchBox
        v-model:value="state.keyword"
        size="small"
        style="width: 10rem"
      />
    </div>
    <ProceduresTable
      v-show="!metadata.procedure"
      :db="database"
      :database="metadata.database"
      :schema="metadata.schema"
      :procedures="metadata.schema.procedures"
      :keyword="state.keyword"
      @click="select"
    />

    <template v-if="metadata.procedure">
      <CodeViewer
        :db="database"
        :title="metadata.procedure.name"
        :code="metadata.procedure.definition"
        @back="deselect"
      >
        <template #title-icon>
          <ProcedureIcon class="w-4 h-4 text-main" />
        </template>
      </CodeViewer>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive } from "vue";
import { ProcedureIcon } from "@/components/Icon";
import { SearchBox } from "@/components/v2";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
} from "@/store";
import {
  DatabaseMetadata,
  ProcedureMetadata,
  SchemaMetadata,
} from "@/types/proto/v1/database_service";
import {
  extractKeyWithPosition,
  keyWithPosition,
} from "@/views/sql-editor/EditorCommon";
import { useCurrentTabViewStateContext } from "../../context";
import { CodeViewer } from "../common";
import ProceduresTable from "./ProceduresTable.vue";

const { database } = useConnectionOfCurrentSQLEditorTab();
const { viewState, updateViewState } = useCurrentTabViewStateContext();
const databaseMetadata = computed(() => {
  return useDBSchemaV1Store().getDatabaseMetadata(database.value.name);
});
const state = reactive({
  keyword: "",
});

const metadata = computed(() => {
  const database = databaseMetadata.value;
  const schema = database.schemas.find(
    (s) => s.name === viewState.value?.schema
  );
  const [name, position] = extractKeyWithPosition(
    viewState.value?.detail?.procedure ?? ""
  );
  const procedure = schema?.procedures.find(
    (p, i) => p.name === name && i === position
  );
  return { database, schema, procedure };
});

const select = (selected: {
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  procedure: ProcedureMetadata;
  position: number;
}) => {
  updateViewState({
    detail: {
      procedure: keyWithPosition(selected.procedure.name, selected.position),
    },
  });
};

const deselect = () => {
  updateViewState({
    detail: {},
  });
};
</script>

// frontend/src/react/components/sql-editor/Panels/ProceduresPanel/ProceduresPanel.tsx
import { ChevronLeft, FileCode } from "lucide-react";
import { useState } from "react";
import { Button } from "@/react/components/ui/button";
import { useVueState } from "@/react/hooks/useVueState";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
} from "@/store";
import {
  extractKeyWithPosition,
  keyWithPosition,
} from "@/views/sql-editor/EditorCommon/utils";
import { CodeViewer } from "../common/CodeViewer";
import { PanelSearchBox } from "../common/PanelSearchBox";
import { useViewStateNav } from "../common/useViewStateNav";
import { ProceduresTable } from "./ProceduresTable";

export function ProceduresPanel() {
  const dbSchemaStore = useDBSchemaV1Store();
  const { database } = useConnectionOfCurrentSQLEditorTab();
  const databaseName = useVueState(() => database.value.name);
  const db = useVueState(() => database.value);
  const databaseMetadata = useVueState(
    () => dbSchemaStore.getDatabaseMetadata(databaseName ?? ""),
    { deep: true }
  );

  const {
    schema: schemaName,
    detail,
    setDetail,
    clearDetail,
  } = useViewStateNav();

  const [keyword, setKeyword] = useState("");

  const schema = databaseMetadata?.schemas.find((s) => s.name === schemaName);
  const [procName, procPosition] = extractKeyWithPosition(
    detail?.procedure ?? ""
  );
  const procedure = schema?.procedures.find(
    (p, i) => p.name === procName && i === procPosition
  );

  if (!db || !databaseMetadata || !schema) return null;

  if (procedure) {
    return (
      <CodeViewer
        db={db}
        title={procedure.name}
        code={procedure.definition}
        onBack={() => clearDetail()}
        titlePrefix={
          <Button
            variant="ghost"
            className="h-8 px-1 text-sm"
            onClick={() => clearDetail()}
          >
            <ChevronLeft className="size-5" />
            <FileCode className="size-4 text-control" />
            <span className="truncate">{procedure.name}</span>
          </Button>
        }
      />
    );
  }

  return (
    <div className="h-full overflow-hidden flex flex-col">
      <div className="w-full h-11 py-2 px-2 border-b border-block-border flex flex-row gap-x-2 justify-end items-center">
        <PanelSearchBox value={keyword} onChange={setKeyword} />
      </div>
      <div className="flex-1 min-h-0">
        <ProceduresTable
          database={databaseMetadata}
          schema={schema}
          procedures={schema.procedures}
          keyword={keyword}
          onSelect={({ procedure: target, position }) =>
            setDetail({
              procedure: keyWithPosition(target.name, position),
            })
          }
        />
      </div>
    </div>
  );
}
