// frontend/src/react/components/sql-editor/ResultView/EmptyView.tsx
import { useTranslation } from "react-i18next";
import { cn } from "@/react/lib/utils";

interface EmptyViewProps {
  dark: boolean;
}

export function EmptyView({ dark }: EmptyViewProps) {
  const { t } = useTranslation();
  return (
    <div
      className={cn(
        "text-md font-normal",
        dark ? "text-matrix-green-hover" : "text-control-light"
      )}
    >
      {t("sql-editor.no-data-available")}
    </div>
  );
}

// frontend/src/views/sql-editor/EditorCommon/ResultView/EmptyView.vue
<template>
  <div
    class="text-md font-normal"
    :class="[dark ? 'text-matrix-green-hover' : 'text-control-light']"
  >
    {{ $t("sql-editor.no-data-available") }}
  </div>
</template>

<script lang="ts" setup>
import { useSQLResultViewContext } from "./context";

const { dark } = useSQLResultViewContext();
</script>
