// frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RulesSection.vue
<template>
  <div class="flex flex-col gap-y-2">
    <div class="flex items-center justify-between">
      <div class="font-medium text-base">
        {{ sourceDisplayText }}
      </div>
      <NButton size="small" @click="handleAddRule">
        <template #icon>
          <PlusIcon class="w-4" />
        </template>
        {{ $t("custom-approval.approval-flow.add-rule") }}
      </NButton>
    </div>

    <div class="rules-table border border-gray-200 rounded-sm text-sm">
      <!-- Table Header -->
      <div
        class="rules-table-header grid bg-gray-50 border-b border-gray-200 font-medium text-gray-600"
      >
        <div class="px-2 py-2 w-10"></div>
        <div class="px-3 py-2">{{ $t("common.title") }}</div>
        <div class="px-3 py-2">{{ $t("cel.condition.self") }}</div>
        <div class="px-3 py-2">{{ $t("custom-approval.approval-flow.self") }}</div>
        <div class="px-3 py-2 w-24">{{ $t("common.operations") }}</div>
      </div>

      <!-- Draggable Body -->
      <Draggable
        v-model="localRules"
        item-key="uid"
        handle=".drag-handle"
        animation="150"
        ghost-class="rules-row-ghost"
        @end="handleDragEnd"
      >
        <template #item="{ element: rule, index }">
          <div
            class="rules-table-row grid border-b border-gray-100 last:border-b-0 hover:bg-gray-50"
            :class="{ 'bg-gray-50/50': index % 2 === 1 }"
          >
            <div class="px-2 py-2 w-10 flex items-center justify-center">
              <GripVerticalIcon
                class="drag-handle w-4 h-4 text-gray-400 cursor-grab active:cursor-grabbing"
              />
            </div>
            <div class="px-3 py-2 truncate" :title="rule.title">
              {{ rule.title || "-" }}
            </div>
            <div class="px-3 py-2 truncate">
              <code class="text-xs">{{ rule.condition || "true" }}</code>
            </div>
            <div class="px-3 py-2 truncate">
              {{ formatApprovalFlow(rule.flow) }}
            </div>
            <div class="px-3 py-2 w-24 flex items-center gap-x-1">
              <MiniActionButton @click="handleEditRule(rule)">
                <PencilIcon class="w-3" />
              </MiniActionButton>
              <NPopconfirm
                :positive-text="$t('common.confirm')"
                :negative-text="$t('common.cancel')"
                @positive-click="handleDeleteRule(rule)"
              >
                <template #trigger>
                  <MiniActionButton>
                    <TrashIcon class="w-3" />
                  </MiniActionButton>
                </template>
                {{ $t("common.confirm") }}?
              </NPopconfirm>
            </div>
          </div>
        </template>
      </Draggable>

      <!-- Empty State -->
      <div
        v-if="localRules.length === 0"
        class="px-3 py-4 text-center text-gray-400"
      >
        {{ $t("common.no-data") }}
      </div>
    </div>

    <RuleEditModal
      v-model:show="showModal"
      :mode="modalMode"
      :source="source"
      :rule="editingRule"
      :is-fallback="isFallback"
      @save="handleSaveRule"
    />
  </div>
</template>

<script lang="ts" setup>
import {
  GripVerticalIcon,
  PencilIcon,
  PlusIcon,
  TrashIcon,
} from "lucide-vue-next";
import { NButton, NPopconfirm } from "naive-ui";
import { computed, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import Draggable from "vuedraggable";
import { MiniActionButton } from "@/components/v2";
import { pushNotification, useWorkspaceApprovalSettingStore } from "@/store";
import type { LocalApprovalRule } from "@/types";
import { WorkspaceApprovalSetting_Rule_Source } from "@/types/proto-es/v1/setting_service_pb";
import { formatApprovalFlow } from "@/utils";
import { approvalSourceText } from "../../common/utils";
import { useCustomApprovalContext } from "../context";
import RuleEditModal from "./RuleEditModal.vue";

const props = defineProps<{
  source: WorkspaceApprovalSetting_Rule_Source;
}>();

const isFallback = computed(
  () => props.source === WorkspaceApprovalSetting_Rule_Source.SOURCE_UNSPECIFIED
);

const { t } = useI18n();
const store = useWorkspaceApprovalSettingStore();
const context = useCustomApprovalContext();

const showModal = ref(false);
const modalMode = ref<"create" | "edit">("create");
const editingRule = ref<LocalApprovalRule | undefined>();

const rules = computed(() => store.getRulesBySource(props.source));

// Local copy for dragging - synced with store
const localRules = ref<LocalApprovalRule[]>([]);

watch(
  rules,
  (newRules) => {
    localRules.value = [...newRules];
  },
  { immediate: true }
);

const sourceDisplayText = computed(() => approvalSourceText(props.source));

const handleDragEnd = async (event: { oldIndex: number; newIndex: number }) => {
  const { oldIndex, newIndex } = event;
  if (oldIndex === newIndex) return;

  if (!context.hasFeature.value) {
    context.showFeatureModal.value = true;
    // Revert local change
    localRules.value = [...rules.value];
    return;
  }

  try {
    await store.reorderRules(props.source, oldIndex, newIndex);
    pushNotification({
      module: "bytebase",
      style: "SUCCESS",
      title: t("common.updated"),
    });
  } catch {
    // Revert local change on error
    localRules.value = [...rules.value];
  }
};

const handleAddRule = () => {
  if (!context.hasFeature.value) {
    context.showFeatureModal.value = true;
    return;
  }
  modalMode.value = "create";
  editingRule.value = undefined;
  showModal.value = true;
};

const handleEditRule = (rule: LocalApprovalRule) => {
  if (!context.hasFeature.value) {
    context.showFeatureModal.value = true;
    return;
  }
  modalMode.value = "edit";
  editingRule.value = rule;
  showModal.value = true;
};

const handleDeleteRule = async (rule: LocalApprovalRule) => {
  if (!context.hasFeature.value) {
    context.showFeatureModal.value = true;
    return;
  }
  try {
    await store.deleteRule(rule.uid);
    pushNotification({
      module: "bytebase",
      style: "SUCCESS",
      title: t("common.deleted"),
    });
  } catch {
    // Error handled by store
  }
};

const handleSaveRule = async (ruleData: Partial<LocalApprovalRule>) => {
  try {
    if (modalMode.value === "create") {
      await store.addRule(ruleData as Omit<LocalApprovalRule, "uid">);
    } else if (editingRule.value && ruleData.uid) {
      await store.updateRule(ruleData.uid, ruleData);
    }
    showModal.value = false;
    pushNotification({
      module: "bytebase",
      style: "SUCCESS",
      title: t("common.updated"),
    });
  } catch {
    // Error handled by store
  }
};
</script>

<style scoped>
.rules-table-header,
.rules-table-row {
  grid-template-columns: 40px 200px 1fr 280px 96px;
}

.rules-row-ghost {
  opacity: 0.5;
  background: #e0f2fe;
}
</style>

// frontend/src/components/CustomApproval/RulesSection.tsx
import {
  closestCenter,
  DndContext,
  type DragEndEvent,
  DragOverlay,
  type DragStartEvent,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
} from "@dnd-kit/core";
import {
  arrayMove,
  SortableContext,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { GripVertical, Pencil, Plus, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import {
  PermissionGuard,
  usePermissionCheck,
} from "@/components/PermissionGuard";
import { Button } from "@/components/ui/button";
import { ColumnResizeHandle } from "@/components/ui/column-resize-handle";
import { useColumnWidths } from "@/hooks/useColumnWidths";
import { pushNotification } from "@/stores";
import { useWorkspaceApprovalSettingStore } from "@/stores/workspaceApprovalSetting";
import type { LocalApprovalRule } from "@/types";
import type { WorkspaceApprovalSetting_Rule_Source } from "@/types/proto-es/v1/setting_service_pb";
import { WorkspaceApprovalSetting_Rule_Source as RuleSource } from "@/types/proto-es/v1/setting_service_pb";
import { RuleEditSheet } from "./RuleEditSheet";
import { approvalSourceText, formatApprovalFlow } from "./utils";

interface RulesSectionProps {
  source: WorkspaceApprovalSetting_Rule_Source;
  rules: LocalApprovalRule[];
  allowAdmin: boolean;
  hasFeature: boolean;
  onShowFeatureModal: () => void;
}

function SortableRow({
  rule,
  index,
  allowAdmin,
  hasFeature,
  gridStyle,
  onEdit,
  onDelete,
  onShowFeatureModal,
}: {
  rule: LocalApprovalRule;
  index: number;
  allowAdmin: boolean;
  hasFeature: boolean;
  gridStyle: React.CSSProperties;
  onEdit: (rule: LocalApprovalRule) => void;
  onDelete: (rule: LocalApprovalRule) => void;
  onShowFeatureModal: () => void;
}) {
  const { t } = useTranslation();
  const [confirmingDelete, setConfirmingDelete] = useState(false);

  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: rule.uid });

  const style = {
    ...gridStyle,
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.5 : undefined,
  };

  const handleEditClick = () => {
    if (!hasFeature) {
      onShowFeatureModal();
      return;
    }
    onEdit(rule);
  };

  const handleDeleteClick = () => {
    if (!hasFeature) {
      onShowFeatureModal();
      return;
    }
    setConfirmingDelete(true);
  };

  const handleConfirmDelete = () => {
    setConfirmingDelete(false);
    onDelete(rule);
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      className={`grid border-b border-gray-100 last:border-b-0 hover:bg-gray-50 ${
        index % 2 === 1 ? "bg-gray-50/50" : ""
      }`}
    >
      <div className="flex items-center justify-center px-2 py-2">
        <GripVertical
          className="h-4 w-4 cursor-grab text-gray-400 active:cursor-grabbing"
          {...attributes}
          {...listeners}
        />
      </div>
      <div className="truncate px-3 py-2" title={rule.title}>
        {rule.title || "-"}
      </div>
      <div className="overflow-hidden text-ellipsis whitespace-nowrap px-3 py-2">
        <code className="font-mono text-sm">{rule.condition || "true"}</code>
      </div>
      <div
        className="overflow-hidden text-ellipsis whitespace-nowrap px-3 py-2"
        title={formatApprovalFlow(rule.flow)}
      >
        {formatApprovalFlow(rule.flow)}
      </div>
      <div className="flex items-center gap-x-1 px-3 py-2">
        {confirmingDelete ? (
          <div className="flex items-center gap-x-1">
            <Button
              variant="destructive"
              size="xs"
              onClick={handleConfirmDelete}
            >
              {t("common.delete")}
            </Button>
            <Button
              appearance="outline"
              size="xs"
              onClick={() => setConfirmingDelete(false)}
            >
              {t("common.cancel")}
            </Button>
          </div>
        ) : (
          <>
            <button
              type="button"
              className="inline-flex h-6 w-6 items-center justify-center rounded-xs hover:bg-gray-200"
              onClick={handleEditClick}
            >
              <Pencil className="h-3 w-3" />
            </button>
            {allowAdmin && (
              <button
                type="button"
                className="inline-flex h-6 w-6 items-center justify-center rounded-xs hover:bg-gray-200"
                onClick={handleDeleteClick}
              >
                <Trash2 className="h-3 w-3" />
              </button>
            )}
          </>
        )}
      </div>
    </div>
  );
}

function RuleRowOverlay({
  rule,
  gridStyle,
}: {
  rule: LocalApprovalRule;
  gridStyle: React.CSSProperties;
}) {
  return (
    <div
      style={gridStyle}
      className="grid border border-gray-200 bg-blue-50 opacity-50"
    >
      <div className="flex items-center justify-center px-2 py-2">
        <GripVertical className="h-4 w-4 text-gray-400" />
      </div>
      <div className="truncate px-3 py-2">{rule.title || "-"}</div>
      <div className="overflow-hidden text-ellipsis whitespace-nowrap px-3 py-2">
        <code className="font-mono text-sm">{rule.condition || "true"}</code>
      </div>
      <div className="overflow-hidden text-ellipsis whitespace-nowrap px-3 py-2">
        {formatApprovalFlow(rule.flow)}
      </div>
      <div className="px-3 py-2" />
    </div>
  );
}

export function RulesSection({
  source,
  rules,
  allowAdmin,
  hasFeature,
  onShowFeatureModal,
}: RulesSectionProps) {
  const { t } = useTranslation();
  const store = useWorkspaceApprovalSettingStore();
  const [canEdit] = usePermissionCheck(["bb.settings.set"]);

  const [localRules, setLocalRules] = useState(rules);
  useEffect(() => setLocalRules(rules), [rules]);

  const [activeId, setActiveId] = useState<string | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [dialogMode, setDialogMode] = useState<"create" | "edit">("create");
  const [editingRule, setEditingRule] = useState<
    LocalApprovalRule | undefined
  >();

  // Only the title and flow columns are resizable; the other three are
  // fixed (40px gripper, flexible content, 140px actions). The shared hook
  // tracks an array of widths positional to its input, so we hand it just
  // the two resizable columns and compose them into the grid template.
  const { widths: resizableWidths, onResizeStart } = useColumnWidths([
    { defaultWidth: 200, minWidth: 80 },
    { defaultWidth: 280, minWidth: 80 },
  ]);
  const [titleWidth, flowWidth] = resizableWidths;

  const gridStyle = useMemo<React.CSSProperties>(
    () => ({
      gridTemplateColumns: `40px ${titleWidth}px minmax(0, 1fr) ${flowWidth}px 140px`,
    }),
    [titleWidth, flowWidth]
  );

  const isFallback = source === RuleSource.SOURCE_UNSPECIFIED;

  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor)
  );

  const handleAddRule = () => {
    if (!hasFeature) {
      onShowFeatureModal();
      return;
    }
    setDialogMode("create");
    setEditingRule(undefined);
    setDialogOpen(true);
  };

  const handleEditRule = (rule: LocalApprovalRule) => {
    setDialogMode("edit");
    setEditingRule(rule);
    setDialogOpen(true);
  };

  const handleDeleteRule = async (rule: LocalApprovalRule) => {
    try {
      await store.deleteRule(rule.uid);
      pushNotification({
        module: "bytebase",
        style: "SUCCESS",
        title: t("common.deleted"),
      });
    } catch {
      // Error handled by store
    }
  };

  const handleDragStart = (event: DragStartEvent) => {
    setActiveId(event.active.id as string);
  };

  const handleDragEnd = async (event: DragEndEvent) => {
    const { active, over } = event;
    setActiveId(null);

    if (!over || active.id === over.id) return;

    const oldIndex = localRules.findIndex((r) => r.uid === active.id);
    const newIndex = localRules.findIndex((r) => r.uid === over.id);

    if (oldIndex === newIndex) return;

    if (!hasFeature) {
      onShowFeatureModal();
      return;
    }

    // Optimistic local reorder
    setLocalRules(arrayMove(localRules, oldIndex, newIndex));

    try {
      await store.reorderRules(source, oldIndex, newIndex);
      pushNotification({
        module: "bytebase",
        style: "SUCCESS",
        title: t("common.updated"),
      });
    } catch {
      // Revert on error
      setLocalRules([...rules]);
    }
  };

  const handleSaveRule = async (
    ruleData: Omit<LocalApprovalRule, "uid"> & { uid?: string }
  ) => {
    try {
      if (dialogMode === "create") {
        await store.addRule(ruleData as Omit<LocalApprovalRule, "uid">);
      } else if (editingRule && ruleData.uid) {
        await store.updateRule(ruleData.uid, ruleData);
      }
      setDialogOpen(false);
      pushNotification({
        module: "bytebase",
        style: "SUCCESS",
        title: t("common.updated"),
      });
    } catch {
      // Error handled by store
    }
  };

  const activeRule = activeId
    ? localRules.find((r) => r.uid === activeId)
    : undefined;

  return (
    <div className="flex flex-col gap-y-2">
      <div className="flex items-center justify-between">
        <div className="text-base font-medium">
          {approvalSourceText(source)}
        </div>
        <PermissionGuard permissions={["bb.settings.set"]}>
          <Button
            appearance="outline"
            disabled={!canEdit}
            onClick={handleAddRule}
          >
            <Plus className="h-4 w-4" />
            {t("common.create")}
          </Button>
        </PermissionGuard>
      </div>

      <div className="rounded-sm border border-gray-200 text-sm">
        {/* Table Header */}
        <div
          style={gridStyle}
          className="grid border-b border-gray-200 bg-gray-50 font-medium text-gray-600"
        >
          <div className="px-2 py-2" />
          <div className="relative px-3 py-2">
            {t("common.title")}
            <ColumnResizeHandle onMouseDown={(e) => onResizeStart(0, e)} />
          </div>
          <div className="px-3 py-2">{t("cel.condition.self")}</div>
          <div className="relative px-3 py-2">
            {t("custom-approval.approval-flow.self")}
            <ColumnResizeHandle onMouseDown={(e) => onResizeStart(1, e)} />
          </div>
          <div className="px-3 py-2">{t("common.operations")}</div>
        </div>

        {/* Draggable Body */}
        <DndContext
          sensors={sensors}
          collisionDetection={closestCenter}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
        >
          <SortableContext
            items={localRules.map((r) => r.uid)}
            strategy={verticalListSortingStrategy}
          >
            {localRules.map((rule, index) => (
              <SortableRow
                key={rule.uid}
                rule={rule}
                index={index}
                allowAdmin={allowAdmin}
                hasFeature={hasFeature}
                gridStyle={gridStyle}
                onEdit={handleEditRule}
                onDelete={handleDeleteRule}
                onShowFeatureModal={onShowFeatureModal}
              />
            ))}
          </SortableContext>
          <DragOverlay>
            {activeRule ? (
              <RuleRowOverlay rule={activeRule} gridStyle={gridStyle} />
            ) : null}
          </DragOverlay>
        </DndContext>

        {/* Empty State */}
        {localRules.length === 0 && (
          <div className="px-3 py-4 text-center text-gray-400">
            {t("common.no-data")}
          </div>
        )}
      </div>

      <RuleEditSheet
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        mode={dialogMode}
        source={source}
        rule={editingRule}
        isFallback={isFallback}
        allowAdmin={allowAdmin}
        hasFeature={hasFeature}
        onShowFeatureModal={onShowFeatureModal}
        onSave={handleSaveRule}
      />
    </div>
  );
}
