// frontend/src/react/components/sql-editor/Panels/FunctionsPanel/FunctionsTable.tsx
import { useEffect, useMemo, useRef } from "react";
import { useTranslation } from "react-i18next";
import { HighlightLabelText } from "@/react/components/HighlightLabelText";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/react/components/ui/table";
import type {
  DatabaseMetadata,
  FunctionMetadata,
  SchemaMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { keyWithPosition } from "@/views/sql-editor/EditorCommon/utils";
import { useViewStateNav } from "../common/useViewStateNav";

interface FunctionsTableProps {
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  funcs: FunctionMetadata[];
  keyword?: string;
  onSelect: (selected: {
    database: DatabaseMetadata;
    schema: SchemaMetadata;
    func: FunctionMetadata;
    position: number;
  }) => void;
}

export function FunctionsTable({
  database,
  schema,
  funcs,
  keyword,
  onSelect,
}: FunctionsTableProps) {
  const { t } = useTranslation();
  const { detail } = useViewStateNav();
  const containerRef = useRef<HTMLDivElement>(null);

  const rows = useMemo(() => {
    const all = funcs.map((func, position) => ({ func, position }));
    const trimmed = keyword?.trim().toLowerCase();
    if (!trimmed) return all;
    return all.filter(({ func }) => func.name.toLowerCase().includes(trimmed));
  }, [funcs, keyword]);

  const selectedKey = detail?.func;

  useEffect(() => {
    if (!selectedKey) return;
    const el = containerRef.current?.querySelector<HTMLElement>(
      `[data-key="${CSS.escape(selectedKey)}"]`
    );
    el?.scrollIntoView({ block: "nearest" });
  }, [selectedKey]);

  return (
    <div ref={containerRef} className="w-full h-full overflow-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{t("schema-editor.database.name")}</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {rows.map(({ func, position }) => {
            const rowKey = keyWithPosition(func.name, position);
            return (
              <TableRow
                key={rowKey}
                data-key={rowKey}
                className="cursor-pointer"
                data-state={selectedKey === rowKey ? "selected" : undefined}
                onClick={() => onSelect({ database, schema, func, position })}
              >
                <TableCell className="truncate">
                  <HighlightLabelText text={func.name} keyword={keyword} />
                </TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
    </div>
  );
}

// frontend/src/views/sql-editor/EditorPanel/Panels/FunctionsPanel/FunctionsTable.vue
<template>
  <div ref="containerElRef" class="w-full h-full px-2 py-2 overflow-x-auto">
    <NDataTable
      v-bind="$attrs"
      ref="dataTableRef"
      size="small"
      :row-key="({ func, position }) => keyWithPosition(func.name, position)"
      :columns="columns"
      :data="layoutReady ? filteredFuncs : []"
      :row-props="rowProps"
      :max-height="tableBodyHeight"
      :virtual-scroll="true"
      :striped="true"
      :bordered="true"
      :bottom-bordered="true"
      row-class-name="cursor-pointer"
    />
  </div>
</template>

<script setup lang="tsx">
import { NDataTable, type DataTableColumn } from "naive-ui";
import { computed, h, watch } from "vue";
import { useI18n } from "vue-i18n";
import type { ComposedDatabase } from "@/types";
import type {
  DatabaseMetadata,
  FunctionMetadata,
  SchemaMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { getHighlightHTMLByRegExp, useAutoHeightDataTable } from "@/utils";
import { keyWithPosition } from "@/views/sql-editor/EditorCommon";
import { useCurrentTabViewStateContext } from "../../context/viewState";

type FunctionWithPosition = { func: FunctionMetadata; position: number };

const props = defineProps<{
  db: ComposedDatabase;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  funcs: FunctionMetadata[];
  keyword?: string;
  maxHeight?: number;
}>();

const emit = defineEmits<{
  (
    event: "click",
    metadata: {
      database: DatabaseMetadata;
      schema: SchemaMetadata;
      func: FunctionMetadata;
      position: number;
    }
  ): void;
}>();

const { t } = useI18n();
const { viewState } = useCurrentTabViewStateContext();

const funcsWithPosition = computed(() => {
  return props.funcs.map<FunctionWithPosition>((func, position) => ({
    func,
    position,
  }));
});

const filteredFuncs = computed(() => {
  const keyword = props.keyword?.trim().toLowerCase();
  if (keyword) {
    return funcsWithPosition.value.filter(({ func }) =>
      func.name.toLowerCase().includes(keyword)
    );
  }
  return funcsWithPosition.value;
});

const {
  dataTableRef,
  containerElRef,
  tableBodyHeight,
  layoutReady,
  virtualListRef,
} = useAutoHeightDataTable(
  filteredFuncs,
  computed(() => ({
    maxHeight: props.maxHeight ? props.maxHeight : null,
  }))
);

const columns = computed(() => {
  const columns: (DataTableColumn<FunctionWithPosition> & {
    hide?: boolean;
  })[] = [
    {
      key: "name",
      title: t("schema-editor.database.name"),
      resizable: true,
      className: "truncate",
      render: ({ func }) => {
        return h("span", {
          innerHTML: getHighlightHTMLByRegExp(func.name, props.keyword ?? ""),
        });
      },
    },
  ];
  return columns;
});

const rowProps = ({ func, position }: FunctionWithPosition) => {
  return {
    onClick: () => {
      emit("click", {
        database: props.database,
        schema: props.schema,
        func,
        position,
      });
    },
  };
};

watch(
  [() => viewState.value?.detail.func, virtualListRef],
  ([func, vl]) => {
    if (func && vl) {
      vl.scrollTo({ key: func });
    }
  },
  { immediate: true }
);
</script>

<style lang="postcss" scoped>
:deep(.n-data-table-th .n-data-table-resize-button::after) {
  @apply bg-control-bg h-2/3;
}
:deep(.n-data-table-td.input-cell) {
  @apply pl-0.5 pr-1 py-0;
}
</style>
