// frontend/src/react/components/SchemaDiagram/ER/TableNode.tsx
import { Diamond, Key, Pencil } from "lucide-react";
import { useCallback, useMemo } from "react";
import { hashCode } from "@/bbkit/BBUtil";
import { cn } from "@/react/lib/utils";
import type {
  ColumnMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { useGeometry, useSchemaDiagramContext } from "../common/context";
import { FocusButton } from "../common/FocusButton";
import { isIndex, isPrimaryKey } from "../common/schema";
import { isFocusedForeignTable } from "./libs/isFocusedFKTable";

interface TableNodeProps {
  schema: SchemaMetadata;
  table: TableMetadata;
}

const COLOR_LIST = [
  "#64748B",
  "#EF4444",
  "#F97316",
  "#EAB308",
  "#84CC16",
  "#22C55E",
  "#10B981",
  "#06B6D4",
  "#0EA5E9",
  "#3B82F6",
  "#6366F1",
  "#8B5CF6",
  "#A855F7",
  "#D946EF",
  "#EC4899",
  "#F43F5E",
];

/**
 * React port of `ER/TableNode.vue`. One table card with title bar, FK
 * focus button, optional edit pencil, and a column list with PK / index
 * glyphs and edit-on-click affordances when `editable` is on.
 */
export function TableNode({ schema, table }: TableNodeProps) {
  const ctx = useSchemaDiagramContext();
  const {
    dummy,
    editable,
    focusedTables,
    foreignKeys,
    idOfTable,
    rectOfTable,
    schemaStatus,
    tableStatus,
    columnStatus,
    panning,
    events,
  } = ctx;

  const tableColor = useMemo(() => {
    const index = (hashCode(table.name) & 0xfffffff) % COLOR_LIST.length;
    return COLOR_LIST[index];
  }, [table.name]);

  const isTableDropped = useMemo(
    () =>
      schemaStatus(schema) === "dropped" || tableStatus(table) === "dropped",
    [schema, table, schemaStatus, tableStatus]
  );

  const isTableCreated = useMemo(
    () =>
      schemaStatus(schema) === "created" || tableStatus(table) === "created",
    [schema, table, schemaStatus, tableStatus]
  );

  const isTableChanged = useMemo(
    () => tableStatus(table) === "changed",
    [table, tableStatus]
  );

  const tableStatusText = isTableCreated
    ? "Created"
    : isTableDropped
      ? "Dropped"
      : isTableChanged
        ? "Changed"
        : "";

  const tableClasses = useMemo(() => {
    if (focusedTables.size === 0) return "";
    if (focusedTables.has(table)) return "opacity-100";
    if (isFocusedForeignTable(table, focusedTables, foreignKeys)) {
      return "opacity-100";
    }
    return "opacity-20 hover:opacity-100";
  }, [table, focusedTables, foreignKeys]);

  const columnClasses = useCallback(
    (column: ColumnMetadata) => {
      const classes: string[] = [];
      if (editable) classes.push("cursor-pointer");
      const status = columnStatus(column);
      if (status === "changed") classes.push("text-yellow-700 bg-yellow-50");
      else if (status === "created") classes.push("text-green-700 bg-green-50");
      else if (status === "dropped")
        classes.push("text-red-700 bg-red-50 line-through");
      return classes.join(" ");
    },
    [editable, columnStatus]
  );

  const handleClickColumn = useCallback(
    (column: ColumnMetadata, target: "name" | "type") => {
      if (!editable) return;
      if (panning) return;
      void events.emit("edit-column", { schema, table, column, target });
    },
    [editable, panning, events, schema, table]
  );

  const id = idOfTable(table);
  const rect = rectOfTable(table);

  // Register the rect so the canvas's fit-view bbox includes this table.
  useGeometry(rect);

  return (
    <div
      className={cn(
        "absolute overflow-hidden rounded-md shadow-lg border-b border-control-border bg-background w-[16rem] divide-y divide-control-border z-10 transition-opacity",
        tableClasses
      )}
      data-bb-node-type="table"
      data-bb-node-id={dummy ? `dummy-${id}` : id}
      data-bb-status={tableStatus(table)}
      style={{ left: `${rect.x}px`, top: `${rect.y}px` }}
    >
      <h3
        className={cn(
          "group font-medium leading-6 text-white px-2 py-2 rounded-t-md gap-x-1 relative text-center whitespace-pre-wrap break-words"
        )}
        style={{ backgroundColor: tableColor }}
      >
        <FocusButton
          table={table}
          setCenter={false}
          className="invisible group-hover:visible !absolute top-[50%] -mt-[9px] left-1 text-control group-hover:!bg-white/70 group-hover:!text-control"
          focusedClass="!text-white"
        />

        {schema.name !== "" && (
          <>
            <span className={cn(isTableDropped && "line-through")}>
              {schema.name}
            </span>
            <span>.</span>
          </>
        )}
        <span className={cn(isTableDropped && "line-through")}>
          {table.name}
        </span>
        {tableStatusText && (
          <span className="ml-1 text-sm">({tableStatusText})</span>
        )}

        {editable && (
          <button
            type="button"
            className="invisible group-hover:visible absolute top-[50%] -mt-[9px] right-1 text-control bg-white/70 hover:bg-control-bg p-0.5 rounded-sm"
            onClick={() => events.emit("edit-table", { schema, table })}
          >
            <Pencil className="size-4" />
          </button>
        )}
      </h3>

      <table className="w-full text-sm table-fixed">
        <tbody>
          {table.columns.map((column, i) => (
            <tr
              key={i}
              data-bb-column-name={dummy ? `dummy-${column.name}` : column.name}
              data-bb-status={columnStatus(column)}
              className={columnClasses(column)}
            >
              <td className="w-5 py-1.5 relative">
                {isPrimaryKey(table, column) ? (
                  <Key className="size-3 mx-auto text-warning" />
                ) : isIndex(table, column) ? (
                  <Diamond className="size-3 mx-auto text-control-light" />
                ) : null}
              </td>
              <td className="w-auto text-xs py-1.5">
                <div
                  className={cn(
                    "whitespace-pre-wrap break-words pr-1.5",
                    editable && "hover:!text-accent"
                  )}
                  onClick={() => handleClickColumn(column, "name")}
                >
                  {column.name}
                  {columnStatus(column) !== "normal" && (
                    <span className="inline-block rounded-full ml-0.5 h-1.5 w-1.5 bg-accent opacity-75 -translate-y-px" />
                  )}
                </div>
              </td>
              <td className="w-24 text-xs text-control-light py-1.5 text-right">
                <div
                  className={cn(
                    "truncate pr-1.5",
                    editable && "hover:!text-accent"
                  )}
                  onClick={() => handleClickColumn(column, "type")}
                >
                  {column.type}
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// frontend/src/components/SchemaDiagram/ER/TableNode.vue
<template>
  <div
    class="absolute overflow-hidden rounded-md shadow-lg border-b border-gray-200 bg-white w-[16rem] divide-y z-[10] transition-opacity"
    :class="tableClasses"
    bb-node-type="table"
    :bb-node-id="dummy ? `dummy-${idOfTable(table)}` : idOfTable(table)"
    :bb-status="tableStatus(table)"
    :style="{
      left: `${rect.x}px`,
      top: `${rect.y}px`,
    }"
  >
    <h3
      class="group font-medium leading-6 text-white px-2 py-2 rounded-t-md gap-x-1 relative text-center whitespace-pre-wrap break-words"
      :style="{
        'background-color': tableColor,
      }"
    >
      <FocusButton
        :table="table"
        :set-center="false"
        class="invisible group-hover:visible !absolute top-[50%] -mt-[9px] left-1 text-main group-hover:bg-white/70 group-hover:!text-main"
        focused-class="!text-white"
      />

      <template v-if="schema.name !== ''">
        <span :class="[isTableDropped && 'line-through']">
          {{ schema.name }}
        </span>
        <span>.</span>
      </template>
      <span :class="[isTableDropped && 'line-through']">{{ table.name }}</span>
      <span v-if="tableStatusText" class="ml-1 text-sm">
        ({{ tableStatusText }})
      </span>

      <button
        v-if="editable"
        class="invisible group-hover:visible absolute top-[50%] -mt-[9px] right-1 text-main bg-white/70 hover:bg-gray-200 p-0.5 rounded"
        @click="events.emit('edit-table', { schema, table })"
      >
        <heroicons-outline:pencil class="w-4 h-4" />
      </button>
    </h3>

    <table class="w-full text-sm table-fixed">
      <tr
        v-for="(column, i) in table.columns"
        :key="i"
        :bb-column-name="dummy ? `dummy-${column.name}` : column.name"
        :bb-status="columnStatus(column)"
        :class="columnClasses(column)"
      >
        <td class="w-5 py-1.5 relative">
          <heroicons-outline:key
            v-if="isPrimaryKey(table, column)"
            class="w-3 h-3 mx-auto text-amber-500"
          />
          <tabler:diamonds
            v-else-if="isIndex(table, column)"
            class="w-3 h-3 mx-auto text-gray-500"
          />
        </td>
        <td class="w-auto text-xs py-1.5">
          <div
            class="whitespace-pre-wrap break-words pr-1.5"
            :class="editable && 'hover:!text-accent'"
            @click="handleClickColumn(column, 'name')"
          >
            {{ column.name }}
            <span
              v-if="columnStatus(column) !== 'normal'"
              class="inline-block rounded-full ml-0.5 h-1.5 w-1.5 bg-accent opacity-75 translate-y-[-1px]"
            ></span>
          </div>
        </td>
        <td class="w-[6rem] text-xs text-gray-400 py-1.5 text-right">
          <div
            class="truncate pr-1.5"
            :class="editable && 'hover:!text-accent'"
            @click="handleClickColumn(column, 'type')"
          >
            {{ column.type }}
          </div>
        </td>
      </tr>
    </table>
  </div>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import { hashCode } from "@/bbkit/BBUtil";
import {
  ColumnMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto/store/database";
import type { VueClass } from "@/utils";
import {
  useSchemaDiagramContext,
  isPrimaryKey,
  isIndex,
  useGeometry,
  FocusButton,
} from "../common";
import { isFocusedForeignTable } from "./libs/isFocusedFKTable";

const props = withDefaults(
  defineProps<{
    schema: SchemaMetadata;
    table: TableMetadata;
  }>(),
  {}
);

const {
  dummy,
  editable,
  focusedTables,
  foreignKeys,
  idOfTable,
  rectOfTable,
  schemaStatus,
  tableStatus,
  columnStatus,
  panning,
  events,
} = useSchemaDiagramContext();

const COLOR_LIST = [
  "#64748B",
  "#EF4444",
  "#F97316",
  "#EAB308",
  "#84CC16",
  "#22C55E",
  "#10B981",
  "#06B6D4",
  "#0EA5E9",
  "#3B82F6",
  "#6366F1",
  "#8B5CF6",
  "#A855F7",
  "#D946EF",
  "#EC4899",
  "#F43F5E",
];

const tableColor = computed(() => {
  const index = (hashCode(props.table.name) & 0xfffffff) % COLOR_LIST.length;
  return COLOR_LIST[index];
});

const isTableDropped = computed(() => {
  return (
    schemaStatus(props.schema) === "dropped" ||
    tableStatus(props.table) === "dropped"
  );
});

const isTableCreated = computed(() => {
  return (
    schemaStatus(props.schema) === "created" ||
    tableStatus(props.table) === "created"
  );
});

const isTableChanged = computed(() => {
  return tableStatus(props.table) === "changed";
});

const tableClasses = computed((): VueClass => {
  const classes: string[] = [];
  if (focusedTables.value.size > 0) {
    if (focusedTables.value.has(props.table)) {
      classes.push("opacity-100");
    } else if (
      isFocusedForeignTable(props.table, focusedTables.value, foreignKeys.value)
    ) {
      classes.push("opacity-100");
    } else {
      classes.push("opacity-20 hover:opacity-100");
    }
  }
  return classes;
});

const columnClasses = (column: ColumnMetadata): VueClass => {
  const classes: string[] = [];
  if (editable.value) {
    classes.push("cursor-pointer");
  }

  const status = columnStatus(column);
  if (status === "changed") {
    classes.push("text-yellow-700", "bg-yellow-50");
  } else if (status === "created") {
    classes.push("text-green-700", "bg-green-50");
  } else if (status === "dropped") {
    classes.push("text-red-700", "bg-red-50", "line-through");
  }

  return classes;
};

const handleClickColumn = (column: ColumnMetadata, target: "name" | "type") => {
  if (!editable.value) return;
  if (panning.value) return;
  events.emit("edit-column", {
    schema: props.schema,
    table: props.table,
    column,
    target,
  });
};

const tableStatusText = computed(() => {
  if (isTableCreated.value) return "Created";
  if (isTableDropped.value) return "Dropped";
  if (isTableChanged.value) return "Changed";
  return "";
});

const rect = computed(() => rectOfTable(props.table));

useGeometry(rect);
</script>
