// frontend/src/react/components/sql-editor/Panels/common/DefinitionViewer.tsx
import type * as monaco from "monaco-editor";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { MonacoModule } from "@/components/MonacoEditor";
import formatSQL from "@/components/MonacoEditor/sqlFormatter";
import { aiContextEvents } from "@/plugins/ai/logic";
import * as promptUtils from "@/plugins/ai/logic/prompt";
import type { ChatAction } from "@/plugins/ai/types";
import { ReadonlyMonaco } from "@/react/components/monaco/ReadonlyMonaco";
import { useSQLEditorUIStore } from "@/store";
import { dialectOfEngineV1 } from "@/types";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import { getInstanceResource, nextAnimationFrame } from "@/utils";
import { useAIActions } from "./useAIActions";

const AI_ACTIONS: readonly ChatAction[] = ["explain-code"];

interface DefinitionViewerProps {
  db: Database;
  code: string;
  format?: boolean;
  onSelectContent?: (content: string) => void;
}

/**
 * React port of `frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/DefinitionViewer.vue`.
 * Bare Monaco read-only viewer; `format` is owned by the parent (the
 * ViewsPanel detail header has the toggle). Sets `uiStore.isShowingCode`
 * on mount so `Panels.vue` renders the AIChatToSQL pane next to it.
 */
export function DefinitionViewer({
  db,
  code,
  format,
  onSelectContent,
}: DefinitionViewerProps) {
  const uiStore = useSQLEditorUIStore();
  const engine = useMemo(() => getInstanceResource(db).engine, [db]);

  const [formatted, setFormatted] = useState<{
    data: string;
    error: Error | null;
  }>({ data: code, error: null });

  useEffect(() => {
    let cancelled = false;
    formatSQL(code, dialectOfEngineV1(engine)).then((result) => {
      if (cancelled) return;
      setFormatted(result);
    });
    return () => {
      cancelled = true;
    };
  }, [code, engine]);

  const content = format && !formatted.error ? formatted.data : code;

  const [selectedStatement, setSelectedStatement] = useState("");
  const [monacoModule, setMonacoModule] = useState<MonacoModule | null>(null);
  const [editor, setEditor] =
    useState<monaco.editor.IStandaloneCodeEditor | null>(null);

  const handleReady = useCallback(
    (m: MonacoModule, e: monaco.editor.IStandaloneCodeEditor) => {
      setMonacoModule(m);
      setEditor(e);
    },
    []
  );

  useEffect(() => {
    uiStore.isShowingCode = true;
    return () => {
      uiStore.isShowingCode = false;
    };
  }, [uiStore]);

  const handleAIAction = useCallback(
    (action: ChatAction) => {
      const newChat = !uiStore.showAIPanel;
      uiStore.showAIPanel = true;
      if (action !== "explain-code") return;
      const statement = selectedStatement || content;
      void nextAnimationFrame().then(() => {
        void aiContextEvents.emit("send-chat", {
          content: promptUtils.explainCode(statement, engine),
          newChat,
        });
      });
    },
    [uiStore, selectedStatement, content, engine]
  );

  useAIActions({
    monaco: monacoModule,
    editor,
    actions: AI_ACTIONS,
    callback: handleAIAction,
  });

  useEffect(() => {
    if (!editor) return;
    const sub = editor.onDidChangeCursorSelection(() => {
      const selection = editor.getSelection();
      const model = editor.getModel();
      if (!selection || !model) {
        setSelectedStatement("");
        onSelectContent?.("");
        return;
      }
      const selected = model.getValueInRange(selection);
      setSelectedStatement(selected);
      onSelectContent?.(selected);
    });
    return () => sub.dispose();
  }, [editor, onSelectContent]);

  return (
    <ReadonlyMonaco
      content={content}
      className="w-full h-full relative"
      options={{ automaticLayout: true }}
      onReady={handleReady}
    />
  );
}

// frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/DefinitionViewer.vue
<template>
  <NSplit
    :disabled="!showAIPanel"
    :size="editorPanelSize.size"
    :min="editorPanelSize.min"
    :max="editorPanelSize.max"
    :resize-trigger-size="3"
    @update:size="handleEditorPanelResize"
  >
    <template #1>
      <MonacoEditor
        :content="content"
        :readonly="true"
        class="w-full h-full relative"
        @select-content="handleSelectContent"
        @ready="handleEditorReady"
      />
    </template>
    <template #2>
      <div class="h-full overflow-hidden flex flex-col">
        <Suspense>
          <AIChatToSQL key="ai-chat-to-sql" />
          <template #fallback>
            <div
              class="w-full h-full grow flex flex-col items-center justify-center"
            >
              <BBSpin />
            </div>
          </template>
        </Suspense>
      </div>
    </template>
  </NSplit>
</template>

<script setup lang="ts">
import { computedAsync } from "@vueuse/core";
import { NSplit } from "naive-ui";
import { computed, ref } from "vue";
import { BBSpin } from "@/bbkit";
import {
  type IStandaloneCodeEditor,
  MonacoEditor,
  type MonacoModule,
} from "@/components/MonacoEditor";
import formatSQL from "@/components/MonacoEditor/sqlFormatter";
import { AIChatToSQL, useAIActions } from "@/plugins/ai";
import { useAIContext } from "@/plugins/ai/logic";
import * as promptUtils from "@/plugins/ai/logic/prompt";
import { dialectOfEngineV1 } from "@/types";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import { getInstanceResource, nextAnimationFrame } from "@/utils";
import { useSQLEditorContext } from "@/views/sql-editor/context";

const props = defineProps<{
  db: Database;
  code: string;
  format?: boolean;
}>();

const emit = defineEmits<{
  (event: "select-content", content: string): void;
  (event: "back"): void;
}>();

const { showAIPanel, editorPanelSize, handleEditorPanelResize } =
  useSQLEditorContext();
const instanceEngine = computed(() => getInstanceResource(props.db).engine);
const AIContext = useAIContext();
const selectedStatement = ref("");

const formatted = computedAsync(
  async () => {
    const sql = props.code;
    try {
      const result = await formatSQL(
        sql,
        dialectOfEngineV1(instanceEngine.value)
      );
      return result;
    } catch (err) {
      return {
        error: err,
        data: sql,
      };
    }
  },
  {
    error: null,
    data: props.code,
  }
);

const content = computed(() => {
  return props.format && !formatted.value.error
    ? formatted.value.data
    : props.code;
});

const handleSelectContent = (selected: string) => {
  selectedStatement.value = selected;
  emit("select-content", selected);
};

const handleEditorReady = (
  monaco: MonacoModule,
  editor: IStandaloneCodeEditor
) => {
  useAIActions(monaco, editor, AIContext, {
    actions: ["explain-code"],
    callback: async (action) => {
      // start new chat if AI panel is not open
      // continue current chat otherwise
      const newChat = !showAIPanel.value;

      showAIPanel.value = true;
      if (action !== "explain-code") return;
      const statement = selectedStatement.value || content.value;

      await nextAnimationFrame();
      AIContext.events.emit("send-chat", {
        content: promptUtils.explainCode(
          statement,
          getInstanceResource(props.db).engine
        ),
        newChat,
      });
    },
  });
};
</script>
