// frontend/src/modules/sql-editor/components/Panels/PackagesPanel/PackagesPanel.tsx
import { ChevronLeft, Package } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { useAppDatabaseMetadata } from "@/hooks/useAppDatabaseMetadata";
import { extractKeyWithPosition, keyWithPosition } from "@/lib/keyWithPosition";
import { useConnectionOfCurrentSQLEditorTab } from "@/modules/sql-editor/hooks/useSQLEditorState";
import { CodeViewer } from "../common/CodeViewer";
import { PanelSearchBox } from "../common/PanelSearchBox";
import { useViewStateNav } from "../common/useViewStateNav";
import { PackagesTable } from "./PackagesTable";

export function PackagesPanel() {
  const { database } = useConnectionOfCurrentSQLEditorTab();
  const databaseName = database.name;
  const db = database;
  const databaseMetadata = useAppDatabaseMetadata(databaseName ?? "", {
    autoFetch: false,
  });

  const {
    schema: schemaName,
    detail,
    setDetail,
    clearDetail,
  } = useViewStateNav();

  const [keyword, setKeyword] = useState("");

  const schema = databaseMetadata.schemas.find((s) => s.name === schemaName);
  const [packName, packPosition] = extractKeyWithPosition(
    detail?.package ?? ""
  );
  const pack = schema?.packages.find(
    (p, i) => p.name === packName && i === packPosition
  );

  if (!db || !schema) return null;

  if (pack) {
    return (
      <CodeViewer
        db={db}
        title={pack.name}
        code={pack.definition}
        onBack={() => clearDetail()}
        titlePrefix={
          <Button
            appearance="secondary"
            className="h-8 px-1 text-sm"
            onClick={() => clearDetail()}
          >
            <ChevronLeft className="size-5" />
            <Package className="size-4 text-control" />
            <span className="truncate">{pack.name}</span>
          </Button>
        }
      />
    );
  }

  return (
    <div className="h-full overflow-hidden flex flex-col">
      <div className="w-full h-11 py-2 px-2 border-b border-block-border flex flex-row gap-x-2 justify-end items-center">
        <PanelSearchBox value={keyword} onChange={setKeyword} />
      </div>
      <div className="flex-1 min-h-0">
        <PackagesTable
          database={databaseMetadata}
          schema={schema}
          packages={schema.packages}
          keyword={keyword}
          onSelect={({ pack: target, position }) =>
            setDetail({ package: keyWithPosition(target.name, position) })
          }
        />
      </div>
    </div>
  );
}

// frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesPanel.vue
<template>
  <div v-if="metadata?.schema" class="h-full overflow-hidden flex flex-col">
    <div
      v-show="!metadata.package"
      class="w-full h-[44px] py-2 px-2 border-b flex flex-row gap-x-2 justify-end items-center"
    >
      <SearchBox
        v-model:value="state.keyword"
        size="small"
        style="width: 10rem"
      />
    </div>
    <PackagesTable
      v-show="!metadata.package"
      :db="database"
      :database="metadata.database"
      :schema="metadata.schema"
      :packages="metadata.schema.packages"
      :keyword="state.keyword"
      @click="select"
    />

    <template v-if="metadata.package">
      <CodeViewer
        :db="database"
        :title="metadata.package.name"
        :code="metadata.package.definition"
        @back="deselect"
      >
        <template #title-icon>
          <PackageIcon class="w-4 h-4 text-main" />
        </template>
      </CodeViewer>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive } from "vue";
import { PackageIcon } from "@/components/Icon";
import { SearchBox } from "@/components/v2";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
} from "@/store";
import {
  DatabaseMetadata,
  PackageMetadata,
  SchemaMetadata,
} from "@/types/proto/v1/database_service";
import {
  extractKeyWithPosition,
  keyWithPosition,
} from "@/views/sql-editor/EditorCommon";
import { useCurrentTabViewStateContext } from "../../context";
import { CodeViewer } from "../common";
import PackagesTable from "./PackagesTable.vue";

const { database } = useConnectionOfCurrentSQLEditorTab();
const { viewState, updateViewState } = useCurrentTabViewStateContext();
const databaseMetadata = computed(() => {
  return useDBSchemaV1Store().getDatabaseMetadata(database.value.name);
});
const state = reactive({
  keyword: "",
});

const metadata = computed(() => {
  const database = databaseMetadata.value;
  const schema = database.schemas.find(
    (s) => s.name === viewState.value?.schema
  );
  const [name, position] = extractKeyWithPosition(
    viewState.value?.detail?.package ?? ""
  );
  const pack = schema?.packages.find(
    (p, i) => p.name === name && i === position
  );
  return { database, schema, package: pack };
});

const select = (selected: {
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  package: PackageMetadata;
  position: number;
}) => {
  updateViewState({
    detail: {
      package: keyWithPosition(selected.package.name, selected.position),
    },
  });
};

const deselect = () => {
  updateViewState({
    detail: {},
  });
};
</script>
