// frontend/src/react/components/SchemaEditorLite/SchemaEditorLite.tsx
import { cloneDeep } from "lodash-es";
import { Loader2 } from "lucide-react";
import {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  Panel,
  Group as PanelGroup,
  Separator as PanelResizeHandle,
} from "react-resizable-panels";
import type { DatabaseMetadata } from "@/types/proto-es/v1/database_service_pb";
import { AsideTree } from "./Aside/AsideTree";
import { SchemaEditorProvider } from "./context";
import { EditorPanel } from "./EditorPanel";
import type {
  RebuildMetadataEditReset,
  SchemaEditorContextValue,
  SchemaEditorHandle,
  SchemaEditorProps,
} from "./types";
import { useAlgorithm } from "./useAlgorithm";
import { useEditStatus } from "./useEditStatus";
import { useScrollStatus } from "./useScrollStatus";
import { useSelection } from "./useSelection";
import { useTabs } from "./useTabs";

export const SchemaEditorLite = forwardRef<
  SchemaEditorHandle,
  SchemaEditorProps
>(function SchemaEditorLite(props, ref) {
  const {
    project,
    readonly = false,
    selectedRolloutObjects,
    targets: targetsProp,
    loading = false,
    hidePreview = false,
    options,
    onSelectedRolloutObjectsChange,
  } = props;

  const targets = useMemo(() => targetsProp ?? [], [targetsProp]);
  const ready = targets.length > 0;
  const combinedLoading = loading || !ready;

  // Tree rebuild trigger — version bumps cause AsideTree to re-derive tree data
  const [, setTreeBuildVersion] = useState(0);
  const rebuildTreeCallbackRef = useRef<
    ((openFirstChild: boolean) => void) | null
  >(null);

  const rebuildTree = useCallback((openFirstChild: boolean) => {
    setTreeBuildVersion((v) => v + 1);
    rebuildTreeCallbackRef.current?.(openFirstChild);
  }, []);

  // Preview refresh trigger — version bumps cause PreviewPane to re-generate DDL
  const [, setPreviewVersion] = useState(0);
  const refreshPreview = useCallback(() => {
    setPreviewVersion((v) => v + 1);
  }, []);

  // Sub-hooks
  const tabs = useTabs();
  const editStatus = useEditStatus();
  const selection = useSelection(
    selectedRolloutObjects,
    onSelectedRolloutObjectsChange
  );
  const scrollStatus = useScrollStatus();

  // Algorithm layer
  const algorithmCallbacks = useMemo(
    () => ({
      clearTabs: tabs.clearTabs,
      rebuildTree,
    }),
    [tabs.clearTabs, rebuildTree]
  );
  const { rebuildMetadataEdit, applyMetadataEdit } = useAlgorithm(
    editStatus,
    algorithmCallbacks
  );

  // Merge metadata callback (replaces Emittery "merge-metadata" event)
  const mergeMetadata = useCallback(
    (metadatas: DatabaseMetadata[]) => {
      for (const metadata of metadatas) {
        const target = targets.find((t) => t.metadata.name === metadata.name);
        if (!target) continue;

        mergeTableMetadataToTarget({
          metadata,
          mergeTo: target.metadata,
        });
        mergeTableMetadataToTarget({
          metadata,
          mergeTo: target.baselineMetadata,
        });
      }
    },
    [targets]
  );

  // Rebuild edit status callback
  const rebuildEditStatusCallback = useCallback(
    (resets: RebuildMetadataEditReset[]) => {
      if (ready) {
        targets.forEach((target) => {
          rebuildMetadataEdit(target, resets);
        });
      }
    },
    [ready, targets, rebuildMetadataEdit]
  );

  // Compose context value
  const contextValue = useMemo<SchemaEditorContextValue>(
    () => ({
      readonly,
      project,
      targets,
      hidePreview,
      options,
      tabs,
      editStatus,
      selection,
      scrollStatus,
      rebuildTree,
      rebuildEditStatus: rebuildEditStatusCallback,
      refreshPreview,
      mergeMetadata,
      applyMetadataEdit,
      rebuildMetadataEdit,
    }),
    [
      readonly,
      project,
      targets,
      hidePreview,
      options,
      tabs,
      editStatus,
      selection,
      scrollStatus,
      rebuildTree,
      rebuildEditStatusCallback,
      refreshPreview,
      mergeMetadata,
      applyMetadataEdit,
      rebuildMetadataEdit,
    ]
  );

  // Imperative handle
  useImperativeHandle(
    ref,
    () => ({
      applyMetadataEdit,
      refreshPreview,
      isDirty: editStatus.isDirty,
    }),
    [applyMetadataEdit, refreshPreview, editStatus.isDirty]
  );

  return (
    <SchemaEditorProvider value={contextValue}>
      <div className="bb-schema-editor relative flex size-full flex-col overflow-hidden rounded-sm border">
        {combinedLoading && (
          <div className="absolute inset-0 z-10 flex items-center justify-center bg-white/60">
            <Loader2 className="size-8 animate-spin text-accent" />
          </div>
        )}
        {ready && (
          <PanelGroup id="schema-editor" orientation="horizontal">
            <Panel defaultSize={25} minSize={15} maxSize={40}>
              <div className="size-full overflow-hidden">
                <AsideTree />
              </div>
            </Panel>
            <PanelResizeHandle className="w-[3px] bg-control-border transition-colors hover:bg-accent data-[resize-handle-active]:bg-accent" />
            <Panel defaultSize={75}>
              <div className="size-full overflow-hidden">
                <EditorPanel />
              </div>
            </Panel>
          </PanelGroup>
        )}
      </div>
    </SchemaEditorProvider>
  );
});

function mergeTableMetadataToTarget({
  metadata,
  mergeTo,
}: {
  metadata: DatabaseMetadata;
  mergeTo: DatabaseMetadata;
}) {
  for (const schema of metadata.schemas) {
    if (schema.tables.length === 0) continue;
    const targetSchema = mergeTo.schemas.find((s) => s.name === schema.name);
    if (!targetSchema) continue;

    for (const table of schema.tables) {
      if (!targetSchema.tables.find((t) => t.name === table.name)) {
        targetSchema.tables.push(cloneDeep(table));
      }
    }
  }
}

// frontend/src/components/SchemaEditorLite/SchemaEditorLite.vue
<template>
  <div
    class="bb-schema-editor w-full h-full flex flex-col border rounded-lg overflow-hidden relative"
    v-bind="$attrs"
  >
    <MaskSpinner v-if="combinedLoading" />
    <Splitpanes
      class="default-theme w-full flex-1 flex flex-row overflow-hidden relative"
    >
      <Pane min-size="15" size="25">
        <Aside
          v-if="ready"
          @update-is-editing="$emit('update-is-editing', $event)"
        />
      </Pane>
      <Pane min-size="60" size="75">
        <Editor v-if="ready" />
      </Pane>
    </Splitpanes>
  </div>
</template>

<script lang="ts" setup>
import { cloneDeep } from "lodash-es";
import { Splitpanes, Pane } from "splitpanes";
import "splitpanes/dist/splitpanes.css";
import { computed, onMounted, toRef } from "vue";
import MaskSpinner from "@/components/misc/MaskSpinner.vue";
import { useEmitteryEventListener } from "@/composables/useEmitteryEventListener";
import { useSettingV1Store } from "@/store";
import type { DatabaseMetadata } from "@/types/proto-es/v1/database_service_pb";
import type { Project } from "@/types/proto-es/v1/project_service_pb";
import { Setting_SettingName } from "@/types/proto-es/v1/setting_service_pb";
import Aside from "./Aside";
import Editor from "./Editor.vue";
import { useAlgorithm } from "./algorithm";
import { provideSchemaEditorContext } from "./context";
import type { EditTarget, RolloutObject } from "./types";

const props = defineProps<{
  project: Project;
  readonly?: boolean;
  selectedRolloutObjects?: RolloutObject[];
  targets?: EditTarget[];
  loading?: boolean;
  hidePreview?: boolean;
}>();

const emit = defineEmits<{
  (event: "update:selected-rollout-objects", objects: RolloutObject[]): void;
  (event: "update-is-editing", objects: RolloutObject[]): void;
}>();

const settingStore = useSettingV1Store();

// Prepare schema template contexts.
onMounted(async () => {
  await settingStore.getOrFetchSettingByName(
    Setting_SettingName.SCHEMA_TEMPLATE
  );
});

const targets = computed(() => {
  return props.targets ?? [];
});

const ready = computed(() => {
  return targets.value.length > 0;
});

const combinedLoading = computed(() => {
  return props.loading || !ready.value;
});

const classificationConfig = computed(() => {
  if (!props.project.dataClassificationConfigId) {
    return;
  }
  return settingStore.getProjectClassification(
    props.project.dataClassificationConfigId
  );
});

const context = provideSchemaEditorContext({
  targets,
  project: toRef(props, "project"),
  classificationConfig,
  readonly: toRef(props, "readonly"),
  selectedRolloutObjects: toRef(props, "selectedRolloutObjects"),
  hidePreview: toRef(props, "hidePreview"),
});
const { rebuildMetadataEdit, applyMetadataEdit } = useAlgorithm(context);

useEmitteryEventListener(context.events, "rebuild-edit-status", (params) => {
  if (ready.value) {
    targets.value.forEach((target) => {
      rebuildMetadataEdit(target, params.resets);
    });
  }
});

useEmitteryEventListener(
  context.events,
  "update:selected-rollout-objects",
  (objects) => {
    emit("update:selected-rollout-objects", objects);
  }
);

useEmitteryEventListener(context.events, "merge-metadata", (metadatas) => {
  for (const metadata of metadatas) {
    const target = props.targets?.find(
      (t) => t.metadata.name === metadata.name
    );
    if (!target) {
      continue;
    }

    mergeTableMetadataToTarge({
      metadata,
      mergeTo: target.metadata,
    });
    mergeTableMetadataToTarge({
      metadata,
      mergeTo: target.baselineMetadata,
    });
  }
});

const mergeTableMetadataToTarge = ({
  metadata,
  mergeTo,
}: {
  metadata: DatabaseMetadata;
  mergeTo: DatabaseMetadata;
}) => {
  for (const schema of metadata.schemas) {
    if (schema.tables.length === 0) {
      continue;
    }
    const targetSchema = mergeTo.schemas.find((s) => s.name === schema.name);
    if (!targetSchema) {
      continue;
    }

    for (const table of schema.tables) {
      if (!targetSchema.tables.find((t) => t.name === table.name)) {
        // eslint-disable-next-line vue/no-mutating-props
        targetSchema.tables.push(cloneDeep(table));
      }
    }
  }
};

const refreshPreview = () => {
  context.events.emit("refresh-preview");
};

defineExpose({
  applyMetadataEdit,
  refreshPreview,
  isDirty: computed(() => context.dirtyPaths.value.size > 0),
});
</script>

<style lang="postcss" scoped>
/* splitpanes pane style */
.bb-schema-editor :deep(.splitpanes.default-theme .splitpanes__pane) {
  @apply bg-transparent !transition-none;
}

.bb-schema-editor :deep(.splitpanes.default-theme .splitpanes__splitter) {
  @apply bg-gray-100 border-none;
}

.bb-schema-editor :deep(.splitpanes.default-theme .splitpanes__splitter:hover) {
  @apply bg-indigo-300;
}

.bb-schema-editor
  :deep(.splitpanes.default-theme .splitpanes__splitter::before),
.bb-schema-editor
  :deep(.splitpanes.default-theme .splitpanes__splitter::after) {
  @apply bg-gray-700 opacity-50 text-white;
}

.bb-schema-editor
  :deep(.splitpanes.default-theme .splitpanes__splitter:hover::before),
.bb-schema-editor
  :deep(.splitpanes.default-theme .splitpanes__splitter:hover::after) {
  @apply bg-white opacity-100;
}
</style>
