// frontend/src/modules/schema-editor/TabsContainer.tsx
import {
  Database as DatabaseIcon,
  FileCode,
  FunctionSquare,
  Table2,
  View,
  X,
} from "lucide-react";
import { useEffect, useRef } from "react";
import { EllipsisText } from "@/components/ui/ellipsis-text";
import { cn } from "@/lib/utils";
import { extractDatabaseResourceName } from "@/utils";
import { useSchemaEditorContext } from "./context";
import type { EditStatus, TabContext } from "./types";

export function TabsContainer() {
  const { tabs, editStatus } = useSchemaEditorContext();
  const { tabList, currentTab, setCurrentTab, closeTab } = tabs;
  const activeTabRef = useRef<HTMLDivElement>(null);

  // Auto-scroll active tab into view
  useEffect(() => {
    if (activeTabRef.current) {
      activeTabRef.current.scrollIntoView({
        behavior: "smooth",
        block: "nearest",
        inline: "nearest",
      });
    }
  }, [currentTab?.id]);

  if (tabList.length === 0) return null;

  return (
    <div className="flex items-stretch border-b border-control-border">
      <div className="flex flex-1 items-stretch overflow-x-auto scrollbar-hide">
        {tabList.map((tab) => {
          const isActive = tab.id === currentTab?.id;
          const status = getTabStatus(tab, editStatus);
          return (
            <div
              key={tab.id}
              ref={isActive ? activeTabRef : undefined}
              className={cn(
                "flex h-9 w-40 shrink-0 cursor-pointer items-center gap-x-2 border-r border-t border-control-border pl-2 pr-1 text-xs transition-colors",
                isActive
                  ? "border-t-[3px] border-t-accent bg-accent/10 pt-0.5 text-accent"
                  : "border-t-transparent pt-1 text-control-light hover:bg-control-bg",
                status === "dropped" && "text-error line-through",
                status === "created" && "text-success",
                status === "updated" && "text-warning"
              )}
              onClick={() => setCurrentTab(tab.id)}
            >
              <TabIcon type={tab.type} />
              <EllipsisText text={getTabName(tab)} className="flex-1" />
              <button
                className="block size-5 shrink-0 rounded-xs p-0.5 text-control-light transition-colors hover:bg-control-bg hover:text-control"
                onClick={(e) => {
                  e.stopPropagation();
                  closeTab(tab.id);
                }}
              >
                <X className="size-full" />
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function TabIcon({ type }: { type: TabContext["type"] }) {
  const cls = "size-3.5 shrink-0";
  switch (type) {
    case "database":
      return <DatabaseIcon className={cls} />;
    case "table":
      return <Table2 className={cls} />;
    case "view":
      return <View className={cls} />;
    case "procedure":
      return <FileCode className={cls} />;
    case "function":
      return <FunctionSquare className={cls} />;
  }
}

function getTabName(tab: TabContext): string {
  const meta = tab.metadata as Record<string, { name: string }>;
  if (tab.type === "database") {
    return extractDatabaseResourceName(meta.database.name).databaseName;
  }
  const schema = meta.schema?.name;
  const objectName =
    meta.table?.name ??
    meta.view?.name ??
    meta.procedure?.name ??
    meta.function?.name ??
    "";
  if (schema) {
    return `${schema}.${objectName}`;
  }
  return objectName;
}

function getTabStatus(
  tab: TabContext,
  editStatus: ReturnType<typeof useSchemaEditorContext>["editStatus"]
): EditStatus {
  if (tab.type === "table") {
    return editStatus.getTableStatus(tab.database, tab.metadata);
  }
  return "normal";
}

// frontend/src/components/SchemaEditorLite/TabsContainer.vue
<template>
  <div class="flex justify-between items-center">
    <div
      class="relative flex flex-1 flex-nowrap overflow-hidden overflow bg-gray-100 select-none shrink-0 rounded-sm"
    >
      <div
        ref="tabsContainerRef"
        class="flex flex-nowrap overflow-x-auto max-x-full hide-scrollbar overscroll-none px-1 gap-x-1"
      >
        <div
          v-for="tab in tabList"
          ref="tabsContainerRef"
          :key="tab.id"
          :class="[
            `relative px-1 py-1 my-1 rounded-sm w-40 flex flex-row justify-between items-center shrink-0 border border-transparent cursor-pointer`,
            `tab-${tab.id}`,
            tab.id === currentTab?.id && 'bg-white border-gray-200 shadow-sm',
          ]"
          @click="handleSelectTab(tab)"
        >
          <div class="flex flex-row justify-start items-center mr-1">
            <span class="mr-1">
              <DatabaseIcon
                v-if="tab.type === 'database'"
                class="w-4 h-4 text-gray-400"
              />
              <TableIcon
                v-if="tab.type === 'table'"
                class="w-4 h-4 text-gray-400"
              />
              <ViewIcon
                v-if="tab.type === 'view'"
                class="w-4 h-4 text-gray-400"
              />
              <ProcedureIcon
                v-if="tab.type === 'procedure'"
                class="w-4 h-4 text-gray-400"
              />
              <FunctionIcon
                v-if="tab.type === 'function'"
                class="w-4 h-4 text-gray-400"
              />
            </span>
            <NEllipsis
              class="text-sm w-20 leading-4"
              :class="getTabComputedClassList(tab)"
              >{{ getTabName(tab) }}</NEllipsis
            >
          </div>
          <span class="tab-close-button shrink-0 flex">
            <XIcon
              class="rounded-sm w-4 h-auto text-gray-400 hover:text-gray-600"
              @click.stop.prevent="handleCloseTab(tab)"
            />
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { XIcon } from "lucide-vue-next";
import { NEllipsis } from "naive-ui";
import scrollIntoView from "scroll-into-view-if-needed";
import { nextTick, ref, watch } from "vue";
import { extractDatabaseResourceName } from "@/utils";
import {
  DatabaseIcon,
  FunctionIcon,
  ProcedureIcon,
  TableIcon,
  ViewIcon,
} from "../Icon";
import { useSchemaEditorContext } from "./context";
import type { TabContext } from "./types";

const { tabList, currentTab, setCurrentTab, closeTab, getTableStatus } =
  useSchemaEditorContext();
const tabsContainerRef = ref();
const searchPattern = ref("");
const originalTabContext = ref<TabContext | undefined>(undefined);

watch(
  () => currentTab.value,
  () => {
    if (currentTab.value !== originalTabContext.value) {
      searchPattern.value = "";
      originalTabContext.value = currentTab.value;
    }

    nextTick(() => {
      const element = tabsContainerRef.value?.querySelector(
        `.tab-${currentTab.value?.id}`
      );
      if (element) {
        scrollIntoView(element, {
          scrollMode: "if-needed",
        });
      }
    });
  }
);

const getTabComputedClassList = (tab: TabContext) => {
  if (tab.type === "table") {
    const { database, metadata } = tab;
    const status = getTableStatus(database, metadata);

    if (status === "dropped") {
      return ["text-red-700", "line-through"];
    }
    if (status === "created") {
      return ["text-green-700"];
    }
    if (status === "updated") {
      return ["text-yellow-700"];
    }
  }
  return [];
};

const getTabName = (tab: TabContext) => {
  if (tab.type === "database") {
    const { database } = tab;
    return extractDatabaseResourceName(database.name).databaseName;
  }
  if (tab.type === "table") {
    const {
      metadata: { schema, table },
    } = tab;
    const parts = [table.name];
    if (schema.name) {
      parts.unshift(schema.name);
    }
    return parts.join(".");
  }
  if (tab.type === "view") {
    const {
      metadata: { schema, view },
    } = tab;
    const parts = [view.name];
    if (schema.name) {
      parts.unshift(schema.name);
    }
    return parts.join(".");
  }
  if (tab.type === "procedure") {
    const {
      metadata: { schema, procedure },
    } = tab;
    const parts = [procedure.name];
    if (schema.name) {
      parts.unshift(schema.name);
    }
    return parts.join(".");
  }
  if (tab.type === "function") {
    const {
      metadata: { schema, function: func },
    } = tab;
    const parts = [func.name];
    if (schema.name) {
      parts.unshift(schema.name);
    }
    return parts.join(".");
  }
  // Should never reach here.
  return "unknown tab";
};

const handleSelectTab = (tab: TabContext) => {
  setCurrentTab(tab.id);
};

const handleCloseTab = (tab: TabContext) => {
  closeTab(tab.id);
};
</script>
