// frontend/src/views/sql-editor/EditorPanel/Panels/common/CodeViewer.vue
<template>
  <div
    class="w-full h-[44px] px-2 py-2 border-b flex flex-row justify-between items-center"
    :class="headerClass"
  >
    <div class="flex justify-start items-center gap-2">
      <slot name="title-prefix">
        <NButton text @click="$emit('back')">
          <ChevronLeftIcon class="w-5 h-5" />
          <div class="flex items-center gap-1">
            <slot name="title-icon" />
            <span>{{ title }}</span>
          </div>
        </NButton>
      </slot>
    </div>
    <div class="flex justify-end items-center gap-2">
      <NCheckbox v-model:checked="format">
        {{ $t("sql-editor.format") }}
      </NCheckbox>
      <OpenAIButton
        size="small"
        :statement="selectedStatement || content"
        :actions="['explain-code']"
      />
    </div>
  </div>

  <Splitpanes
    class="default-theme flex flex-row items-stretch flex-1 w-full overflow-hidden"
    @resized="handleAIPanelResize($event, 1)"
  >
    <Pane class="flex flex-col h-full overflow-hidden">
      <slot name="content-prefix" />
      <MonacoEditor
        :content="content"
        :readonly="true"
        :format-content-options="{
          disabled: format,
          callback: handleFormatContent,
        }"
        class="flex-1 w-full h-full relative"
        @select-content="selectedStatement = $event"
        @ready="handleEditorReady"
      />
    </Pane>
    <Pane
      v-if="showAIPanel"
      :size="AIPanelSize"
      class="overflow-hidden flex flex-col"
    >
      <Suspense>
        <AIChatToSQL key="ai-chat-to-sql" />
        <template #fallback>
          <div
            class="w-full h-full flex-grow flex flex-col items-center justify-center"
          >
            <BBSpin />
          </div>
        </template>
      </Suspense>
    </Pane>
  </Splitpanes>
</template>

<script setup lang="ts">
import { computedAsync, useLocalStorage } from "@vueuse/core";
import { ChevronLeftIcon } from "lucide-vue-next";
import { NButton, NCheckbox } from "naive-ui";
import { Pane, Splitpanes } from "splitpanes";
import { computed, ref } from "vue";
import { BBSpin } from "@/bbkit";
import {
  MonacoEditor,
  type IStandaloneCodeEditor,
  type MonacoModule,
} from "@/components/MonacoEditor";
import formatSQL from "@/components/MonacoEditor/sqlFormatter";
import { AIChatToSQL, useAIActions } from "@/plugins/ai";
import { useAIContext } from "@/plugins/ai/logic";
import * as promptUtils from "@/plugins/ai/logic/prompt";
import type { ComposedDatabase } from "@/types";
import { dialectOfEngineV1 } from "@/types";
import { nextAnimationFrame, type VueClass } from "@/utils";
import { OpenAIButton } from "@/views/sql-editor/EditorCommon";
import { useSQLEditorContext } from "@/views/sql-editor/context";

const props = defineProps<{
  db: ComposedDatabase;
  title: string;
  code: string;
  headerClass?: VueClass;
}>();

defineEmits<{
  (event: "back"): void;
}>();

const { showAIPanel, AIPanelSize, handleAIPanelResize } = useSQLEditorContext();
const AIContext = useAIContext();
const format = useLocalStorage<boolean>(
  "bb.sql-editor.editor-panel.code-viewer.format",
  false
);
const instanceEngine = computed(() => props.db.instanceResource.engine);
const selectedStatement = ref("");

const formatted = computedAsync(
  async () => {
    const sql = props.code;
    try {
      const result = await formatSQL(
        sql,
        dialectOfEngineV1(instanceEngine.value)
      );
      return result;
    } catch (err) {
      return {
        error: err,
        data: sql,
      };
    }
  },
  {
    error: null,
    data: props.code,
  }
);

const content = computed(() => {
  return format.value && !formatted.value.error
    ? formatted.value.data
    : props.code;
});

const handleFormatContent = () => {
  format.value = true;
};

const handleEditorReady = (
  monaco: MonacoModule,
  editor: IStandaloneCodeEditor
) => {
  useAIActions(monaco, editor, AIContext, {
    actions: ["explain-code"],
    callback: async (action) => {
      // start new chat if AI panel is not open
      // continue current chat otherwise
      const newChat = !showAIPanel.value;

      showAIPanel.value = true;
      if (action !== "explain-code") return;

      const statement = selectedStatement.value || content.value;

      await nextAnimationFrame();
      AIContext.events.emit("send-chat", {
        content: promptUtils.explainCode(
          statement,
          props.db.instanceResource.engine
        ),
        newChat,
      });
    },
  });
};
</script>

// frontend/src/react/components/sql-editor/Panels/common/CodeViewer.tsx
import { ChevronLeft } from "lucide-react";
import type * as monaco from "monaco-editor";
import {
  type ReactNode,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from "react";
import { useTranslation } from "react-i18next";
import type { MonacoModule } from "@/components/MonacoEditor";
import formatSQL from "@/components/MonacoEditor/sqlFormatter";
import { aiContextEvents } from "@/plugins/ai/logic";
import * as promptUtils from "@/plugins/ai/logic/prompt";
import type { ChatAction } from "@/plugins/ai/types";
import { ReadonlyMonaco } from "@/react/components/monaco/ReadonlyMonaco";
import { Button } from "@/react/components/ui/button";
import { cn } from "@/react/lib/utils";
import { useSQLEditorUIStore } from "@/store";
import { dialectOfEngineV1 } from "@/types";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import {
  getInstanceResource,
  nextAnimationFrame,
  STORAGE_KEY_SQL_EDITOR_CODE_VIEWER_FORMAT,
} from "@/utils";
import { OpenAIButton } from "../../OpenAIButton";
import { useAIActions } from "./useAIActions";

const AI_ACTIONS: readonly ChatAction[] = ["explain-code"];

interface CodeViewerProps {
  db: Database;
  title: string;
  code: string;
  onBack?: () => void;
  /** Replaces the default back-button + title row in the header. */
  titlePrefix?: ReactNode;
  /** Slot above the Monaco editor; mirrors Vue's `content-prefix`. */
  contentPrefix?: ReactNode;
  headerClassName?: string;
}

/**
 * React port of the Vue `CodeViewer`. Renders header (back button +
 * format toggle + OpenAIButton) and a read-only Monaco editor.
 *
 * Note on AI integration: the AIChatToSQL side pane lives in
 * `Panels.vue` and is gated by `uiStore.showAIPanel && uiStore.isShowingCode`.
 * This component flips `isShowingCode` on mount so the host knows when
 * to render the AI pane next to it. Same parity as the Vue CodeViewer
 * NSplit, just hoisted one level up.
 */
export function CodeViewer({
  db,
  title,
  code,
  onBack,
  titlePrefix,
  contentPrefix,
  headerClassName,
}: CodeViewerProps) {
  const { t } = useTranslation();
  const uiStore = useSQLEditorUIStore();

  const [format, setFormat] = useState<boolean>(() => {
    if (typeof window === "undefined") return false;
    const stored = localStorage.getItem(
      STORAGE_KEY_SQL_EDITOR_CODE_VIEWER_FORMAT
    );
    return stored === "true";
  });

  useEffect(() => {
    localStorage.setItem(
      STORAGE_KEY_SQL_EDITOR_CODE_VIEWER_FORMAT,
      String(format)
    );
  }, [format]);

  const [formatted, setFormatted] = useState<{
    data: string;
    error: Error | null;
  }>({ data: code, error: null });

  const engine = useMemo(() => getInstanceResource(db).engine, [db]);

  useEffect(() => {
    let cancelled = false;
    formatSQL(code, dialectOfEngineV1(engine)).then((result) => {
      if (cancelled) return;
      setFormatted(result);
    });
    return () => {
      cancelled = true;
    };
  }, [code, engine]);

  const content = format && !formatted.error ? formatted.data : code;

  const [selectedStatement, setSelectedStatement] = useState("");
  const [monacoModule, setMonacoModule] = useState<MonacoModule | null>(null);
  const [editor, setEditor] =
    useState<monaco.editor.IStandaloneCodeEditor | null>(null);

  const handleReady = useCallback(
    (m: MonacoModule, e: monaco.editor.IStandaloneCodeEditor) => {
      setMonacoModule(m);
      setEditor(e);
    },
    []
  );

  // Tell Panels.vue to host the AIChatToSQL pane while a code surface is
  // mounted. Cleared on unmount so navigating back to the list view drops
  // the pane (matches Vue CodeViewer's auto-unmount on detail-clear).
  useEffect(() => {
    uiStore.isShowingCode = true;
    return () => {
      uiStore.isShowingCode = false;
    };
  }, [uiStore]);

  const handleAIAction = useCallback(
    (action: ChatAction) => {
      const newChat = !uiStore.showAIPanel;
      uiStore.showAIPanel = true;
      if (action !== "explain-code") return;
      const statement = selectedStatement || content;
      void nextAnimationFrame().then(() => {
        void aiContextEvents.emit("send-chat", {
          content: promptUtils.explainCode(statement, engine),
          newChat,
        });
      });
    },
    [uiStore, selectedStatement, content, engine]
  );

  useAIActions({
    monaco: monacoModule,
    editor,
    actions: AI_ACTIONS,
    callback: handleAIAction,
  });

  useEffect(() => {
    if (!editor) return;
    const sub = editor.onDidChangeCursorSelection(() => {
      const selection = editor.getSelection();
      const model = editor.getModel();
      if (!selection || !model) {
        setSelectedStatement("");
        return;
      }
      setSelectedStatement(model.getValueInRange(selection));
    });
    return () => sub.dispose();
  }, [editor]);

  return (
    <div className="h-full flex flex-col overflow-hidden">
      <div
        className={cn(
          "w-full h-11 px-2 py-2 border-b border-block-border flex flex-row justify-between items-center shrink-0",
          headerClassName
        )}
      >
        <div className="flex justify-start items-center gap-2 min-w-0">
          {titlePrefix ?? (
            <Button
              variant="ghost"
              className="h-8 px-1 text-sm"
              onClick={onBack}
            >
              <ChevronLeft className="size-5" />
              <span className="truncate">{title}</span>
            </Button>
          )}
        </div>
        <div className="flex justify-end items-center gap-x-3">
          <label className="flex items-center gap-x-1 text-sm text-control cursor-pointer select-none">
            <input
              type="checkbox"
              checked={format}
              onChange={(event) => setFormat(event.target.checked)}
              className="accent-accent"
            />
            {t("sql-editor.format")}
          </label>
          <OpenAIButton
            size="sm"
            actions={["explain-code"]}
            statement={selectedStatement || content}
          />
        </div>
      </div>
      <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
        {contentPrefix}
        <ReadonlyMonaco
          content={content}
          className="flex-1 w-full h-full relative"
          options={{ automaticLayout: true }}
          onReady={handleReady}
        />
      </div>
    </div>
  );
}
