// frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/ColumnInfo.vue
<template>
  <div
    class="grid min-w-[14rem] max-w-[18rem] gap-x-2 gap-y-1 break-all"
    style="grid-template-columns: auto 1fr"
  >
    <InfoItem :title="$t('common.name')">
      {{ column.name }}
    </InfoItem>
    <InfoItem :title="$t('common.type')">
      {{ column.type }}
    </InfoItem>
    <InfoItem :title="$t('common.Default')">
      {{ getColumnDefaultValuePlaceholder(column) }}
    </InfoItem>
    <InfoItem :title="$t('database.nullable')">
      {{ column.nullable }}
    </InfoItem>
    <InfoItem v-if="characterSet" :title="$t('db.character-set')">
      {{ characterSet }}
    </InfoItem>
    <InfoItem v-if="collation" :title="$t('db.collation')">
      {{ collation }}
    </InfoItem>
    <InfoItem v-if="column.userComment" :title="$t('database.comment')">
      {{ column.userComment }}
    </InfoItem>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { getColumnDefaultValuePlaceholder } from "@/components/SchemaEditorV1/utils/columnDefaultValue";
import { ComposedDatabase } from "@/types";
import { Engine } from "@/types/proto/v1/common";
import {
  ColumnMetadata,
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto/v1/database_service";
import InfoItem from "./InfoItem.vue";

const props = defineProps<{
  db: ComposedDatabase;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table: TableMetadata;
  column: ColumnMetadata;
}>();

const instanceEngine = computed(() => {
  return props.db.instanceEntity.engine;
});

const characterSet = computed(() => {
  if (
    [Engine.POSTGRES, Engine.CLICKHOUSE, Engine.SNOWFLAKE].includes(
      instanceEngine.value
    )
  ) {
    return props.column.characterSet;
  }
  return "";
});

const collation = computed(() => {
  if ([Engine.CLICKHOUSE, Engine.SNOWFLAKE].includes(instanceEngine.value)) {
    return props.column.collation;
  }
  return "";
});
</script>

// frontend/src/react/components/sql-editor/SchemaPane/HoverPanel/ColumnInfo.tsx
import { create } from "@bufbuild/protobuf";
import { Check, X } from "lucide-react";
import { useTranslation } from "react-i18next";
import { getColumnDefaultValuePlaceholder } from "@/react/components/SchemaEditorLite/core/columnDefaultValue";
import { useAppDatabase } from "@/react/hooks/useAppDatabase";
import { useAppStore } from "@/react/stores/app";
import { Engine } from "@/types/proto-es/v1/common_pb";
import { ColumnMetadataSchema } from "@/types/proto-es/v1/database_service_pb";
import { getInstanceResource } from "@/utils";
import { InfoItem } from "./InfoItem";

type Props = {
  readonly database: string;
  readonly schema?: string;
  readonly table: string;
  readonly column: string;
};

/**
 * Replaces `HoverPanel/ColumnInfo.vue`. Character set is shown only for
 * Postgres / ClickHouse / Snowflake; collation only for ClickHouse /
 * Snowflake (other engines surface these at the table level).
 */
export function ColumnInfo({ database, schema, table, column }: Props) {
  const { t } = useTranslation();
  const databaseEntity = useAppDatabase(database);
  const tableMetadata = useAppStore((s) =>
    s.getTableMetadata({ database, schema, table })
  );

  const columnMetadata =
    tableMetadata.columns.find((col) => col.name === column) ??
    create(ColumnMetadataSchema, {});
  const instanceEngine = getInstanceResource(databaseEntity).engine;

  const characterSet =
    instanceEngine === Engine.POSTGRES ||
    instanceEngine === Engine.CLICKHOUSE ||
    instanceEngine === Engine.SNOWFLAKE
      ? columnMetadata.characterSet
      : "";
  const collation =
    instanceEngine === Engine.CLICKHOUSE || instanceEngine === Engine.SNOWFLAKE
      ? columnMetadata.collation
      : "";

  return (
    <div className="min-w-56 max-w-[18rem] gap-y-1">
      <InfoItem title={t("common.name")}>{columnMetadata.name}</InfoItem>
      <InfoItem title={t("common.type")}>{columnMetadata.type}</InfoItem>
      <InfoItem title={t("common.Default")}>
        {getColumnDefaultValuePlaceholder(columnMetadata)}
      </InfoItem>
      <InfoItem title={t("database.nullable")}>
        <div className="inline-flex items-center justify-end">
          {columnMetadata.nullable ? (
            <Check className="size-4" />
          ) : (
            <X className="size-4" />
          )}
        </div>
      </InfoItem>
      {characterSet ? (
        <InfoItem title={t("db.character-set")}>{characterSet}</InfoItem>
      ) : null}
      {collation ? (
        <InfoItem title={t("db.collation")}>{collation}</InfoItem>
      ) : null}
      {columnMetadata.comment ? (
        <InfoItem title={t("database.comment")}>
          {columnMetadata.comment}
        </InfoItem>
      ) : null}
    </div>
  );
}
