// frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ExternalTableInfo.vue
<template>
  <div class="min-w-56 max-w-[18rem] gap-y-1">
    <InfoItem :title="$t('common.name')">
      {{ externalTableMetadata.name }}
    </InfoItem>
    <InfoItem :title="$t('database.external-server-name')">
      {{ externalTableMetadata.externalServerName }}
    </InfoItem>
    <InfoItem :title="$t('database.external-database-name')">
      {{ externalTableMetadata.externalDatabaseName }}
    </InfoItem>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useDBSchemaV1Store } from "@/store";
import InfoItem from "./InfoItem.vue";

const props = defineProps<{
  database: string;
  schema?: string;
  externalTable: string;
}>();

const dbSchema = useDBSchemaV1Store();

const externalTableMetadata = computed(() =>
  dbSchema.getExternalTableMetadata({
    database: props.database,
    schema: props.schema,
    externalTable: props.externalTable,
  })
);
</script>

// frontend/src/react/components/sql-editor/SchemaPane/HoverPanel/ExternalTableInfo.tsx
import { useTranslation } from "react-i18next";
import { useDBSchemaV1Store } from "@/store";
import { InfoItem } from "./InfoItem";

type Props = {
  readonly database: string;
  readonly schema?: string;
  readonly externalTable: string;
};

/** Replaces `HoverPanel/ExternalTableInfo.vue`. */
export function ExternalTableInfo({ database, schema, externalTable }: Props) {
  const { t } = useTranslation();
  const dbSchema = useDBSchemaV1Store();
  const externalTableMetadata = dbSchema.getExternalTableMetadata({
    database,
    schema,
    externalTable,
  });

  return (
    <div className="min-w-56 max-w-[18rem] gap-y-1">
      <InfoItem title={t("common.name")}>{externalTableMetadata.name}</InfoItem>
      <InfoItem title={t("database.external-server-name")}>
        {externalTableMetadata.externalServerName}
      </InfoItem>
      <InfoItem title={t("database.external-database-name")}>
        {externalTableMetadata.externalDatabaseName}
      </InfoItem>
    </div>
  );
}
