// frontend/src/components/SchemaTemplate/ClassificationTree.vue
<template>
  <div class="divide-block-border space-y-4 h-full">
    <SearchBox
      v-model:value="state.searchText"
      style="max-width: 100%"
      :placeholder="$t('schema-template.classification.search')"
    />

    <NTree
      ref="treeRef"
      block-line
      style="height: 100%; user-select: none"
      :data="treeData"
      :multiple="false"
      :selectable="true"
      :pattern="state.searchText"
      :show-irrelevant-nodes="false"
      :expand-on-click="true"
      :render-suffix="renderSuffix"
      :render-label="renderLabel"
      :node-props="nodeProps"
      :virtual-scroll="false"
      :theme-overrides="{ nodeHeight: '21px' }"
    />
  </div>
</template>

<script lang="ts" setup>
import type { TreeOption } from "naive-ui";
import { NTree } from "naive-ui";
import { computed, reactive, h } from "vue";
import type { DataClassificationSetting_DataClassificationConfig } from "@/types/proto-es/v1/setting_service_pb";
import { getHighlightHTMLByKeyWords } from "@/utils";
import { SearchBox } from "../v2";
import ClassificationLevelBadge from "./ClassificationLevelBadge.vue";

const props = defineProps<{
  classificationConfig: DataClassificationSetting_DataClassificationConfig;
}>();

const emit = defineEmits<{
  (event: "apply", classificationId: string): void;
}>();

interface LocalState {
  searchText: string;
}

interface TreeNode extends TreeOption {
  key: string;
  label: string;
  levelId?: string;
  children?: TreeNode[];
}

interface ClassificationMap {
  [key: string]: {
    id: string;
    label: string;
    levelId?: string;
    children: ClassificationMap;
  };
}

const state = reactive<LocalState>({
  searchText: "",
});

const nodeProps = ({ option }: { option: TreeOption }) => {
  return {
    onClick() {
      if (!option.isLeaf || !option.key) {
        return;
      }
      emit("apply", option.key as string);
    },
  };
};

const sortClassification = (
  item1: { id: string },
  item2: { id: string }
): number => {
  const id1s = item1.id.split("-");
  const id2s = item2.id.split("-");

  if (id1s.length !== id2s.length) {
    return id1s.length - id2s.length;
  }

  for (let i = 0; i < id1s.length; i++) {
    if (id1s[i] === id2s[i]) {
      continue;
    }
    if (Number.isNaN(id1s[i]) || Number.isNaN(id1s[i])) {
      return id1s[i].localeCompare(id2s[i]);
    }
    return Number(id1s[i]) - Number(id2s[i]);
  }

  // shouldn't has duplicate id
  return 0;
};

const treeData = computed((): TreeNode[] => {
  const classifications = Object.values(
    props.classificationConfig.classification
  ).sort(sortClassification);

  const classificationMap: ClassificationMap = {};
  for (const classification of classifications) {
    const ids = classification.id.split("-");
    let tmp = classificationMap;
    for (let i = 0; i < ids.length - 1; i++) {
      tmp = tmp[ids.slice(0, i + 1).join("-")].children;
      if (!tmp) {
        break;
      }
    }
    if (tmp) {
      tmp[classification.id] = {
        id: classification.id,
        label: classification.title,
        levelId: classification.levelId,
        children: {},
      };
    }
  }
  return getTreeNodeList(classificationMap);
});

const getTreeNodeList = (classificationMap: ClassificationMap): TreeNode[] => {
  return Object.values(classificationMap)
    .sort(sortClassification)
    .map((item) => {
      const children = getTreeNodeList(item.children);
      return {
        key: item.id,
        label: `${item.id} ${item.label}`,
        levelId: item.levelId,
        isLeaf: children.length === 0,
        children,
      };
    });
};

const renderSuffix = ({ option }: { option: TreeOption }) => {
  const node = option as any as TreeNode;
  if (!node.levelId) {
    return null;
  }

  return h(ClassificationLevelBadge, {
    showText: false,
    classification: node.key,
    classificationConfig: props.classificationConfig,
  });
};

const renderLabel = ({ option }: { option: TreeOption }) => {
  const node = option as any as TreeNode;
  return h("span", {
    innerHTML: getHighlightHTMLByKeyWords(node.label, state.searchText),
  });
};
</script>

// frontend/src/components/ClassificationTree.tsx
import { ChevronRight } from "lucide-react";
import { type JSX, useCallback, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { SearchInput } from "@/components/ui/search-input";
import type { TreeDataNode } from "@/components/ui/tree";
import { Tree } from "@/components/ui/tree";
import type { DataClassificationSetting_DataClassificationConfig } from "@/types/proto-es/v1/setting_service_pb";
import { classificationLevelBackgroundClasses } from "./classification-level";

interface TreeNode {
  key: string;
  label: string;
  level?: number;
  children: TreeNode[];
}

interface ClassificationMap {
  [key: string]: {
    id: string;
    label: string;
    level?: number;
    children: ClassificationMap;
  };
}

function sortClassification(a: { id: string }, b: { id: string }): number {
  const id1s = a.id.split("-");
  const id2s = b.id.split("-");
  if (id1s.length !== id2s.length) return id1s.length - id2s.length;
  for (let i = 0; i < id1s.length; i++) {
    if (id1s[i] === id2s[i]) continue;
    if (Number.isNaN(Number(id1s[i])) || Number.isNaN(Number(id2s[i]))) {
      return id1s[i].localeCompare(id2s[i]);
    }
    return Number(id1s[i]) - Number(id2s[i]);
  }
  return 0;
}

function buildTreeData(
  config: DataClassificationSetting_DataClassificationConfig
): TreeNode[] {
  const classifications = Object.values(config.classification).sort(
    sortClassification
  );
  const map: ClassificationMap = {};
  for (const c of classifications) {
    const ids = c.id.split("-");
    let tmp = map;
    for (let i = 0; i < ids.length - 1; i++) {
      const parentKey = ids.slice(0, i + 1).join("-");
      if (!tmp[parentKey]) break;
      tmp = tmp[parentKey].children;
    }
    tmp[c.id] = {
      id: c.id,
      label: c.title,
      level: c.level,
      children: {},
    };
  }

  function toNodes(m: ClassificationMap): TreeNode[] {
    return Object.values(m)
      .sort(sortClassification)
      .map((item) => ({
        key: item.id,
        label: `${item.id} ${item.label}`,
        level: item.level,
        children: toNodes(item.children),
      }));
  }
  return toNodes(map);
}

function LevelBadge({
  level,
  config,
}: {
  level: number;
  config: DataClassificationSetting_DataClassificationConfig;
}) {
  const levelObj = config.levels.find((l) => l.level === level);
  if (!levelObj) return null;
  const color =
    classificationLevelBackgroundClasses[level - 1] ?? "bg-control-bg-hover";
  return (
    <span className={`ml-1 px-1 py-0.5 rounded-xs text-xs ${color}`}>
      {levelObj.title}
    </span>
  );
}

function highlightText(text: string, keyword: string) {
  if (!keyword) return text;
  const lower = text.toLowerCase();
  const kw = keyword.toLowerCase();
  const parts: (string | JSX.Element)[] = [];
  let cursor = 0;
  let idx = lower.indexOf(kw, cursor);
  while (idx !== -1) {
    if (idx > cursor) parts.push(text.slice(cursor, idx));
    parts.push(
      <b key={idx} className="text-accent">
        {text.slice(idx, idx + keyword.length)}
      </b>
    );
    cursor = idx + keyword.length;
    idx = lower.indexOf(kw, cursor);
  }
  if (cursor < text.length) parts.push(text.slice(cursor));
  return <>{parts}</>;
}

function toTreeData(node: TreeNode): TreeDataNode<TreeNode> {
  return {
    id: node.key,
    data: node,
    children: node.children.map(toTreeData),
  };
}

function collectAllIds(nodes: TreeDataNode<TreeNode>[]): string[] {
  const ids: string[] = [];
  for (const n of nodes) {
    ids.push(n.id);
    if (n.children)
      ids.push(...collectAllIds(n.children as TreeDataNode<TreeNode>[]));
  }
  return ids;
}

function collectMatchingIds(nodes: TreeNode[], keyword: string): Set<string> {
  const ids = new Set<string>();
  function walk(node: TreeNode): boolean {
    const selfMatches = node.label
      .toLowerCase()
      .includes(keyword.toLowerCase());
    const childMatches = node.children.some((c) => walk(c));
    if (selfMatches || childMatches) {
      ids.add(node.key);
      return true;
    }
    return false;
  }
  for (const n of nodes) walk(n);
  return ids;
}

export function ClassificationTree({
  config,
  onApply,
}: {
  readonly config: DataClassificationSetting_DataClassificationConfig;
  readonly onApply?: (classificationId: string) => void;
}) {
  const { t } = useTranslation();
  const [searchText, setSearchText] = useState("");
  const treeData = useMemo(
    () => buildTreeData(config).map(toTreeData),
    [config]
  );
  const expandedIds = useMemo(() => collectAllIds(treeData), [treeData]);
  const matchingIds = useMemo(() => {
    if (!searchText) return null;
    return collectMatchingIds(
      treeData.map((n) => n.data),
      searchText
    );
  }, [treeData, searchText]);

  const searchMatch = useCallback(
    (node: TreeDataNode<TreeNode>) => {
      if (!matchingIds) return true;
      return matchingIds.has(node.data.key);
    },
    [matchingIds]
  );

  return (
    <div className="flex flex-col gap-4">
      <div>
        <SearchInput
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
          placeholder={t("schema-template.classification.search")}
        />
      </div>
      <Tree<TreeNode>
        data={treeData}
        expandedIds={expandedIds}
        searchTerm={searchText || undefined}
        searchMatch={searchMatch}
        height={400}
        rowHeight={32}
        renderNode={({ node, style }) => {
          const treeNode = node.data.data;
          const hasChildren = (node.data.children?.length ?? 0) > 0;
          return (
            <div
              style={style}
              className="flex items-center gap-1 py-1 px-1 rounded-xs hover:bg-control-bg cursor-pointer select-none text-sm"
              onClick={() => {
                if (!hasChildren && onApply) {
                  onApply(treeNode.key);
                } else {
                  node.toggle();
                }
              }}
            >
              {hasChildren ? (
                <ChevronRight
                  className={`size-4 shrink-0 transition-transform ${node.isOpen ? "rotate-90" : ""}`}
                />
              ) : (
                <span className="size-4 shrink-0" />
              )}
              <span>{highlightText(treeNode.label, searchText)}</span>
              {treeNode.level != null && treeNode.level !== 0 && (
                <LevelBadge level={treeNode.level} config={config} />
              )}
            </div>
          );
        }}
      />
    </div>
  );
}
