// frontend/src/components/DataExportButton.tsx
import dayjs from "dayjs";
import saveAs from "file-saver";
import JSZip from "jszip";
import { ChevronDown, Copy, Download, Wand2 } from "lucide-react";
import {
  type ReactNode,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { useTranslation } from "react-i18next";
import { Button, type ButtonProps } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Sheet,
  SheetBody,
  SheetContent,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Tooltip } from "@/components/ui/tooltip";
import { writeTextToClipboard } from "@/lib/clipboard";
import { cn } from "@/lib/utils";
import { pushNotification } from "@/stores";
import { ExportFormat } from "@/types/proto-es/v1/common_pb";
import { MaxRowCountSelect } from "./MaxRowCountSelect";

export type DownloadContent = {
  content: Uint8Array;
  filename: string;
};

export interface ExportOption {
  limit: number;
  format: ExportFormat;
  password: string;
}

export type DataExportRequest = {
  options: ExportOption;
  resolve: (content: DownloadContent[]) => void;
  reject: (reason?: unknown) => void;
};

type Size = "tiny" | "sm" | "md" | "lg";
type ViewMode = "DRAWER" | "DROPDOWN";

interface DataExportButtonProps {
  size?: Size;
  disabled?: boolean;
  supportFormats: ExportFormat[];
  supportPassword?: boolean;
  viewMode: ViewMode;
  tooltip?: ReactNode;
  text?: string;
  validate?: (option: ExportOption) => boolean;
  maximumExportCount?: number;
  /** Custom form content rendered above the row-count / format / password fields in DRAWER mode. */
  formContent?: ReactNode;
  onExport: (req: DataExportRequest) => void;
  className?: string;
}

const SIZE_TO_BUTTON: Record<Size, ButtonProps["size"]> = {
  tiny: "xs",
  sm: "sm",
  md: "default",
  lg: "lg",
};

const ROW_COUNT_PRESET = [1, 100, 500, 1000, 5000, 10000, 100000];

const GENERATED_PASSWORD_LENGTH = 8;
const GENERATED_PASSWORD_CHARSET =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

const generateRandomPassword = (length = GENERATED_PASSWORD_LENGTH) => {
  const values = new Uint32Array(length);
  crypto.getRandomValues(values);
  let out = "";
  for (let i = 0; i < length; i++) {
    out +=
      GENERATED_PASSWORD_CHARSET[values[i] % GENERATED_PASSWORD_CHARSET.length];
  }
  return out;
};

const computeMaximumPreset = (maximum: number) => {
  const list = ROW_COUNT_PRESET.filter((n) => n <= maximum);
  if (maximum !== Number.MAX_VALUE && !list.includes(maximum)) {
    list.push(maximum);
  }
  return list[list.length - 1] ?? 1000;
};

const getExportFileType = (format: ExportFormat) => {
  switch (format) {
    case ExportFormat.CSV:
      return "text/csv";
    case ExportFormat.JSON:
      return "application/json";
    case ExportFormat.SQL:
      return "application/sql";
    case ExportFormat.XLSX:
      return "application/vnd.ms-excel";
    default:
      return "application/octet-stream";
  }
};

const toBlob = (
  { content, filename }: DownloadContent,
  format: ExportFormat
) => {
  const isZip = filename.endsWith(".zip");
  const fileType = isZip ? "application/zip" : getExportFileType(format);
  const buffer = content.buffer.slice(
    content.byteOffset,
    content.byteOffset + content.byteLength
  ) as ArrayBuffer;
  return new Blob([buffer], { type: fileType });
};

const downloadSingle = (entry: DownloadContent, format: ExportFormat) => {
  const blob = toBlob(entry, format);
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.download = entry.filename;
  link.href = url;
  link.click();
  window.URL.revokeObjectURL(url);
};

const downloadZip = async (
  contents: DownloadContent[],
  format: ExportFormat
) => {
  const zip = new JSZip();
  for (const entry of contents) {
    zip.file(entry.filename, toBlob(entry, format));
  }
  const zipFile = await zip.generateAsync({ type: "blob" });
  saveAs(zipFile, `download_${dayjs().format("YYYY-MM-DDTHH-mm-ss")}.zip`);
};

const downloadAll = async (
  contents: DownloadContent[],
  format: ExportFormat
) => {
  if (contents.length === 0) return;
  if (contents.length === 1) {
    downloadSingle(contents[0], format);
    return;
  }
  await downloadZip(contents, format);
};

/**
 * - DRAWER view: opens a Sheet with row-count / format / optional password
 *   fields, plus a `formContent` slot for caller-provided fields (e.g. the
 *   batch-export database picker).
 * - DROPDOWN view: a hover dropdown of formats; if `supportPassword` is set,
 *   selecting a format opens a small Dialog to capture an optional password.
 */
export function DataExportButton({
  size = "sm",
  disabled = false,
  supportFormats,
  supportPassword = false,
  viewMode,
  tooltip,
  text,
  validate,
  maximumExportCount = Number.MAX_VALUE,
  formContent,
  onExport,
  className,
}: DataExportButtonProps) {
  const { t } = useTranslation();

  const [isRequesting, setIsRequesting] = useState(false);
  const [showDrawer, setShowDrawer] = useState(false);
  const [showPasswordDialog, setShowPasswordDialog] = useState(false);

  const presetMax = useMemo(
    () => computeMaximumPreset(maximumExportCount),
    [maximumExportCount]
  );
  const defaultLimit = useMemo(() => Math.min(presetMax, 1000), [presetMax]);

  const [limit, setLimit] = useState<number>(defaultLimit);
  const [format, setFormat] = useState<ExportFormat>(supportFormats[0]);
  const [password, setPassword] = useState("");

  const resetForm = useCallback(() => {
    setLimit(defaultLimit);
    setFormat(supportFormats[0]);
    setPassword("");
  }, [defaultLimit, supportFormats]);

  // Reset form whenever the drawer transitions to OPEN. Depending on
  // `resetForm` here would re-fire the reset on every parent re-render
  // because `supportFormats` typically arrives as a fresh inline array
  // (e.g. `supportFormats={[CSV, JSON, SQL, XLSX]}` from
  // `SingleResultView`), which churns `resetForm`'s identity and would
  // clobber the user's just-changed `limit` / `format` / `password`.
  // Drive the reset off `showDrawer` alone via a ref to the latest
  // `resetForm`.
  const resetFormRef = useRef(resetForm);
  resetFormRef.current = resetForm;
  useEffect(() => {
    if (showDrawer) {
      resetFormRef.current();
    }
  }, [showDrawer]);

  // Clear password each time the password dialog opens.
  useEffect(() => {
    if (showPasswordDialog) {
      setPassword("");
    }
  }, [showPasswordDialog]);

  const buttonText = text ?? t("common.export");

  const currentOption: ExportOption = useMemo(
    () => ({ limit, format, password }),
    [limit, format, password]
  );

  const validateOption = validate ?? (() => true);
  const formIsValid = limit > 0 && validateOption(currentOption);

  const doExport = useCallback(() => {
    if (isRequesting) return;
    setIsRequesting(true);
    const options: ExportOption = { ...currentOption };

    new Promise<DownloadContent[]>((resolve, reject) => {
      onExport({ options, resolve, reject });
    })
      .then((contents) => downloadAll(contents, options.format))
      .then(() => {
        pushNotification({
          module: "bytebase",
          style: "SUCCESS",
          title: t("common.succeed"),
          description: t("audit-log.export-finished"),
        });
      })
      .catch((error: unknown) => {
        pushNotification({
          module: "bytebase",
          style: "CRITICAL",
          title: "Failed to export data",
          description: JSON.stringify(error),
        });
      })
      .finally(() => {
        setIsRequesting(false);
        setShowDrawer(false);
        setShowPasswordDialog(false);
      });
  }, [currentOption, isRequesting, onExport, t]);

  // Returns true when the clipboard write succeeded — Generate callers
  // gate the password commit on that so the masked input doesn't end up
  // holding a value the user can never read back. PR #20491 bot review
  // #3349557577.
  const copyPasswordToClipboard = useCallback(
    async (value: string): Promise<boolean> => {
      if (!value) return false;
      try {
        if (!(await writeTextToClipboard(value))) {
          throw new Error("clipboard unavailable");
        }
        pushNotification({
          module: "bytebase",
          style: "SUCCESS",
          title: t("common.copied"),
        });
        return true;
      } catch {
        pushNotification({
          module: "bytebase",
          style: "CRITICAL",
          title: t("common.failed"),
        });
        return false;
      }
    },
    [t]
  );

  const handleGeneratePassword = useCallback(async () => {
    const next = generateRandomPassword();
    // Only commit the generated password to state after the user has it
    // on their clipboard. If the copy fails (insecure context, denied
    // permission) the input stays empty so the user isn't left signing
    // an export ZIP with a password they can't read back from the masked
    // input.
    const copied = await copyPasswordToClipboard(next);
    if (copied) {
      setPassword(next);
    }
  }, [copyPasswordToClipboard]);

  const handleSelectDropdownFormat = (selected: ExportFormat) => {
    setFormat(selected);
    if (supportPassword) {
      setShowPasswordDialog(true);
    } else {
      // Run after state batched.
      queueMicrotask(doExport);
    }
  };

  const triggerButton = (
    <Button
      variant="default"
      size={SIZE_TO_BUTTON[size]}
      disabled={disabled || isRequesting}
      onClick={(e) => {
        e.preventDefault();
        if (viewMode === "DRAWER") setShowDrawer(true);
      }}
      className={cn("gap-x-1", className)}
      aria-label={buttonText}
    >
      <Download className="size-4" />
      {size !== "tiny" && <span>{buttonText}</span>}
    </Button>
  );

  const dropdownTrigger = (
    <DropdownMenu>
      <Tooltip content={tooltip} side="bottom">
        <DropdownMenuTrigger
          render={
            <Button
              variant="default"
              size={SIZE_TO_BUTTON[size]}
              disabled={disabled || isRequesting}
              className={cn("gap-x-1", className)}
              aria-label={buttonText}
            >
              <Download className="size-4" />
              {size !== "tiny" && <span>{buttonText}</span>}
              <ChevronDown className="size-3" />
            </Button>
          }
        />
      </Tooltip>
      <DropdownMenuContent align="end">
        {supportFormats.map((fmt) => (
          <DropdownMenuItem
            key={fmt}
            onClick={() => handleSelectDropdownFormat(fmt)}
          >
            {t("sql-editor.download-as-file", {
              file: ExportFormat[fmt],
            })}
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );

  return (
    <>
      {viewMode === "DROPDOWN" ? (
        dropdownTrigger
      ) : (
        <Tooltip content={tooltip} side="bottom">
          {triggerButton}
        </Tooltip>
      )}

      {viewMode === "DRAWER" && (
        <Sheet open={showDrawer} onOpenChange={setShowDrawer}>
          <SheetContent width="medium">
            <SheetHeader>
              <SheetTitle>
                {t("custom-approval.risk-rule.risk.namespace.data_export")}
              </SheetTitle>
            </SheetHeader>
            <SheetBody>
              <div className="flex flex-col gap-y-4">
                {formContent}

                <div className="flex flex-col gap-y-1">
                  <label className="text-sm text-control">
                    {t("export-data.export-rows")}
                  </label>
                  <MaxRowCountSelect
                    value={limit}
                    onChange={setLimit}
                    maximum={presetMax}
                    className="h-9"
                  />
                </div>

                <div className="flex flex-col gap-y-1">
                  <label className="text-sm text-control">
                    {t("export-data.export-format")}
                  </label>
                  <Select
                    value={String(format)}
                    onValueChange={(value) => {
                      if (value) setFormat(Number(value) as ExportFormat);
                    }}
                  >
                    <SelectTrigger className="w-full">
                      <SelectValue>{ExportFormat[format]}</SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      {supportFormats.map((fmt) => (
                        <SelectItem key={fmt} value={String(fmt)}>
                          {ExportFormat[fmt]}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {supportPassword && (
                  <div className="flex flex-col gap-y-1">
                    <label className="text-sm text-control">
                      {t("export-data.password-optional")}
                    </label>
                    <Input
                      type="password"
                      autoComplete="new-password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                    />
                    <div className="flex items-center gap-x-2 mt-1">
                      <Button
                        type="button"
                        appearance="outline"
                        size="sm"
                        onClick={handleGeneratePassword}
                      >
                        <Wand2 className="size-4 mr-1" />
                        {t("export-data.generate-password")}
                      </Button>
                      <Button
                        type="button"
                        appearance="outline"
                        size="sm"
                        disabled={!password}
                        onClick={() => void copyPasswordToClipboard(password)}
                      >
                        <Copy className="size-4 mr-1" />
                        {t("common.copy")}
                      </Button>
                    </div>
                  </div>
                )}
              </div>
            </SheetBody>
            <SheetFooter>
              <Button appearance="outline" onClick={() => setShowDrawer(false)}>
                {t("common.cancel")}
              </Button>
              <Button
                variant="default"
                disabled={!formIsValid || isRequesting}
                onClick={doExport}
              >
                {t("common.confirm")}
              </Button>
            </SheetFooter>
          </SheetContent>
        </Sheet>
      )}

      {viewMode === "DROPDOWN" && supportPassword && (
        <Dialog open={showPasswordDialog} onOpenChange={setShowPasswordDialog}>
          <DialogContent className="w-[26rem] max-w-[calc(100vw-4rem)]">
            <div className="flex flex-col gap-y-3">
              <DialogTitle>{t("export-data.password-optional")}</DialogTitle>
              <p className="text-sm text-control-light">
                {t("export-data.password-info")}
              </p>
              <Input
                type="password"
                autoComplete="new-password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                autoFocus
              />
              <div className="flex items-center justify-end gap-x-2 pt-2">
                <Button
                  appearance="outline"
                  size="sm"
                  onClick={() => setShowPasswordDialog(false)}
                >
                  {t("common.cancel")}
                </Button>
                <Button
                  variant="default"
                  size="sm"
                  disabled={isRequesting}
                  onClick={doExport}
                >
                  {t("common.export")}
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      )}
    </>
  );
}

// frontend/src/components/DataExportButton.vue
<template>
  <NDropdown
    trigger="hover"
    :options="exportDropdownOptions"
    :disabled="viewMode === 'DRAWER' || disabled"
    @select="tryExportViaDropdown"
  >
    <NTooltip :disabled="!tooltip">
      <template #trigger>
        <NButton
          :quaternary="size === 'tiny'"
          :size="size"
          type="primary"
          v-bind="$attrs"
          :loading="state.isRequesting"
          :disabled="state.isRequesting || disabled"
          @click="handleClickExportButton"
        >
          <template #icon>
            <DownloadIcon class="h-4 w-4" />
          </template>
          <span v-if="size !== 'tiny'">
            {{ text }}
          </span>
        </NButton>
      </template>
      <span class="text-sm"> {{ tooltip }} </span>
    </NTooltip>
  </NDropdown>

  <Drawer v-if="viewMode === 'DRAWER'" v-model:show="state.showDrawer">
    <DrawerContent
      :title="$t('custom-approval.risk-rule.risk.namespace.data_export')"
      class="w-200 max-w-[100vw] relative"
    >
      <template #default>
        <NForm
          ref="formRef"
          :model="formData"
          :rules="rules"
          label-placement="left"
        >
          <slot name="form" />
          <NFormItem path="limit" :label="$t('export-data.export-rows')">
            <MaxRowCountSelect v-model:value="formData.limit" />
          </NFormItem>
          <NFormItem path="format" :label="$t('export-data.export-format')">
            <NRadioGroup v-model:value="formData.format">
              <NRadio
                v-for="format in supportFormats"
                :key="format"
                :value="format"
              >
                {{ ExportFormat[format] }}
              </NRadio>
            </NRadioGroup>
          </NFormItem>
          <NFormItem
            v-if="supportPassword"
            path="password"
            :label="$t('export-data.password-optional')"
          >
            <BBTextField
              v-model:value="formData.password"
              type="password"
              :input-props="{ autocomplete: 'new-password' }"
            />
          </NFormItem>
        </NForm>
      </template>
      <template #footer>
        <div class="flex flex-row items-center justify-end gap-x-3">
          <NButton @click="state.showDrawer = false">
            {{ $t("common.cancel") }}
          </NButton>
          <ErrorTipsButton
            :button-props="{
              type: 'primary',
              loading: state.isRequesting,
              disabled:
                formErrors.length > 0 ||
                state.isRequesting ||
                !validate(formData),
            }"
            :errors="formErrors"
            @click="tryExportViaForm"
          >
            {{ $t("common.confirm") }}
          </ErrorTipsButton>
        </div>
      </template>
    </DrawerContent>
  </Drawer>

  <BBModal
    :show="state.showModal"
    :title="$t('export-data.password-optional')"
    class="shadow-inner outline-solid outline-gray-200"
    @close="state.showModal = false"
  >
    <div class="w-80">
      <span class="textinfolabel">{{ $t("export-data.password-info") }}</span>
      <BBTextField
        v-model:value="formData.password"
        class="my-2"
        :focus-on-mount="true"
      />
    </div>
    <div class="w-full flex items-center justify-end mt-2 space-x-3">
      <NButton @click="state.showModal = false">
        {{ $t("common.cancel") }}
      </NButton>
      <NButton type="primary" @click="exportViaDropdown">
        {{ $t("common.export") }}
      </NButton>
    </div>
  </BBModal>
</template>

<script lang="ts" setup>
import { asyncComputed } from "@vueuse/core";
import dayjs from "dayjs";
import saveAs from "file-saver";
import JSZip from "jszip";
import { DownloadIcon } from "lucide-vue-next";
import type { FormInst, FormRules } from "naive-ui";
import {
  NButton,
  NDropdown,
  NForm,
  NFormItem,
  NRadio,
  NRadioGroup,
  NTooltip,
} from "naive-ui";
import { computed, reactive, ref, watch } from "vue";
import { BBModal, BBTextField } from "@/bbkit";
import { t } from "@/plugins/i18n";
import { pushNotification } from "@/store";
import { ExportFormat } from "@/types/proto-es/v1/common_pb";
import { isNullOrUndefined } from "@/utils";
import MaxRowCountSelect from "./GrantRequestPanel/MaxRowCountSelect.vue";
import { Drawer, DrawerContent, ErrorTipsButton } from "./v2";

interface LocalState {
  isRequesting: boolean;
  showDrawer: boolean;
  showModal: boolean;
}

export type DownloadContent = {
  content: Uint8Array;
  filename: string;
};

export interface ExportOption {
  limit: number;
  format: ExportFormat;
  password: string;
}

const props = withDefaults(
  defineProps<{
    size?: "small" | "tiny" | "medium" | "large";
    disabled?: boolean;
    supportFormats: ExportFormat[];
    supportPassword?: boolean;
    viewMode: "DRAWER" | "DROPDOWN";
    tooltip?: string;
    text?: string;
    validate?: (option: ExportOption) => boolean;
  }>(),
  {
    size: "small",
    disabled: false,
    tooltip: undefined,
    supportPassword: false,
    text: () => t("common.export"),
    validate: (_: ExportOption) => true,
  }
);

const defaultFormData = (): ExportOption => ({
  limit: 1000,
  format: props.supportFormats[0],
  password: "",
});

const emit = defineEmits<{
  (
    event: "export",
    option: {
      resolve: (content: DownloadContent[]) => void;
      reject: (reason?: any) => void;
      options: ExportOption;
    }
  ): Promise<void>;
}>();

const state = reactive<LocalState>({
  isRequesting: false,
  showDrawer: false,
  showModal: false,
});
const formRef = ref<FormInst>();
const formData = ref<ExportOption>(defaultFormData());

const rules: FormRules = {
  limit: [
    {
      required: true,
      validator: (rule, value: number) => {
        if (isNullOrUndefined(value)) {
          return new Error(t("export-data.error.export-rows-required"));
        }
        if (value <= 0) {
          return new Error(t("export-data.error.export-rows-must-gt-zero"));
        }
        return true;
      },
      trigger: ["input", "blur-sm"],
    },
  ],
  format: [
    {
      required: true,
    },
  ],
};

const exportDropdownOptions = computed(() => {
  return props.supportFormats.map((format) => ({
    label: t("sql-editor.download-as-file", {
      file: ExportFormat[format],
    }),
    key: format,
  }));
});

const tryExportViaDropdown = (format: ExportFormat) => {
  formData.value.format = format;
  if (props.supportPassword) {
    state.showModal = true;
  } else {
    doExport();
  }
};

const exportViaDropdown = () => {
  state.showModal = false;
  doExport();
};

const tryExportViaForm = (e: MouseEvent) => {
  e.preventDefault();
  formRef.value?.validate((errors) => {
    if (errors) return;
    doExport();
  });
};

const formErrors = asyncComputed(() => {
  if (!formRef.value) return [];
  try {
    return new Promise<string[]>((resolve) => {
      formRef.value!.validate((errors) => {
        resolve(
          errors?.flatMap((err) => err.map((e) => e.message ?? "")) ?? []
        );
      });
    });
  } catch {
    return [];
  }
}, []);

const handleClickExportButton = (e: MouseEvent) => {
  e.preventDefault();
  if (props.viewMode === "DROPDOWN") return;

  state.showDrawer = true;
};

const doExport = () => {
  if (state.isRequesting) {
    return;
  }

  state.isRequesting = true;
  const options = { ...formData.value };

  new Promise<DownloadContent[]>((resolve, reject) => {
    return emit("export", {
      resolve,
      reject,
      options,
    });
  })
    .then((content: DownloadContent[]) => {
      return doDownload(content, options.format);
    })
    .then(() => {
      pushNotification({
        module: "bytebase",
        style: "SUCCESS",
        title: t("common.succeed"),
        description: t("audit-log.export-finished"),
      });
    })
    .catch((error) => {
      pushNotification({
        module: "bytebase",
        style: "CRITICAL",
        title: `Failed to export data`,
        description: JSON.stringify(error),
      });
    })
    .finally(() => {
      state.isRequesting = false;
      state.showDrawer = false;
    });
};

const getExportFileType = (format: ExportFormat) => {
  switch (format) {
    case ExportFormat.CSV:
      return "text/csv";
    case ExportFormat.JSON:
      return "application/json";
    case ExportFormat.SQL:
      return "application/sql";
    case ExportFormat.XLSX:
      return "application/vnd.ms-excel";
  }
};

const convertSingleFile = async (
  { content, filename }: DownloadContent,
  format: ExportFormat
) => {
  const isZip = filename.endsWith(".zip");
  const fileType = isZip ? "application/zip" : getExportFileType(format);

  // Create Blob from Uint8Array
  const buffer = content.buffer.slice(
    content.byteOffset,
    content.byteOffset + content.byteLength
  ) as ArrayBuffer; // TypeScript 5.9.2 requires explicit ArrayBuffer type
  return new Blob([buffer], {
    type: fileType,
  });
};

const doDownloadSingleFile = async (
  content: DownloadContent,
  format: ExportFormat
) => {
  const blob = await convertSingleFile(content, format);
  const url = window.URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.download = content.filename;
  link.href = url;
  link.click();
};

const doDownload = async (content: DownloadContent[], format: ExportFormat) => {
  if (content.length === 1) {
    return doDownloadSingleFile(content[0], format);
  }

  const zip = new JSZip();
  for (const c of content) {
    const blob = await convertSingleFile(c, format);
    zip.file(c.filename, blob);
  }

  const zipFile = await zip.generateAsync({ type: "blob" });
  const fileName = `download_${dayjs().format("YYYY-MM-DDTHH-mm-ss")}.zip`;
  saveAs(zipFile, fileName);
};

watch(
  () => [state.showDrawer, state.showModal],
  ([showDrawer, showModal]) => {
    if (showDrawer) {
      formData.value = defaultFormData();
    } else if (showModal) {
      formData.value.password = "";
    }
  },
  { immediate: true }
);
</script>
