// frontend/src/components/FeatureGuard/FeatureAttention.vue
<template>
  <BBAttention
    v-if="show"
    v-bind="$attrs"
    :type="hasFeature ? type : 'warning'"
    :title="$t(`dynamic.subscription.features.${featureKey}.title`)"
    :description="descriptionText"
    :action-text="actionText"
    @click="onClick"
  />

</template>

<script lang="ts" setup>
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { BBAttention } from "@/bbkit";
import { INSTANCE_ROUTE_DASHBOARD } from "@/router/dashboard/workspaceRoutes";
import { useActuatorV1Store, useSubscriptionV1Store } from "@/store";
import { ENTERPRISE_INQUIRE_LINK, instanceLimitFeature } from "@/types";
import type {
  Instance,
  InstanceResource,
} from "@/types/proto-es/v1/instance_service_pb";
import {
  PlanFeature,
  PlanType,
} from "@/types/proto-es/v1/subscription_service_pb";
import { autoSubscriptionRoute, hasWorkspacePermissionV2 } from "@/utils";

const props = withDefaults(
  defineProps<{
    feature: PlanFeature;
    description?: string;
    type?: "info" | "warning" | "error";
    instance?: Instance | InstanceResource;
  }>(),
  {
    type: "info",
    description: "",
    instance: undefined,
  }
);

const router = useRouter();
const { t } = useI18n();
const actuatorStore = useActuatorV1Store();
const subscriptionStore = useSubscriptionV1Store();

const hasPermission = computed(() =>
  hasWorkspacePermissionV2("bb.settings.set")
);

const canManageInstanceLicense = computed((): boolean => {
  return hasWorkspacePermissionV2("bb.instances.update");
});

const hasFeature = computed(() => {
  return subscriptionStore.hasInstanceFeature(props.feature);
});

const instanceMissingLicense = computed(() => {
  return subscriptionStore.instanceMissingLicense(
    props.feature,
    props.instance
  );
});

const existInstanceWithoutLicense = computed(() => {
  return (
    actuatorStore.totalInstanceCount > actuatorStore.activatedInstanceCount &&
    instanceLimitFeature.has(props.feature)
  );
});

const show = computed(() => {
  if (!hasFeature.value) {
    // show missing feature attention.
    return true;
  }
  if (instanceMissingLicense.value) {
    // show missing instance license attention.
    return true;
  }
  if (!props.instance && existInstanceWithoutLicense.value) {
    return true;
  }
  return false;
});

const actionText = computed(() => {
  if (!hasPermission.value) {
    return "";
  }

  if (!hasFeature.value) {
    return t("subscription.request-n-days-trial", {
      days: subscriptionStore.trialingDays,
    });
  }

  if (!canManageInstanceLicense.value) {
    return "";
  }
  return t("subscription.instance-assignment.assign-license");
});

const featureKey = PlanFeature[props.feature].split(".").join("-");

const descriptionText = computed(() => {
  let description = props.description;
  if (!description) {
    description = t(`dynamic.subscription.features.${featureKey}.desc`);
  }

  if (!hasFeature.value) {
    const startTrial = subscriptionStore.isTrialing
      ? ""
      : t("subscription.trial-for-days", {
          days: subscriptionStore.trialingDays,
        });
    // Check if feature is available in any plan
    // TODO(d): simplify the check.
    const requiredPlan = subscriptionStore.getMinimumRequiredPlan(
      props.feature
    );
    if (
      requiredPlan === PlanType.FREE &&
      subscriptionStore.hasFeature(props.feature)
    ) {
      return `${description}\n${startTrial}`;
    }
    const trialText = t("subscription.required-plan-with-trial", {
      requiredPlan: t(
        `subscription.plan.${PlanType[requiredPlan].toLowerCase()}.title`
      ),
      startTrial: startTrial,
    });

    return `${description}\n${trialText}`;
  }

  const attention = t(
    "subscription.instance-assignment.missing-license-attention"
  );
  return `${description}\n${attention}`;
});

const onClick = () => {
  if (!hasFeature.value) {
    window.open(ENTERPRISE_INQUIRE_LINK, "_blank");
    return;
  }
  if (instanceMissingLicense.value || existInstanceWithoutLicense.value) {
    router.push({
      name: INSTANCE_ROUTE_DASHBOARD,
      query: {
        assignLicense: "1",
        instances: props.instance?.name,
      },
    });
    return;
  }
  router.push(autoSubscriptionRoute());
};
</script>

// frontend/src/components/FeatureAttention.tsx
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { router } from "@/app/router";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { useServerState, useSubscriptionState } from "@/hooks/useAppState";
import { useAppStore } from "@/stores/app";
import { ENTERPRISE_INQUIRE_LINK, instanceLimitFeature } from "@/types";
import type {
  Instance,
  InstanceResource,
} from "@/types/proto-es/v1/instance_service_pb";
import {
  PlanFeature,
  PlanType,
} from "@/types/proto-es/v1/subscription_service_pb";
import { autoSubscriptionRoute, hasWorkspacePermissionV2 } from "@/utils";
import { InstanceAssignmentSheet } from "./InstanceAssignmentSheet";

export function FeatureAttention({
  feature,
  description: descriptionProp,
  instance,
}: {
  feature: PlanFeature;
  description?: string;
  instance?: Instance | InstanceResource;
}) {
  const { t } = useTranslation();
  const { trialingDays, isTrialing } = useSubscriptionState();
  const { totalInstanceCount, activatedInstanceCount } = useServerState();
  const [showInstanceAssignment, setShowInstanceAssignment] = useState(false);

  const hasFeature = useAppStore((state) => state.hasInstanceFeature(feature));
  const instanceMissingLicense = useAppStore((state) =>
    state.instanceMissingLicense(feature, instance)
  );
  const hasUnifiedInstanceLicense = useAppStore((state) =>
    state.hasUnifiedInstanceLicense()
  );
  const requiredPlan = useAppStore((state) =>
    state.getMinimumRequiredPlan(feature)
  );
  const featureIncludedInPlan = useAppStore((state) =>
    state.hasFeature(feature)
  );
  const existInstanceWithoutLicense =
    !hasUnifiedInstanceLicense &&
    totalInstanceCount > activatedInstanceCount &&
    instanceLimitFeature.has(feature);

  const show =
    !hasFeature ||
    instanceMissingLicense ||
    (!instance && existInstanceWithoutLicense);
  if (!show) return null;

  const isWarning = !hasFeature;
  const featureKey = PlanFeature[feature].split(".").join("-");

  const title = t(`dynamic.subscription.features.${featureKey}.title`);

  const featureDesc =
    descriptionProp || t(`dynamic.subscription.features.${featureKey}.desc`);

  let descriptionText: string;
  if (!hasFeature) {
    const startTrial = isTrialing
      ? ""
      : t("subscription.trial-for-days", {
          days: trialingDays,
        });
    if (requiredPlan === PlanType.FREE && featureIncludedInPlan) {
      descriptionText = `${featureDesc}\n${startTrial}`;
    } else {
      const trialText = t("subscription.required-plan-with-trial", {
        requiredPlan: t(
          `subscription.plan.${PlanType[requiredPlan].toLowerCase()}.title`
        ),
        startTrial,
      });
      descriptionText = `${featureDesc}\n${trialText}`;
    }
  } else {
    const attention = t(
      "subscription.instance-assignment.missing-license-attention"
    );
    descriptionText = `${featureDesc}\n${attention}`;
  }

  const hasPermission = hasWorkspacePermissionV2("bb.settings.set");

  let actionText = "";
  if (hasPermission) {
    if (!hasFeature) {
      actionText = t("subscription.request-n-days-trial", {
        days: trialingDays,
      });
    } else if (
      !hasUnifiedInstanceLicense &&
      hasWorkspacePermissionV2("bb.instances.update")
    ) {
      actionText = t("subscription.instance-assignment.assign-license");
    }
  }

  const onAction = () => {
    if (!hasFeature) {
      window.open(ENTERPRISE_INQUIRE_LINK, "_blank");
      return;
    }
    if (instanceMissingLicense || existInstanceWithoutLicense) {
      setShowInstanceAssignment(true);
      return;
    }
    router.push(autoSubscriptionRoute());
  };

  return (
    <>
      <Alert
        variant={isWarning ? "warning" : "info"}
        title={title}
        description={
          <span className="whitespace-pre-line">{descriptionText}</span>
        }
      >
        {actionText && (
          <div className="mt-3 flex justify-end">
            <Button
              appearance="solid"
              size="sm"
              className="shrink-0 whitespace-nowrap"
              onClick={onAction}
            >
              {actionText}
            </Button>
          </div>
        )}
      </Alert>
      {!hasUnifiedInstanceLicense && (
        <InstanceAssignmentSheet
          open={showInstanceAssignment}
          selectedInstanceList={instance ? [instance.name] : []}
          onOpenChange={setShowInstanceAssignment}
        />
      )}
    </>
  );
}
