// frontend/src/components/TableSchemaViewer.vue
<template>
  <div
    class="w-full h-auto flex flex-col justify-start items-center"
    v-bind="$attrs"
  >
    <div class="w-full flex flex-row justify-between items-center gap-x-2 mb-2">
      <div class="textlabel flex-1 truncate">
        {{ resourceName }}
      </div>
      <div class="flex flex-row justify-end items-center">
        <CopyButton :content="schemaString || ''" />
      </div>
    </div>
    <MonacoEditor
      :content="schemaString || ''"
      :readonly="true"
      class="border w-full h-auto grow"
    />
  </div>
</template>

<script lang="ts" setup>
import { create } from "@bufbuild/protobuf";
import { computed, nextTick, onMounted, ref } from "vue";
import { MonacoEditor } from "@/components/MonacoEditor";
import { CopyButton } from "@/components/v2";
import { databaseServiceClientConnect } from "@/connect";
import type {
  Database,
  GetSchemaStringRequest_ObjectType,
} from "@/types/proto-es/v1/database_service_pb";
import { GetSchemaStringRequestSchema } from "@/types/proto-es/v1/database_service_pb";
import { getInstanceResource, hasSchemaProperty } from "@/utils";

const props = defineProps<{
  database: Database;
  schema?: string;
  object?: string;
  type?: GetSchemaStringRequest_ObjectType;
}>();

const schemaString = ref<string | null>(null);

const engine = computed(() => {
  return getInstanceResource(props.database).engine;
});

const resourceName = computed(() => {
  if (props.object) {
    if (hasSchemaProperty(engine.value)) {
      return `${props.schema}.${props.object}`;
    } else {
      return props.object;
    }
  }
  if (props.schema) {
    return props.schema;
  }
  return props.database.name;
});

onMounted(async () => {
  nextTick(async () => {
    const request = create(GetSchemaStringRequestSchema, {
      name: props.database.name,
      type: props.type,
      schema: props.schema,
      object: props.object,
    });
    const response =
      await databaseServiceClientConnect.getSchemaString(request);
    schemaString.value = response.schemaString.trim();
  });
});
</script>

// frontend/src/components/TableSchemaViewer.tsx
import { create } from "@bufbuild/protobuf";
import { useEffect, useState } from "react";
import { databaseServiceClientConnect } from "@/api";
import { ReadonlyMonaco } from "@/components/monaco/ReadonlyMonaco";
import { CopyButton } from "@/components/ui/copy-button";
import {
  type Database,
  type GetSchemaStringRequest_ObjectType,
  GetSchemaStringRequestSchema,
} from "@/types/proto-es/v1/database_service_pb";
import { getInstanceResource, hasSchemaProperty } from "@/utils";

type Props = {
  readonly database: Database;
  readonly schema?: string;
  readonly object?: string;
  readonly type?: GetSchemaStringRequest_ObjectType;
  readonly className?: string;
};

/**
 * Fetches the SDL-style schema text for a database / schema / table /
 * view via `databaseServiceClientConnect.getSchemaString` and displays
 * it read-only. Header shows a `schema.object` (or `object` for
 * engines without schemas) breadcrumb plus a Copy-to-clipboard button.
 */
export function TableSchemaViewer({
  database,
  schema,
  object,
  type,
  className,
}: Props) {
  const [schemaString, setSchemaString] = useState<string>("");

  const engine = getInstanceResource(database).engine;
  const resourceName = object
    ? hasSchemaProperty(engine)
      ? `${schema}.${object}`
      : object
    : schema || database.name;

  useEffect(() => {
    let cancelled = false;
    const request = create(GetSchemaStringRequestSchema, {
      name: `${database.name}/schemaString`,
      type,
      schema,
      object,
    });
    void databaseServiceClientConnect
      .getSchemaString(request)
      .then((response) => {
        if (cancelled) return;
        setSchemaString(response.schemaString.trim());
      });
    return () => {
      cancelled = true;
    };
  }, [database.name, schema, object, type]);

  return (
    <div
      className={`w-full h-auto flex flex-col justify-start items-center ${className ?? ""}`}
    >
      <div className="w-full flex flex-row justify-between items-center gap-x-2 mb-2">
        <div className="text-sm text-control flex-1 truncate">
          {resourceName}
        </div>
        <CopyButton content={schemaString} disabled={!schemaString} size="sm" />
      </div>
      <ReadonlyMonaco
        content={schemaString}
        className="border w-full h-auto grow"
      />
    </div>
  );
}
