// frontend/src/modules/sql-editor/components/SchemaPane/SyncSchemaButton.tsx
import { RefreshCcw } from "lucide-react";
import { useState } from "react";
import { Trans, useTranslation } from "react-i18next";
import { HumanizeTs } from "@/components/HumanizeTs";
import { Button } from "@/components/ui/button";
import { Tooltip } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { useConnectionOfCurrentSQLEditorTab } from "@/modules/sql-editor/hooks/useSQLEditorState";
import { useAppStore } from "@/stores/app";
import { getDateForPbTimestampProtoEs, isValidDatabaseName } from "@/types";

/**
 * RefreshCcw button with a hover tooltip showing the last sync time +
 * click-to-sync hint.
 *
 *  - Disabled when the active tab has no valid database connection (no
 *    `database.name`) or while a sync is in flight.
 *  - On click, calls the app store's `syncDatabase(name, refresh=true)`,
 *    then `getOrFetchDatabaseMetadata({ skipCache: true })` so the
 *    SchemaPane reactively rebuilds with the fresh metadata.
 *  - Spinner: the icon spins while `isSyncing` is true.
 */
export function SyncSchemaButton({ className }: { className?: string }) {
  const { t } = useTranslation();
  const { database } = useConnectionOfCurrentSQLEditorTab();

  const [isSyncing, setIsSyncing] = useState(false);
  const disabled = !isValidDatabaseName(database.name);

  const syncNow = async () => {
    if (disabled) return;
    setIsSyncing(true);
    try {
      const appStore = useAppStore.getState();
      await appStore.syncDatabase(database.name, true);
      await appStore.getOrFetchDatabaseMetadata({
        database: database.name,
        skipCache: true,
      });
    } finally {
      setIsSyncing(false);
    }
  };

  const lastSyncDate = getDateForPbTimestampProtoEs(
    database.successfulSyncTime
  );
  const lastSyncTs = lastSyncDate
    ? Math.floor(lastSyncDate.getTime() / 1000)
    : 0;

  const button = (
    <Button
      appearance="outline"
      size="sm"
      type="button"
      disabled={disabled || isSyncing}
      onClick={syncNow}
      className={cn("px-1.5", className)}
    >
      <RefreshCcw
        className={cn(
          "size-4",
          isSyncing && "animate-[spin_2s_linear_infinite]"
        )}
      />
    </Button>
  );

  if (disabled) {
    // No tooltip when disabled, so we don't surface a "last synced" tooltip
    // with stale-looking placeholder data.
    return button;
  }

  return (
    <Tooltip
      side="bottom"
      content={
        <div className="flex flex-col gap-1">
          {lastSyncTs > 0 ? (
            <Trans
              t={t}
              i18nKey="sql-editor.last-synced"
              components={{ time: <HumanizeTs ts={lastSyncTs} /> }}
            />
          ) : null}
          <div>
            {isSyncing
              ? t("sql-editor.sync-in-progress")
              : t("sql-editor.click-to-sync-now")}
          </div>
        </div>
      }
    >
      {button}
    </Tooltip>
  );
}

// frontend/src/views/sql-editor/AsidePanel/SchemaPane/SyncSchemaButton.vue
<template>
  <NPopover :disabled="disabled" placement="bottom-start">
    <template #trigger>
      <NButton
        style="--n-padding: 0 5px"
        :disabled="disabled || isSyncing"
        v-bind="$attrs"
        @click="syncNow"
      >
        <template #icon>
          <RefreshCcwIcon
            class="w-4 h-4"
            :class="[isSyncing && 'animate-[spin_2s_linear_infinite]']"
          />
        </template>
      </NButton>
    </template>
    <template #default>
      <div class="flex flex-col gap-1">
        <i18n-t tag="div" keypath="sql-editor.last-synced">
          <template #time>
            <HumanizeDate
              :date="getDateForPbTimestampProtoEs(database.successfulSyncTime)"
            />
          </template>
        </i18n-t>
        <div v-if="!isSyncing">{{ $t("sql-editor.click-to-sync-now") }}</div>
        <div v-if="isSyncing">{{ $t("sql-editor.sync-in-progress") }}</div>
      </div>
    </template>
  </NPopover>
</template>

<script setup lang="ts">
import { RefreshCcwIcon } from "lucide-vue-next";
import { NButton, NPopover } from "naive-ui";
import { computed, ref } from "vue";
import HumanizeDate from "@/components/misc/HumanizeDate.vue";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
  useDatabaseV1Store,
} from "@/store";
import { getDateForPbTimestampProtoEs, isValidDatabaseName } from "@/types";

defineOptions({
  inheritAttrs: false,
});

const { database } = useConnectionOfCurrentSQLEditorTab();

const disabled = computed(() => {
  return !isValidDatabaseName(database.value.name);
});

const isSyncing = ref(false);

const syncNow = async () => {
  if (disabled.value) {
    return;
  }
  try {
    isSyncing.value = true;
    await useDatabaseV1Store().syncDatabase(
      database.value.name,
      /* refresh */ true
    );

    await useDBSchemaV1Store().getOrFetchDatabaseMetadata({
      database: database.value.name,
      skipCache: true,
    });
  } finally {
    isSyncing.value = false;
  }
};
</script>
