// frontend/src/react/components/sql-editor/ConnectionPane/actions.tsx
import {
  ExternalLink,
  Link as LinkIcon,
  SquarePen,
  Wrench,
} from "lucide-react";
import { useCallback, useMemo } from "react";
import { useTranslation } from "react-i18next";
import { useVueState } from "@/react/hooks/useVueState";
import { router } from "@/router";
import { PROJECT_V1_ROUTE_DATABASE_DETAIL } from "@/router/dashboard/projectV1";
import {
  useSQLEditorStore,
  useSQLEditorTabStore,
  useSQLEditorUIStore,
  useSQLEditorWorksheetStore,
} from "@/store";
import type {
  BatchQueryContext,
  SQLEditorConnection,
  SQLEditorTabMode,
  SQLEditorTreeNode,
} from "@/types";
import {
  instanceOfSQLEditorTreeNode,
  isConnectableSQLEditorTreeNode,
} from "@/types";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import {
  extractDatabaseResourceName,
  extractInstanceResourceName,
  extractProjectResourceName,
  getInstanceResource,
  instanceV1HasAlterSchema,
  instanceV1HasReadonlyMode,
} from "@/utils";
import { sqlEditorEvents } from "@/views/sql-editor/events";

type ActionKey =
  | "connect"
  | "connect-in-new-tab"
  | "connect-in-admin-mode"
  | "view-database-detail"
  | "alter-schema";

export type ConnectionMenuItem = {
  readonly key: ActionKey;
  readonly label: string;
  readonly icon: React.ReactNode;
  readonly onSelect: () => void;
};

const DEFAULT_TAB_MODE: SQLEditorTabMode = "WORKSHEET";

/**
 * Replaces frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/actions.tsx's `setConnection`.
 * Connects the current tab or creates a new worksheet, then sets the tab
 * mode + batch-query context and flips the aside panel to `SCHEMA`.
 */
export function setConnection(options: {
  database?: Database;
  mode?: SQLEditorTabMode;
  newTab: boolean;
  batchQueryContext?: BatchQueryContext;
}) {
  const { database, mode = DEFAULT_TAB_MODE, newTab } = options;
  const connection: SQLEditorConnection = {
    instance: database
      ? extractDatabaseResourceName(database.name).instance
      : "",
    database: database?.name ?? "",
  };

  const tabStore = useSQLEditorTabStore();
  const uiStore = useSQLEditorUIStore();
  const worksheetStore = useSQLEditorWorksheetStore();

  const batchQueryContext: BatchQueryContext = Object.assign(
    { databases: [] } as BatchQueryContext,
    tabStore.currentTab?.batchQueryContext,
    options.batchQueryContext
  );

  const createOrUpdate = () => {
    if (!newTab && tabStore.currentTab) {
      return worksheetStore.maybeUpdateWorksheet({
        tabId: tabStore.currentTab.id,
        worksheet: tabStore.currentTab.worksheet,
        title: tabStore.currentTab.title,
        database: connection.database,
        statement: tabStore.currentTab.statement,
      });
    }
    return worksheetStore.createWorksheet({
      database: connection.database,
    });
  };

  void createOrUpdate().then((tab) => {
    if (tab) {
      tabStore.updateTab(tab.id, { mode, batchQueryContext });
      uiStore.asidePanelTab = "SCHEMA";
    }
  });
}

/**
 * Replaces `useDropdown` from the Vue `actions.tsx`.
 * Returns the dynamic menu items for a right-clicked tree node. Consumers
 * render the resulting items in their own context menu UI.
 */
export function useConnectionMenu(node: SQLEditorTreeNode | null) {
  const { t } = useTranslation();
  const editorStore = useSQLEditorStore();
  const uiStore = useSQLEditorUIStore();
  const allowAdmin = useVueState(() => editorStore.allowAdmin);

  const items = useMemo<ConnectionMenuItem[]>(() => {
    if (!node || node.disabled) return [];

    const { type, target } = node.meta;
    const out: ConnectionMenuItem[] = [];

    if (isConnectableSQLEditorTreeNode(node)) {
      const database = target as Database;
      const instance = instanceOfSQLEditorTreeNode(node);
      if (instance && instanceV1HasReadonlyMode(instance)) {
        out.push({
          key: "connect",
          label: t("database.select"),
          icon: <LinkIcon className="size-4" />,
          onSelect: () => {
            setConnection({ database, newTab: false });
            uiStore.showConnectionPanel = false;
          },
        });
        out.push({
          key: "connect-in-new-tab",
          label: t("sql-editor.open-in-new-tab"),
          icon: <LinkIcon className="size-4" />,
          onSelect: () => {
            setConnection({ database, newTab: true });
            uiStore.showConnectionPanel = false;
          },
        });
      }
      if (allowAdmin) {
        out.push({
          key: "connect-in-admin-mode",
          label: t("sql-editor.connect-in-admin-mode"),
          icon: <Wrench className="size-4" />,
          onSelect: () => {
            setConnection({ database, mode: "ADMIN", newTab: false });
            uiStore.showConnectionPanel = false;
          },
        });
      }
    }

    if (type === "database") {
      const database = target as Database;
      const { instance, databaseName } = extractDatabaseResourceName(
        database.name
      );
      out.push({
        key: "view-database-detail",
        label: t("sql-editor.view-database-detail"),
        icon: <ExternalLink className="size-4" />,
        onSelect: () => {
          const route = router.resolve({
            name: PROJECT_V1_ROUTE_DATABASE_DETAIL,
            params: {
              projectId: extractProjectResourceName(database.project),
              instanceId: extractInstanceResourceName(instance),
              databaseName,
            },
          });
          window.open(route.href, "_blank");
        },
      });
      if (instanceV1HasAlterSchema(getInstanceResource(database))) {
        out.push({
          key: "alter-schema",
          label: t("database.edit-schema"),
          icon: <SquarePen className="size-4" />,
          onSelect: () => {
            void sqlEditorEvents.emit("alter-schema", {
              databaseName: database.name,
              schema: "",
              table: "",
            });
            uiStore.showConnectionPanel = false;
          },
        });
      }
    }
    return out;
  }, [node, allowAdmin, t, uiStore]);

  const handleSelect = useCallback(
    (key: ActionKey) => {
      items.find((item) => item.key === key)?.onSelect();
    },
    [items]
  );

  return { items, handleSelect };
}

// frontend/src/views/sql-editor/AsidePanel/ConnectionPane/actions.tsx
import {
  ExternalLinkIcon,
  LinkIcon,
  SquarePenIcon,
  WrenchIcon,
} from "lucide-vue-next";
import type { DropdownOption } from "naive-ui";
import { computed, ref } from "vue";
import { useRouter } from "vue-router";
import { t } from "@/plugins/i18n";
import { PROJECT_V1_ROUTE_DATABASE_DETAIL } from "@/router/dashboard/projectV1";
import { useCurrentUserV1, usePageMode } from "@/store";
import {
  DEFAULT_SQL_EDITOR_TAB_MODE,
  instanceOfSQLEditorTreeNode,
  isConnectableSQLEditorTreeNode,
  type ComposedDatabase,
  type CoreSQLEditorTab,
  type Position,
  type SQLEditorTabMode as TabMode,
  type SQLEditorTreeNode as TreeNode,
} from "@/types";
import {
  emptySQLEditorConnection,
  extractInstanceResourceName,
  extractProjectResourceName,
  hasWorkspacePermissionV2,
  instanceV1HasAlterSchema,
  instanceV1HasReadonlyMode,
  tryConnectToCoreSQLEditorTab,
} from "@/utils";
import { useSQLEditorContext } from "../../context";

type DropdownOptionWithTreeNode = DropdownOption & {
  onSelect: () => void;
};

export const useDropdown = () => {
  const router = useRouter();
  const { events: editorEvents } = useSQLEditorContext();
  const pageMode = usePageMode();

  const show = ref(false);
  const position = ref<Position>({
    x: 0,
    y: 0,
  });
  const context = ref<TreeNode>();

  const me = useCurrentUserV1();
  const allowAdmin = computed(() =>
    hasWorkspacePermissionV2(me.value, "bb.instances.adminExecute")
  );

  const options = computed((): DropdownOptionWithTreeNode[] => {
    const node = context.value;
    if (!node) {
      return [];
    }
    const { type, target } = node.meta;
    if (type === "project") {
      return [];
    } else {
      // Don't show any context menu actions for disabled
      // instances/databases
      if (node.disabled) {
        return [];
      }

      const items: DropdownOptionWithTreeNode[] = [];

      if (isConnectableSQLEditorTreeNode(node)) {
        const instance = instanceOfSQLEditorTreeNode(node);
        if (instance && instanceV1HasReadonlyMode(instance)) {
          items.push({
            key: "connect",
            label: t("sql-editor.connect"),
            icon: () => <LinkIcon class="w-4 h-4" />,
            onSelect: () => setConnection(node),
          });
          items.push({
            key: "connect-in-new-tab",
            label: t("sql-editor.connect-in-new-tab"),
            icon: () => <LinkIcon class="w-4 h-4" />,
            onSelect: () =>
              setConnection(
                node,
                { sheet: "", mode: DEFAULT_SQL_EDITOR_TAB_MODE },
                /* newTab */ true
              ),
          });
        }
        if (allowAdmin.value) {
          items.push({
            key: "connect-in-admin-mode",
            label: t("sql-editor.connect-in-admin-mode"),
            icon: () => <WrenchIcon class="w-4 h-4" />,
            onSelect: () => setConnection(node, { sheet: "", mode: "ADMIN" }),
          });
        }
      }
      if (pageMode.value === "BUNDLED") {
        if (type === "database") {
          const database = target as ComposedDatabase;
          items.push({
            key: "view-database-detail",
            label: t("sql-editor.view-database-detail"),
            icon: () => <ExternalLinkIcon class="w-4 h-4" />,
            onSelect: () => {
              const route = router.resolve({
                name: PROJECT_V1_ROUTE_DATABASE_DETAIL,
                params: {
                  projectId: extractProjectResourceName(database.project),
                  instanceId: extractInstanceResourceName(database.instance),
                  databaseName: database.databaseName,
                },
              });
              const url = route.href;
              window.open(url, "_blank");
            },
          });
          if (instanceV1HasAlterSchema(database.instanceEntity)) {
            items.push({
              key: "alter-schema",
              label: t("database.edit-schema"),
              icon: () => <SquarePenIcon class="w-4 h-4" />,
              onSelect: () => {
                const db = node.meta.target as ComposedDatabase;
                editorEvents.emit("alter-schema", {
                  databaseUID: db.uid,
                  schema: "",
                  table: "",
                });
              },
            });
          }
        }
      }
      return items;
    }
  });

  const handleSelect = (key: string) => {
    const option = options.value.find((item) => item.key === key);
    if (!option) {
      return;
    }
    option.onSelect();
    show.value = false;
  };

  const handleClickoutside = () => {
    show.value = false;
  };

  return { show, position, context, options, handleSelect, handleClickoutside };
};

export const setConnection = (
  node: TreeNode<"database">,
  extra: { sheet: string; mode: TabMode } = {
    sheet: "",
    mode: DEFAULT_SQL_EDITOR_TAB_MODE,
  },
  newTab = false
) => {
  if (!node) {
    return;
  }
  if (!isConnectableSQLEditorTreeNode(node)) {
    // one more guard
    return;
  }
  const coreTab: CoreSQLEditorTab = {
    connection: emptySQLEditorConnection(),
    ...extra,
  };
  const conn = coreTab.connection;
  const database = node.meta.target as ComposedDatabase;
  conn.instance = database.instance;
  conn.database = database.name;
  tryConnectToCoreSQLEditorTab(coreTab, /* overrideTitle */ true, newTab);
};
