// frontend/src/plugins/agent/components/AgentChat.vue
<script setup lang="ts">
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import { unified } from "unified";
import { computed, nextTick, ref, watch } from "vue";
import AstToMarkdown from "@/plugins/ai/components/ChatView/Markdown/AstToVNode.vue";
import type { AgentMessage } from "../logic/types";
import { useAgentStore } from "../store/agent";
import ToolCallCard from "./ToolCallCard.vue";

const markdownProcessor = unified().use(remarkParse).use(remarkGfm);

const parseMarkdown = (content: string) => {
  return markdownProcessor.parse(content ?? "");
};

const agentStore = useAgentStore();
const chatContainer = ref<HTMLElement | null>(null);

const displayMessages = computed(() =>
  agentStore.messages.filter(
    (message): message is AgentMessage =>
      message.role === "user" || message.role === "assistant"
  )
);

function getToolResult(
  messageId: string,
  toolCallId: string
): string | undefined {
  const fullIndex = agentStore.messages.findIndex(
    (message) => message.id === messageId
  );
  if (fullIndex < 0) {
    return undefined;
  }

  for (let index = fullIndex + 1; index < agentStore.messages.length; index++) {
    const message = agentStore.messages[index];
    if (message.role === "tool" && message.toolCallId === toolCallId) {
      return message.content;
    }
    if (
      message.role === "assistant" &&
      message.content &&
      !message.toolCalls?.length
    ) {
      break;
    }
  }
  return undefined;
}

watch(
  [() => agentStore.currentChatId, () => agentStore.messages.length],
  async () => {
    await nextTick();
    if (chatContainer.value) {
      chatContainer.value.scrollTop = chatContainer.value.scrollHeight;
    }
  }
);
</script>

<template>
  <div ref="chatContainer" class="overflow-y-auto space-y-3 p-3">
    <template v-for="msg in displayMessages" :key="msg.id">
      <div v-if="msg.role === 'user'" class="flex justify-end">
        <div class="max-w-[80%] rounded-lg bg-blue-50 px-3 py-2 text-sm">
          {{ msg.content }}
        </div>
      </div>
      <div v-else class="flex flex-col gap-y-2">
        <div
          v-if="msg.content"
          class="max-w-[80%] rounded-lg bg-gray-50 px-3 py-2 text-sm markdown-content"
        >
          <AstToMarkdown :ast="parseMarkdown(msg.content)" />
        </div>
        <ToolCallCard
          v-for="toolCall in msg.toolCalls"
          :key="toolCall.id"
          :tool-call="toolCall"
          :result="getToolResult(msg.id, toolCall.id)"
        />
      </div>
    </template>
    <div
      v-if="agentStore.loading"
      class="flex items-center gap-x-2 text-sm text-gray-400"
    >
      <span class="animate-pulse">&#9679;</span> {{ $t("common.loading") }}
    </div>
    <div
      v-if="agentStore.error"
      class="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-600"
    >
      {{ agentStore.error }}
    </div>
  </div>
</template>

<style scoped lang="postcss">
.markdown-content :deep(p) {
  @apply my-1;
}
.markdown-content :deep(p:first-child) {
  @apply mt-0;
}
.markdown-content :deep(p:last-child) {
  @apply mb-0;
}
.markdown-content :deep(pre) {
  @apply my-1 overflow-x-auto rounded bg-gray-100 p-2 text-xs;
}
.markdown-content :deep(code) {
  @apply rounded bg-gray-200 px-1 text-xs;
}
.markdown-content :deep(pre code) {
  @apply bg-transparent px-0;
}
.markdown-content :deep(ul),
.markdown-content :deep(ol) {
  @apply my-1 pl-5;
}
.markdown-content :deep(ul) {
  @apply list-disc;
}
.markdown-content :deep(ol) {
  @apply list-decimal;
}
.markdown-content :deep(li) {
  @apply my-0.5;
}
.markdown-content :deep(h1),
.markdown-content :deep(h2),
.markdown-content :deep(h3) {
  @apply my-1 font-semibold;
}
.markdown-content :deep(a) {
  @apply text-blue-600 underline;
}
.markdown-content :deep(blockquote) {
  @apply my-1 border-l-2 border-gray-300 pl-2 text-gray-600;
}
.markdown-content :deep(table) {
  @apply my-1 border-collapse text-xs;
}
.markdown-content :deep(th),
.markdown-content :deep(td) {
  @apply border border-gray-300 px-2 py-1;
}
</style>

// frontend/src/modules/agent/components/AgentChat.tsx
import { useEffect, useMemo, useRef } from "react";
import { useTranslation } from "react-i18next";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { SETTING_ROUTE_WORKSPACE_GENERAL } from "@/app/router/handles";
import { RouterLink } from "@/components/RouterLink";
import { Button, buttonVariants } from "@/components/ui/button";
import {
  AI_ASSISTANT_PRODUCT_INTRO,
  PRODUCT_INTRO_QUERY_KEY,
} from "@/lib/productIntro";
import { hasWorkspacePermissionV2 } from "@/utils";
import type { AgentMessage, ToolCall } from "../logic/types";
import {
  selectCurrentChatRequiresAIConfiguration,
  selectError,
  selectLoading,
  selectMessages,
  useAgentStore,
} from "../store/agent";
import { ToolCallCard } from "./ToolCallCard";

interface AgentChatProps {
  className?: string;
}

export function AgentChat({ className }: AgentChatProps) {
  const { t } = useTranslation();
  const chatContainerRef = useRef<HTMLDivElement>(null);

  const messages = useAgentStore(selectMessages);
  const loading = useAgentStore(selectLoading);
  const error = useAgentStore(selectError);
  const showAIConfigurationRecovery = useAgentStore(
    selectCurrentChatRequiresAIConfiguration
  );
  const currentChatId = useAgentStore((s) => s.currentChatId);
  const allMessages = useAgentStore(selectMessages);
  const clearError = useAgentStore((s) => s.clearError);

  const allowConfigure = hasWorkspacePermissionV2("bb.settings.set");

  const displayMessages = useMemo(
    () =>
      messages.filter(
        (message): message is AgentMessage =>
          message.role === "user" || message.role === "assistant"
      ),
    [messages]
  );

  function getToolResult(
    messageId: string,
    toolCallId: string,
    duplicateIndex = 0
  ): string | undefined {
    const fullIndex = allMessages.findIndex(
      (message) => message.id === messageId
    );
    if (fullIndex < 0) return undefined;

    let matchingResultIndex = 0;
    for (let index = fullIndex + 1; index < allMessages.length; index++) {
      const message = allMessages[index];
      if (message.role === "tool" && message.toolCallId === toolCallId) {
        if (matchingResultIndex === duplicateIndex) {
          return message.content;
        }
        matchingResultIndex++;
      }
      if (
        message.role === "assistant" &&
        message.content &&
        !message.toolCalls?.length
      ) {
        break;
      }
    }
    return undefined;
  }

  function getToolCallDuplicateIndex(
    toolCalls: ToolCall[],
    currentToolCallIndex: number
  ): number {
    const currentToolCall = toolCalls[currentToolCallIndex];
    let duplicateIndex = 0;
    for (let index = 0; index < currentToolCallIndex; index++) {
      if (toolCalls[index]?.id === currentToolCall.id) {
        duplicateIndex++;
      }
    }
    return duplicateIndex;
  }

  function goConfigure() {
    clearError(currentChatId);
  }

  function dismiss() {
    clearError(currentChatId);
  }

  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop =
        chatContainerRef.current.scrollHeight;
    }
  }, [currentChatId, messages.length]);

  return (
    <div
      ref={chatContainerRef}
      className={`flex flex-col overflow-y-auto gap-3 p-3 ${className ?? ""}`}
    >
      {displayMessages.map((msg) =>
        msg.role === "user" ? (
          <div key={msg.id} className="flex justify-end">
            <div className="max-w-[80%] rounded-sm bg-blue-50 px-3 py-2 text-sm">
              {msg.content}
            </div>
          </div>
        ) : (
          <div key={msg.id} className="flex flex-col gap-y-2">
            {msg.content && (
              <div className="max-w-[80%] rounded-sm bg-control-bg px-3 py-2 text-sm">
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{
                    p: ({ children }) => (
                      <p className="my-1 first:mt-0 last:mb-0">{children}</p>
                    ),
                    pre: ({ children }) => (
                      <pre className="my-1 overflow-x-auto rounded-xs bg-control-bg p-2 text-xs">
                        {children}
                      </pre>
                    ),
                    code: ({ children }) => (
                      <code className="break-all rounded-xs bg-control-bg-hover px-1 text-xs">
                        {children}
                      </code>
                    ),
                    ul: ({ children }) => (
                      <ul className="my-1 list-disc pl-5">{children}</ul>
                    ),
                    ol: ({ children }) => (
                      <ol className="my-1 list-decimal pl-5">{children}</ol>
                    ),
                    li: ({ children }) => (
                      <li className="my-0.5">{children}</li>
                    ),
                    h1: ({ children }) => (
                      <h1 className="my-1 font-semibold">{children}</h1>
                    ),
                    h2: ({ children }) => (
                      <h2 className="my-1 font-semibold">{children}</h2>
                    ),
                    h3: ({ children }) => (
                      <h3 className="my-1 font-semibold">{children}</h3>
                    ),
                    a: ({ children, href }) => (
                      <a
                        className="text-accent underline"
                        href={href}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        {children}
                      </a>
                    ),
                    blockquote: ({ children }) => (
                      <blockquote className="my-1 border-l-2 border-control-border pl-2 text-control-light">
                        {children}
                      </blockquote>
                    ),
                    table: ({ children }) => (
                      <table className="my-1 border-collapse text-xs">
                        {children}
                      </table>
                    ),
                    th: ({ children }) => (
                      <th className="border border-control-border px-2 py-1">
                        {children}
                      </th>
                    ),
                    td: ({ children }) => (
                      <td className="border border-control-border px-2 py-1">
                        {children}
                      </td>
                    ),
                  }}
                >
                  {msg.content}
                </ReactMarkdown>
              </div>
            )}
            {msg.toolCalls?.map((toolCall, index, toolCalls) => (
              <ToolCallCard
                key={`${msg.id}:${toolCall.id}:${index}`}
                toolCall={toolCall}
                result={getToolResult(
                  msg.id,
                  toolCall.id,
                  getToolCallDuplicateIndex(toolCalls, index)
                )}
              />
            ))}
          </div>
        )
      )}

      {loading && (
        <div className="flex items-center gap-x-2 text-sm text-control-placeholder">
          <span className="animate-pulse">&#9679;</span> {t("common.loading")}
        </div>
      )}

      {showAIConfigurationRecovery ? (
        <div className="max-w-[80%] rounded-sm border border-amber-200 bg-amber-50 px-3 py-3 text-sm text-amber-900">
          <div className="font-medium">
            {t("agent.ai-not-configured.title")}
          </div>
          <div className="mt-1">{t("agent.ai-not-configured.description")}</div>
          <div className="mt-3 flex flex-wrap gap-x-2 gap-y-2">
            {allowConfigure && (
              <RouterLink
                to={{
                  name: SETTING_ROUTE_WORKSPACE_GENERAL,
                  hash: "#ai-assistant",
                  query: {
                    [PRODUCT_INTRO_QUERY_KEY]: AI_ASSISTANT_PRODUCT_INTRO,
                  },
                }}
                className={buttonVariants({ size: "sm" })}
                onClick={goConfigure}
              >
                {t("agent.ai-not-configured.configure")}
              </RouterLink>
            )}
            <Button appearance="outline" size="sm" onClick={dismiss}>
              {t("common.dismiss")}
            </Button>
          </div>
          {!allowConfigure && (
            <div className="mt-1 text-amber-800">
              {t("agent.ai-not-configured.contact-admin")}
            </div>
          )}
        </div>
      ) : (
        error && (
          <div className="rounded-sm bg-red-50 px-3 py-2 text-sm text-error">
            {error}
          </div>
        )
      )}
    </div>
  );
}
