// frontend/src/views/sql-editor/EditorCommon/DatabaseChooser.vue
<template>
  <NButton
    :disabled="disabled || !projectContextReady"
    type="primary"
    size="small"
    ghost
    style="
      justify-content: end;
      --n-padding: 0 8px;
      --n-color-hover: rgb(var(--color-accent) / 0.05);
      --n-color-pressed: rgb(var(--color-accent) / 0.05);
      --n-color-focus: rgb(var(--color-accent) / 0.05);
    "
    @click="changeConnection"
  >
    <div
      v-if="
        currentTab &&
        isValidInstanceName(instance.name) &&
        isValidDatabaseName(database.name)
      "
      class="flex flex-row items-center text-main"
    >
      <NPopover v-if="isInBatchMode" placement="bottom">
        <template #trigger>
          <SquareStackIcon class="w-4 h-4 mr-1 text-accent" />
        </template>
        <template #default>
          {{ $t("sql-editor.batch-query.batch") }}
        </template>
      </NPopover>
      <EnvironmentV1Name
        :environment="database.effectiveEnvironmentEntity"
        :link="false"
      />
      <ChevronRightIcon class="shrink-0 h-4 w-4 text-control-light" />
      <div class="flex items-center gap-1">
        <InstanceV1EngineIcon
          :instance="instance"
          show-status
          class="shrink-0"
        />
        <span>{{ instance.title }}</span>
      </div>
      <ChevronRightIcon class="shrink-0 h-4 w-4 text-control-light" />
      <div class="flex items-center gap-1">
        <DatabaseIcon class="shrink-0" />
        <span>{{ database.databaseName }}</span>
      </div>
    </div>
    <template v-else>
      {{ $t("sql-editor.select-a-database-to-start") }}
    </template>
  </NButton>
</template>

<script lang="ts" setup>
import { ChevronRightIcon, SquareStackIcon } from "lucide-vue-next";
import { NButton, NPopover } from "naive-ui";
import { storeToRefs } from "pinia";
import { DatabaseIcon } from "@/components/Icon";
import { EnvironmentV1Name, InstanceV1EngineIcon } from "@/components/v2";
import {
  useConnectionOfCurrentSQLEditorTab,
  useSQLEditorStore,
  useSQLEditorTabStore,
} from "@/store";
import { isValidDatabaseName, isValidInstanceName } from "@/types";
import { useSQLEditorContext } from "../context";

const { currentTab, isInBatchMode } = storeToRefs(useSQLEditorTabStore());
const { showConnectionPanel } = useSQLEditorContext();
const { projectContextReady } = storeToRefs(useSQLEditorStore());

const { instance, database } = useConnectionOfCurrentSQLEditorTab();

const changeConnection = () => {
  showConnectionPanel.value = true;
};

defineProps<{
  disabled?: boolean;
}>();
</script>

<style lang="postcss" scoped>
:deep(.n-button__content) {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>

// frontend/src/modules/sql-editor/components/DatabaseChooser.tsx
import { ChevronRight, Database, SquareStack } from "lucide-react";
import { useTranslation } from "react-i18next";
import { EngineIcon } from "@/components/EngineIcon";
import { EnvironmentLabel } from "@/components/EnvironmentLabel";
import { Tooltip } from "@/components/ui/tooltip";
import { ConnectionChooserButton } from "@/modules/sql-editor/components/ConnectionChooserButton";
import { useConnectionOfCurrentSQLEditorTab } from "@/modules/sql-editor/hooks/useSQLEditorState";
import { useSQLEditorStore } from "@/modules/sql-editor/store";
import { useSQLEditorEditorState } from "@/modules/sql-editor/store/editor";
import {
  useCurrentSQLEditorTab,
  useIsInBatchMode,
} from "@/modules/sql-editor/store/tab";
import { isValidDatabaseName, isValidInstanceName } from "@/types";
import {
  extractDatabaseResourceName,
  getDatabaseEnvironment,
  getInstanceResource,
} from "@/utils";

type DatabaseChooserProps = {
  readonly disabled?: boolean;
};

/**
 * Breadcrumb-style chooser showing the current connection
 * (Environment > Instance > Database). Click opens the connection panel.
 */
export function DatabaseChooser({ disabled = false }: DatabaseChooserProps) {
  const { t } = useTranslation();
  const setShowConnectionPanel = useSQLEditorStore(
    (s) => s.setShowConnectionPanel
  );
  const { database } = useConnectionOfCurrentSQLEditorTab();

  const currentTab = useCurrentSQLEditorTab();
  const isInBatchMode = useIsInBatchMode();
  const projectContextReady = useSQLEditorEditorState(
    (s) => s.projectContextReady
  );

  const instance = getInstanceResource(database);
  const environment = getDatabaseEnvironment(database);
  const databaseName = extractDatabaseResourceName(database.name).databaseName;

  const isConnected =
    !!currentTab &&
    isValidInstanceName(instance.name) &&
    isValidDatabaseName(database.name);

  const handleClick = () => {
    setShowConnectionPanel(true);
  };

  return (
    <ConnectionChooserButton
      disabled={disabled || !projectContextReady}
      onClick={handleClick}
      className="overflow-hidden"
    >
      {isConnected ? (
        <div className="flex flex-row items-center text-control truncate">
          {isInBatchMode && (
            <Tooltip content={t("sql-editor.batch-query.batch")}>
              <SquareStack className="size-4 mr-1 text-accent" />
            </Tooltip>
          )}
          <EnvironmentLabel environmentName={environment.name} />
          <ChevronRight className="size-4 shrink-0 text-control-light" />
          <div className="flex items-center gap-1">
            <EngineIcon engine={instance.engine} className="size-4" />
            <span className="truncate">{instance.title}</span>
          </div>
          <ChevronRight className="size-4 shrink-0 text-control-light" />
          <div className="flex items-center gap-1 truncate">
            <Database className="size-4 shrink-0" />
            <span className="truncate">{databaseName}</span>
          </div>
        </div>
      ) : (
        <span>{t("sql-editor.select-a-database-to-start")}</span>
      )}
    </ConnectionChooserButton>
  );
}
