// frontend/src/views/sql-editor/TabList/TabList.vue
<template>
  <div
    class="bb-sql-editor-tab-list flex justify-between items-center box-border text-gray-500 text-sm border-b pr-2 gap-1"
  >
    <NScrollbar
      ref="scrollbarRef"
      :x-scrollable="true"
      trigger="hover"
      class="scrollbar"
      content-class="flex gap-x-1"
      @scroll="recalculateScrollState"
    >
      <VueDraggable
        id="tab-list"
        ref="tabListRef"
        v-model="tabStore.openTabList"
        :animation="300"
        class="relative flex flex-nowrap overflow-hidden h-9 pt-0.5 hide-scrollbar"
        :class="{
          'more-left': scrollState.moreLeft,
          'more-right': scrollState.moreRight,
        }"
        ghost-class="ghost"
      >
        <TabItem
          v-for="(tab, index) in tabStore.openTabList"
          :key="tab.id"
          :tab="tab"
          :index="index"
          :data-tab-id="tab.id"
          @select="(tab) => tabStore.setCurrentTabId(tab.id)"
          @close="(tab) => handleRemoveTab(tab)"
          @contextmenu.stop.prevent="
            contextMenuRef?.show(tab, index, $event)
          "
        />
      </VueDraggable>

      <div
        class="shrink-0 sticky right-0 bg-white flex items-stretch justify-end"
      >
        <button
          class="bg-gray-200/20 hover:bg-accent/10py-1 px-1.5 border-t border-x rounded-t hover:border-accent"
          :disabled="state.loading"
          @click="handleAddTab"
        >
          <PlusIcon class="h-5 w-5" stroke-width="2.5" />
        </button>
      </div>
    </NScrollbar>

    <ProfileBrandingLogo
      size="small"
      :logo-url="workspaceStore.currentWorkspace?.logo"
    >
      <ProfileDropdown :link="true" />
    </ProfileBrandingLogo>

    <ContextMenu ref="contextMenuRef" />
  </div>
</template>

<script lang="ts" setup>
import { useResizeObserver } from "@vueuse/core";
import { PlusIcon } from "lucide-vue-next";
import { NScrollbar, useDialog } from "naive-ui";
import scrollIntoView from "scroll-into-view-if-needed";
import { computed, nextTick, onMounted, reactive, ref, watch } from "vue";
import { VueDraggable } from "vue-draggable-plus";
import { useI18n } from "vue-i18n";
import ProfileBrandingLogo from "@/components/ProfileBrandingLogo.vue";
import ProfileDropdown from "@/components/ProfileDropdown.vue";
import { useEmitteryEventListener } from "@/composables/useEmitteryEventListener";
import { useSQLEditorTabStore, useWorkspaceV1Store } from "@/store";
import type { SQLEditorTab } from "@/types";
import { defer, usePreventBackAndForward } from "@/utils";
import { useSQLEditorContext } from "../context";
import ContextMenu from "./ContextMenu.vue";
import { useTabListContext } from "./context";
import TabItem from "./TabItem/TabItem.vue";

type LocalState = {
  hoverTabId: string;
  loading: boolean;
};

const tabStore = useSQLEditorTabStore();
const editorContext = useSQLEditorContext();
const context = useTabListContext();
const workspaceStore = useWorkspaceV1Store();

const { t } = useI18n();
const dialog = useDialog();

const state = reactive<LocalState>({
  hoverTabId: "",
  loading: false,
});
const scrollbarRef = ref<InstanceType<typeof NScrollbar>>();
const tabListRef = ref<InstanceType<typeof VueDraggable>>();
const contextMenuRef = ref<InstanceType<typeof ContextMenu>>();

const scrollState = reactive({
  moreLeft: false,
  moreRight: false,
});

const scrollElement = computed((): HTMLElement | null | undefined => {
  return scrollbarRef.value?.scrollbarInstRef?.containerRef;
});

const handleAddTab = async () => {
  if (state.loading) {
    return;
  }

  state.loading = true;
  try {
    await editorContext.createWorksheet({});
    nextTick(() => {
      requestAnimationFrame(() => {
        const elem = scrollElement.value;
        if (elem) {
          elem.scrollTo(elem.scrollWidth, 0);
        }
        requestAnimationFrame(() => {
          recalculateScrollState();
        });
      });
    });
  } finally {
    state.loading = false;
  }
};

const handleRemoveTab = async (tab: SQLEditorTab, focusWhenConfirm = false) => {
  const _defer = defer<boolean>();
  if (tab.mode === "WORKSHEET" && tab.status !== "CLEAN") {
    if (focusWhenConfirm) {
      tabStore.setCurrentTabId(tab.id);
    }
    const $dialog = dialog.create({
      title: t("sql-editor.hint-tips.confirm-to-close-unsaved-sheet.title"),
      content: t("sql-editor.hint-tips.confirm-to-close-unsaved-sheet.content"),
      type: "warning",
      autoFocus: false,
      closable: false,
      maskClosable: false,
      closeOnEsc: false,
      onPositiveClick() {
        remove();
        $dialog.destroy();
        _defer.resolve(true);
      },
      onNegativeClick() {
        $dialog.destroy();
        _defer.resolve(false);
      },
      positiveText: t("sql-editor.close-sheet"),
      negativeText: t("common.cancel"),
      showIcon: false,
    });
  } else {
    remove();
    _defer.resolve(true);
  }

  function remove() {
    tabStore.closeTab(tab.id);
    nextTick(recalculateScrollState);
  }

  return _defer.promise;
};

usePreventBackAndForward(scrollElement);
useResizeObserver(tabListRef, () => {
  recalculateScrollState();
});

const recalculateScrollState = () => {
  contextMenuRef.value?.hide();

  const element = scrollElement.value;
  if (!element) {
    return;
  }

  const { scrollWidth, offsetWidth, scrollLeft } = element;

  if (scrollLeft === 0) {
    scrollState.moreLeft = false;
  } else {
    scrollState.moreLeft = true;
  }

  if (scrollWidth > offsetWidth) {
    // The actual width is wider than the visible width
    const rightBound = scrollLeft + offsetWidth;
    if (rightBound < scrollWidth) {
      scrollState.moreRight = true;
    } else {
      scrollState.moreRight = false;
    }
  } else {
    scrollState.moreRight = false;
  }
};

watch(
  () => tabStore.currentTabId,
  (id) => {
    requestAnimationFrame(() => {
      // Scroll the selected tab into view if needed.
      const tabElements = Array.from(document.querySelectorAll(".tab-item"));
      const tabElement = tabElements.find(
        (elem) => elem.getAttribute("data-tab-id") === id
      );
      if (tabElement) {
        scrollIntoView(tabElement, {
          scrollMode: "if-needed",
        });
      }
    });
  },
  { immediate: true }
);

onMounted(() => recalculateScrollState());

useEmitteryEventListener(
  context.events,
  "close-tab",
  async ({ tab, index, action }) => {
    const { openTabList } = tabStore;

    const remove = async (tab: SQLEditorTab) => {
      await handleRemoveTab(tab, true);
      await new Promise((r) => requestAnimationFrame(r));
    };

    const max = openTabList.length - 1;
    switch (action) {
      case "CLOSE": {
        await remove(tab);
        return;
      }
      case "CLOSE_OTHERS": {
        for (let i = max; i > index; i--) {
          await remove(openTabList[i]);
        }
        for (let i = index - 1; i >= 0; i--) {
          await remove(openTabList[i]);
        }
        return;
      }
      case "CLOSE_TO_THE_RIGHT": {
        for (let i = max; i > index; i--) {
          await remove(openTabList[i]);
        }
        return;
      }
      case "CLOSE_SAVED": {
        for (let i = max; i >= 0; i--) {
          const tab = openTabList[i];
          if (tab.status === "CLEAN") {
            await remove(tab);
          }
        }
        return;
      }
      case "CLOSE_ALL": {
        for (let i = max; i >= 0; i--) {
          await remove(openTabList[i]);
        }
        return;
      }
    }
  }
);
</script>

<style lang="postcss">
.bb-sql-editor-tab-list .ghost {
  opacity: 0.3;
  background-color: white;
}
.bb-sql-editor-tab-list .scrollbar .n-scrollbar-rail--horizontal--bottom {
  inset: auto 2px 2px 2px !important;
}
</style>

// frontend/src/modules/sql-editor/components/TabList.tsx
import {
  closestCenter,
  DndContext,
  type DragEndEvent,
  PointerSensor,
  useSensor,
  useSensors,
} from "@dnd-kit/core";
import {
  horizontalListSortingStrategy,
  SortableContext,
} from "@dnd-kit/sortable";
import { Plus } from "lucide-react";
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
} from "react";
import { useTranslation } from "react-i18next";
import scrollIntoView from "scroll-into-view-if-needed";
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { tabListEvents } from "@/modules/sql-editor/model/TabList/events";
import { useSQLEditorStore } from "@/modules/sql-editor/store";
import {
  getSQLEditorTabsState,
  useOpenTabList,
  useSQLEditorTabState,
} from "@/modules/sql-editor/store/tab";
import type { SQLEditorTab } from "@/types/sqlEditor/tab";
import { TabContextMenu, type TabContextMenuHandle } from "./TabContextMenu";
import { TabItem } from "./TabItem/TabItem";

type CloseTabAction =
  | "CLOSE"
  | "CLOSE_OTHERS"
  | "CLOSE_TO_THE_RIGHT"
  | "CLOSE_SAVED"
  | "CLOSE_ALL";

type PendingClose = {
  tab: SQLEditorTab;
  resolve: (confirmed: boolean) => void;
};

/**
 * Replaces frontend/src/views/sql-editor/TabList/TabList.vue.
 * Horizontal tab bar at the top of the SQL editor. Drag-reorder via
 * @dnd-kit, overflow-x scroll, "+" button to add a new worksheet, and
 * right-click context menu delegated to TabContextMenu.
 */
export function TabList() {
  const { t } = useTranslation();
  const createWorksheet = useSQLEditorStore((s) => s.createWorksheet);

  // Zustand's selector subscribes to in-place tab mutations because
  // `updateTab` reassigns / triggers an immer produce on `tabsById`,
  // bumping the slice identity.
  const tabs = useOpenTabList();
  const currentTabId = useSQLEditorTabState((s) => s.currentTabId);

  const scrollRef = useRef<HTMLDivElement>(null);
  const contextMenuRef = useRef<TabContextMenuHandle>(null);

  const [loading, setLoading] = useState(false);
  const [scrollState, setScrollState] = useState({
    moreLeft: false,
    moreRight: false,
  });
  const [pendingClose, setPendingClose] = useState<PendingClose | null>(null);

  const recalculateScrollState = useCallback(() => {
    contextMenuRef.current?.hide();
    const el = scrollRef.current;
    if (!el) return;
    const { scrollWidth, offsetWidth, scrollLeft } = el;
    setScrollState({
      moreLeft: scrollLeft > 0,
      moreRight:
        scrollWidth > offsetWidth
          ? scrollLeft + offsetWidth < scrollWidth
          : false,
    });
  }, []);

  // Initial measure + resize observer.
  useLayoutEffect(() => {
    recalculateScrollState();
    const el = scrollRef.current;
    if (!el) return;
    const ro = new ResizeObserver(() => recalculateScrollState());
    ro.observe(el);
    return () => ro.disconnect();
  }, [recalculateScrollState]);

  // Prevent the trackpad / horizontal wheel from triggering browser
  // back/forward navigation when the tab list can't scroll further.
  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    const handler = (e: WheelEvent) => {
      const maxX = el.scrollWidth - el.clientWidth;
      const target = el.scrollLeft + e.deltaX;
      if (target < 0 || target > maxX) {
        e.preventDefault();
      }
    };
    el.addEventListener("wheel", handler, { passive: false });
    return () => el.removeEventListener("wheel", handler);
  }, []);

  // Scroll the selected tab into view whenever the active tab changes.
  useEffect(() => {
    if (!currentTabId) return;
    requestAnimationFrame(() => {
      const el = document.querySelector(
        `[data-tab-id="${currentTabId}"]`
      ) as HTMLElement | null;
      if (el) {
        scrollIntoView(el, { scrollMode: "if-needed" });
      }
    });
  }, [currentTabId]);

  const confirmCloseUnsaved = useCallback(
    (tab: SQLEditorTab) =>
      new Promise<boolean>((resolve) => {
        setPendingClose({ tab, resolve });
      }),
    []
  );

  const removeTab = useCallback(
    async (tab: SQLEditorTab, focusWhenConfirm = false) => {
      const tabsState = getSQLEditorTabsState();
      if (tab.mode === "WORKSHEET" && tab.status !== "CLEAN") {
        if (focusWhenConfirm) {
          tabsState.setCurrentTabId(tab.id);
        }
        const confirmed = await confirmCloseUnsaved(tab);
        if (!confirmed) return false;
      }
      tabsState.closeTab(tab.id);
      requestAnimationFrame(recalculateScrollState);
      return true;
    },
    [confirmCloseUnsaved, recalculateScrollState]
  );

  const handleAddTab = async () => {
    if (loading) return;
    setLoading(true);
    try {
      await createWorksheet({});
      requestAnimationFrame(() => {
        const el = scrollRef.current;
        if (el) el.scrollTo(el.scrollWidth, 0);
        requestAnimationFrame(recalculateScrollState);
      });
    } finally {
      setLoading(false);
    }
  };

  const handleSelect = (tab: SQLEditorTab) => {
    getSQLEditorTabsState().setCurrentTabId(tab.id);
  };

  const handleClose = (tab: SQLEditorTab) => {
    void removeTab(tab);
  };

  const handleContextMenu = (
    tab: SQLEditorTab,
    index: number,
    e: React.MouseEvent
  ) => {
    contextMenuRef.current?.show(tab, index, e);
  };

  // Drag-reorder.
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 4 } })
  );

  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over || active.id === over.id) return;
    const oldIndex = tabs.findIndex((t) => t.id === active.id);
    const newIndex = tabs.findIndex((t) => t.id === over.id);
    if (oldIndex < 0 || newIndex < 0) return;
    const next = [...tabs];
    const [moved] = next.splice(oldIndex, 1);
    next.splice(newIndex, 0, moved);
    // Rewrite the persisted tab order without touching individual tabs.
    getSQLEditorTabsState().setOpenTabListOrder(
      next.map((tab) => ({
        id: tab.id,
        worksheet: tab.worksheet,
        mode: tab.mode,
        batchQueryContext: tab.batchQueryContext,
        treeState: tab.treeState,
        viewState: tab.viewState,
      }))
    );
  };

  // Listen for close-tab events from the context menu (batch actions).
  useEffect(() => {
    const unsubscribe = tabListEvents.on(
      "close-tab",
      async ({ data: { tab, index, action } }) => {
        const tabsState = getSQLEditorTabsState();
        const snapshot = tabsState.openTmpTabList
          .map((persisted) => tabsState.tabsById.get(persisted.id))
          .filter((t): t is SQLEditorTab => !!t);
        const max = snapshot.length - 1;
        const remove = async (t: SQLEditorTab) => {
          await removeTab(t, true);
          await new Promise((r) => requestAnimationFrame(r));
        };
        switch (action as CloseTabAction) {
          case "CLOSE":
            await remove(tab);
            return;
          case "CLOSE_OTHERS": {
            for (let i = max; i > index; i--) await remove(snapshot[i]);
            for (let i = index - 1; i >= 0; i--) await remove(snapshot[i]);
            return;
          }
          case "CLOSE_TO_THE_RIGHT": {
            for (let i = max; i > index; i--) await remove(snapshot[i]);
            return;
          }
          case "CLOSE_SAVED": {
            for (let i = max; i >= 0; i--) {
              const t = snapshot[i];
              if (t.status === "CLEAN") await remove(t);
            }
            return;
          }
          case "CLOSE_ALL": {
            for (let i = max; i >= 0; i--) await remove(snapshot[i]);
            return;
          }
        }
      }
    );
    return () => {
      unsubscribe();
    };
  }, [removeTab]);

  return (
    <div
      className={cn(
        "bb-sql-editor-tab-list flex justify-between items-center",
        // pl-2 keeps the first tab off the vertical resize bar to its left.
        "box-border text-control-light text-sm border-b pl-2 pr-2 gap-1"
      )}
    >
      <div
        ref={scrollRef}
        onScroll={recalculateScrollState}
        className={cn(
          "flex-1 overflow-x-auto overflow-y-hidden scrollbar-thin",
          scrollState.moreLeft && "more-left",
          scrollState.moreRight && "more-right"
        )}
      >
        <DndContext
          sensors={sensors}
          collisionDetection={closestCenter}
          onDragEnd={handleDragEnd}
        >
          <SortableContext
            items={tabs.map((tab) => tab.id)}
            strategy={horizontalListSortingStrategy}
          >
            <div className="relative flex flex-nowrap h-9 pt-0.5">
              {tabs.map((tab, index) => (
                <TabItem
                  key={tab.id}
                  tab={tab}
                  index={index}
                  onSelect={handleSelect}
                  onClose={handleClose}
                  onContextMenu={handleContextMenu}
                />
              ))}
              <div className="shrink-0 sticky right-0 bg-background flex items-stretch justify-end">
                <button
                  type="button"
                  className={cn(
                    "bg-control-bg/20 hover:bg-accent/10 py-1 px-1.5",
                    "border-t border-x rounded-t hover:border-accent disabled:opacity-50"
                  )}
                  disabled={loading}
                  onClick={handleAddTab}
                  aria-label={t("common.add")}
                >
                  <Plus className="size-5" strokeWidth={2.5} />
                </button>
              </div>
            </div>
          </SortableContext>
        </DndContext>
      </div>

      <TabContextMenu ref={contextMenuRef} />

      <AlertDialog
        open={pendingClose !== null}
        // Vue's confirm dialog used `closeOnEsc: false`, `maskClosable: false`,
        // `closable: false` — the user MUST click Cancel or "Close sheet".
        // Cancel Base UI's close when the reason is Esc / outside-click so
        // the dialog stays open and forces an explicit choice.
        onOpenChange={(
          open: boolean,
          eventDetails?: { reason?: string; cancel?: () => void }
        ) => {
          if (
            !open &&
            (eventDetails?.reason === "escape-key" ||
              eventDetails?.reason === "outside-press")
          ) {
            eventDetails.cancel?.();
            return;
          }
          if (!open && pendingClose) {
            pendingClose.resolve(false);
            setPendingClose(null);
          }
        }}
      >
        <AlertDialogContent className="max-w-md p-6">
          <AlertDialogTitle>
            {t("sql-editor.hint-tips.confirm-to-close-unsaved-sheet.title")}
          </AlertDialogTitle>
          <AlertDialogDescription>
            {t("sql-editor.hint-tips.confirm-to-close-unsaved-sheet.content")}
          </AlertDialogDescription>
          <AlertDialogFooter className="mt-4 flex justify-end gap-x-2">
            <Button
              appearance="outline"
              onClick={() => {
                pendingClose?.resolve(false);
                setPendingClose(null);
              }}
            >
              {t("common.cancel")}
            </Button>
            <Button
              variant="default"
              onClick={() => {
                pendingClose?.resolve(true);
                setPendingClose(null);
              }}
            >
              {t("sql-editor.close-sheet")}
            </Button>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
