// frontend/src/views/sql-editor/AsidePanel/TreeNode/InstanceNode.vue
<template>
  <div class="flex items-center max-w-full overflow-hidden gap-x-1">
    <InstanceV1EngineIcon :instance="instance" />
    <EnvironmentV1Name
      v-if="!hasEnvironmentContext"
      :environment="instance.environmentEntity"
      :link="false"
      class="text-control-light"
    />
    <HighlightLabelText
      :text="instance.title"
      :keyword="keyword"
      class="flex-1 truncate"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { EnvironmentV1Name, InstanceV1EngineIcon } from "@/components/v2";
import {
  SQLEditorTreeNode as TreeNode,
  SQLEditorTreeFactor as Factor,
} from "@/types";
import HighlightLabelText from "./HighlightLabelText.vue";

const props = defineProps<{
  node: TreeNode;
  factors: Factor[];
  keyword: string;
}>();

const instance = computed(
  () => (props.node as TreeNode<"instance">).meta.target
);

const hasEnvironmentContext = computed(() => {
  return props.factors.includes("environment");
});
</script>

// frontend/src/modules/sql-editor/components/ConnectionPane/TreeNode/InstanceNode.tsx
import { EngineIcon } from "@/components/EngineIcon";
import { HighlightLabelText } from "@/components/HighlightLabelText";
import type { SQLEditorTreeNode } from "@/types";
import { instanceV1Name } from "@/utils";

type Props = {
  readonly node: SQLEditorTreeNode;
  readonly keyword: string;
};

export function InstanceNode({ node, keyword }: Props) {
  const target = (node as SQLEditorTreeNode<"instance">).meta.target;
  const instance = {
    ...target,
    $typeName: "bytebase.v1.InstanceResource" as const,
  };
  return (
    <div className="flex items-center max-w-full overflow-hidden gap-x-1">
      <span className="inline-flex items-center gap-x-1">
        <EngineIcon engine={instance.engine} className="size-4" />
        <span className="truncate">
          <HighlightLabelText
            text={instanceV1Name(instance)}
            keyword={keyword}
          />
        </span>
      </span>
    </div>
  );
}
