// frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/Label.vue
<template>
  <template v-if="type === 'instance'">
    <InstanceNode :node="node" :keyword="keyword" />
  </template>
  <template v-if="type === 'environment'">
    <EnvironmentV1Name
      :environment="(node as TreeNode<'environment'>).meta.target"
      :keyword="keyword"
      :link="false"
    />
  </template>
  <template v-if="type === 'database'">
    <DatabaseNode
      v-bind="$attrs"
      :node="node"
      :keyword="keyword"
      :checked="checked"
      :check-disabled="checkDisabled"
      :check-tooltip="checkTooltip"
      @click="$emit('click')"
      @update:checked="event => $emit('update:checked', event)"
    />
  </template>
  <template v-if="type === 'label'">
    <LabelNode :node="node" :keyword="keyword" />
  </template>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import { EnvironmentV1Name } from "@/components/v2";
import type { SQLEditorTreeNode as TreeNode } from "@/types";
import DatabaseNode from "./DatabaseNode.vue";
import InstanceNode from "./InstanceNode.vue";
import LabelNode from "./LabelNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
  checked: boolean;
  checkDisabled?: boolean;
  checkTooltip?: string;
}>();

defineEmits<{
  (event: "click"): void;
  (event: "update:checked", checked: boolean): void;
}>();

const type = computed(() => props.node.meta.type);
</script>

// frontend/src/modules/sql-editor/components/ConnectionPane/TreeNode/Label.tsx
import { EnvironmentLabel } from "@/components/EnvironmentLabel";
import { isDarkTheme } from "@/modules/sql-editor/components/theme/derive";
import { useSQLEditorTheme } from "@/modules/sql-editor/components/theme/SQLEditorThemeScope";
import type { SQLEditorTreeNode } from "@/types";
import { DatabaseNode } from "./DatabaseNode";
import { InstanceNode } from "./InstanceNode";
import { LabelNode } from "./LabelNode";

type Props = {
  readonly node: SQLEditorTreeNode;
  readonly keyword: string;
  readonly checked: boolean;
  readonly checkDisabled?: boolean;
  readonly checkTooltip?: string;
  readonly onCheckedChange?: (checked: boolean) => void;
};

/**
 * Dispatches on `node.meta.type` to render the right leaf component; only
 * the `database` case consumes the checkbox/click callbacks.
 */
export function Label(props: Props) {
  const { node, keyword } = props;
  const type = node.meta.type;

  if (type === "instance") {
    return <InstanceNode node={node} keyword={keyword} />;
  }
  if (type === "environment") {
    return <EnvironmentNodeLabel node={node} />;
  }
  if (type === "database") {
    return (
      <DatabaseNode
        node={node}
        keyword={keyword}
        checked={props.checked}
        checkDisabled={props.checkDisabled}
        checkTooltip={props.checkTooltip}
        onCheckedChange={props.onCheckedChange}
      />
    );
  }
  if (type === "label") {
    return <LabelNode node={node} keyword={keyword} />;
  }
  return null;
}

function EnvironmentNodeLabel({ node }: Readonly<{ node: SQLEditorTreeNode }>) {
  const environment = (node as SQLEditorTreeNode<"environment">).meta.target;
  const theme = useSQLEditorTheme();
  const darkTheme = isDarkTheme(theme);

  return (
    <EnvironmentLabel
      environment={environment}
      link={false}
      styleOptions={
        darkTheme
          ? {
              defaultColorTextColor: theme.tokens["--color-accent-hover"],
              backgroundAlpha: 0.18,
            }
          : undefined
      }
    />
  );
}
