// frontend/src/views/sql-editor/TabList/TabItem/AdminLabel.vue
<template>
  <label class="flex items-center text-sm h-5 ml-0.5 whitespace-nowrap">
    <template v-if="!hideEnvironment">
      <EnvironmentV1Name
        :environment="database.effectiveEnvironmentEntity"
        :link="false"
      />
      <ChevronRightIcon class="flex-shrink-0 h-4 w-4 opacity-70" />
    </template>
    <template v-if="isValidInstanceName(instance.name)">
      <span>{{ instance.title }}</span>
      <ChevronRightIcon class="flex-shrink-0 h-4 w-4 opacity-70" />
    </template>
    <template v-if="isValidDatabaseName(database.name)">
      <span>{{ database.databaseName }}</span>
    </template>
  </label>
</template>

<script lang="ts" setup>
import { ChevronRightIcon } from "lucide-vue-next";
import { computed } from "vue";
import { EnvironmentV1Name } from "@/components/v2";
import { useDatabaseV1ByName } from "@/store";
import { type SQLEditorTab, UNKNOWN_ID } from "@/types";
import { isValidInstanceName, isValidDatabaseName } from "@/types";

const props = defineProps<{
  tab: SQLEditorTab;
}>();

const connection = computed(() => props.tab.connection);

const { database } = useDatabaseV1ByName(
  computed(() => connection.value.database)
);

const instance = computed(() => {
  return database.value.instanceResource;
});

const hideEnvironment = computed(() => {
  return database.value.effectiveEnvironmentEntity?.id === String(UNKNOWN_ID);
});
</script>

// frontend/src/modules/sql-editor/components/TabItem/AdminLabel.tsx
import { ChevronRight } from "lucide-react";
import { useAppDatabase } from "@/hooks/useAppDatabase";
import { UNKNOWN_ID } from "@/types/const";
import type { SQLEditorTab } from "@/types/sqlEditor/tab";
import { isValidDatabaseName } from "@/types/v1/database";
import { isValidInstanceName } from "@/types/v1/instance";
import {
  extractDatabaseResourceName,
  getDatabaseEnvironment,
  getInstanceResource,
} from "@/utils";

type Props = {
  readonly tab: SQLEditorTab;
};

/**
 * Breadcrumb shown in the tab title when a tab is in ADMIN mode:
 * `environment > instance > database`. Hides the environment segment when
 * the database has no environment (unknown).
 */
export function AdminLabel({ tab }: Props) {
  const dbName = tab.connection.database;
  // Self-fetches on mount / name change and reactively re-reads the cached
  // database.
  const database = useAppDatabase(dbName);
  const instance = getInstanceResource(database);
  const environment = getDatabaseEnvironment(database);
  const { databaseName } = extractDatabaseResourceName(database.name);
  const hideEnvironment = environment?.id === String(UNKNOWN_ID);

  return (
    <label className="flex items-center text-sm h-5 ml-0.5 whitespace-nowrap">
      {!hideEnvironment && (
        <>
          <span>{environment.title}</span>
          <ChevronRight className="shrink-0 h-4 w-4 opacity-70" />
        </>
      )}
      {isValidInstanceName(instance.name) && (
        <>
          <span>{instance.title}</span>
          <ChevronRight className="shrink-0 h-4 w-4 opacity-70" />
        </>
      )}
      {isValidDatabaseName(database.name) && <span>{databaseName}</span>}
    </label>
  );
}
