// frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/LabelNode.vue
<template>
  <div class="truncate">
    <span>{{ label.key }}</span>
    <span class="mr-0.5">:</span>
    <HighlightLabelText
      v-if="label.value"
      :text="label.value"
      :keyword="keyword"
    />
    <span v-else class="text-control-placeholder">
      {{ $t("label.empty-label-value") }}
    </span>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { HighlightLabelText } from "@/components/v2";
import type { SQLEditorTreeNode as TreeNode } from "@/types";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const label = computed(() => (props.node as TreeNode<"label">).meta.target);
</script>

// frontend/src/react/components/sql-editor/ConnectionPane/TreeNode/LabelNode.tsx
import { useTranslation } from "react-i18next";
import { HighlightLabelText } from "@/react/components/HighlightLabelText";
import type { SQLEditorTreeNode } from "@/types";

type Props = {
  readonly node: SQLEditorTreeNode;
  readonly keyword: string;
};

/** Replaces frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/LabelNode.vue. */
export function LabelNode({ node, keyword }: Props) {
  const { t } = useTranslation();
  const label = (node as SQLEditorTreeNode<"label">).meta.target;

  return (
    <div className="truncate">
      <span>{label.key}</span>
      <span className="mr-0.5">:</span>
      {label.value ? (
        <HighlightLabelText text={label.value} keyword={keyword} />
      ) : (
        <span className="text-control-placeholder">
          {t("label.empty-label-value")}
        </span>
      )}
    </div>
  );
}
