// frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TableDetail.vue
<template>
  <div
    class="w-full h-7 flex flex-row gap-x-2 justify-between items-center"
  >
    <NTabs
      v-model:value="state.view"
      size="small"
      style="height: 28px; --n-tab-gap: 1rem"
    >
      <template #prefix>
        <NButton text @click="deselect">
          <ChevronLeftIcon class="w-5 h-5" />
          <div class="flex items-center gap-1">
            <TableIcon class="w-4 h-4" />
            <span>{{ table.name }}</span>
          </div>
        </NButton>
      </template>
      <template v-if="tabItems.length > 1">
        <NTab v-for="tab in tabItems" :key="tab.view" :name="tab.view">
          <div class="flex items-center gap-1">
            <component :is="{ render: tab.icon }" class="w-4 h-4" />
            {{ tab.text }}
          </div>
        </NTab>
      </template>
      <template #suffix>
        <SearchBox
          v-model:value="state.keyword"
          size="small"
          style="width: 10rem"
        />
      </template>
    </NTabs>
  </div>
  <ColumnsTable
    v-show="state.view === 'COLUMNS'"
    :db="db"
    :database="database"
    :schema="schema"
    :table="table"
    :keyword="state.keyword"
  />
  <IndexesTable
    v-show="state.view === 'INDEXES'"
    :db="db"
    :database="database"
    :schema="schema"
    :table="table"
    :keyword="state.keyword"
  />
  <ForeignKeysTable
    v-show="state.view === 'FOREIGN-KEYS'"
    :db="db"
    :database="database"
    :schema="schema"
    :table="table"
    :keyword="state.keyword"
  />
  <TriggersTable
    v-show="state.view === 'TRIGGERS'"
    :db="db"
    :database="database"
    :schema="schema"
    :table="table"
    :keyword="state.keyword"
    @click="
      ({ trigger, position }) =>
        updateViewState({
          detail: {
            table: table.name,
            trigger: keyWithPosition(trigger.name, position),
          },
        })
    "
  />
  <PartitionsTable
    v-show="state.view === 'PARTITIONS'"
    :db="db"
    :database="database"
    :schema="schema"
    :table="table"
    :keyword="state.keyword"
  />
</template>

<script setup lang="ts">
import { ChevronLeftIcon } from "lucide-vue-next";
import { NButton, NTab, NTabs } from "naive-ui";
import { computed, h, reactive, watch } from "vue";
import { useI18n } from "vue-i18n";
import {
  ColumnIcon,
  ForeignKeyIcon,
  IndexIcon,
  TableIcon,
  TablePartitionIcon,
  TriggerIcon,
} from "@/components/Icon";
import { SearchBox } from "@/components/v2";
import type {
  Database,
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { keyWithPosition } from "@/views/sql-editor/EditorCommon";
import { useCurrentTabViewStateContext } from "../../context/viewState";
import ColumnsTable from "./ColumnsTable.vue";
import ForeignKeysTable from "./ForeignKeysTable.vue";
import IndexesTable from "./IndexesTable.vue";
import PartitionsTable from "./PartitionsTable.vue";
import TriggersTable from "./TriggersTable.vue";

type View = "COLUMNS" | "INDEXES" | "FOREIGN-KEYS" | "PARTITIONS" | "TRIGGERS";
type LocalState = {
  view: View;
  keyword: string;
};

const props = defineProps<{
  db: Database;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table: TableMetadata;
}>();

const { t } = useI18n();
const { viewState, updateViewState } = useCurrentTabViewStateContext();
const state = reactive<LocalState>({
  view: "COLUMNS",
  keyword: "",
});

const tabItems = computed(() => {
  const items = [
    { view: "COLUMNS", text: t("database.columns"), icon: () => h(ColumnIcon) },
  ];
  const { table } = props;
  if (table.indexes.length > 0) {
    items.push({
      view: "INDEXES",
      text: t("schema-editor.index.indexes"),
      icon: () => h(IndexIcon),
    });
  }
  if (table.foreignKeys.length > 0) {
    items.push({
      view: "FOREIGN-KEYS",
      text: t("database.foreign-keys"),
      icon: () => h(ForeignKeyIcon),
    });
  }
  if (table.triggers.length > 0) {
    items.push({
      view: "TRIGGERS",
      text: t("db.triggers"),
      icon: () => h(TriggerIcon),
    });
  }
  if (table.partitions.length > 0) {
    items.push({
      view: "PARTITIONS",
      text: t("schema-editor.table-partition.partitions"),
      icon: () => h(TablePartitionIcon),
    });
  }
  return items;
});

const deselect = () => {
  updateViewState({
    detail: {},
  });
};

watch(
  [
    () => viewState.value?.detail.table,
    () => viewState.value?.detail.column,
    () => viewState.value?.detail.index,
    () => viewState.value?.detail.foreignKey,
    () => viewState.value?.detail.trigger,
    () => viewState.value?.detail.partition,
  ],
  ([table, column, index, foreignKey, trigger, partition]) => {
    if (!table) return;
    if (column) {
      state.view = "COLUMNS";
      return;
    }
    if (index) {
      state.view = "INDEXES";
      return;
    }
    if (foreignKey) {
      state.view = "FOREIGN-KEYS";
      return;
    }
    if (partition) {
      state.view = "PARTITIONS";
      return;
    }
    if (trigger) {
      state.view = "TRIGGERS";
      return;
    }
    // fallback
    state.view = "COLUMNS";
  },
  { immediate: true }
);
</script>

// frontend/src/react/components/sql-editor/Panels/TablesPanel/TableDetail.tsx
import {
  ChevronLeft,
  Columns,
  KeyRound,
  Layers,
  Link as LinkIcon,
  Table as TableIcon,
  Zap,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/react/components/ui/button";
import {
  Tabs,
  TabsList,
  TabsPanel,
  TabsTrigger,
} from "@/react/components/ui/tabs";
import type {
  Database,
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import {
  extractKeyWithPosition,
  keyWithPosition,
} from "@/views/sql-editor/EditorCommon/utils";
import { CodeViewer } from "../common/CodeViewer";
import { PanelSearchBox } from "../common/PanelSearchBox";
import { ColumnsTable } from "../common/tables/ColumnsTable";
import { ForeignKeysTable } from "../common/tables/ForeignKeysTable";
import { IndexesTable } from "../common/tables/IndexesTable";
import { PartitionsTable } from "../common/tables/PartitionsTable";
import { useViewStateNav } from "../common/useViewStateNav";
import { TriggersTable } from "../TriggersPanel/TriggersTable";

type TabView =
  | "COLUMNS"
  | "INDEXES"
  | "FOREIGN-KEYS"
  | "TRIGGERS"
  | "PARTITIONS";

interface TableDetailProps {
  db: Database;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table: TableMetadata;
}

export function TableDetail({ db, database, schema, table }: TableDetailProps) {
  const { t } = useTranslation();
  const { detail, setDetail, clearDetail } = useViewStateNav();
  const [tab, setTab] = useState<TabView>("COLUMNS");
  const [keyword, setKeyword] = useState("");

  // Sync the active tab with the detail anchor (column / index / FK /
  // partition / trigger). Mirrors the Vue watch in TableDetail.vue.
  useEffect(() => {
    if (!detail?.table) return;
    if (detail.column) {
      setTab("COLUMNS");
      return;
    }
    if (detail.index) {
      setTab("INDEXES");
      return;
    }
    if (detail.foreignKey) {
      setTab("FOREIGN-KEYS");
      return;
    }
    if (detail.partition) {
      setTab("PARTITIONS");
      return;
    }
    if (detail.trigger) {
      setTab("TRIGGERS");
      return;
    }
    setTab("COLUMNS");
  }, [
    detail?.table,
    detail?.column,
    detail?.index,
    detail?.foreignKey,
    detail?.partition,
    detail?.trigger,
  ]);

  const tabs = useMemo(() => {
    const out: { view: TabView; text: string; Icon: typeof Columns }[] = [
      { view: "COLUMNS", text: t("database.columns"), Icon: Columns },
    ];
    if (table.indexes.length > 0)
      out.push({
        view: "INDEXES",
        text: t("schema-editor.index.indexes"),
        Icon: KeyRound,
      });
    if (table.foreignKeys.length > 0)
      out.push({
        view: "FOREIGN-KEYS",
        text: t("database.foreign-keys"),
        Icon: LinkIcon,
      });
    if (table.triggers.length > 0)
      out.push({ view: "TRIGGERS", text: t("db.triggers"), Icon: Zap });
    if (table.partitions.length > 0)
      out.push({
        view: "PARTITIONS",
        text: t("schema-editor.table-partition.partitions"),
        Icon: Layers,
      });
    return out;
  }, [table, t]);

  // When a trigger row is clicked, the TRIGGERS tab swaps to a CodeViewer.
  const [triggerName, triggerPosition] = extractKeyWithPosition(
    detail?.trigger ?? ""
  );
  const trigger =
    detail?.trigger && detail.trigger !== "-1"
      ? table.triggers.find(
          (tr, i) => tr.name === triggerName && i === triggerPosition
        )
      : undefined;

  const deselectTrigger = () => {
    setDetail({ trigger: "-1" });
  };

  if (trigger) {
    return (
      <CodeViewer
        db={db}
        title={trigger.name}
        code={trigger.body}
        onBack={deselectTrigger}
        titlePrefix={
          <Button
            variant="ghost"
            className="h-8 px-1 text-sm"
            onClick={deselectTrigger}
          >
            <ChevronLeft className="size-5" />
            <Zap className="size-4 text-control" />
            <span className="truncate">{trigger.name}</span>
          </Button>
        }
      />
    );
  }

  return (
    <Tabs
      value={tab}
      onValueChange={(value) => setTab(value as TabView)}
      className="h-full flex flex-col overflow-hidden"
    >
      <div className="flex items-center justify-between gap-x-3 px-2 py-1 border-b border-block-border shrink-0">
        <div className="flex items-center gap-x-3 min-w-0">
          <Button
            variant="ghost"
            className="h-8 px-1 text-sm shrink-0"
            onClick={() => clearDetail()}
          >
            <ChevronLeft className="size-5" />
            <TableIcon className="size-4 text-control" />
            <span className="truncate">{table.name}</span>
          </Button>
          {tabs.length > 1 ? (
            <TabsList className="gap-x-3">
              {tabs.map(({ view, text, Icon }) => (
                <TabsTrigger
                  key={view}
                  value={view}
                  className="flex items-center gap-x-1 pb-1.5"
                >
                  <Icon className="size-4" />
                  {text}
                </TabsTrigger>
              ))}
            </TabsList>
          ) : null}
        </div>
        <PanelSearchBox value={keyword} onChange={setKeyword} />
      </div>
      <TabsPanel value="COLUMNS" className="flex-1 min-h-0 mt-0">
        <ColumnsTable
          db={db}
          database={database}
          schema={schema}
          table={table}
          columns={table.columns}
          flavor="table"
          keyword={keyword}
        />
      </TabsPanel>
      {table.indexes.length > 0 ? (
        <TabsPanel value="INDEXES" className="flex-1 min-h-0 mt-0">
          <IndexesTable table={table} keyword={keyword} />
        </TabsPanel>
      ) : null}
      {table.foreignKeys.length > 0 ? (
        <TabsPanel value="FOREIGN-KEYS" className="flex-1 min-h-0 mt-0">
          <ForeignKeysTable db={db} table={table} keyword={keyword} />
        </TabsPanel>
      ) : null}
      {table.triggers.length > 0 ? (
        <TabsPanel value="TRIGGERS" className="flex-1 min-h-0 mt-0">
          <TriggersTable
            table={table}
            triggers={table.triggers}
            keyword={keyword}
            onSelect={({ trigger: target, position }) =>
              setDetail({
                table: table.name,
                trigger: keyWithPosition(target.name, position),
              })
            }
          />
        </TabsPanel>
      ) : null}
      {table.partitions.length > 0 ? (
        <TabsPanel value="PARTITIONS" className="flex-1 min-h-0 mt-0">
          <PartitionsTable table={table} keyword={keyword} />
        </TabsPanel>
      ) : null}
    </Tabs>
  );
}
