// frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesTable.vue
<template>
  <div ref="containerElRef" class="w-full h-full overflow-x-auto">
    <NDataTable
      v-bind="$attrs"
      ref="dataTableRef"
      size="small"
      :row-key="(table) => table.name"
      :columns="columns"
      :data="layoutReady ? filteredTables : []"
      :row-props="rowProps"
      :max-height="tableBodyHeight"
      :virtual-scroll="true"
      :striped="true"
      :bordered="true"
      :bottom-bordered="true"
      row-class-name="cursor-pointer"
    />
  </div>
</template>

<script setup lang="tsx">
import { type DataTableColumn, NDataTable } from "naive-ui";
import { computed, h, watch } from "vue";
import { useI18n } from "vue-i18n";
import type {
  Database,
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import {
  bytesToString,
  getHighlightHTMLByRegExp,
  getInstanceResource,
  hasIndexSizeProperty,
  hasTableEngineProperty,
  instanceV1HasCollationAndCharacterSet,
  useAutoHeightDataTable,
} from "@/utils";
import { EllipsisCell } from "../../common";
import { useCurrentTabViewStateContext } from "../../context/viewState";

const props = defineProps<{
  db: Database;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  tables: TableMetadata[];
  keyword?: string;
  maxHeight?: number;
}>();

const emit = defineEmits<{
  (
    event: "click",
    metadata: {
      database: DatabaseMetadata;
      schema: SchemaMetadata;
      table: TableMetadata;
    }
  ): void;
}>();

const { viewState } = useCurrentTabViewStateContext();
const { t } = useI18n();
const instanceResource = computed(() => {
  return getInstanceResource(props.db);
});

const filteredTables = computed(() => {
  const keyword = props.keyword?.trim().toLowerCase();
  if (keyword) {
    return props.tables.filter((table) =>
      table.name.toLowerCase().includes(keyword)
    );
  }
  return props.tables;
});
const {
  dataTableRef,
  containerElRef,
  virtualListRef,
  tableBodyHeight,
  layoutReady,
} = useAutoHeightDataTable(
  filteredTables,
  computed(() => ({
    maxHeight: props.maxHeight ? props.maxHeight : null,
  }))
);

const columns = computed(() => {
  const downGrade = filteredTables.value.length > 50;
  const columns: (DataTableColumn<TableMetadata> & { hide?: boolean })[] = [
    {
      key: "name",
      title: t("schema-editor.database.name"),
      resizable: true,
      className: "truncate",
      render: (table) => {
        return h("span", {
          innerHTML: getHighlightHTMLByRegExp(table.name, props.keyword ?? ""),
        });
      },
    },
    {
      key: "engine",
      title: t("schema-editor.database.engine"),
      hide: !hasTableEngineProperty(instanceResource.value),
      resizable: true,
      minWidth: 120,
      maxWidth: 180,
    },
    {
      key: "collation",
      title: t("schema-editor.database.collation"),
      hide: !instanceV1HasCollationAndCharacterSet(instanceResource.value),
      resizable: true,
      minWidth: 120,
      maxWidth: 180,
    },
    {
      key: "rowCountEst",
      title: t("database.row-count-est"),
      resizable: true,
      minWidth: 120,
      maxWidth: 180,
      render: (row) => {
        return String(row.rowCount);
      },
    },
    {
      key: "dataSize",
      title: t("database.data-size"),
      resizable: true,
      minWidth: 120,
      maxWidth: 180,
      render: (row) => {
        return bytesToString(Number(row.dataSize));
      },
    },
    {
      key: "indexSize",
      title: t("database.index-size"),
      hide: !hasIndexSizeProperty(instanceResource.value),
      resizable: true,
      minWidth: 120,
      maxWidth: 180,
      render: (row) => {
        return bytesToString(Number(row.indexSize));
      },
    },
    {
      key: "comment",
      title: t("schema-editor.database.comment"),
      resizable: true,
      minWidth: 140,
      maxWidth: 320,
      className: "overflow-hidden",
      render: (table) => {
        return h(EllipsisCell, {
          content: table.comment,
          downGrade,
        });
      },
    },
  ];
  return columns.filter((col) => !col.hide);
});

const rowProps = (table: TableMetadata) => {
  return {
    onClick: () => {
      emit("click", {
        database: props.database,
        schema: props.schema,
        table,
      });
    },
  };
};

watch(
  [() => viewState.value?.detail.table, virtualListRef],
  ([table, vl]) => {
    if (table && vl) {
      vl.scrollTo({ key: table });
    }
  },
  { immediate: true }
);
</script>

<style lang="postcss" scoped>
:deep(.n-data-table-th .n-data-table-resize-button::after) {
  background-color: rgb(var(--color-control-bg));
  height: 66.666667%;
}
:deep(.n-data-table-td.input-cell) {
  padding-left: 0.125rem;
  padding-right: 0.25rem;
  padding-top: 0;
  padding-bottom: 0;
}
</style>

// frontend/src/react/components/sql-editor/Panels/TablesPanel/TablesTable.tsx
import { useEffect, useMemo, useRef } from "react";
import { useTranslation } from "react-i18next";
import { HighlightLabelText } from "@/react/components/HighlightLabelText";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/react/components/ui/table";
import type {
  Database,
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { bytesToString, getInstanceResource } from "@/utils";
import {
  hasIndexSizeProperty,
  hasTableEngineProperty,
  instanceV1HasCollationAndCharacterSet,
} from "@/utils/v1/instance";
import { EllipsisCell } from "../common/EllipsisCell";
import { useViewStateNav } from "../common/useViewStateNav";

interface TablesTableProps {
  db: Database;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  tables: TableMetadata[];
  keyword?: string;
  onSelect: (selected: {
    database: DatabaseMetadata;
    schema: SchemaMetadata;
    table: TableMetadata;
  }) => void;
}

export function TablesTable({
  db,
  database,
  schema,
  tables,
  keyword,
  onSelect,
}: TablesTableProps) {
  const { t } = useTranslation();
  const { detail } = useViewStateNav();
  const containerRef = useRef<HTMLDivElement>(null);

  const filtered = useMemo(() => {
    const trimmed = keyword?.trim().toLowerCase();
    if (!trimmed) return tables;
    return tables.filter((table) => table.name.toLowerCase().includes(trimmed));
  }, [tables, keyword]);

  const instance = useMemo(() => getInstanceResource(db), [db]);
  const showEngine = hasTableEngineProperty(instance);
  const showCollation = instanceV1HasCollationAndCharacterSet(instance);
  const showIndexSize = hasIndexSizeProperty(instance);

  const selectedKey = detail?.table;

  useEffect(() => {
    if (!selectedKey) return;
    const el = containerRef.current?.querySelector<HTMLElement>(
      `[data-key="${CSS.escape(selectedKey)}"]`
    );
    el?.scrollIntoView({ block: "nearest" });
  }, [selectedKey]);

  return (
    <div ref={containerRef} className="w-full h-full overflow-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{t("schema-editor.database.name")}</TableHead>
            {showEngine ? (
              <TableHead>{t("schema-editor.database.engine")}</TableHead>
            ) : null}
            {showCollation ? (
              <TableHead>{t("schema-editor.database.collation")}</TableHead>
            ) : null}
            <TableHead>{t("database.row-count-est")}</TableHead>
            <TableHead>{t("database.data-size")}</TableHead>
            {showIndexSize ? (
              <TableHead>{t("database.index-size")}</TableHead>
            ) : null}
            <TableHead>{t("schema-editor.database.comment")}</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {filtered.map((table) => (
            <TableRow
              key={table.name}
              data-key={table.name}
              data-state={selectedKey === table.name ? "selected" : undefined}
              className="cursor-pointer"
              onClick={() => onSelect({ database, schema, table })}
            >
              <TableCell className="truncate max-w-[280px]">
                <HighlightLabelText text={table.name} keyword={keyword} />
              </TableCell>
              {showEngine ? (
                <TableCell className="truncate">{table.engine}</TableCell>
              ) : null}
              {showCollation ? (
                <TableCell className="truncate">{table.collation}</TableCell>
              ) : null}
              <TableCell>{String(table.rowCount)}</TableCell>
              <TableCell>{bytesToString(Number(table.dataSize))}</TableCell>
              {showIndexSize ? (
                <TableCell>{bytesToString(Number(table.indexSize))}</TableCell>
              ) : null}
              <TableCell className="truncate max-w-[320px]">
                <EllipsisCell content={table.comment} />
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
