// frontend/src/react/components/sql-editor/TabItem/Label.tsx
import { create } from "@bufbuild/protobuf";
import { useEffect, useRef, useState } from "react";
import { EllipsisText } from "@/react/components/ui/ellipsis-text";
import { cn } from "@/react/lib/utils";
import { useSQLEditorTabStore, useWorkSheetStore } from "@/store";
import { WorksheetSchema } from "@/types/proto-es/v1/worksheet_service_pb";
import type { SQLEditorTab } from "@/types/sqlEditor/tab";
import { tabListEvents } from "@/views/sql-editor/TabList/events";

type Props = {
  readonly tab: SQLEditorTab;
};

/**
 * Replaces frontend/src/views/sql-editor/TabList/TabItem/Label.vue.
 * Tab title with:
 *  - Double-click to enter in-place rename.
 *  - Listens for external `rename-tab` events (fired from the context menu)
 *    so right-click → Rename still works during the Vue → React migration.
 *  - Ellipsis + native tooltip via EllipsisText.
 */
export function Label({ tab }: Props) {
  const tabStore = useSQLEditorTabStore();
  const worksheetStore = useWorkSheetStore();

  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(tab.title);
  const inputRef = useRef<HTMLInputElement>(null);

  const readonly = tab.viewState.view !== "CODE";

  const beginEdit = () => {
    if (readonly) return;
    setDraft(tab.title);
    setEditing(true);
  };

  const cancelEdit = () => {
    setEditing(false);
    setDraft(tab.title);
  };

  const confirmEdit = () => {
    const title = draft.trim();
    if (title === "") {
      cancelEdit();
      return;
    }
    tabStore.updateTab(tab.id, { title });
    if (tab.worksheet) {
      void worksheetStore.patchWorksheet(
        create(WorksheetSchema, {
          name: tab.worksheet,
          title,
        }),
        ["title"]
      );
    }
    setEditing(false);
  };

  // Select all text on mount (fires only when a new edit session starts via
  // the `editing` transition).
  useEffect(() => {
    if (editing) {
      // Defer so the input is actually mounted before we focus + select.
      requestAnimationFrame(() => {
        inputRef.current?.focus();
        inputRef.current?.select();
      });
    }
  }, [editing]);

  // Keep draft in sync when the tab title updates from elsewhere (auto-save,
  // worksheet fetch) while not editing.
  useEffect(() => {
    if (!editing) {
      setDraft(tab.title);
    }
  }, [tab.title, editing]);

  // Respond to external rename-tab events (fired from the context menu).
  // `readonly` + `tab.id` are the only closure values we care about; the
  // other helpers are referentially stable via the Pinia store singletons.
  useEffect(() => {
    const unsubscribe = tabListEvents.on("rename-tab", (payload) => {
      if (payload.tab.id !== tab.id) return;
      tabStore.setCurrentTabId(tab.id);
      if (readonly) return;
      setDraft(tab.title);
      setEditing(true);
    });
    return () => {
      unsubscribe();
    };
  }, [tab.id, tab.title, readonly, tabStore]);

  return (
    <div
      className={cn(
        "label relative min-w-24 max-w-64 overflow-hidden",
        tab.status === "CLEAN" && "clean",
        tab.status === "DIRTY" && "dirty",
        tab.status === "SAVING" && "saving"
      )}
    >
      {/* Keep the title mounted (just `invisible`) while editing so the
          parent retains its line-height; otherwise the empty text collapses
          the relative container and the `absolute inset-0` input shrinks to
          zero height → the cursor is visible but the text field is not. */}
      <EllipsisText
        text={tab.title}
        className={cn("text-sm leading-5 block", editing && "invisible")}
      />
      {/* Invisible "expand" dbl-click layer — EllipsisText strips onDblClick */}
      {!editing && !readonly && (
        <div
          className="absolute inset-0 cursor-text"
          onDoubleClick={beginEdit}
        />
      )}
      {editing && (
        <input
          ref={inputRef}
          type="text"
          className="absolute inset-0 border-0 border-b p-0 text-sm leading-5 bg-background"
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onBlur={confirmEdit}
          onKeyDown={(e) => {
            if (e.nativeEvent.isComposing) return;
            if (e.key === "Enter") {
              (e.target as HTMLInputElement).blur();
            } else if (e.key === "Escape") {
              cancelEdit();
            }
          }}
        />
      )}
    </div>
  );
}

// frontend/src/views/sql-editor/TabList/TabItem/Label.vue
<template>
  <div class="label" :class="[tab.status.toLowerCase()]">
    <NEllipsis
      class="name"
      :tooltip="{
        placement: 'top',
        delay: 250,
      }"
      :class="state.editing && 'invisible'"
      @dblclick="beginEdit"
    >
      {{ state.title }}
    </NEllipsis>

    <input
      v-if="state.editing"
      ref="inputRef"
      v-model="state.title"
      type="text"
      class="edit"
      @blur="confirmEdit"
      @keyup.enter="(e) => (e.target as HTMLInputElement).blur()"
      @keyup.esc="cancelEdit"
    />
  </div>
</template>
<script lang="ts" setup>
import { create } from "@bufbuild/protobuf";
import { NEllipsis } from "naive-ui";
import { computed, nextTick, reactive, ref, watch } from "vue";
import { useEmitteryEventListener } from "@/composables/useEmitteryEventListener";
import {
  useSQLEditorTabStore,
  useWorkSheetStore,
  useTabViewStateStore,
} from "@/store";
import type { SQLEditorTab } from "@/types";
import { WorksheetSchema } from "@/types/proto-es/v1/worksheet_service_pb";
import { useTabListContext } from "../context";

type LocalState = {
  editing: boolean;
  title: string;
};

const props = defineProps<{
  tab: SQLEditorTab;
}>();

const state = reactive<LocalState>({
  editing: false,
  title: props.tab.title,
});

const tabStore = useSQLEditorTabStore();
const worksheetV1Store = useWorkSheetStore();
const tabViewStateStore = useTabViewStateStore();
const inputRef = ref<HTMLInputElement>();
const { events } = useTabListContext();

const readonly = computed(
  () => tabViewStateStore.getViewState(props.tab.id).view !== "CODE"
);

const isCurrentTab = computed(() => props.tab.id === tabStore.currentTabId);

useEmitteryEventListener(events, "rename-tab", ({ tab }) => {
  if (tab.id === props.tab.id) {
    tabStore.setCurrentTabId(tab.id);
    beginEdit();
  }
});

const beginEdit = () => {
  if (readonly.value) {
    return;
  }
  state.editing = true;
  state.title = props.tab.title;
  nextTick(() => {
    inputRef.value?.focus();
  });
};

const confirmEdit = () => {
  const { tab } = props;

  const title = state.title.trim();
  if (title === "") {
    return cancelEdit();
  }

  tab.title = title;
  tab.status = "DIRTY";
  if (tab.worksheet) {
    worksheetV1Store
      .patchWorksheet(
        create(WorksheetSchema, {
          name: tab.worksheet,
          title,
        }),
        ["title"]
      )
      .then(() => {
        tab.status = "CLEAN";
      });
  }

  state.editing = false;
};

const cancelEdit = () => {
  state.editing = false;
  state.title = props.tab.title;
};

watch(
  () => props.tab.title,
  (title) => {
    state.title = title;
  }
);
watch(isCurrentTab, (value) => {
  if (!value) {
    cancelEdit();
  }
});
</script>

<style scoped lang="postcss">
.label {
  @apply relative flex items-center whitespace-nowrap min-w-[6rem] max-w-[12rem] truncate;
}

.label :deep(.name) {
  @apply h-6 w-full flex items-center text-sm;
}
.edit {
  @apply border-0 border-b absolute inset-0 p-0 text-sm;
}

.label.new :deep(.name) {
  @apply italic;
}
</style>
