// frontend/src/modules/sql-editor/components/TabItem/Prefix.tsx
import { PencilLine, Users, Wrench } from "lucide-react";
import { useSheetContext } from "@/modules/sql-editor/model/Sheet";
import { useAppStore } from "@/stores/app";
import type { SQLEditorTab } from "@/types/sqlEditor/tab";
import { SheetConnectionIcon } from "../SheetConnectionIcon";

type Props = {
  readonly tab: SQLEditorTab;
};

/**
 * Replaces frontend/src/views/sql-editor/TabList/TabItem/Prefix.vue.
 * Leading icons on a tab row:
 *  - Pencil for draft (no worksheet yet).
 *  - Users glyph when viewing someone else's shared worksheet.
 *  - Wrench when the tab is in ADMIN mode.
 *  - Engine icon / unlink glyph via SheetConnectionIcon.
 */
export function Prefix({ tab }: Props) {
  const { isWorksheetCreator } = useSheetContext();

  const isDraft = !tab.worksheet && tab.viewState.view === "CODE";

  const sheet = useAppStore((s) =>
    tab.worksheet ? s.getWorksheetByName(tab.worksheet) : null
  );

  return (
    <div className="opacity-80 flex items-center gap-x-2">
      {isDraft ? (
        <PencilLine className="size-4" />
      ) : (
        <>
          {sheet && !isWorksheetCreator(sheet) && <Users className="size-4" />}
          {tab.mode === "ADMIN" && <Wrench className="size-4" />}
        </>
      )}
      <SheetConnectionIcon tab={tab} />
    </div>
  );
}

// frontend/src/views/sql-editor/TabList/TabItem/Prefix.vue
<template>
  <div class="opacity-80 flex items-center gap-x-2">
    <PencilLineIcon v-if="isDraft" class="w-4 h-4" />
    <template v-else>
      <UsersIcon
        v-if="sheet && !isWorksheetCreator(sheet)"
        class="w-4 h-4"
      />
      <WrenchIcon v-if="tab.mode === 'ADMIN'" class="w-4 h-4" />
    </template>
    <ReactPageMount page="SheetConnectionIcon" :tab="tab" />
  </div>
</template>

<script lang="ts" setup>
import { PencilLineIcon, UsersIcon, WrenchIcon } from "lucide-vue-next";
import { computed } from "vue";
import ReactPageMount from "@/react/ReactPageMount.vue";
import { useWorkSheetStore } from "@/store";
import type { SQLEditorTab } from "@/types";
import { useSheetContext } from "@/views/sql-editor/Sheet";

const props = defineProps<{
  tab: SQLEditorTab;
}>();

const sheetV1Store = useWorkSheetStore();
const { isWorksheetCreator } = useSheetContext();

const isDraft = computed(() => {
  const { worksheet, viewState } = props.tab;
  if (worksheet) {
    return false;
  }
  return viewState.view === "CODE";
});

const sheet = computed(() => {
  const { worksheet: sheetName } = props.tab;
  if (sheetName) {
    const sheet = sheetV1Store.getWorksheetByName(sheetName);
    if (sheet) {
      return sheet;
    }
  }
  return null;
});
</script>
