// frontend/src/modules/sql-editor/components/TabItem/TabItem.tsx
import { useSortable } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { useState } from "react";
import { useAppDatabase } from "@/hooks/useAppDatabase";
import { cn } from "@/lib/utils";
import { useSQLEditorTabState } from "@/modules/sql-editor/store/tab";
import { useAppStore } from "@/stores/app";
import { isValidDatabaseName } from "@/types";
import { UNKNOWN_ID } from "@/types/const";
import type { SQLEditorTab } from "@/types/sqlEditor/tab";
import { hexToRgb } from "@/utils";
import { AdminLabel } from "./AdminLabel";
import { Label } from "./Label";
import { Prefix } from "./Prefix";
import { Suffix } from "./Suffix";

type Props = {
  readonly tab: SQLEditorTab;
  readonly index: number;
  readonly onSelect: (tab: SQLEditorTab, index: number) => void;
  readonly onClose: (tab: SQLEditorTab, index: number) => void;
  readonly onContextMenu: (
    tab: SQLEditorTab,
    index: number,
    e: React.MouseEvent
  ) => void;
};

/**
 * One row in the tab bar. Composes Prefix + (Label|AdminLabel) + Suffix,
 * handles left-click to select + contextmenu emit, and ties into @dnd-kit's
 * sortable for drag-reorder inside TabList.
 */
export function TabItem({
  tab,
  index,
  onSelect,
  onClose,
  onContextMenu,
}: Props) {
  const currentTabId = useSQLEditorTabState((s) => s.currentTabId);
  const [hovering, setHovering] = useState(false);

  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: tab.id });

  const isCurrentTab = tab.id === currentTabId;

  // Derive the environment tint (used as the top border on the current tab).
  // Subscribes via the app store so the tab re-renders when the database
  // and its environment hydrate async — without this the tab sticks on
  // the fallback `#4f46e5` indigo and looks more saturated than intended.
  const database = useAppDatabase(tab.connection.database ?? "");
  const environmentTintColor = useAppStore((s) => {
    if (!isValidDatabaseName(database.name)) return undefined;
    const environment = s.getEnvironmentByName(
      database.effectiveEnvironment ?? ""
    );
    if (!environment || environment.id === String(UNKNOWN_ID)) return undefined;
    return environment.color || undefined;
  });
  // Per-environment tint only. The active-tab fallback (no env color) is
  // themed via the `accent` token classes below instead of a hardcoded indigo,
  // so it stays readable in dark themes.
  const envColorRgb =
    isCurrentTab && environmentTintColor
      ? hexToRgb(environmentTintColor).join(", ")
      : "";

  const bodyStyle = envColorRgb
    ? {
        backgroundColor: `rgba(${envColorRgb}, 0.1)`,
        borderTopColor: `rgb(${envColorRgb})`,
        color: `rgb(${envColorRgb})`,
      }
    : undefined;

  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.3 : undefined,
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      data-tab-id={tab.id}
      className={cn(
        "tab-item cursor-pointer border-r bg-background relative",
        "gap-x-2",
        isCurrentTab && "current",
        hovering && "bg-control-bg",
        `status-${tab.status.toLowerCase()}`
      )}
      {...attributes}
      {...listeners}
      onMouseEnter={() => setHovering(true)}
      onMouseLeave={() => setHovering(false)}
      onMouseDown={(e) => {
        if (e.button !== 0) return;
        onSelect(tab, index);
      }}
      onContextMenu={(e) => {
        e.preventDefault();
        e.stopPropagation();
        onContextMenu(tab, index, e);
      }}
    >
      <div
        className={cn(
          "body flex items-center justify-between gap-x-2 pl-2 pr-1 border-t h-9",
          isCurrentTab ? "pt-0.5 border-t-[3px] bg-background" : "pt-1",
          // Active tab without a per-environment color: accent token (adapts to
          // light/dark) replaces the old hardcoded indigo that was dim on dark.
          isCurrentTab &&
            !envColorRgb &&
            "border-accent text-accent bg-accent/10"
        )}
        style={bodyStyle}
      >
        <Prefix tab={tab} />
        {tab.mode === "ADMIN" ? <AdminLabel tab={tab} /> : <Label tab={tab} />}
        <Suffix tab={tab} onClose={() => onClose(tab, index)} />
      </div>
    </div>
  );
}

// frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue
<template>
  <div
    class="tab-item"
    :class="[
      {
        current: isCurrentTab,
        hovering: state.hovering,
      },
      tab.status.toLowerCase(),
    ]"
    :data-status="tab.status"
    :data-sheet="tab.worksheet"
    :data-connection="JSON.stringify(tab.connection)"
    @mousedown.left="$emit('select', tab, index)"
    @mouseenter="state.hovering = true"
    @mouseleave="state.hovering = false"
  >
    <div
      class="body"
      :style="
        backgroundColorRgb.length > 0
          ? {
              backgroundColor: `rgba(${backgroundColorRgb[0]}, ${backgroundColorRgb[1]}, ${backgroundColorRgb[2]}, 0.5)`,
              borderTopColor: `rgb(${backgroundColorRgb[0]}, ${backgroundColorRgb[1]}, ${backgroundColorRgb[2]})`,
              color: `rgb(${backgroundColorRgb[0]}, ${backgroundColorRgb[1]}, ${backgroundColorRgb[2]})`,
            }
          : {}
      "
    >
      <Prefix :tab="tab" />
      <Label v-if="tab.mode === 'WORKSHEET'" :tab="tab" />
      <AdminLabel v-else :tab="tab" />
      <Suffix :tab="tab" @close="$emit('close', tab, index)" />
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed, reactive } from "vue";
import { useSQLEditorTabStore } from "@/store";
import { type SQLEditorTab, UNKNOWN_ENVIRONMENT_NAME } from "@/types";
import { connectionForSQLEditorTab, hexToRgb } from "@/utils";
import AdminLabel from "./AdminLabel.vue";
import Label from "./Label.vue";
import Prefix from "./Prefix.vue";
import Suffix from "./Suffix.vue";

type LocalState = {
  hovering: boolean;
};

const props = defineProps<{
  tab: SQLEditorTab;
  index: number;
}>();

defineEmits<{
  (e: "select", tab: SQLEditorTab, index: number): void;
  (e: "close", tab: SQLEditorTab, index: number): void;
}>();

const state = reactive<LocalState>({
  hovering: false,
});

const tabStore = useSQLEditorTabStore();

const isCurrentTab = computed(() => props.tab.id === tabStore.currentTabId);

const environment = computed(() => {
  const { database } = connectionForSQLEditorTab(props.tab);
  const environment = database?.effectiveEnvironmentEntity;
  if (environment?.name === UNKNOWN_ENVIRONMENT_NAME) {
    return;
  }
  return environment;
});

const backgroundColorRgb = computed(() => {
  if (!isCurrentTab.value) {
    return [];
  }
  if (!environment.value || !environment.value.color) {
    return hexToRgb("#4f46e5");
  }
  return hexToRgb(environment.value.color);
});
</script>

<style scoped lang="postcss">
.tab-item {
  @apply cursor-pointer border-r bg-white gap-x-2 relative;
}
.hovering {
  @apply bg-gray-50;
}
.tab-item.admin {
  @apply !bg-dark-bg;
}

.body {
  @apply flex items-center justify-between gap-x-1 pl-2 pr-1 border-t pt-[4px] h-[36px];
}
.current .body {
  @apply relative bg-white border-t-[3px] pt-[2px];
}

.tab-item.admin .body {
  @apply text-matrix-green-hover;
}
.tab-item.admin.current .body {
  @apply !bg-dark-bg border-matrix-green-hover;
}
</style>
