// frontend/src/views/sql-editor/EditorPanel/Panels/TriggersPanel/TriggersPanel.vue
<template>
    <div v-if="metadata?.schema" class="h-full overflow-hidden flex flex-col">
      <div
        v-show="!metadata.trigger"
        class="w-full h-[44px] py-2 px-2 border-b flex flex-row gap-x-2 justify-end items-center"
      >
        <SearchBox
          v-model:value="state.keyword"
          size="small"
          style="width: 10rem"
        />
      </div>
      <TriggersTable
        v-show="!metadata.trigger"
        :db="database"
        :database="metadata.database"
        :schema="metadata.schema"
        :table="metadata.table"
        :triggers="metadata.table?.triggers"
        :keyword="state.keyword"
        @click="select"
      />
  
      <template v-if="metadata.trigger">
        <CodeViewer
          :db="database"
          :title="metadata.trigger.name"
          :code="metadata.trigger.body"
          @back="deselect"
        >
          <template #title-icon>
            <TriggerIcon class="w-4 h-4 text-main" />
          </template>
        </CodeViewer>
      </template>
    </div>
  </template>
  
  <script setup lang="ts">
  import { computed, reactive } from "vue";
  import { SearchBox } from "@/components/v2";
  import {
    useConnectionOfCurrentSQLEditorTab,
    useDBSchemaV1Store,
  } from "@/store";
  import {
    TriggerMetadata,
  } from "@/types/proto/v1/database_service";
  import {
    extractKeyWithPosition,
    keyWithPosition,
  } from "@/views/sql-editor/EditorCommon";
  import { useCurrentTabViewStateContext } from "../../context/viewState";
  import { CodeViewer } from "../common";
  import TriggersTable from "./TriggersTable.vue";
  import TriggerIcon from "@/components/Icon/TriggerIcon.vue";
  
  const { database } = useConnectionOfCurrentSQLEditorTab();
  const { viewState, updateViewState } = useCurrentTabViewStateContext();
  const databaseMetadata = computed(() => {
    return useDBSchemaV1Store().getDatabaseMetadata(database.value.name);
  });
  const state = reactive({
    keyword: "",
  });
  
  const metadata = computed(() => {
    const database = databaseMetadata.value;
    const schema = database.schemas.find(
      (s) => s.name === viewState.value?.schema
    );
    const table = schema?.tables.find(
      (t) => t.name === viewState.value?.table
    );
    const [name, position] = extractKeyWithPosition(
      viewState.value?.detail?.trigger ?? ""
    );
    const trigger = table?.triggers.find(
      (p, i) => p.name === name && i === position
    );
    return { database, schema, table, trigger };
  });
  
  const select = (selected: {
    trigger: TriggerMetadata;
    position: number;
  }) => {
    updateViewState({
      detail: {
        trigger: keyWithPosition(selected.trigger.name, selected.position),
      },
    });
  };
  
  const deselect = () => {
    updateViewState({
      detail: {},
    });
  };
  </script>

// frontend/src/react/components/sql-editor/Panels/TriggersPanel/TriggersPanel.tsx
import { ChevronLeft, Zap } from "lucide-react";
import { useState } from "react";
import { Button } from "@/react/components/ui/button";
import { useVueState } from "@/react/hooks/useVueState";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
} from "@/store";
import {
  extractKeyWithPosition,
  keyWithPosition,
} from "@/views/sql-editor/EditorCommon/utils";
import { CodeViewer } from "../common/CodeViewer";
import { PanelSearchBox } from "../common/PanelSearchBox";
import { useViewStateNav } from "../common/useViewStateNav";
import { TriggersTable } from "./TriggersTable";

/**
 * Standalone TriggersPanel. The Vue version reads `viewState.table` to
 * scope the trigger list to a specific table; the React port preserves
 * that behavior.
 */
export function TriggersPanel() {
  const dbSchemaStore = useDBSchemaV1Store();
  const { database } = useConnectionOfCurrentSQLEditorTab();
  const databaseName = useVueState(() => database.value.name);
  const db = useVueState(() => database.value);
  const databaseMetadata = useVueState(
    () => dbSchemaStore.getDatabaseMetadata(databaseName ?? ""),
    { deep: true }
  );

  const {
    schema: schemaName,
    viewState,
    detail,
    setDetail,
    clearDetail,
  } = useViewStateNav();

  const [keyword, setKeyword] = useState("");

  const schema = databaseMetadata?.schemas.find((s) => s.name === schemaName);
  const table = schema?.tables.find((t) => t.name === viewState?.table);

  const [triggerName, triggerPosition] = extractKeyWithPosition(
    detail?.trigger ?? ""
  );
  const trigger = table?.triggers.find(
    (tr, i) => tr.name === triggerName && i === triggerPosition
  );

  if (!db || !databaseMetadata || !schema) return null;

  if (trigger) {
    return (
      <CodeViewer
        db={db}
        title={trigger.name}
        code={trigger.body}
        onBack={() => clearDetail()}
        titlePrefix={
          <Button
            variant="ghost"
            className="h-8 px-1 text-sm"
            onClick={() => clearDetail()}
          >
            <ChevronLeft className="size-5" />
            <Zap className="size-4 text-control" />
            <span className="truncate">{trigger.name}</span>
          </Button>
        }
      />
    );
  }

  return (
    <div className="h-full overflow-hidden flex flex-col">
      <div className="w-full h-11 py-2 px-2 border-b border-block-border flex flex-row gap-x-2 justify-end items-center">
        <PanelSearchBox value={keyword} onChange={setKeyword} />
      </div>
      <div className="flex-1 min-h-0">
        <TriggersTable
          table={table}
          triggers={table?.triggers}
          keyword={keyword}
          onSelect={({ trigger: target, position }) =>
            setDetail({ trigger: keyWithPosition(target.name, position) })
          }
        />
      </div>
    </div>
  );
}
