// frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/HoverPanel.vue
<template>
  <div
    ref="popoverRef"
    v-zindexable="{ enabled: true }"
    class="fixed border border-gray-100 rounded bg-white p-2 shadow transition-[top] text-sm"
    :class="[show ? 'visible' : ' invisible pointer-events-none']"
    :style="{
      left: `${displayPosition.x}px`,
      top: `${displayPosition.y}px`,
    }"
  >
    <template v-if="state">
      <ColumnInfo
        v-if="state.column && state.table"
        :database="state.database"
        :schema="state.schema"
        :table="state.table"
        :column="state.column"
      />
      <TablePartitionInfo
        v-else-if="state.table && state.partition"
        :database="state.database"
        :schema="state.schema"
        :table="state.table"
        :partition="state.partition"
      />
      <TableInfo
        v-else-if="state.table"
        :database="state.database"
        :schema="state.schema"
        :table="state.table"
      />
      <ExternalTableInfo
        v-else-if="state.externalTable"
        :database="state.database"
        :schema="state.schema"
        :external-table="state.externalTable"
      />
      <ViewInfo
        v-else-if="state.view"
        :database="state.database"
        :schema="state.schema"
        :view="state.view"
      />
    </template>
  </div>
</template>

<script setup lang="ts">
import { onClickOutside, useElementSize, useEventListener } from "@vueuse/core";
import { zindexable as vZindexable } from "vdirs";
import { computed, ref } from "vue";
import type { Position } from "@/types";
import { minmax } from "@/utils";
import ColumnInfo from "./ColumnInfo.vue";
import ExternalTableInfo from "./ExternalTableInfo.vue";
import TableInfo from "./TableInfo.vue";
import TablePartitionInfo from "./TablePartitionInfo.vue";
import ViewInfo from "./ViewInfo.vue";
import { useHoverStateContext } from "./hover-state";

const props = defineProps<{
  offsetX: number;
  offsetY: number;
  margin: number;
}>();

const emit = defineEmits<{
  (event: "click-outside", e: MouseEvent): void;
}>();

const { state, position, update } = useHoverStateContext();

const popoverRef = ref<HTMLDivElement>();
onClickOutside(popoverRef, (e) => {
  emit("click-outside", e);
});
const { height: popoverHeight } = useElementSize(popoverRef, undefined, {
  box: "border-box",
});

const show = computed(() => {
  const show =
    state.value !== undefined &&
    position.value.x !== 0 &&
    position.value.y !== 0;
  return show;
});

const displayPosition = computed(() => {
  const p: Position = {
    x: position.value.x + props.offsetX,
    y: position.value.y + props.offsetY,
  };
  const yMin = props.margin;
  const yMax = window.innerHeight - popoverHeight.value - props.margin;
  p.y = minmax(p.y, yMin, yMax);

  return p;
});

useEventListener(popoverRef, "mouseenter", () => {
  // Keep the hover panel visible with a small delay to prevent flicker
  update(state.value, "before", 50);
});
useEventListener(popoverRef, "mouseleave", () => {
  update(undefined, "after");
});
</script>

// frontend/src/modules/sql-editor/components/SchemaPane/HoverPanel/HoverPanel.tsx
import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { getLayerRoot, LAYER_SURFACE_CLASS } from "@/components/ui/layer";
import { cn } from "@/lib/utils";
import type { Position } from "@/types";
import { minmax } from "@/utils";
import { useHoverState } from "../hover-state";
import { ColumnInfo } from "./ColumnInfo";
import { ExternalTableInfo } from "./ExternalTableInfo";
import { TableInfo } from "./TableInfo";
import { TablePartitionInfo } from "./TablePartitionInfo";
import { ViewInfo } from "./ViewInfo";

type Props = {
  readonly offsetX: number;
  readonly offsetY: number;
  readonly margin: number;
  readonly onClickOutside?: (e: MouseEvent) => void;
};

/**
 * Floating, cursor-anchored panel that previews schema metadata for the
 * hovered tree row. Most-specific shape wins:
 *   column + table → ColumnInfo
 *   table  + partition → TablePartitionInfo
 *   table              → TableInfo
 *   externalTable      → ExternalTableInfo
 *   view               → ViewInfo
 *
 * Position is driven by `useHoverState()`'s sparse `state` + cursor
 * `position`. The y coordinate is clamped so the panel never escapes the
 * viewport. Mounted into the shared overlay layer via a portal so the
 * absolute coords are document-relative regardless of where SchemaPane
 * lives in the DOM.
 *
 * Hover-keep: mouseenter on the panel itself reschedules the open delay
 * to 50ms so the panel doesn't flash off when the cursor crosses from a
 * row onto the panel. mouseleave triggers the standard 350ms close.
 */
export function HoverPanel({
  offsetX,
  offsetY,
  margin,
  onClickOutside,
}: Props) {
  const { state, position, update } = useHoverState();
  const popoverRef = useRef<HTMLDivElement | null>(null);
  const [popoverHeight, setPopoverHeight] = useState(0);

  useLayoutEffect(() => {
    const el = popoverRef.current;
    if (!el) return;
    setPopoverHeight(el.getBoundingClientRect().height);
    const ro = new ResizeObserver(() => {
      setPopoverHeight(el.getBoundingClientRect().height);
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, [state]);

  const show = state !== undefined && position.x !== 0 && position.y !== 0;

  const displayPosition = useMemo<Position>(() => {
    const p: Position = {
      x: position.x + offsetX,
      y: position.y + offsetY,
    };
    if (typeof window !== "undefined") {
      const yMin = margin;
      const yMax = window.innerHeight - popoverHeight - margin;
      p.y = minmax(p.y, yMin, yMax);
    }
    return p;
  }, [position, offsetX, offsetY, margin, popoverHeight]);

  useEffect(() => {
    if (!show || !onClickOutside) return;
    const handler = (e: MouseEvent) => {
      const el = popoverRef.current;
      if (el && !el.contains(e.target as Node)) {
        onClickOutside(e);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [show, onClickOutside]);

  // Render nothing at all when there's no state to show — avoids a stray
  // 0×0 element sitting at top-left until the user hovers something.
  if (!state) return null;

  let body: React.ReactNode = null;
  if (state.column && state.table) {
    body = (
      <ColumnInfo
        database={state.database}
        schema={state.schema}
        table={state.table}
        column={state.column}
      />
    );
  } else if (state.table && state.partition) {
    body = (
      <TablePartitionInfo
        database={state.database}
        schema={state.schema}
        table={state.table}
        partition={state.partition}
      />
    );
  } else if (state.table) {
    body = (
      <TableInfo
        database={state.database}
        schema={state.schema}
        table={state.table}
      />
    );
  } else if (state.externalTable) {
    body = (
      <ExternalTableInfo
        database={state.database}
        schema={state.schema}
        externalTable={state.externalTable}
      />
    );
  } else if (state.view) {
    body = (
      <ViewInfo
        database={state.database}
        schema={state.schema}
        view={state.view}
      />
    );
  }

  const panel = (
    <div
      ref={popoverRef}
      className={cn(
        "fixed border border-block-border rounded-sm bg-background p-2 shadow-sm transition-[top] text-sm",
        LAYER_SURFACE_CLASS,
        !show && "invisible pointer-events-none"
      )}
      style={{
        left: `${displayPosition.x}px`,
        top: `${displayPosition.y}px`,
      }}
      onMouseEnter={() => update(state, "before", 50)}
      onMouseLeave={() => update(undefined, "after")}
    >
      {body}
    </div>
  );

  if (typeof document === "undefined") return null;
  return createPortal(panel, getLayerRoot("overlay"));
}
