// frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/TableInfo.vue
<template>
  <div class="min-w-[14rem] max-w-[18rem] gap-y-1">
    <InfoItem :title="$t('common.name')">
      {{ name }}
    </InfoItem>
    <InfoItem v-if="engine" :title="$t('database.engine')">
      {{ engine }}
    </InfoItem>
    <InfoItem :title="$t('database.row-count-estimate')">
      {{ table.rowCount }}
    </InfoItem>
    <InfoItem :title="$t('database.data-size')">
      {{ bytesToString(table.dataSize.toNumber()) }}
    </InfoItem>
    <InfoItem v-if="indexSize" :title="$t('database.index-size')">
      {{ indexSize }}
    </InfoItem>
    <InfoItem v-if="collation" :title="$t('db.collation')">
      {{ collation }}
    </InfoItem>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { ComposedDatabase } from "@/types";
import { Engine } from "@/types/proto/v1/common";
import {
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto/v1/database_service";
import { bytesToString } from "@/utils";
import InfoItem from "./InfoItem.vue";

const props = defineProps<{
  db: ComposedDatabase;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table: TableMetadata;
}>();

const instanceEngine = computed(() => props.db.instanceEntity.engine);

const hasSchemaProperty = computed(() => {
  return [Engine.POSTGRES, Engine.RISINGWAVE].includes(instanceEngine.value);
});

const name = computed(() => {
  const { schema, table } = props;
  if (hasSchemaProperty.value) {
    return `${schema.name}.${table.name}`;
  }
  return table.name;
});

const engine = computed(() => {
  if ([Engine.POSTGRES, Engine.SNOWFLAKE].includes(instanceEngine.value)) {
    return "";
  }
  return props.table.engine;
});

const indexSize = computed(() => {
  if ([Engine.CLICKHOUSE, Engine.SNOWFLAKE].includes(instanceEngine.value)) {
    return "";
  }
  return bytesToString(props.table.indexSize.toNumber());
});

const collation = computed(() => {
  if (
    [Engine.CLICKHOUSE, Engine.SNOWFLAKE, Engine.POSTGRES].includes(
      instanceEngine.value
    )
  ) {
    return "";
  }
  return props.table.collation;
});
</script>

// frontend/src/modules/sql-editor/components/SchemaPane/HoverPanel/TableInfo.tsx
import { useTranslation } from "react-i18next";
import { EngineIcon } from "@/components/EngineIcon";
import { useAppDatabase } from "@/hooks/useAppDatabase";
import { useAppStore } from "@/stores/app";
import { Engine } from "@/types/proto-es/v1/common_pb";
import { bytesToString, getInstanceResource } from "@/utils";
import { engineNameV1 } from "@/utils/v1/instance";
import { InfoItem } from "./InfoItem";

type Props = {
  readonly database: string;
  readonly schema?: string;
  readonly table: string;
};

/**
 * Index size and collation are hidden for ClickHouse + Snowflake; collation
 * is also hidden for Postgres because the engine reports it at the column
 * level instead of the table level. Comment is shown only when present.
 */
export function TableInfo({ database, schema, table }: Props) {
  const { t } = useTranslation();
  const databaseEntity = useAppDatabase(database);
  const tableMetadata = useAppStore((s) =>
    s.getTableMetadata({ database, schema, table })
  );
  const instanceEngine = getInstanceResource(databaseEntity).engine;

  const indexSize =
    instanceEngine === Engine.CLICKHOUSE || instanceEngine === Engine.SNOWFLAKE
      ? ""
      : bytesToString(Number(tableMetadata.indexSize));
  const collation =
    instanceEngine === Engine.CLICKHOUSE ||
    instanceEngine === Engine.SNOWFLAKE ||
    instanceEngine === Engine.POSTGRES
      ? ""
      : tableMetadata.collation;
  const comment = tableMetadata.comment;

  return (
    <div className="min-w-56 max-w-[18rem] gap-y-1">
      <InfoItem title={t("common.name")}>{tableMetadata.name}</InfoItem>
      <InfoItem title={t("database.engine")}>
        <span className="flex items-center gap-x-1">
          <EngineIcon engine={instanceEngine} className="size-4" />
          {engineNameV1(instanceEngine)}
        </span>
      </InfoItem>
      <InfoItem title={t("database.row-count-estimate")}>
        {String(tableMetadata.rowCount)}
      </InfoItem>
      <InfoItem title={t("database.data-size")}>
        {bytesToString(Number(tableMetadata.dataSize))}
      </InfoItem>
      {indexSize ? (
        <InfoItem title={t("database.index-size")}>{indexSize}</InfoItem>
      ) : null}
      {collation ? (
        <InfoItem title={t("db.collation")}>{collation}</InfoItem>
      ) : null}
      {comment ? (
        <InfoItem title={t("database.comment")}>{comment}</InfoItem>
      ) : null}
    </div>
  );
}
