// frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ViewInfo.vue
<template>
  <CommonText :content="viewMetadata.comment" />
</template>

<script setup lang="tsx">
import { computed } from "vue";
import { useDBSchemaV1Store } from "@/store";
import CommonText from "./CommonText.vue";

const props = defineProps<{
  database: string;
  schema?: string;
  view: string;
}>();

const dbSchema = useDBSchemaV1Store();

const viewMetadata = computed(() =>
  dbSchema.getViewMetadata({
    database: props.database,
    schema: props.schema,
    view: props.view,
  })
);
</script>

// frontend/src/modules/sql-editor/components/SchemaPane/HoverPanel/ViewInfo.tsx
import { useAppStore } from "@/stores/app";
import { CommonText } from "./CommonText";

type Props = {
  readonly database: string;
  readonly schema?: string;
  readonly view: string;
};

/** Just the view's comment, wrapped. */
export function ViewInfo({ database, schema, view }: Props) {
  const viewMetadata = useAppStore((s) =>
    s.getViewMetadata({ database, schema, view })
  );
  return <CommonText content={viewMetadata.comment} />;
}
