// frontend/src/react/components/task-run-log/SectionHeader.tsx
import { ChevronDown, ChevronRight } from "lucide-react";
import type { ButtonHTMLAttributes } from "react";
import { cn } from "@/react/lib/utils";
import type { Section } from "./types";

export interface SectionHeaderProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, "onClick"> {
  section: Section;
  isExpanded: boolean;
  indent?: boolean;
  onToggle: () => void;
}

export function SectionHeader({
  section,
  isExpanded,
  indent = false,
  onToggle,
  className,
  ...props
}: SectionHeaderProps) {
  const StatusIcon = section.statusIcon;

  return (
    <button
      type="button"
      aria-expanded={isExpanded}
      className={cn(
        "flex w-full items-center gap-x-2 py-1.5 bg-white hover:bg-gray-50 cursor-pointer select-none text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2",
        indent ? "px-6" : "px-3",
        className
      )}
      onClick={onToggle}
      {...props}
    >
      {isExpanded ? (
        <ChevronDown className="h-3.5 w-3.5 shrink-0 text-gray-400" />
      ) : (
        <ChevronRight className="h-3.5 w-3.5 shrink-0 text-gray-400" />
      )}
      <StatusIcon
        className={cn(
          "h-3.5 w-3.5 shrink-0",
          section.statusClass,
          section.status === "running" && "animate-spin"
        )}
      />
      <span className="text-gray-700">{section.label}</span>
      {section.entryCount > 1 ? (
        <span className="text-gray-400">({section.entryCount})</span>
      ) : null}
      <span className="flex-1" />
      {section.duration ? (
        <span className="text-gray-500 tabular-nums">{section.duration}</span>
      ) : null}
    </button>
  );
}

export default SectionHeader;

// frontend/src/components/Plan/components/RolloutView/v2/TaskRunLogViewer/SectionHeader.vue
<template>
  <div
    class="flex items-center gap-x-2 py-1.5 bg-white hover:bg-gray-50 cursor-pointer select-none"
    :class="indent ? 'px-6' : 'px-3'"
    @click="$emit('toggle')"
  >
    <component
      :is="isExpanded ? ChevronDownIcon : ChevronRightIcon"
      class="w-3.5 h-3.5 text-gray-400 shrink-0"
    />
    <component
      :is="section.statusIcon"
      class="w-3.5 h-3.5 shrink-0"
      :class="[section.statusClass, { 'animate-spin': section.status === 'running' }]"
    />
    <span class="text-gray-700">{{ section.label }}</span>
    <span v-if="section.entryCount > 1" class="text-gray-400">
      ({{ section.entryCount }})
    </span>
    <span class="flex-1" />
    <span v-if="section.duration" class="text-gray-500 tabular-nums">
      {{ section.duration }}
    </span>
  </div>
</template>

<script lang="ts" setup>
import { ChevronDownIcon, ChevronRightIcon } from "lucide-vue-next";
import type { Section } from "./types";

defineProps<{
  section: Section;
  isExpanded: boolean;
  indent?: boolean;
}>();

defineEmits<{
  toggle: [];
}>();
</script>
