// frontend/src/components/SchemaDiagram/Navigator/TreeNode/Suffix.vue
<template>
  <template v-if="node.type === 'schema'">
    <!-- nothing -->
  </template>
  <template v-if="node.type === 'table'">
    <FocusButton
      :table="(node as TreeNode<'table'>).data"
      :set-center="true"
      class="focus-btn"
    />
  </template>
</template>

<script lang="ts" setup>
import { FocusButton } from "../../common";
import type { TreeNode } from "../types";

defineProps<{
  node: TreeNode;
}>();
</script>

<style lang="postcss">
.bb-schema-diagram-nav-tree .n-tree-node:hover .focus-btn {
  @apply !visible;
}
</style>

// frontend/src/react/components/SchemaDiagram/Navigator/TreeNode/Suffix.tsx
import { FocusButton } from "../../common/FocusButton";
import type { NavigatorTreeNode } from "../types";
import { isTypedNode } from "../utils";

interface SuffixProps {
  node: NavigatorTreeNode;
}

/** React port of `Navigator/TreeNode/Suffix.vue`. */
export function Suffix({ node }: SuffixProps) {
  if (isTypedNode(node, "table")) {
    return <FocusButton table={node.data} setCenter className="focus-btn" />;
  }
  return null;
}
