// frontend/src/react/components/sql-editor/ConnectionPane/DatabaseHoverPanel/DatabaseHoverPanel.tsx
import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useTranslation } from "react-i18next";
import { EnvironmentLabel } from "@/react/components/EnvironmentLabel";
import { getLayerRoot, LAYER_SURFACE_CLASS } from "@/react/components/ui/layer";
import { useVueState } from "@/react/hooks/useVueState";
import { cn } from "@/react/lib/utils";
import { useSQLEditorStore } from "@/store";
import type { Position, SQLEditorTreeNode } from "@/types";
import {
  getDatabaseProject,
  getInstanceResource,
  instanceV1Name,
  minmax,
  projectV1Name,
} from "@/utils";
import { useHoverState } from "./hover-state";

type Props = {
  readonly offsetX: number;
  readonly offsetY: number;
  readonly margin: number;
  readonly onClickOutside?: (e: MouseEvent) => void;
};

/**
 * Replaces frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/DatabaseHoverPanel/DatabaseHoverPanel.vue.
 * Floating panel anchored at the hovered tree row showing database context
 * (environment, instance, project, labels). Clamps the y coordinate so the
 * panel stays fully within the viewport.
 */
export function DatabaseHoverPanel({
  offsetX,
  offsetY,
  margin,
  onClickOutside,
}: Props) {
  const { t } = useTranslation();
  const editorStore = useSQLEditorStore();
  const { state, position, update } = useHoverState();

  const hasProjectContext = useVueState(() => !!editorStore.project);

  const popoverRef = useRef<HTMLDivElement | null>(null);
  const [popoverHeight, setPopoverHeight] = useState(0);

  useLayoutEffect(() => {
    const el = popoverRef.current;
    if (!el) return;
    setPopoverHeight(el.getBoundingClientRect().height);
    const ro = new ResizeObserver(() => {
      setPopoverHeight(el.getBoundingClientRect().height);
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, [state]);

  const database = useMemo(() => {
    if (!state?.node) return undefined;
    const { type, target } = state.node.meta;
    if (type !== "database") return undefined;
    return target as SQLEditorTreeNode<"database">["meta"]["target"];
  }, [state]);

  const show = state !== undefined && position.x !== 0 && position.y !== 0;

  const displayPosition = useMemo<Position>(() => {
    const p: Position = {
      x: position.x + offsetX,
      y: position.y + offsetY,
    };
    if (typeof window !== "undefined") {
      const yMin = margin;
      const yMax = window.innerHeight - popoverHeight - margin;
      p.y = minmax(p.y, yMin, yMax);
    }
    return p;
  }, [position, offsetX, offsetY, margin, popoverHeight]);

  useEffect(() => {
    if (!show || !onClickOutside) return;
    const handler = (e: MouseEvent) => {
      const el = popoverRef.current;
      if (el && !el.contains(e.target as Node)) {
        onClickOutside(e);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [show, onClickOutside]);

  if (!database && !show) return null;

  const panel = (
    <div
      ref={popoverRef}
      className={cn(
        "fixed border border-gray-100 rounded-sm bg-white p-2 shadow-sm transition-all text-sm",
        LAYER_SURFACE_CLASS,
        !show && "pointer-events-none opacity-0"
      )}
      style={{
        left: `${displayPosition.x}px`,
        top: `${displayPosition.y}px`,
      }}
      onMouseEnter={() => update(state, "before", 50)}
      onMouseLeave={() => update(undefined, "after")}
    >
      {database ? (
        <div
          className="grid min-w-56 max-w-[18rem] gap-x-2 gap-y-1"
          style={{ gridTemplateColumns: "auto 1fr" }}
        >
          <div className="contents">
            <div className="text-gray-500 font-medium">
              {t("common.environment")}
            </div>
            <div className="text-main text-right flex justify-end">
              <EnvironmentLabel
                environmentName={database.effectiveEnvironment}
              />
            </div>
          </div>
          <div className="contents">
            <div className="text-gray-500 font-medium">
              {t("common.instance")}
            </div>
            <div className="text-main text-right truncate">
              {instanceV1Name(getInstanceResource(database))}
            </div>
          </div>
          {!hasProjectContext && (
            <div className="contents">
              <div className="text-gray-500 font-medium">
                {t("common.project")}
              </div>
              <div className="text-main text-right truncate">
                {projectV1Name(getDatabaseProject(database))}
              </div>
            </div>
          )}
          <div className="contents">
            <div className="text-gray-500 font-medium">
              {t("common.labels")}
            </div>
            <div className="text-main flex flex-row justify-end flex-wrap gap-1">
              {Object.entries(database.labels).map(([key, value]) => (
                <div
                  key={key}
                  className="text-xs py-px px-1 bg-gray-200/75 rounded-xs"
                >
                  <span>{key}</span>
                  {value ? (
                    <>
                      <span>:</span>
                      <span>{value}</span>
                    </>
                  ) : null}
                </div>
              ))}
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );

  if (typeof document === "undefined") return null;
  return createPortal(panel, getLayerRoot("overlay"));
}

// frontend/src/views/sql-editor/AsidePanel/ConnectionPane/DatabaseHoverPanel/DatabaseHoverPanel.vue
<template>
  <div
    v-show="show && database"
    ref="popoverRef"
    v-zindexable="{ enabled: true }"
    class="fixed border border-gray-100 rounded bg-white p-2 shadow transition-all text-sm"
    :class="!show && 'pointer-events-none'"
    :style="{
      left: `${displayPosition.x}px`,
      top: `${displayPosition.y}px`,
    }"
  >
    <template v-if="database">
      <div
        class="grid min-w-[14rem] max-w-[18rem] gap-x-2 gap-y-1"
        style="grid-template-columns: auto 1fr"
      >
        <div class="contents">
          <div class="text-gray-500 font-medium">
            {{ $t("common.environment") }}
          </div>
          <div class="text-main text-right">
            <EnvironmentV1Name
              :environment="database.effectiveEnvironmentEntity"
              :link="false"
            />
          </div>
        </div>
        <div class="contents">
          <div class="text-gray-500 font-medium">
            {{ $t("common.instance") }}
          </div>
          <div class="text-main text-right">
            <InstanceV1Name :instance="database.instanceEntity" :link="false" />
          </div>
        </div>
        <div v-if="!hasProjectContext" class="contents">
          <div class="text-gray-500 font-medium">
            {{ $t("common.project") }}
          </div>
          <div class="text-main text-right">
            <ProjectV1Name :project="database.projectEntity" :link="false" />
          </div>
        </div>
        <div class="contents">
          <div class="text-gray-500 font-medium">{{ $t("common.labels") }}</div>
          <div class="text-main flex flex-row justify-end flex-wrap gap-1">
            <div
              v-for="(value, key) in database.labels"
              :key="key"
              class="text-xs py-px px-1 bg-gray-200/75 rounded-sm"
            >
              <span>{{ key }}</span>
              <template v-if="value">
                <span>:</span>
                <span>{{ value }}</span>
              </template>
            </div>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { onClickOutside, useElementSize, useEventListener } from "@vueuse/core";
import { zindexable as vZindexable } from "vdirs";
import { computed, ref } from "vue";
import {
  EnvironmentV1Name,
  InstanceV1Name,
  ProjectV1Name,
} from "@/components/v2";
import { useSQLEditorTreeStore } from "@/store";
import type { Position, SQLEditorTreeNodeTarget } from "@/types";
import { minmax } from "@/utils";
import { useHoverStateContext } from "./hover-state";

const props = defineProps<{
  offsetX: number;
  offsetY: number;
  margin: number;
}>();

const emit = defineEmits<{
  (event: "click-outside", e: MouseEvent): void;
}>();

const treeStore = useSQLEditorTreeStore();
const { state, position, update } = useHoverStateContext();

const popoverRef = ref<HTMLDivElement>();
onClickOutside(popoverRef, (e) => {
  emit("click-outside", e);
});
const { height: popoverHeight } = useElementSize(popoverRef, undefined, {
  box: "border-box",
});

const show = computed(
  () =>
    state.value !== undefined &&
    position.value.x !== 0 &&
    position.value.y !== 0
);
const database = computed(() => {
  if (!state.value?.node) return undefined;
  const { type, target } = state.value.node.meta;
  if (type !== "database") return undefined;
  return target as SQLEditorTreeNodeTarget<"database">;
});

const hasProjectContext = computed(() => {
  return !!treeStore.currentProject;
});

const displayPosition = computed(() => {
  const p: Position = {
    x: position.value.x + props.offsetX,
    y: position.value.y + props.offsetY,
  };
  const yMin = props.margin;
  const yMax = window.innerHeight - popoverHeight.value - props.margin;
  p.y = minmax(p.y, yMin, yMax);

  return p;
});

useEventListener(popoverRef, "mouseenter", () => {
  // Reset the value immediately to cancel other pending setting values
  update(state.value, "before", 0 /* overrideDelay */);
});
useEventListener(popoverRef, "mouseleave", () => {
  update(undefined, "before");
});
</script>
