// frontend/src/react/pages/project/database-detail/legacy/DatabaseObjectExplorer.vue
<template>
  <div>
    <div
      v-if="hasSchemaPropertyV1"
      class="mb-4 flex flex-row items-center justify-start"
    >
      <span class="mr-2 text-lg leading-6 font-medium text-main">
        {{ $t("common.schema") }}
      </span>
      <NSelect
        :value="selectedSchemaName"
        :options="schemaNameOptions"
        :disabled="loading"
        :placeholder="$t('database.schema.select')"
        class="w-auto! min-w-48"
        @update:value="
          $emit('update:selected-schema-name', (($event as string) ?? '').trim())
        "
      />
    </div>

    <template v-if="databaseEngine !== Engine.REDIS">
      <div class="mb-4 flex w-full flex-row items-center justify-between">
        <div class="text-lg leading-6 font-medium text-main">
          <span v-if="databaseEngine === Engine.MONGODB">
            {{ $t("db.collections") }}
          </span>
          <span v-else>{{ $t("db.tables") }}</span>
        </div>
        <SearchBox
          :value="tableSearchKeyword"
          :placeholder="$t('common.filter-by-name')"
          :disabled="loading"
          @update:value="$emit('update:table-search-keyword', $event)"
        />
      </div>

      <TableDataTable
        :database="database"
        :schema-name="selectedSchemaName"
        :table-list="tableList"
        :search="tableSearchKeyword.trim().toLowerCase()"
        :loading="loading"
      />

      <div class="mb-4 mt-6 text-lg leading-6 font-medium text-main">
        {{ $t("db.views") }}
      </div>
      <ViewDataTable
        :database="database"
        :schema-name="selectedSchemaName"
        :view-list="viewList"
        :loading="loading"
      />

      <template
        v-if="
          databaseEngine === Engine.POSTGRES || databaseEngine === Engine.HIVE
        "
      >
        <div class="mb-4 mt-6 flex w-full flex-row items-center justify-between">
          <div class="text-lg leading-6 font-medium text-main">
            {{ $t("db.external-tables") }}
          </div>
          <SearchBox
            :value="externalTableSearchKeyword"
            :placeholder="$t('common.filter-by-name')"
            :disabled="loading"
            @update:value="$emit('update:external-table-search-keyword', $event)"
          />
        </div>
        <ExternalTableDataTable
          :database="database"
          :schema-name="selectedSchemaName"
          :external-table-list="externalTableList"
          :search="externalTableSearchKeyword.trim().toLowerCase()"
          :loading="loading"
        />
      </template>

      <template v-if="databaseEngine === Engine.POSTGRES">
        <div class="mb-4 mt-6 text-lg leading-6 font-medium text-main">
          {{ $t("db.extensions") }}
        </div>
        <DBExtensionDataTable
          :db-extension-list="dbExtensionList"
          :loading="loading"
        />
      </template>

      <template
        v-if="
          databaseEngine === Engine.POSTGRES || databaseEngine === Engine.MSSQL
        "
      >
        <div class="mb-4 mt-6 text-lg leading-6 font-medium text-main">
          {{ $t("db.functions") }}
        </div>
        <FunctionDataTable
          :database="database"
          :schema-name="selectedSchemaName"
          :function-list="functionList"
          :loading="loading"
        />
      </template>

      <template v-if="instanceV1SupportsSequence(databaseEngine)">
        <div class="mb-4 mt-6 text-lg leading-6 font-medium text-main">
          {{ $t("db.sequences") }}
        </div>
        <SequenceDataTable
          :database="database"
          :schema-name="selectedSchemaName"
          :sequence-list="sequenceList"
          :loading="loading"
        />
      </template>

      <template v-if="databaseEngine === Engine.SNOWFLAKE">
        <div class="mb-4 mt-6 text-lg leading-6 font-medium text-main">
          {{ $t("db.streams") }}
        </div>
        <StreamTable
          :database="database"
          :schema-name="selectedSchemaName"
          :stream-list="streamList"
          :loading="loading"
        />

        <div class="mb-4 mt-6 text-lg leading-6 font-medium text-main">
          {{ $t("db.tasks") }}
        </div>
        <TaskTable
          :database="database"
          :schema-name="selectedSchemaName"
          :task-list="taskList"
          :loading="loading"
        />
      </template>

      <template v-if="instanceV1SupportsPackage(databaseEngine)">
        <div class="mb-4 mt-6 text-lg leading-6 font-medium text-main">
          {{ $t("db.packages") }}
        </div>
        <PackageDataTable
          :database="database"
          :schema-name="selectedSchemaName"
          :package-list="packageList"
          :loading="loading"
        />
      </template>
    </template>
  </div>
</template>
<script setup lang="ts">
import { NSelect } from "naive-ui";
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import DBExtensionDataTable from "@/components/DBExtensionDataTable.vue";
import ExternalTableDataTable from "@/components/ExternalTableDataTable.vue";
import FunctionDataTable from "@/components/FunctionDataTable.vue";
import PackageDataTable from "@/components/PackageDataTable.vue";
import SequenceDataTable from "@/components/SequenceDataTable.vue";
import StreamTable from "@/components/StreamTable.vue";
import TableDataTable from "@/components/TableDataTable.vue";
import TaskTable from "@/components/TaskTable.vue";
import ViewDataTable from "@/components/ViewDataTable.vue";
import { SearchBox } from "@/components/v2";
import { useDBSchemaV1Store } from "@/store";
import { Engine } from "@/types/proto-es/v1/common_pb";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import {
  getDatabaseEngine,
  hasSchemaProperty,
  instanceV1SupportsPackage,
  instanceV1SupportsSequence,
} from "@/utils";

const props = defineProps<{
  database: Database;
  loading: boolean;
  selectedSchemaName: string;
  tableSearchKeyword: string;
  externalTableSearchKeyword: string;
}>();

defineEmits<{
  (event: "update:selected-schema-name", value: string): void;
  (event: "update:table-search-keyword", value: string): void;
  (event: "update:external-table-search-keyword", value: string): void;
}>();

const dbSchemaStore = useDBSchemaV1Store();
const { t } = useI18n();

const databaseEngine = computed(() => {
  return getDatabaseEngine(props.database);
});

const hasSchemaPropertyV1 = computed(() => {
  return hasSchemaProperty(databaseEngine.value);
});

const schemaList = computed(() => {
  return dbSchemaStore.getSchemaList(props.database.name);
});

const schemaNameOptions = computed(() => {
  return schemaList.value.map((schema) => ({
    value: schema.name,
    label: schema.name || t("db.schema.default"),
  }));
});

const tableList = computed(() => {
  return dbSchemaStore.getTableList({
    database: props.database.name,
    schema: props.selectedSchemaName,
  });
});

const viewList = computed(() => {
  return dbSchemaStore.getViewList({
    database: props.database.name,
    schema: props.selectedSchemaName,
  });
});

const dbExtensionList = computed(() => {
  return dbSchemaStore.getExtensionList(props.database.name);
});

const externalTableList = computed(() => {
  return dbSchemaStore.getExternalTableList({
    database: props.database.name,
    schema: props.selectedSchemaName,
  });
});

const functionList = computed(() => {
  return dbSchemaStore.getFunctionList({
    database: props.database.name,
    schema: props.selectedSchemaName,
  });
});

const streamList = computed(() => {
  if (hasSchemaPropertyV1.value) {
    return (
      schemaList.value.find(
        (schema) => schema.name === props.selectedSchemaName
      )?.streams || []
    );
  }
  return dbSchemaStore
    .getDatabaseMetadata(props.database.name)
    .schemas.map((schema) => schema.streams)
    .flat();
});

const taskList = computed(() => {
  if (hasSchemaPropertyV1.value) {
    return (
      schemaList.value.find(
        (schema) => schema.name === props.selectedSchemaName
      )?.tasks || []
    );
  }
  return dbSchemaStore
    .getDatabaseMetadata(props.database.name)
    .schemas.map((schema) => schema.tasks)
    .flat();
});

const packageList = computed(() => {
  if (hasSchemaPropertyV1.value) {
    return (
      schemaList.value.find(
        (schema) => schema.name === props.selectedSchemaName
      )?.packages || []
    );
  }
  return dbSchemaStore
    .getDatabaseMetadata(props.database.name)
    .schemas.map((schema) => schema.packages)
    .flat();
});

const sequenceList = computed(() => {
  if (hasSchemaPropertyV1.value) {
    return (
      schemaList.value.find(
        (schema) => schema.name === props.selectedSchemaName
      )?.sequences || []
    );
  }
  return dbSchemaStore
    .getDatabaseMetadata(props.database.name)
    .schemas.map((schema) => schema.sequences)
    .flat();
});
</script>

// frontend/src/react/pages/project/database-detail/overview/DatabaseObjectExplorer.tsx
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Input } from "@/react/components/ui/input";
import { useVueState } from "@/react/hooks/useVueState";
import { useDBSchemaV1Store } from "@/store";
import { Engine } from "@/types/proto-es/v1/common_pb";
import type {
  Database,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import {
  bytesToString,
  getDatabaseEngine,
  hasSchemaProperty,
  instanceV1SupportsPackage,
  instanceV1SupportsSequence,
} from "@/utils";
import {
  type ObjectSectionRow,
  ObjectSectionTable,
} from "./ObjectSectionTable";
import { TableDetailDialog } from "./TableDetailDialog";

function filterByKeyword(name: string, keyword: string) {
  return name.toLowerCase().includes(keyword.trim().toLowerCase());
}

export function DatabaseObjectExplorer({
  database,
  loading,
  selectedSchemaName,
  tableSearchKeyword,
  externalTableSearchKeyword,
  onSelectedSchemaNameChange,
  onTableSearchKeywordChange,
  onExternalTableSearchKeywordChange,
}: {
  database: Database;
  loading: boolean;
  selectedSchemaName: string;
  tableSearchKeyword: string;
  externalTableSearchKeyword: string;
  onSelectedSchemaNameChange: (value: string) => void;
  onTableSearchKeywordChange: (value: string) => void;
  onExternalTableSearchKeywordChange: (value: string) => void;
}) {
  const { t } = useTranslation();
  const dbSchemaStore = useDBSchemaV1Store();
  const databaseEngine = getDatabaseEngine(database);
  const supportsSchema = hasSchemaProperty(databaseEngine);
  const schemaList = useVueState(() =>
    dbSchemaStore.getSchemaList(database.name)
  );
  const tableList = useVueState(() =>
    dbSchemaStore.getTableList({
      database: database.name,
      schema: selectedSchemaName,
    })
  );
  const viewList = useVueState(() =>
    dbSchemaStore.getViewList({
      database: database.name,
      schema: selectedSchemaName,
    })
  );
  const extensionList = useVueState(() =>
    dbSchemaStore.getExtensionList(database.name)
  );
  const externalTableList = useVueState(() =>
    dbSchemaStore.getExternalTableList({
      database: database.name,
      schema: selectedSchemaName,
    })
  );
  const functionList = useVueState(() =>
    dbSchemaStore.getFunctionList({
      database: database.name,
      schema: selectedSchemaName,
    })
  );
  const databaseMetadata = useVueState(() =>
    dbSchemaStore.getDatabaseMetadata(database.name)
  );
  const [selectedTable, setSelectedTable] = useState<TableMetadata>();

  const currentSchema =
    databaseMetadata.schemas.find(
      (schema) => schema.name === selectedSchemaName
    ) || databaseMetadata.schemas[0];

  const tableRows: ObjectSectionRow[] = tableList
    .filter((table) => filterByKeyword(table.name, tableSearchKeyword))
    .map((table) => ({
      key: table.name,
      name: table.name,
      description: `${String(table.rowCount)} rows, ${bytesToString(Number(table.dataSize))}`,
      comment: table.comment,
      onClick: () => setSelectedTable(table),
    }));

  const viewRows: ObjectSectionRow[] = viewList.map((view) => ({
    key: view.name,
    name: view.name,
    description: view.definition || "-",
    comment: view.comment,
  }));

  const externalTableRows: ObjectSectionRow[] = externalTableList
    .filter((table) => filterByKeyword(table.name, externalTableSearchKeyword))
    .map((table) => ({
      key: table.name,
      name: table.name,
      description:
        [table.externalServerName, table.externalDatabaseName]
          .filter(Boolean)
          .join(" / ") || "-",
    }));

  const extensionRows: ObjectSectionRow[] = extensionList.map((extension) => ({
    key: extension.name,
    name: extension.name,
    description: extension.version || "-",
    comment: extension.description,
  }));

  const functionRows: ObjectSectionRow[] = functionList.map((fn) => ({
    key: fn.name,
    name: fn.name,
    description: fn.signature || fn.definition || "-",
    comment: fn.comment,
  }));

  const sequenceRows: ObjectSectionRow[] = (currentSchema?.sequences || []).map(
    (sequence) => ({
      key: sequence.name,
      name: sequence.name,
      description: sequence.dataType || "-",
      comment: sequence.comment,
    })
  );

  const streamRows: ObjectSectionRow[] = (currentSchema?.streams || []).map(
    (stream) => ({
      key: stream.name,
      name: stream.name,
      description: stream.tableName || "-",
      comment: stream.comment,
    })
  );

  const taskRows: ObjectSectionRow[] = (currentSchema?.tasks || []).map(
    (task) => ({
      key: task.name,
      name: task.name,
      description: task.schedule || task.id || "-",
      comment: task.comment,
    })
  );

  const packageRows: ObjectSectionRow[] = (currentSchema?.packages || []).map(
    (pkg) => ({
      key: pkg.name,
      name: pkg.name,
      description: pkg.definition || "-",
    })
  );

  return (
    <div className="space-y-6 pt-6">
      {supportsSchema && (
        <div className="flex flex-wrap items-center gap-x-2 gap-y-2">
          <label
            className="text-lg font-medium text-main"
            htmlFor="schema-select"
          >
            {t("common.schema")}
          </label>
          <select
            id="schema-select"
            className="min-w-48 rounded-xs border border-control-border bg-white px-3 py-2 text-sm text-main"
            disabled={loading}
            value={selectedSchemaName}
            onChange={(event) =>
              onSelectedSchemaNameChange(event.target.value.trim())
            }
          >
            {schemaList.map((schema) => (
              <option key={schema.name} value={schema.name}>
                {schema.name || t("db.schema.default")}
              </option>
            ))}
          </select>
        </div>
      )}

      {databaseEngine !== Engine.REDIS && (
        <>
          <section className="space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div className="text-lg font-medium text-main">
                {databaseEngine === Engine.MONGODB
                  ? t("db.collections")
                  : t("db.tables")}
              </div>
              <Input
                className="w-full max-w-sm"
                disabled={loading}
                placeholder={t("common.filter-by-name")}
                value={tableSearchKeyword}
                onChange={(event) =>
                  onTableSearchKeywordChange(event.target.value)
                }
              />
            </div>
            <ObjectSectionTable rows={tableRows} />
          </section>

          <section className="space-y-4">
            <div className="text-lg font-medium text-main">{t("db.views")}</div>
            <ObjectSectionTable rows={viewRows} />
          </section>

          {(databaseEngine === Engine.POSTGRES ||
            databaseEngine === Engine.HIVE) && (
            <section className="space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="text-lg font-medium text-main">
                  {t("db.external-tables")}
                </div>
                <Input
                  className="w-full max-w-sm"
                  disabled={loading}
                  placeholder={t("common.filter-by-name")}
                  value={externalTableSearchKeyword}
                  onChange={(event) =>
                    onExternalTableSearchKeywordChange(event.target.value)
                  }
                />
              </div>
              <ObjectSectionTable rows={externalTableRows} />
            </section>
          )}

          {databaseEngine === Engine.POSTGRES && (
            <section className="space-y-4">
              <div className="text-lg font-medium text-main">
                {t("db.extensions")}
              </div>
              <ObjectSectionTable rows={extensionRows} />
            </section>
          )}

          {(databaseEngine === Engine.POSTGRES ||
            databaseEngine === Engine.MSSQL) && (
            <section className="space-y-4">
              <div className="text-lg font-medium text-main">
                {t("db.functions")}
              </div>
              <ObjectSectionTable rows={functionRows} />
            </section>
          )}

          {instanceV1SupportsSequence(databaseEngine) && (
            <section className="space-y-4">
              <div className="text-lg font-medium text-main">
                {t("db.sequences")}
              </div>
              <ObjectSectionTable rows={sequenceRows} />
            </section>
          )}

          {databaseEngine === Engine.SNOWFLAKE && (
            <>
              <section className="space-y-4">
                <div className="text-lg font-medium text-main">
                  {t("db.streams")}
                </div>
                <ObjectSectionTable rows={streamRows} />
              </section>
              <section className="space-y-4">
                <div className="text-lg font-medium text-main">
                  {t("db.tasks")}
                </div>
                <ObjectSectionTable rows={taskRows} />
              </section>
            </>
          )}

          {instanceV1SupportsPackage(databaseEngine) && (
            <section className="space-y-4">
              <div className="text-lg font-medium text-main">
                {t("db.packages")}
              </div>
              <ObjectSectionTable rows={packageRows} />
            </section>
          )}
        </>
      )}

      <TableDetailDialog
        open={!!selectedTable}
        table={selectedTable}
        onOpenChange={(open) => {
          if (!open) {
            setSelectedTable(undefined);
          }
        }}
      />
    </div>
  );
}
