// frontend/src/views/sql-editor/AsidePanel/WorksheetPane/FilterMenuItem.vue
<template>
  <div class="menu-item">
    <div class="flex flex-row items-center gap-x-4 justify-between">
      <span>{{ label }}</span>
      <NSwitch size="small" :value="value" @update:value="handleUpdate" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { NSwitch } from "naive-ui";

defineProps<{
  label: string;
  value: boolean;
}>();

const emit = defineEmits<{
  "update:value": [value: boolean];
}>();

const handleUpdate = (val: boolean) => {
  emit("update:value", val);
};
</script>

// frontend/src/react/components/sql-editor/FilterMenuItem.tsx
import { Switch } from "@/react/components/ui/switch";

type Props = {
  readonly label: string;
  readonly value: boolean;
  readonly onValueChange: (value: boolean) => void;
};

export function FilterMenuItem({ label, value, onValueChange }: Props) {
  return (
    <div className="flex flex-row items-center justify-between gap-x-4 px-3 py-2 text-sm">
      <span>{label}</span>
      <Switch size="sm" checked={value} onCheckedChange={onValueChange} />
    </div>
  );
}
