// frontend/src/views/sql-editor/EditorCommon/SchemaChooser.vue
<template>
  <ConnectChooser
    v-if="show"
    v-model:value="chosenSchema"
    :options="options"
    :is-chosen="isChosen"
    :placeholder="$t('database.schema.select')"
  />
</template>

<script setup lang="ts">
import { type SelectOption } from "naive-ui";
import { storeToRefs } from "pinia";
import { computed, watchEffect } from "vue";
import { useI18n } from "vue-i18n";
import { useRoute } from "vue-router";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
  useSQLEditorTabStore,
} from "@/store";
import { instanceAllowsSchemaScopedQuery } from "@/utils";
import { convertEngineToNew } from "@/utils/v1/common-conversions";
import ConnectChooser from "./ConnectChooser.vue";

const SchemaOptionValueUnspecified = "-1";

const { t } = useI18n();
const route = useRoute();
const { currentTab: tab } = storeToRefs(useSQLEditorTabStore());
const { database, instance } = useConnectionOfCurrentSQLEditorTab();
const show = computed(() => {
  return instanceAllowsSchemaScopedQuery(convertEngineToNew(instance.value.engine));
});

const databaseMetadata = computed(() => {
  return useDBSchemaV1Store().getDatabaseMetadata(database.value.name);
});
const options = computed(() => {
  const options = databaseMetadata.value.schemas.map<SelectOption>(
    (schema) => ({
      value: schema.name,
      label: schema.name || t("db.schema.default"),
    })
  );
  options.unshift({
    value: SchemaOptionValueUnspecified,
    label: t("database.schema.unspecified"),
  });
  return options;
});

const chosenSchema = computed<string>({
  get() {
    const schema = tab.value?.connection.schema;
    if (schema === undefined) return SchemaOptionValueUnspecified;
    return schema;
  },
  set(value) {
    if (!tab.value) return;
    tab.value.connection.schema =
      value === SchemaOptionValueUnspecified ? undefined : value;
  },
});

watchEffect(() => {
  if (route.query.schema) {
    chosenSchema.value = route.query.schema as string;
  }
});

const isChosen = computed(() => {
  return chosenSchema.value !== SchemaOptionValueUnspecified;
});
</script>

// frontend/src/react/components/sql-editor/SchemaChooser.tsx
import { useEffect, useMemo } from "react";
import { useTranslation } from "react-i18next";
import { useVueState } from "@/react/hooks/useVueState";
import { router } from "@/router";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
  useSQLEditorTabStore,
} from "@/store";
import { instanceAllowsSchemaScopedQuery } from "@/utils";
import { ConnectChooser } from "./ConnectChooser";

const SchemaOptionValueUnspecified = "-1";

/**
 * Replaces frontend/src/views/sql-editor/EditorCommon/SchemaChooser.vue.
 * Visible only for engines that support schema-scoped queries.
 * Selected schema persists to the current tab's connection.schema.
 */
export function SchemaChooser() {
  const { t } = useTranslation();
  const tabStore = useSQLEditorTabStore();
  const dbSchemaStore = useDBSchemaV1Store();
  const connection = useConnectionOfCurrentSQLEditorTab();

  const engine = useVueState(() => connection.instance.value.engine);
  const databaseName = useVueState(() => connection.database.value.name);
  const tabSchema = useVueState(() => tabStore.currentTab?.connection.schema);
  const schemas = useVueState(
    () => dbSchemaStore.getDatabaseMetadata(databaseName).schemas
  );

  const show = instanceAllowsSchemaScopedQuery(engine);

  const options = useMemo(() => {
    const opts = schemas.map((schema) => ({
      value: schema.name,
      label: schema.name || t("db.schema.default"),
    }));
    return [
      {
        value: SchemaOptionValueUnspecified,
        label: t("database.schema.unspecified"),
      },
      ...opts,
    ];
  }, [schemas, t]);

  const value =
    tabSchema === undefined ? SchemaOptionValueUnspecified : tabSchema;
  const isChosen = value !== SchemaOptionValueUnspecified;

  const handleChange = (next: string) => {
    if (!tabStore.currentTab) return;
    tabStore.currentTab.connection.schema =
      next === SchemaOptionValueUnspecified ? undefined : next;
  };

  // Seed from URL query parameter on mount and whenever the query param OR
  // the active tab changes. Mirrors Vue's watchEffect, which implicitly
  // tracked both `route.query.schema` and `tab.value` (the latter via the
  // setter's reactive reads) so that switching to a new tab with the URL
  // query still present re-seeded the new tab's connection.schema.
  const queryParam = useVueState(
    () => router.currentRoute.value.query.schema as string | undefined
  );
  const currentTabId = useVueState(() => tabStore.currentTab?.id);
  useEffect(() => {
    if (queryParam) handleChange(queryParam);
  }, [queryParam, currentTabId]);

  if (!show) return null;

  return (
    <ConnectChooser
      value={value}
      onChange={handleChange}
      options={options}
      isChosen={isChosen}
      placeholder={t("database.schema.select")}
    />
  );
}
