// frontend/src/layouts/SQLEditorLayout.vue
<template>
  <div class="relative h-screen overflow-hidden flex flex-col">
    <ul
      id="sql-editor-debug"
      class="hidden text-xs font-mono max-h-[33vh] max-w-[40vw] overflow-auto fixed bottom-0 right-0 p-2 bg-white/50 border border-gray-400 z-999999"
    ></ul>

    <BannersWrapper />
    <template v-if="ready">
      <ProvideSQLEditorContext />
    </template>
  </div>
</template>

<script lang="ts" setup>
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import BannersWrapper from "@/components/BannersWrapper.vue";
import ProvideSQLEditorContext from "@/components/ProvideSQLEditorContext.vue";
import { useEnvironmentV1Store, useSettingV1Store } from "@/store";
import { Setting_SettingName } from "@/types/proto-es/v1/setting_service_pb";
import { provideSQLEditorContext } from "@/views/sql-editor/context";
import { provideSheetContext } from "@/views/sql-editor/Sheet";
import { provideTabListContext } from "@/views/sql-editor/TabList/context";

const router = useRouter();

// provide context for SQL Editor
provideSQLEditorContext();
// provide context for sheets
provideSheetContext();
// provide context for tabs
provideTabListContext();

const ready = ref(false);

// We may tweak the resource loading here, and pre-load some frontend component
// resources, and make a loading screen here in the future.
const prepare = async () => {
  await router.isReady();

  await Promise.all([
    useSettingV1Store().getOrFetchSettingByName(
      Setting_SettingName.WORKSPACE_PROFILE
    ),
    useEnvironmentV1Store().fetchEnvironments(),
  ]);
  ready.value = true;
};

onMounted(prepare);
</script>

// frontend/src/react/components/sql-editor/SQLEditorLayout.tsx
import { useEffect, useState } from "react";
import { BannersWrapper } from "@/react/components/BannersWrapper";
import { router } from "@/router";
import { useEnvironmentV1Store, useSettingV1Store } from "@/store";
import { Setting_SettingName } from "@/types/proto-es/v1/setting_service_pb";
import { provideSheetContext } from "@/views/sql-editor/Sheet";
import { RequestDrawerHost } from "./RequestDrawerHost";
import { SQLEditorRouteShell } from "./SQLEditorRouteShell";
import { useSQLEditorAutoSave } from "./useSQLEditorAutoSave";

/**
 * React port of `frontend/src/layouts/SQLEditorLayout.vue`.
 *
 * Top-level shell of the SQL Editor route. Wires up:
 *  - the legacy `#sql-editor-debug` teleport target (kept hidden by
 *    default, used by debug `<li>` strings the inner shells emit).
 *  - the React `<BannersWrapper>` at the top.
 *  - workspace profile + environment fetch on mount, gated by Vue
 *    Router's `isReady()` so the SQL Editor doesn't bootstrap before
 *    initial route resolution.
 *  - `useSQLEditorAutoSave()` — the 2-second debounced worksheet
 *    auto-save extracted from the legacy `provideSQLEditorContext()`.
 *  - the `<SQLEditorRouteShell>` once `ready` flips true.
 */
export function SQLEditorLayout() {
  const settingStore = useSettingV1Store();
  const environmentStore = useEnvironmentV1Store();
  // Boots the per-view watchers (selectedKeys ↔ active tab) the moment
  // the layout appears. The sheet-context singleton is module-level and
  // lazy — calling it here ensures the watchers are wired before any
  // child component reads from it.
  provideSheetContext();

  const [ready, setReady] = useState(false);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      await router.isReady();
      await Promise.all([
        settingStore.getOrFetchSettingByName(
          Setting_SettingName.WORKSPACE_PROFILE
        ),
        environmentStore.fetchEnvironments(),
      ]);
      if (!cancelled) setReady(true);
    })();
    return () => {
      cancelled = true;
    };
  }, [settingStore, environmentStore]);

  useSQLEditorAutoSave();

  return (
    <div className="relative h-screen overflow-hidden flex flex-col">
      {/* Hidden teleport target inherited from the Vue layout. The debug
          probes (Pinia connection, current tab, etc.) write `<li>`
          children into this list when manually unhidden via dev tools.
          The fixed positioning is enough to stack above the editor body
          on its own — the legacy `z-999999` was a layering escape hatch
          that the React layering policy now forbids. */}
      <ul
        id="sql-editor-debug"
        className="hidden text-xs font-mono max-h-[33vh] max-w-[40vw] overflow-auto fixed bottom-0 right-0 p-2 bg-white/50 border border-gray-400"
      />
      <BannersWrapper />
      {ready && (
        <RequestDrawerHost>
          <SQLEditorRouteShell />
        </RequestDrawerHost>
      )}
    </div>
  );
}
