// frontend/src/views/sql-editor/EditorPanel/Welcome.vue
<template>
  <div
    class="w-full h-auto flex-grow flex flex-col items-center justify-center"
  >
    <HideInStandaloneMode>
      <BytebaseLogo component="span" class="mb-4 -mt-[10vh]" />
    </HideInStandaloneMode>
    <div class="flex flex-col items-start gap-y-2 w-max">
      <NButton
        type="primary"
        class="!w-full !justify-start"
        @click="changeConnection"
      >
        <template #icon>
          <LinkIcon class="w-4 h-4" />
        </template>
        {{ $t("sql-editor.connect-to-a-database") }}
      </NButton>
      <NButton
        v-if="showCreateInstanceButton"
        type="default"
        class="!w-full !justify-start"
        @click="gotoInstanceCreatePage"
      >
        <template #icon>
          <LayersIcon class="w-4 h-4" />
        </template>
        {{ $t("sql-editor.add-a-new-instance") }}
      </NButton>
      <NButton
        type="default"
        class="!w-full !justify-start"
        @click="createNewWorksheet"
      >
        <template #icon>
          <SquarePenIcon class="w-4 h-4" />
        </template>
        {{ $t("sql-editor.create-a-worksheet") }}
      </NButton>
    </div>
  </div>
</template>

<script setup lang="ts">
import { LayersIcon, LinkIcon, SquarePenIcon } from "lucide-vue-next";
import { NButton } from "naive-ui";
import { computed } from "vue";
import { useRouter } from "vue-router";
import BytebaseLogo from "@/components/BytebaseLogo.vue";
import HideInStandaloneMode from "@/components/misc/HideInStandaloneMode.vue";
import { SQL_EDITOR_SETTING_INSTANCE_MODULE } from "@/router/sqlEditor";
import { useSQLEditorTabStore } from "@/store";
import { useSidebarItems as useSettingItems } from "../Setting/Sidebar";
import { useSQLEditorContext } from "../context";

const { showConnectionPanel } = useSQLEditorContext();
const { itemList: settingItemList } = useSettingItems();
const router = useRouter();

const showCreateInstanceButton = computed(() => {
  return (
    settingItemList.value.findIndex(
      (item) => item.name === SQL_EDITOR_SETTING_INSTANCE_MODULE
    ) >= 0
  );
});

const changeConnection = () => {
  showConnectionPanel.value = true;
};

const createNewWorksheet = () => {
  useSQLEditorTabStore().addTab();
};

const gotoInstanceCreatePage = () => {
  if (
    settingItemList.value.findIndex(
      (item) => item.name === SQL_EDITOR_SETTING_INSTANCE_MODULE
    ) < 0
  ) {
    return;
  }
  router.push({
    name: SQL_EDITOR_SETTING_INSTANCE_MODULE,
    hash: `#add`,
  });
};
</script>

// frontend/src/react/components/sql-editor/Welcome.tsx
import { LayersIcon, LinkIcon } from "lucide-react";
import { useTranslation } from "react-i18next";
import { BytebaseLogo } from "@/react/components/BytebaseLogo";
import { usePermissionCheck } from "@/react/components/PermissionGuard";
import { useAppProject } from "@/react/hooks/useAppProject";
import { router } from "@/react/router";
import { INSTANCE_ROUTE_DASHBOARD } from "@/react/router/handles";
import { useSQLEditorEditorState } from "@/react/stores/sqlEditor/editor";
import { WelcomeButton } from "./WelcomeButton";

export type WelcomeProps = {
  /**
   * Called when the user clicks "Connect to a database". Vue parent
   * passes a callback that sets `asidePanelTab = "SCHEMA"` and
   * `showConnectionPanel = true` on the Vue-side SQL Editor context.
   */
  readonly onChangeConnection: () => void;
};

export function Welcome({ onChangeConnection }: WelcomeProps) {
  const { t } = useTranslation();
  const projectName = useSQLEditorEditorState((s) => s.project);

  const resolvedProject = useAppProject(projectName);
  const project = projectName ? resolvedProject : undefined;

  const [showCreateInstanceButton] = usePermissionCheck([
    "bb.instances.create",
  ]);
  const [showConnectButton] = usePermissionCheck(["bb.sql.select"], project);

  const handleCreateInstance = () => {
    router.push({
      name: INSTANCE_ROUTE_DASHBOARD,
      hash: "#add",
    });
  };

  return (
    <div className="w-full h-full flex flex-col items-center justify-center gap-y-4">
      <BytebaseLogo />
      <div className="flex items-center flex-wrap gap-4">
        {showCreateInstanceButton && (
          <WelcomeButton
            variant="secondary"
            icon={<LayersIcon strokeWidth={1.5} className="size-8" />}
            onClick={handleCreateInstance}
          >
            {t("sql-editor.add-a-new-instance")}
          </WelcomeButton>
        )}
        {showConnectButton && (
          <WelcomeButton
            variant="primary"
            icon={<LinkIcon strokeWidth={1.5} className="size-8" />}
            onClick={onChangeConnection}
          >
            {t("sql-editor.connect-to-a-database")}
          </WelcomeButton>
        )}
      </div>
    </div>
  );
}
