// frontend/src/plugins/ai/components/ChatView/Markdown/CodeBlock.vue
<template>
  <div
    ref="containerRef"
    class="flex flex-col overflow-x-hidden border border-gray-500 rounded-sm bg-white"
    :data-message-wrapper-width="messageWrapperWidth"
    :style="`width: ${combinedWidth}px`"
  >
    <div class="flex items-center justify-between px-1 pt-1">
      <div class="text-xs">SQL</div>
      <div class="flex items-center justify-end gap-2">
        <NPopover placement="bottom">
          <template #trigger>
            <button
              class="inline-flex items-center justify-center hover:text-accent cursor-pointer"
              @click="handleExecute"
            >
              <PlayIcon class="w-3.5 h-3.5" />
            </button>
          </template>
          <div class="whitespace-nowrap">
            {{ $t("common.run") }}
          </div>
        </NPopover>
        <NPopover placement="bottom">
          <template #trigger>
            <button
              class="inline-flex items-center justify-center hover:text-accent cursor-pointer"
              @click.capture="handleInsertAtCaret"
            >
              <InsertAtCaretIcon :size="14" />
            </button>
          </template>
          <div class="whitespace-nowrap">
            {{ $t("plugin.ai.actions.insert-at-caret") }}
          </div>
        </NPopover>
        <NPopover placement="bottom">
          <template #trigger>
            <CopyButton :content="code" />
          </template>
          <div class="whitespace-nowrap">
            {{ $t("common.copy") }}
          </div>
        </NPopover>
      </div>
    </div>

    <MonacoEditor
      :content="code"
      :readonly="true"
      :auto-focus="false"
      :auto-height="{
        min: 20,
        max: 120,
        padding: 2,
      }"
      :options="{
        fontSize: 12,
        lineHeight: 14,
        lineNumbers: 'off',
        wordWrap: 'on',
        scrollbar: {
          vertical: 'hidden',
          horizontal: 'hidden',
          useShadows: false,
          verticalScrollbarSize: 0,
          horizontalScrollbarSize: 0,
          alwaysConsumeMouseWheel: false,
        },
      }"
      class="h-auto"
    />
  </div>
</template>

<script lang="ts" setup>
import { useElementSize } from "@vueuse/core";
import { PlayIcon } from "lucide-vue-next";
import { NPopover } from "naive-ui";
import { computed, ref } from "vue";
import { MonacoEditor } from "@/components/MonacoEditor";
import { CopyButton } from "@/components/v2";
import { useAIContext } from "@/plugins/ai/logic";
import { findAncestor } from "@/utils";
import { useSQLEditorContext } from "@/views/sql-editor/context";
import InsertAtCaretIcon from "./InsertAtCaretIcon.vue";

export type CodeBlockProps = {
  width: number;
};

const props = defineProps<
  CodeBlockProps & {
    code: string;
  }
>();

const { events, showHistoryDialog } = useAIContext();
const { events: editorEvents } = useSQLEditorContext();
const containerRef = ref<HTMLElement>();
const messageWrapperRef = computed(() =>
  findAncestor(containerRef.value, ".message")
);
const { width: messageWrapperWidth } = useElementSize(messageWrapperRef);
const combinedWidth = computed(() => {
  const PADDING = 8;
  const min = 8 * 16; /* 8rem */
  const auto = messageWrapperWidth.value * props.width - PADDING * 2;
  return Math.max(min, auto);
});

const handleExecute = () => {
  events.emit("run-statement", {
    statement: props.code,
  });
  showHistoryDialog.value = false;
};

const handleInsertAtCaret = () => {
  const { code } = props;
  editorEvents.emit("insert-at-caret", {
    content: code,
  });
  showHistoryDialog.value = false;
};
</script>

// frontend/src/plugins/ai/react/ChatView/Markdown/CodeBlock.tsx
import { PlayIcon } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { MonacoEditor } from "@/react/components/monaco/MonacoEditor";
import { CopyButton } from "@/react/components/ui/copy-button";
import { Tooltip } from "@/react/components/ui/tooltip";
import { findAncestor } from "@/utils";
import { sqlEditorEvents } from "@/views/sql-editor/events";
import { useAIContext } from "../../context";

export type CodeBlockProps = {
  /** Fraction (0..1) of the parent `.message` width the snippet card occupies. */
  width: number;
};

type Props = CodeBlockProps & {
  code: string;
};

const MIN_WIDTH_PX = 8 * 16; // 8rem — same minimum as the Vue source.
const PADDING_PX = 8;

/**
 * React port of `plugins/ai/components/ChatView/Markdown/CodeBlock.vue`.
 *
 * Renders a SQL snippet inside a read-only `MonacoEditor` with three
 * actions:
 *   - Run: `aiContextEvents.emit("run-statement", { statement })`
 *     (the SQL editor host listens and executes the snippet)
 *   - Insert-at-caret: `sqlEditorEvents.emit("insert-at-caret", { content })`
 *   - Copy: writes to the clipboard with an ephemeral "Copied" indicator.
 *
 * Width is adaptive: measure the nearest `.message` ancestor (set by
 * `ChatView`) via ResizeObserver and clamp to `[MIN_WIDTH_PX, ...]`.
 * `width` is the fraction of the message bubble this card occupies —
 * `AIMessageView` passes `0.85`.
 */
export function CodeBlock({ code, width }: Props) {
  const { t } = useTranslation();
  const { events, setShowHistoryDialog } = useAIContext();

  const containerRef = useRef<HTMLDivElement | null>(null);
  // The message wrapper element is mounted by `ChatView` with the
  // `.message` class. We measure it (not our own container) so the
  // snippet can size relative to the bubble even when the bubble shrinks
  // due to a sibling layout change.
  const [messageWidth, setMessageWidth] = useState(0);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const messageEl = findAncestor(el, ".message");
    if (!(messageEl instanceof HTMLElement)) return;
    const update = () => setMessageWidth(messageEl.clientWidth);
    update();
    const observer = new ResizeObserver(update);
    observer.observe(messageEl);
    return () => observer.disconnect();
  }, []);

  const computedWidth = Math.max(
    MIN_WIDTH_PX,
    messageWidth * width - PADDING_PX * 2
  );

  const handleExecute = () => {
    events.emit("run-statement", { statement: code });
    setShowHistoryDialog(false);
  };

  const handleInsertAtCaret = () => {
    sqlEditorEvents.emit("insert-at-caret", { content: code });
    setShowHistoryDialog(false);
  };

  return (
    <div
      ref={containerRef}
      className="flex flex-col overflow-x-hidden border border-gray-500 rounded-sm bg-white"
      style={{ width: `${computedWidth}px` }}
    >
      <div className="flex items-center justify-between px-1 pt-1">
        <div className="text-xs">SQL</div>
        <div className="flex items-center justify-end gap-2">
          <Tooltip content={t("common.run")} side="bottom">
            <button
              type="button"
              className="inline-flex items-center justify-center hover:text-accent cursor-pointer"
              onClick={handleExecute}
              aria-label={t("common.run")}
            >
              <PlayIcon className="size-3.5" />
            </button>
          </Tooltip>
          <Tooltip
            content={t("plugin.ai.actions.insert-at-caret")}
            side="bottom"
          >
            <button
              type="button"
              className="inline-flex items-center justify-center hover:text-accent cursor-pointer"
              onClick={handleInsertAtCaret}
              aria-label={t("plugin.ai.actions.insert-at-caret")}
            >
              <InsertAtCaretIconCompact />
            </button>
          </Tooltip>
          <CopyButton content={code} />
        </div>
      </div>

      <MonacoEditor
        content={code}
        readOnly
        autoFocus={false}
        autoHeight
        min={20}
        max={120}
        options={{
          fontSize: 12,
          lineHeight: 14,
          lineNumbers: "off",
          wordWrap: "on",
          scrollbar: {
            vertical: "hidden",
            horizontal: "hidden",
            useShadows: false,
            verticalScrollbarSize: 0,
            horizontalScrollbarSize: 0,
            alwaysConsumeMouseWheel: false,
          },
        }}
        className="h-auto"
      />
    </div>
  );
}

/**
 * Inline copy of `InsertAtCaretIcon` at a fixed 14px to match the other
 * action buttons. Avoids an extra import + size prop juggling.
 */
function InsertAtCaretIconCompact() {
  return (
    <span
      style={{ width: 14, height: 14 }}
      className="relative inline-block"
      aria-hidden="true"
    >
      <svg
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <line x1="21" y1="6" x2="3" y2="6" />
        <line x1="15" y1="12" x2="3" y2="12" />
        <line x1="17" y1="18" x2="3" y2="18" />
      </svg>
    </span>
  );
}
