// frontend/src/views/Page403.vue
<template>
  <NoPermissionPlaceholder
    class="mx-6 my-2"
    :path="fromPath"
    :api="requestAPI"
    :resources="resources"
    :permissions="permissions"
  >
    <template #action>
      <div class="mt-2">
        <NButton size="small" @click.prevent="goHome">
          <template #icon><ChevronLeftIcon /></template>
          {{ $t("error-page.go-back-home") }}
        </NButton>
      </div>
    </template>
  </NoPermissionPlaceholder>
</template>

<script lang="ts" setup>
import { ChevronLeftIcon } from "lucide-vue-next";
import { NButton } from "naive-ui";
import { computed } from "vue";
import { useRoute, useRouter } from "vue-router";
import NoPermissionPlaceholder from "@/components/misc/NoPermissionPlaceholder.vue";
import { WORKSPACE_ROOT_MODULE } from "@/router/dashboard/workspaceRoutes";
import type { Permission } from "@/types";

const route = useRoute();
const router = useRouter();

const permissions = computed<Permission[]>(() => {
  const permQuery = route.query.permissions;
  if (typeof permQuery === "string" && permQuery) {
    return permQuery.split(",").filter((r) => r) as Permission[];
  }
  return [];
});

const resources = computed(() => {
  const resources = route.query.resources;
  if (typeof resources === "string") {
    return resources.split(",").filter((r) => r);
  }
  return [];
});

const fromPath = computed(() => {
  return route.query.from as string;
});

const requestAPI = computed(() => {
  return route.query.api as string;
});

const goHome = () => {
  router.push({ name: WORKSPACE_ROOT_MODULE });
};
</script>

// frontend/src/routes/workspace/Page403.tsx
import { ChevronLeft, ShieldAlert } from "lucide-react";
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { router } from "@/app/router";
import { WORKSPACE_ROUTE_LANDING } from "@/app/router/handles";
import { RouterLink } from "@/components/RouterLink";
import { buttonVariants } from "@/components/ui/button";
import type { Permission } from "@/types";

export function Page403() {
  const { t } = useTranslation();

  const query = useMemo(() => {
    const route = router.currentRoute.value;
    return route.query as Record<string, string | undefined>;
  }, []);

  const permissions = useMemo<Permission[]>(() => {
    const raw = query.permissions;
    if (raw) return raw.split(",").filter(Boolean) as Permission[];
    return [];
  }, [query]);

  const resources = useMemo(() => {
    const raw = query.resources;
    if (raw) return raw.split(",").filter(Boolean);
    return [];
  }, [query]);

  const fromPath = query.from;
  const requestAPI = query.api;

  return (
    <div className="mx-6 my-2">
      <div className="rounded-md border border-red-200 bg-red-50 p-4">
        <div className="flex items-start gap-3">
          <ShieldAlert className="h-5 w-5 text-red-600 mt-0.5 shrink-0" />
          <div className="flex flex-col gap-2">
            <div className="font-medium text-red-800">
              {t("common.missing-required-permission", { permissions: "" })}
            </div>
            {fromPath && <div>Path: {fromPath}</div>}
            {requestAPI && <div>API: {requestAPI}</div>}
            {resources.length > 0 && (
              <div>
                {t("common.resources")}
                <ul className="list-disc pl-4">
                  {resources.map((r) => (
                    <li key={r}>{r}</li>
                  ))}
                </ul>
              </div>
            )}
            {permissions.length > 0 && (
              <div>
                {t("common.required-permission")}
                <ul className="list-disc pl-4">
                  {permissions.map((p) => (
                    <li key={p}>{p}</li>
                  ))}
                </ul>
              </div>
            )}
            <div className="mt-2">
              <RouterLink
                to={{ name: WORKSPACE_ROUTE_LANDING }}
                className={buttonVariants({
                  appearance: "outline",
                  size: "sm",
                })}
              >
                <ChevronLeft className="h-4 w-4" />
                {t("error-page.go-back-home")}
              </RouterLink>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
