// frontend/src/components/RoleSelect.tsx
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { FeatureBadge } from "@/components/FeatureBadge";
import { Combobox, type ComboboxGroup } from "@/components/ui/combobox";
import {
  displayRoleDescriptionFromList,
  displayRoleTitleFromList,
} from "@/lib/role";
import { useAppStore } from "@/stores/app";
import {
  PRESET_PROJECT_ROLES,
  PRESET_ROLES,
  PRESET_WORKSPACE_ROLES,
} from "@/types/iam";
import type { Role } from "@/types/proto-es/v1/role_service_pb";
import { PlanFeature } from "@/types/proto-es/v1/subscription_service_pb";
import { displayRoleDescription, displayRoleTitle } from "@/utils";

interface RoleSelectProps {
  value: string[];
  onChange: (roles: string[]) => void;
  disabled?: boolean;
  scope?: "project";
  multiple?: boolean;
  placeholder?: string;
  filterRole?: (role: Role) => boolean;
}

export function RoleSelect({
  value,
  onChange,
  disabled,
  scope,
  multiple = true,
  placeholder,
  filterRole,
}: RoleSelectProps) {
  const { t } = useTranslation();
  const roleList = useAppStore((state) => state.roleList);
  const hasCustomRoleFeature = useAppStore((s) =>
    s.hasInstanceFeature(PlanFeature.FEATURE_CUSTOM_ROLES)
  );

  const groups: ComboboxGroup[] = useMemo(() => {
    const isCustomRole = (name: string) => !PRESET_ROLES.includes(name);
    const visibleRole = (name: string) => {
      if (!filterRole) {
        return true;
      }
      const role = roleList.find((role) => role.name === name);
      return role ? filterRole(role) : false;
    };

    const workspace = PRESET_WORKSPACE_ROLES.filter(visibleRole).map(
      (name) => ({
        value: name,
        label: displayRoleTitle(name),
        description: displayRoleDescription(name),
      })
    );

    const project = PRESET_PROJECT_ROLES.filter(visibleRole).map((name) => ({
      value: name,
      label: displayRoleTitle(name),
      description: displayRoleDescription(name),
    }));

    const custom = roleList
      .filter((r) => !PRESET_ROLES.includes(r.name))
      .filter((r) => !filterRole || filterRole(r))
      .map((r) => ({
        value: r.name,
        label: displayRoleTitleFromList(r.name, roleList),
        description: displayRoleDescriptionFromList(r.name, roleList),
        disabled: !hasCustomRoleFeature,
        render: () => (
          <div className="flex items-center gap-x-1">
            <span>{displayRoleTitleFromList(r.name, roleList)}</span>
            {isCustomRole(r.name) && !hasCustomRoleFeature && (
              <FeatureBadge
                feature={PlanFeature.FEATURE_CUSTOM_ROLES}
                clickable={false}
              />
            )}
          </div>
        ),
      }));

    const result: ComboboxGroup[] = [];
    if (scope !== "project" && workspace.length > 0)
      result.push({
        label: t("role.workspace-roles.self"),
        options: workspace,
      });
    if (project.length > 0)
      result.push({ label: t("role.project-roles.self"), options: project });
    if (custom.length > 0)
      result.push({ label: t("role.custom-roles.self"), options: custom });
    return result;
  }, [filterRole, roleList, hasCustomRoleFeature, scope, t]);

  const defaultPlaceholder = multiple
    ? t("settings.members.select-role", { count: 2 })
    : t("settings.members.assign-role");

  if (multiple) {
    return (
      <Combobox
        multiple
        value={value}
        onChange={onChange}
        options={groups}
        placeholder={placeholder || defaultPlaceholder}
        disabled={disabled}
        portal
      />
    );
  }

  return (
    <Combobox
      value={value[0] ?? ""}
      onChange={(v) => onChange(v ? [v] : [])}
      options={groups}
      placeholder={placeholder || defaultPlaceholder}
      disabled={disabled}
      portal
    />
  );
}

// frontend/src/components/v2/Select/RoleSelect.vue
<template>
  <NSelect
    v-bind="$attrs"
    :value="value"
    :multiple="multiple"
    :disabled="disabled"
    :clearable="clearable"
    :options="availableRoleOptions"
    :max-tag-count="'responsive'"
    :filterable="true"
    :render-label="renderLabel"
    :placeholder="$t('settings.members.select-role', multiple ? 2 : 1)"
    to="body"
    @update:value="onValueUpdate"
  />
  <FeatureModal
    :feature="PlanFeature.FEATURE_CUSTOM_ROLES"
    :open="showFeatureModal"
    @cancel="showFeatureModal = false"
  />
</template>

<script setup lang="tsx">
import type { SelectGroupOption, SelectOption } from "naive-ui";
import { NSelect } from "naive-ui";
import { computed, h, ref } from "vue";
import FeatureBadge from "@/components/FeatureGuard/FeatureBadge.vue";
import FeatureModal from "@/components/FeatureGuard/FeatureModal.vue";
import { t } from "@/plugins/i18n";
import { featureToRef, useRoleStore } from "@/store";
import {
  PRESET_PROJECT_ROLES,
  PRESET_ROLES,
  PRESET_WORKSPACE_ROLES,
} from "@/types";
import { PlanFeature } from "@/types/proto-es/v1/subscription_service_pb";
import { displayRoleTitle } from "@/utils";

const props = withDefaults(
  defineProps<{
    value?: string[] | string | undefined;
    disabled?: boolean;
    clearable?: boolean;
    multiple?: boolean;
    suffix?: string;
    includeWorkspaceRoles?: boolean;
    filter?: (role: string) => boolean;
  }>(),
  {
    clearable: true,
    includeWorkspaceRoles: true,
    suffix: () =>
      ` (${t("common.optional")}, ${t(
        "role.project-roles.apply-to-all-projects"
      ).toLocaleLowerCase()})`,
  }
);

const emit = defineEmits<{
  (event: "update:value", val: string | string[]): void;
}>();

const roleStore = useRoleStore();
const showFeatureModal = ref(false);
const hasCustomRoleFeature = featureToRef(PlanFeature.FEATURE_CUSTOM_ROLES);

const filterRole = (role: string) => {
  if (!props.filter) {
    return true;
  }
  return props.filter(role);
};

const availableRoleOptions = computed(
  (): (SelectOption | SelectGroupOption)[] => {
    const roleGroups: SelectGroupOption[] = [];

    if (props.includeWorkspaceRoles) {
      roleGroups.push({
        type: "group",
        key: "workspace-roles",
        label: t("role.workspace-roles.self"),
        children: PRESET_WORKSPACE_ROLES.filter(filterRole).map((role) => ({
          label: displayRoleTitle(role),
          value: role,
        })),
      });
    }

    roleGroups.push({
      type: "group",
      key: "project-roles",
      label: t("role.project-roles.self") + props.suffix,
      children: PRESET_PROJECT_ROLES.filter(filterRole).map((role) => ({
        label: displayRoleTitle(role),
        value: role,
      })),
    });

    const customRoles = roleStore.roleList
      .map((role) => role.name)
      .filter((role) => !PRESET_ROLES.includes(role) && filterRole(role));
    if (customRoles.length > 0) {
      roleGroups.push({
        type: "group",
        key: "custom-roles",
        label: t("role.custom-roles.self") + props.suffix,
        children: customRoles.map((role) => ({
          label: displayRoleTitle(role),
          value: role,
        })),
      });
    }

    return roleGroups;
  }
);

const renderLabel = (option: SelectOption) => {
  const label = h("span", {}, option.label as string);
  if (hasCustomRoleFeature.value || !option.value) {
    return label;
  }
  if (PRESET_ROLES.includes(option.value as string)) {
    return label;
  }

  const icon = h(FeatureBadge, {
    feature: PlanFeature.FEATURE_CUSTOM_ROLES,
    clickable: false,
  });
  return h(
    "div",
    {
      class: "flex items-center gap-1",
    },
    [label, icon]
  );
};

const includeCustomRole = (values: string[]) => {
  return values.some((val) => !PRESET_ROLES.includes(val));
};

const onValueUpdate = (val: string | string[]) => {
  let hasCustomRole = false;
  if (Array.isArray(val)) {
    hasCustomRole = includeCustomRole(val);
  } else {
    hasCustomRole = includeCustomRole([val]);
  }
  if (hasCustomRole && !hasCustomRoleFeature.value) {
    showFeatureModal.value = true;
    return;
  }
  emit("update:value", val);
};
</script>
