// frontend/src/views/sql-editor/EditorPanel/Panels/SequencesPanel/SequencesPanel.vue
<template>
  <div v-if="metadata?.schema" class="h-full overflow-hidden flex flex-col">
    <div
      v-show="!metadata.func"
      class="w-full h-[44px] py-2 px-2 border-b flex flex-row gap-x-2 justify-end items-center"
    >
      <SearchBox
        v-model:value="state.keyword"
        size="small"
        style="width: 10rem"
      />
    </div>
    <SequencesTable
      :db="database"
      :database="metadata.database"
      :schema="metadata.schema"
      :sequences="metadata.schema.sequences"
      :keyword="state.keyword"
      @click="select"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, reactive } from "vue";
import { SearchBox } from "@/components/v2";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
} from "@/store";
import type {
  DatabaseMetadata,
  SchemaMetadata,
  SequenceMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import {
  extractKeyWithPosition,
  keyWithPosition,
} from "@/views/sql-editor/EditorCommon";
import { useCurrentTabViewStateContext } from "../../context/viewState";
import SequencesTable from "./SequencesTable.vue";

const { database } = useConnectionOfCurrentSQLEditorTab();
const { viewState, updateViewState } = useCurrentTabViewStateContext();
const databaseMetadata = computed(() => {
  return useDBSchemaV1Store().getDatabaseMetadata(database.value.name);
});
const state = reactive({
  keyword: "",
});

const metadata = computed(() => {
  const database = databaseMetadata.value;
  const schema = database.schemas.find(
    (s) => s.name === viewState.value?.schema
  );
  const [name, position] = extractKeyWithPosition(
    viewState.value?.detail?.func ?? ""
  );
  const func = schema?.functions.find(
    (f, i) => f.name === name && i === position
  );
  return { database, schema, func };
});

const select = (selected: {
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  sequence: SequenceMetadata;
  position: number;
}) => {
  updateViewState({
    detail: {
      sequence: keyWithPosition(selected.sequence.name, selected.position),
    },
  });
};
</script>

// frontend/src/react/components/sql-editor/Panels/SequencesPanel/SequencesPanel.tsx
import { useState } from "react";
import { useVueState } from "@/react/hooks/useVueState";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
} from "@/store";
import { keyWithPosition } from "@/views/sql-editor/EditorCommon/utils";
import { PanelSearchBox } from "../common/PanelSearchBox";
import { useViewStateNav } from "../common/useViewStateNav";
import { SequencesTable } from "./SequencesTable";

/**
 * React port of `frontend/src/views/sql-editor/EditorPanel/Panels/SequencesPanel/*`.
 * List-only panel — clicking a row updates `viewState.detail.sequence`
 * to scroll that row into view (no separate detail surface).
 */
export function SequencesPanel() {
  const dbSchemaStore = useDBSchemaV1Store();
  const { database } = useConnectionOfCurrentSQLEditorTab();
  const databaseName = useVueState(() => database.value.name);
  const databaseMetadata = useVueState(
    () => dbSchemaStore.getDatabaseMetadata(databaseName ?? ""),
    { deep: true }
  );

  const { schema: schemaName, setDetail } = useViewStateNav();

  const [keyword, setKeyword] = useState("");

  const schema = databaseMetadata?.schemas.find((s) => s.name === schemaName);
  if (!databaseMetadata || !schema) return null;

  return (
    <div className="h-full overflow-hidden flex flex-col">
      <div className="w-full h-11 py-2 px-2 border-b border-block-border flex flex-row gap-x-2 justify-end items-center">
        <PanelSearchBox value={keyword} onChange={setKeyword} />
      </div>
      <div className="flex-1 min-h-0">
        <SequencesTable
          database={databaseMetadata}
          schema={schema}
          sequences={schema.sequences}
          keyword={keyword}
          onSelect={({ sequence, position }) =>
            setDetail({
              sequence: keyWithPosition(sequence.name, position),
            })
          }
        />
      </div>
    </div>
  );
}
