// frontend/src/components/SchemaDiagram/SchemaDiagram.vue
<template>
  <div class="w-full h-full relative overflow-hidden flex">
    <Navigator />

    <Canvas class="flex-1">
      <template #desktop>
        <template v-for="(schema, i) in selectedSchemas" :key="`schema-${i}`">
          <TableNode
            v-for="table in schema.tables"
            :key="idOfTable(table)"
            :schema="schema"
            :table="table"
            :class="initialized ? '' : 'invisible'"
          />
        </template>

        <template v-if="initialized">
          <ForeignKeyLine v-for="(fk, i) in foreignKeys" :key="i" :fk="fk" />
        </template>
      </template>

      <div
        v-if="busy || !initialized"
        class="absolute inset-0 bg-white/40 flex items-center justify-center"
      >
        <BBSpin />
      </div>
    </Canvas>
  </div>
</template>

<script lang="ts" setup>
import Emittery from "emittery";
import { uniqueId } from "lodash-es";
import { computed, nextTick, ref, toRef, watch } from "vue";
import { BBSpin } from "@/bbkit";
import type { ComposedDatabase } from "@/types";
import type {
  ColumnMetadata,
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto/v1/database_service";
import Canvas from "./Canvas";
import type { GraphNodeItem, GraphEdgeItem } from "./ER";
import { ForeignKeyLine, TableNode, autoLayout } from "./ER";
import Navigator from "./Navigator";
import { provideSchemaDiagramContext } from "./common";
import type {
  Point,
  Rect,
  Size,
  SchemaDiagramContext,
  ForeignKey,
  EditStatus,
  Geometry,
} from "./types";

const props = withDefaults(
  defineProps<{
    database: ComposedDatabase;
    databaseMetadata: DatabaseMetadata;
    editable?: boolean;
    schemaStatus?: (schema: SchemaMetadata) => EditStatus;
    tableStatus?: (table: TableMetadata) => EditStatus;
    columnStatus?: (column: ColumnMetadata) => EditStatus;
  }>(),
  {
    editable: false,
    schemaStatus: () => "normal" as EditStatus,
    tableStatus: () => "normal" as EditStatus,
    columnStatus: () => "normal" as EditStatus,
  }
);

const emit = defineEmits<{
  (event: "edit-table", schema: SchemaMetadata, table: TableMetadata): void;
  (
    event: "edit-column",
    schema: SchemaMetadata,
    table: TableMetadata,
    column: ColumnMetadata,
    target: "name" | "type"
  ): void;
}>();

const initialized = ref(false);
const dummy = ref(false);
const busy = ref(false);
const zoom = ref(1);
const position = ref<Point>({ x: 0, y: 0 });
const panning = ref(false);
const geometries = ref(new Set<Geometry>());
const focusedTables = ref(new Set<TableMetadata>());
const selectedSchemaNames = ref<string[]>([]);

const selectedSchemas = computed(() => {
  return props.databaseMetadata.schemas.filter((schema) =>
    selectedSchemaNames.value.includes(schema.name)
  );
});

const render = () => {
  nextTick(() => {
    events.emit("render");
  });
};

const events: SchemaDiagramContext["events"] = new Emittery();

const tableIds = ref(new WeakMap<TableMetadata, string>());
const rectsByTableId = ref(new Map<string, Rect>());
const foreignKeys = computed((): ForeignKey[] => {
  const find = (s: string, t: string, c: string) => {
    const schema = selectedSchemas.value.find((schema) => schema.name === s);
    const table = schema?.tables.find((table) => table.name === t);
    const column = c;
    return { schema, table, column };
  };
  const fks: ForeignKey[] = [];
  selectedSchemas.value.forEach((schema) => {
    schema.tables.forEach((table) => {
      table.foreignKeys.forEach((fkMetadata) => {
        const {
          columns,
          referencedSchema,
          referencedTable,
          referencedColumns,
        } = fkMetadata;
        for (let i = 0; i < columns.length; i++) {
          const to = find(
            referencedSchema,
            referencedTable,
            referencedColumns[i]
          );
          if (to.schema && to.table) {
            fks.push({
              from: { schema, table, column: columns[i] },
              to,
              metadata: fkMetadata,
            } as ForeignKey);
          }
        }
      });
    });
  });

  return fks;
});

const idOfTable = (table: TableMetadata): string => {
  const ids = tableIds.value;
  if (ids.has(table)) return ids.get(table)!;
  const id = `table-${table.name}-${uniqueId()}`;
  ids.set(table, id);
  return id;
};

const rectOfTable = (table: TableMetadata): Rect => {
  const id = idOfTable(table);
  return rectsByTableId.value.get(id) ?? { x: 0, y: 0, width: 0, height: 0 };
};

const layout = () => {
  return nextTick(async () => {
    const nodeList = selectedSchemas.value
      .flatMap((schema) => {
        return schema.tables.map((table) => {
          const id = idOfTable(table);
          const elem = document.querySelector(`[bb-node-id="${id}"]`)!;
          return {
            group: `schema-${schema.name}`,
            table,
            id,
            elem,
          };
        });
      })
      .filter((item) => !!item.elem)
      .map<GraphNodeItem>((item) => {
        const size: Size = {
          width: item.elem.clientWidth,
          height: item.elem.clientHeight,
        };
        return {
          group: item.group,
          id: item.id,
          size,
          children: [],
        };
      });

    const edgeList = foreignKeys.value.map<GraphEdgeItem>((fk) => {
      const { from, to } = fk;
      const fromTableId = idOfTable(from.table);
      const toTableId = idOfTable(to.table);
      return {
        id: `${from.schema.name}.${fromTableId}.${from.column}->${to.schema.name}.${toTableId}.${to.column}`,
        from: fromTableId,
        to: toTableId,
      };
    });
    const { rects } = await autoLayout(nodeList, edgeList);
    for (const [id, rect] of rects) {
      rectsByTableId.value.set(id, rect);
    }

    render();
  });
};

events.on("layout", layout);
events.on("edit-table", ({ schema, table }) =>
  emit("edit-table", schema, table)
);
events.on("edit-column", ({ schema, table, column, target }) =>
  emit("edit-column", schema, table, column, target)
);

provideSchemaDiagramContext({
  database: toRef(props, "database"),
  databaseMetadata: toRef(props, "databaseMetadata"),
  editable: computed(() => props.editable),
  foreignKeys,
  dummy,
  busy,
  zoom,
  position,
  panning,
  geometries,
  focusedTables,
  idOfTable,
  rectOfTable,
  render,
  layout,
  schemaStatus: props.schemaStatus,
  tableStatus: props.tableStatus,
  columnStatus: props.columnStatus,
  events,
  selectedSchemaNames,
  selectedSchemas,
});

// autoLayout and fit view at the first time the diagram is mounted.
watch(
  () => props.databaseMetadata,
  () => {
    selectedSchemaNames.value = [props.databaseMetadata.schemas[0]?.name ?? ""];
  },
  { immediate: true }
);

watch(
  () => selectedSchemaNames.value,
  async () => {
    focusedTables.value = new Set();
    await layout();
    initialized.value = true;
    nextTick(() => {
      events.emit("fit-view");
    });
  },
  { immediate: true }
);
</script>

// frontend/src/modules/schema-diagram/SchemaDiagram.tsx
import { LoaderCircle } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type {
  ColumnMetadata,
  Database,
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { extractDatabaseResourceName } from "@/utils";
import { Canvas } from "./Canvas/Canvas";
import {
  SchemaDiagramProvider,
  useSchemaDiagramContext,
} from "./common/context";
import { ForeignKeyLine } from "./ER/ForeignKeyLine";
import {
  type ForeignKeyEdge,
  useAutoLayout,
} from "./ER/libs/autoLayout/useAutoLayout";
import { TableNode } from "./ER/TableNode";
import { Navigator } from "./Navigator/Navigator";
import type { EditStatus } from "./types";

interface SchemaDiagramProps {
  database: Database;
  databaseMetadata: DatabaseMetadata;
  editable?: boolean;
  schemaStatus?: (schema: SchemaMetadata) => EditStatus;
  tableStatus?: (table: TableMetadata) => EditStatus;
  columnStatus?: (column: ColumnMetadata) => EditStatus;
  onEditTable?: (schema: SchemaMetadata, table: TableMetadata) => void;
  onEditColumn?: (
    schema: SchemaMetadata,
    table: TableMetadata,
    column: ColumnMetadata,
    target: "name" | "type"
  ) => void;
}

/**
 * Composes Navigator + Canvas inside the per-instance React context;
 * an inner `<Body>` component runs the ELK layout when metadata /
 * selection changes.
 */
export function SchemaDiagram({
  database,
  databaseMetadata,
  editable = false,
  schemaStatus,
  tableStatus,
  columnStatus,
  onEditTable,
  onEditColumn,
}: SchemaDiagramProps) {
  return (
    <SchemaDiagramProvider
      database={database}
      databaseMetadata={databaseMetadata}
      editable={editable}
      schemaStatus={schemaStatus}
      tableStatus={tableStatus}
      columnStatus={columnStatus}
    >
      <Body
        databaseName={database.name}
        onEditTable={onEditTable}
        onEditColumn={onEditColumn}
      />
    </SchemaDiagramProvider>
  );
}

interface BodyProps {
  databaseName: string;
  onEditTable?: SchemaDiagramProps["onEditTable"];
  onEditColumn?: SchemaDiagramProps["onEditColumn"];
}

function Body({ databaseName, onEditTable, onEditColumn }: BodyProps) {
  const ctx = useSchemaDiagramContext();
  const {
    busy,
    selectedSchemas,
    selectedSchemaNames,
    setSelectedSchemaNames,
    setFocusedTables,
    foreignKeys,
    idOfTable,
    mergeTableRects,
    events,
    databaseMetadata,
  } = ctx;

  // Pick the first schema as the initial selection, NOT all of them. (Most
  // diagrams target a single schema; users can opt into others via the
  // SchemaSelector.)
  const lastInitializedMetadataRef = useRef<DatabaseMetadata | null>(null);
  useEffect(() => {
    if (lastInitializedMetadataRef.current === databaseMetadata) return;
    lastInitializedMetadataRef.current = databaseMetadata;
    const first = databaseMetadata.schemas[0]?.name ?? "";
    setSelectedSchemaNames([first]);
  }, [databaseMetadata, setSelectedSchemaNames]);

  const [initialized, setInitialized] = useState(false);

  // Edge list for ELK derived from foreignKeys.
  const edges = useMemo<ForeignKeyEdge[]>(
    () =>
      foreignKeys.map((fk) => ({
        fromSchema: fk.from.schema.name,
        fromTable: fk.from.table,
        fromColumn: fk.from.column,
        toSchema: fk.to.schema.name,
        toTable: fk.to.table,
        toColumn: fk.to.column,
      })),
    [foreignKeys]
  );

  const sizeOfTable = useCallback((id: string) => {
    const elem = document.querySelector(`[data-bb-node-id="${id}"]`);
    if (!elem) return null;
    const rect = elem.getBoundingClientRect();
    return { width: rect.width, height: rect.height };
  }, []);

  const runLayout = useAutoLayout({
    selectedSchemas,
    edges,
    idOfTable,
    sizeOfTable,
  });

  // Drive the layout when (a) selectedSchemas changes, (b) the diagram
  // emits "layout" via the context (e.g. external trigger).
  const driveLayout = useCallback(async () => {
    setFocusedTables(new Set());
    // Defer one frame so newly-mounted TableNodes have laid out their
    // DOM before we measure them.
    await new Promise<void>((resolve) =>
      requestAnimationFrame(() => resolve())
    );
    const rects = await runLayout();
    if (!rects) return;
    mergeTableRects(rects);
    setInitialized(true);
    requestAnimationFrame(() => {
      void events.emit("fit-view");
      void events.emit("render");
    });
  }, [runLayout, mergeTableRects, setFocusedTables, events]);

  // Re-run layout on selection change.
  // (selectedSchemas is a reference-stable derived from selectedSchemaNames
  // + databaseMetadata, but listing its identity is enough.)
  useEffect(() => {
    if (selectedSchemaNames.length === 0) return;
    void driveLayout();
    void selectedSchemas;
  }, [selectedSchemas, selectedSchemaNames, driveLayout]);

  // External `layout` trigger.
  useEffect(() => {
    const off = events.on("layout", () => {
      void driveLayout();
    });
    return () => {
      off();
    };
  }, [events, driveLayout]);

  // External `edit-table` / `edit-column` events bridge to caller props.
  useEffect(() => {
    if (!onEditTable) return;
    const off = events.on("edit-table", ({ data: { schema, table } }) => {
      onEditTable(schema, table);
    });
    return () => {
      off();
    };
  }, [events, onEditTable]);

  useEffect(() => {
    if (!onEditColumn) return;
    const off = events.on(
      "edit-column",
      ({ data: { schema, table, column, target } }) => {
        onEditColumn(schema, table, column, target);
      }
    );
    return () => {
      off();
    };
  }, [events, onEditColumn]);

  const screenshotFilename = useCallback(() => {
    const { databaseName: shortName } =
      extractDatabaseResourceName(databaseName);
    return `${shortName}.png`;
  }, [databaseName]);

  return (
    <div className="w-full h-full relative overflow-hidden flex">
      <Navigator />

      <div className="flex-1 relative">
        <Canvas screenshotFilename={screenshotFilename}>
          {selectedSchemas.map((schema) =>
            schema.tables.map((table) => (
              <TableNode key={idOfTable(table)} schema={schema} table={table} />
            ))
          )}
          {initialized &&
            foreignKeys.map((fk, i) => <ForeignKeyLine key={i} fk={fk} />)}
        </Canvas>

        {(busy || !initialized) && (
          <div
            className="absolute inset-0 bg-background/40 flex items-center justify-center pointer-events-none"
            data-screenshot-hide
          >
            <LoaderCircle className="size-6 text-accent animate-spin" />
          </div>
        )}
      </div>
    </div>
  );
}
