// frontend/src/components/Revision/RevisionDetailPanel.vue
<template>
  <div v-if="revision" class="w-full">
    <div class="flex flex-row items-center gap-2">
      <p class="text-lg flex gap-x-1">
        <span class="text-control">{{ $t("common.version") }}:</span>
        <span class="font-bold text-main">{{ revision.version }}</span>
      </p>
    </div>
    <div
      class="mt-3 text-control text-base flex flex-row items-center flex-wrap gap-x-4"
    >
      <span>
        {{ $t("database.revision.applied-at") }}:
        <HumanizeDate
          :date="getDateForPbTimestampProtoEs(revision.createTime)"
        />
      </span>
      <span v-if="relatedIssueUID">
        {{ $t("common.issue") }}:
        <RouterLink class="normal-link" :to="`/${revision.issue}`"
          >#{{ relatedIssueUID }}</RouterLink
        >
      </span>
    </div>
  </div>

  <div class="flex flex-col my-4">
    <p class="w-auto flex items-center text-base text-main mb-2 gap-x-2">
      <span>{{ $t("common.statement") }}</span>
      <CopyButton :content="statement" />
    </p>
    <MonacoEditor
      class="h-auto max-h-[480px] min-h-[120px] border rounded-[3px] text-sm overflow-clip relative"
      :content="statement"
      :readonly="true"
      :auto-height="{ min: 120, max: 480 }"
    />
  </div>

  <div v-if="logEntries.length > 0" class="my-4">
    <p class="w-auto flex items-center text-base text-main mb-2">
      {{ $t("issue.task-run.logs") }}
    </p>
    <TaskRunLogViewer :entries="logEntries" :sheet="sheet" />
  </div>
</template>

<script lang="ts" setup>
import { create } from "@bufbuild/protobuf";
import { computedAsync } from "@vueuse/core";
import { computed, reactive, ref, watch } from "vue";
import { MonacoEditor } from "@/components/MonacoEditor";
import { CopyButton } from "@/components/v2";
import { rolloutServiceClientConnect } from "@/grpcweb";
import { useRevisionStore, useSheetV1Store } from "@/store";
import { type ComposedDatabase, getDateForPbTimestampProtoEs } from "@/types";
import type { TaskRun } from "@/types/proto-es/v1/rollout_service_pb";
import {
  GetTaskRunLogRequestSchema,
  GetTaskRunRequestSchema,
} from "@/types/proto-es/v1/rollout_service_pb";
import { extractIssueUID, getSheetStatement } from "@/utils";
import HumanizeDate from "../misc/HumanizeDate.vue";
import TaskRunLogViewer from "../Plan/components/RolloutView/v2/TaskRunLogViewer.vue";

interface LocalState {
  loading: boolean;
}

const props = defineProps<{
  database: ComposedDatabase;
  revisionName: string;
}>();

const state = reactive<LocalState>({
  loading: false,
});

const revisionStore = useRevisionStore();
const sheetStore = useSheetV1Store();
const taskRun = ref<TaskRun | undefined>(undefined);

watch(
  () => props.revisionName,
  async (revisionName) => {
    if (!revisionName) {
      return;
    }

    state.loading = true;
    const revision = await revisionStore.getOrFetchRevisionByName(revisionName);
    if (revision) {
      if (revision.taskRun) {
        // Fetch the task run details.
        const request = create(GetTaskRunRequestSchema, {
          name: revision.taskRun,
        });
        const response = await rolloutServiceClientConnect.getTaskRun(request);
        taskRun.value = response;
      }
      // Prepare the sheet data from task run.
      if (revision.sheet) {
        await sheetStore.getOrFetchSheetByName(revision.sheet);
      }
    }
    state.loading = false;
  },
  { immediate: true }
);

// Fetch task run log
const taskRunLog = computedAsync(async () => {
  if (!taskRun.value?.name) return undefined;
  const request = create(GetTaskRunLogRequestSchema, {
    parent: taskRun.value.name,
  });
  return await rolloutServiceClientConnect.getTaskRunLog(request);
}, undefined);

const logEntries = computed(() => taskRunLog.value?.entries ?? []);

const revision = computed(() =>
  revisionStore.getRevisionByName(props.revisionName)
);

const sheet = computed(() =>
  revision.value?.sheet
    ? sheetStore.getSheetByName(revision.value.sheet)
    : undefined
);

const statement = computed(() =>
  sheet.value ? getSheetStatement(sheet.value) : ""
);

const relatedIssueUID = computed(() => {
  const uid = extractIssueUID(revision.value?.issue || "");
  if (!uid) return null;
  return uid;
});
</script>

// frontend/src/react/components/revision/RevisionDetailPanel.tsx
import { ArrowUpRight, LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { sheetServiceClientConnect } from "@/connect";
import { ReadonlyMonaco } from "@/react/components/monaco";
import { RouterLink } from "@/react/components/RouterLink";
import { TaskRunLogViewer } from "@/react/components/task-run-log";
import { CopyButton } from "@/react/components/ui/copy-button";
import { useRevisionByName } from "@/react/hooks/useAppState";
import { useAppStore } from "@/react/stores/app";
import { getTimeForPbTimestampProtoEs } from "@/types";
import { bytesToString, formatAbsoluteDateTime } from "@/utils";
import { extractTaskLink, getRevisionType } from "@/utils/v1/revision";

export interface RevisionDetailPanelProps {
  revisionName: string;
}

export function RevisionDetailPanel({
  revisionName,
}: RevisionDetailPanelProps) {
  const { t } = useTranslation();
  const fetchRevision = useAppStore((state) => state.fetchRevision);
  const revision = useRevisionByName(revisionName);
  const [loading, setLoading] = useState(false);
  const [statement, setStatement] = useState("");

  useEffect(() => {
    if (!revisionName) {
      setLoading(false);
      setStatement("");
      return;
    }

    let cancelled = false;

    setLoading(true);
    setStatement("");

    void fetchRevision(revisionName)
      .then(async (rev) => {
        if (!rev?.sheet) {
          return;
        }

        try {
          const sheet = await sheetServiceClientConnect.getSheet({
            name: rev.sheet,
            raw: true,
          });
          if (!cancelled && sheet.content) {
            setStatement(new TextDecoder().decode(sheet.content));
          }
        } catch (error) {
          console.error("Failed to fetch sheet content", error);
        }
      })
      .catch((error) => {
        console.error("Failed to fetch revision details", error);
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [fetchRevision, revisionName]);

  const taskFullLink = revision?.taskRun
    ? extractTaskLink(revision.taskRun)
    : "";
  const formattedCreateTime = revision
    ? formatAbsoluteDateTime(getTimeForPbTimestampProtoEs(revision.createTime))
    : "";
  const formattedStatementSize = statement
    ? bytesToString(new TextEncoder().encode(statement).length)
    : "";

  if (loading) {
    return (
      <div className="flex items-center justify-center py-2 text-sm text-gray-400">
        <LoaderCircle className="h-4 w-4 animate-spin" />
      </div>
    );
  }

  if (!revision) {
    return null;
  }

  return (
    <div className="focus:outline-hidden" tabIndex={0}>
      <main className="relative flex flex-col gap-y-6">
        <div className="flex flex-col gap-y-4">
          <h2 className="text-2xl font-semibold text-main">
            {revision.version}
          </h2>
          <div className="flex items-center gap-x-3 text-sm text-control-light">
            <span>{getRevisionType(revision.type)}</span>
            {formattedCreateTime ? <span aria-hidden="true">•</span> : null}
            {formattedCreateTime ? <span>{formattedCreateTime}</span> : null}
          </div>
        </div>

        <div className="flex flex-col gap-y-6">
          {revision.taskRun ? (
            <div className="flex flex-col gap-y-2">
              <div className="flex items-center justify-between">
                <p className="text-lg text-main">{t("issue.task-run.logs")}</p>
                {taskFullLink ? (
                  <RouterLink
                    to={{ path: taskFullLink }}
                    className="flex items-center gap-x-1 text-sm text-control-light transition-colors hover:text-accent"
                  >
                    {t("common.show-more")}
                    <ArrowUpRight className="h-4 w-4" />
                  </RouterLink>
                ) : null}
              </div>
              <TaskRunLogViewer taskRunName={revision.taskRun} />
            </div>
          ) : null}

          <div className="flex flex-col gap-y-2">
            <p className="flex items-center gap-x-2 text-lg text-main">
              {t("common.statement")}
              {formattedStatementSize ? (
                <span className="text-sm font-normal text-control-light">
                  ({formattedStatementSize})
                </span>
              ) : null}
              <CopyButton content={statement} />
            </p>
            <div className="overflow-hidden rounded-sm border border-control-border bg-white">
              <ReadonlyMonaco
                content={statement}
                className="relative h-auto max-h-[600px] min-h-[120px]"
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default RevisionDetailPanel;
