// frontend/src/react/components/sql-editor/Panels/common/tables/ColumnsTable.tsx
import { useEffect, useMemo, useRef } from "react";
import { useTranslation } from "react-i18next";
import { engineSupportsMultiSchema } from "@/components/SchemaEditorLite/spec";
import { HighlightLabelText } from "@/react/components/HighlightLabelText";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/react/components/ui/table";
import { Engine } from "@/types/proto-es/v1/common_pb";
import type {
  ColumnMetadata,
  Database,
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { getInstanceResource } from "@/utils";
import { EllipsisCell } from "../EllipsisCell";
import { useViewStateNav } from "../useViewStateNav";

export type ColumnsTableFlavor = "table" | "view" | "external-table";

interface ColumnsTableProps {
  db: Database;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  /** Required when `flavor === "table"` so primary-key + FK columns can resolve. */
  table?: TableMetadata;
  columns: ColumnMetadata[];
  flavor: ColumnsTableFlavor;
  keyword?: string;
}

/**
 * Generic columns table covering TablesPanel, ViewsPanel, and
 * ExternalTablesPanel detail surfaces. The `flavor` prop selects the
 * column header set.
 */
export function ColumnsTable({
  db,
  database,
  schema,
  table,
  columns,
  flavor,
  keyword,
}: ColumnsTableProps) {
  const { t } = useTranslation();
  const { detail } = useViewStateNav();
  const containerRef = useRef<HTMLDivElement>(null);

  const filtered = useMemo(() => {
    const trimmed = keyword?.trim().toLowerCase();
    if (!trimmed) return columns;
    return columns.filter((column) =>
      column.name.toLowerCase().includes(trimmed)
    );
  }, [columns, keyword]);

  const engine = getInstanceResource(db).engine;
  const showOnUpdate =
    flavor === "table" && (engine === Engine.MYSQL || engine === Engine.TIDB);
  const showPrimary = flavor === "table";
  const showForeignKey = flavor === "table";
  const primaryKey = useMemo(() => {
    return flavor === "table"
      ? table?.indexes.find((idx) => idx.primary)
      : undefined;
  }, [flavor, table]);

  const selectedKey = detail?.column;

  useEffect(() => {
    if (!selectedKey) return;
    const el = containerRef.current?.querySelector<HTMLElement>(
      `[data-key="${CSS.escape(selectedKey)}"]`
    );
    el?.scrollIntoView({ block: "nearest" });
  }, [selectedKey]);

  return (
    <div ref={containerRef} className="w-full h-full overflow-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{t("schema-editor.column.name")}</TableHead>
            <TableHead>{t("schema-editor.column.type")}</TableHead>
            <TableHead>{t("schema-editor.column.default")}</TableHead>
            {showOnUpdate ? (
              <TableHead>{t("schema-editor.column.on-update")}</TableHead>
            ) : null}
            <TableHead>{t("schema-editor.column.comment")}</TableHead>
            <TableHead className="w-20">
              {t("schema-editor.column.not-null")}
            </TableHead>
            {showPrimary ? (
              <TableHead className="w-20">
                {t("schema-editor.column.primary")}
              </TableHead>
            ) : null}
            {showForeignKey ? (
              <TableHead>{t("schema-editor.column.foreign-key")}</TableHead>
            ) : null}
          </TableRow>
        </TableHeader>
        <TableBody>
          {filtered.map((column) => (
            <TableRow
              key={column.name}
              data-key={column.name}
              data-state={selectedKey === column.name ? "selected" : undefined}
            >
              <TableCell className="truncate max-w-[200px]">
                <HighlightLabelText text={column.name} keyword={keyword} />
              </TableCell>
              <TableCell className="truncate max-w-[320px]">
                {column.type}
              </TableCell>
              <TableCell className="truncate max-w-[320px]">
                {column.default ? (
                  <span className="text-control">{column.default}</span>
                ) : (
                  <span className="italic text-control-placeholder">
                    {t("schema-editor.default.placeholder")}
                  </span>
                )}
              </TableCell>
              {showOnUpdate ? (
                <TableCell className="truncate max-w-[320px]">
                  <EllipsisCell content={column.onUpdate} />
                </TableCell>
              ) : null}
              <TableCell className="truncate max-w-[320px]">
                <EllipsisCell content={column.comment} />
              </TableCell>
              <TableCell className="w-20">
                <input
                  type="checkbox"
                  checked={!column.nullable}
                  disabled
                  className="accent-accent"
                />
              </TableCell>
              {showPrimary ? (
                <TableCell className="w-20">
                  <input
                    type="checkbox"
                    checked={!!primaryKey?.expressions.includes(column.name)}
                    disabled
                    className="accent-accent"
                  />
                </TableCell>
              ) : null}
              {showForeignKey ? (
                <TableCell>
                  <ForeignKeyDisplay
                    db={db}
                    database={database}
                    schema={schema}
                    table={table}
                    column={column}
                  />
                </TableCell>
              ) : null}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}

function ForeignKeyDisplay({
  db,
  database,
  table,
  column,
}: {
  db: Database;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table?: TableMetadata;
  column: ColumnMetadata;
}) {
  const fks = useMemo(() => {
    if (!table) return [];
    return table.foreignKeys.filter((fk) => fk.columns.includes(column.name));
  }, [table, column.name]);

  if (fks.length === 0) {
    return <span className="italic text-control-placeholder">EMPTY</span>;
  }

  const multiSchema = engineSupportsMultiSchema(getInstanceResource(db).engine);

  return (
    <div className="flex flex-col gap-1">
      {fks.map((fk) => {
        const position = fk.columns.indexOf(column.name);
        if (position < 0) return null;

        const referencedSchema = database.schemas.find(
          (s) => s.name === fk.referencedSchema
        );
        const referencedTable = referencedSchema?.tables.find(
          (t) => t.name === fk.referencedTable
        );
        const referencedColumn = referencedTable?.columns.find(
          (c) => c.name === fk.referencedColumns[position]
        );
        const label = multiSchema
          ? `${referencedSchema?.name ?? ""}.${referencedTable?.name ?? ""}(${referencedColumn?.name ?? ""})`
          : `${referencedTable?.name ?? ""}(${referencedColumn?.name ?? ""})`;
        return (
          <span key={fk.name} className="break-all">
            {label}
          </span>
        );
      })}
    </div>
  );
}

// frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ColumnsTable.vue
<template>
  <div ref="containerElRef" class="w-full h-full overflow-x-auto">
    <NDataTable
      v-bind="$attrs"
      ref="dataTableRef"
      size="small"
      :row-key="(column) => column.name"
      :columns="columns"
      :data="layoutReady ? filteredColumns : []"
      :max-height="tableBodyHeight"
      :virtual-scroll="true"
      :striped="true"
      :bordered="true"
      :bottom-bordered="true"
      row-class-name="cursor-default"
    />
  </div>
</template>

<script lang="ts" setup>
import type { DataTableColumn, DataTableInst } from "naive-ui";
import { NCheckbox, NDataTable } from "naive-ui";
import { computed, h, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import {
  DefaultValueCell,
  ForeignKeyCell,
} from "@/components/SchemaEditorLite/Panels/TableColumnEditor/components";
import type { ComposedDatabase } from "@/types";
import { Engine } from "@/types/proto-es/v1/common_pb";
import type {
  ColumnMetadata,
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto/v1/database_service";
import { convertEngineToNew } from "@/utils/v1/common-conversions";
import { getHighlightHTMLByRegExp, useAutoHeightDataTable } from "@/utils";
import { EllipsisCell } from "../../common";
import { useCurrentTabViewStateContext } from "../../context/viewState";

const props = defineProps<{
  db: ComposedDatabase;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table: TableMetadata;
  keyword?: string;
}>();

const { viewState } = useCurrentTabViewStateContext();
const { containerElRef, virtualListRef, tableBodyHeight, layoutReady } =
  useAutoHeightDataTable();
const dataTableRef = ref<DataTableInst>();
const { t } = useI18n();

const filteredColumns = computed(() => {
  const keyword = props.keyword?.trim().toLowerCase();
  if (keyword) {
    return props.table.columns.filter((column) =>
      column.name.toLowerCase().includes(keyword)
    );
  }
  return props.table.columns;
});

const primaryKey = computed(() => {
  return props.table.indexes.find((idx) => idx.primary);
});

const columns = computed(() => {
  const engine = convertEngineToNew(props.db.instanceResource.engine);
  const downGrade = filteredColumns.value.length > 50;
  const columns: (DataTableColumn<ColumnMetadata> & { hide?: boolean })[] = [
    {
      key: "name",
      title: t("schema-editor.column.name"),
      resizable: true,
      minWidth: 140,
      className: "truncate",
      render: (column) => {
        return h("span", {
          innerHTML: getHighlightHTMLByRegExp(column.name, props.keyword ?? ""),
        });
      },
    },
    {
      key: "type",
      title: t("schema-editor.column.type"),
      resizable: true,
      minWidth: 140,
      maxWidth: 320,
      className: "truncate",
    },
    {
      key: "default-value",
      title: t("schema-editor.column.default"),
      resizable: true,
      minWidth: 140,
      maxWidth: 320,
      className: "input-cell",
      render: (column) => {
        return h(DefaultValueCell, {
          column,
          disabled: true,
          engine: engine,
        });
      },
    },
    {
      key: "on-update",
      title: t("schema-editor.column.on-update"),
      resizable: true,
      minWidth: 140,
      maxWidth: 320,
      hide: engine !== Engine.MYSQL && engine !== Engine.TIDB,
      className: "overflow-hidden",
      render: (column) => {
        return h(EllipsisCell, {
          content: column.onUpdate,
          downGrade,
        });
      },
    },
    {
      key: "comment",
      title: t("schema-editor.column.comment"),
      resizable: true,
      minWidth: 140,
      maxWidth: 320,
      className: "overflow-hidden",
      render: (column) => {
        return h(EllipsisCell, {
          content: column.userComment,
          downGrade,
        });
      },
    },
    {
      key: "not-null",
      title: t("schema-editor.column.not-null"),
      resizable: true,
      minWidth: 80,
      maxWidth: 160,
      className: "checkbox-cell",
      render: (column) => {
        return h(NCheckbox, {
          checked: !column.nullable,
          readonly: true,
        });
      },
    },
    {
      key: "primary",
      title: t("schema-editor.column.primary"),
      resizable: true,
      minWidth: 80,
      maxWidth: 160,
      className: "checkbox-cell",
      render: (column) => {
        return h(NCheckbox, {
          checked: isColumnPrimaryKey(column),
          readonly: true,
        });
      },
    },
    {
      key: "foreign-key",
      title: t("schema-editor.column.foreign-key"),
      resizable: true,
      minWidth: 140,
      maxWidth: 320,
      className: "text-cell",
      render: (column) => {
        return h(ForeignKeyCell, {
          db: props.db,
          database: props.database,
          schema: props.schema,
          table: props.table,
          column: column,
          readonly: true,
          disabled: true,
        });
      },
    },
  ];
  return columns.filter((header) => !header.hide);
});

const isColumnPrimaryKey = (column: ColumnMetadata): boolean => {
  const pk = primaryKey.value;
  if (!pk) return false;
  return pk.expressions.includes(column.name);
};

watch(
  [() => viewState.value?.detail.column, virtualListRef],
  ([column, vl]) => {
    if (column && vl) {
      requestAnimationFrame(() => {
        vl.scrollTo({ key: column });
      });
    }
  },
  { immediate: true }
);
</script>

<style lang="postcss" scoped>
:deep(.n-data-table-th .n-data-table-resize-button::after) {
  @apply bg-control-bg h-2/3;
}
:deep(.n-data-table-td.input-cell) {
  @apply pl-0.5 pr-1 py-0;
}

:deep(.n-data-table-td.input-cell .n-input__placeholder),
:deep(.n-data-table-td.input-cell .n-base-selection-placeholder) {
  @apply italic;
}
:deep(.n-data-table-td.checkbox-cell) {
  @apply pr-1 py-0;
}
:deep(.n-data-table-td.text-cell) {
  @apply pr-1 py-0;
}
</style>
