// frontend/src/react/components/sql-editor/Panels/common/tables/IndexesTable.tsx
import { useEffect, useMemo, useRef } from "react";
import { useTranslation } from "react-i18next";
import { HighlightLabelText } from "@/react/components/HighlightLabelText";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/react/components/ui/table";
import type { TableMetadata } from "@/types/proto-es/v1/database_service_pb";
import { EllipsisCell } from "../EllipsisCell";
import { useViewStateNav } from "../useViewStateNav";

interface IndexesTableProps {
  table: TableMetadata;
  keyword?: string;
}

export function IndexesTable({ table, keyword }: IndexesTableProps) {
  const { t } = useTranslation();
  const { detail } = useViewStateNav();
  const containerRef = useRef<HTMLDivElement>(null);

  const filtered = useMemo(() => {
    const trimmed = keyword?.trim().toLowerCase();
    if (!trimmed) return table.indexes;
    return table.indexes.filter(
      (index) =>
        index.name.toLowerCase().includes(trimmed) ||
        index.expressions.some((column) =>
          column.toLowerCase().includes(trimmed)
        )
    );
  }, [table.indexes, keyword]);

  const selectedKey = detail?.index;

  useEffect(() => {
    if (!selectedKey) return;
    const el = containerRef.current?.querySelector<HTMLElement>(
      `[data-key="${CSS.escape(selectedKey)}"]`
    );
    el?.scrollIntoView({ block: "nearest" });
  }, [selectedKey]);

  return (
    <div ref={containerRef} className="w-full h-full overflow-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{t("schema-editor.column.name")}</TableHead>
            <TableHead>{t("schema-editor.columns")}</TableHead>
            <TableHead>{t("schema-editor.column.comment")}</TableHead>
            <TableHead className="w-20">
              {t("schema-editor.column.primary")}
            </TableHead>
            <TableHead className="w-20">
              {t("schema-editor.index.unique")}
            </TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {filtered.map((index) => (
            <TableRow
              key={index.name}
              data-key={index.name}
              data-state={selectedKey === index.name ? "selected" : undefined}
            >
              <TableCell className="truncate max-w-[200px]">
                <HighlightLabelText text={index.name} keyword={keyword} />
              </TableCell>
              <TableCell className="truncate">
                {index.expressions.map((column, i) => (
                  <span key={`${column}-${i}`}>
                    {i > 0 ? ", " : null}
                    <HighlightLabelText text={column} keyword={keyword} />
                  </span>
                ))}
              </TableCell>
              <TableCell className="truncate max-w-[320px]">
                <EllipsisCell content={index.comment} />
              </TableCell>
              <TableCell className="w-20">
                <input
                  type="checkbox"
                  checked={index.primary}
                  disabled
                  className="accent-accent"
                />
              </TableCell>
              <TableCell className="w-20">
                <input
                  type="checkbox"
                  checked={index.unique}
                  disabled
                  className="accent-accent"
                />
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}

// frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/IndexesTable.vue
<template>
  <div ref="containerElRef" class="w-full h-full overflow-x-auto">
    <NDataTable
      v-bind="$attrs"
      ref="dataTableRef"
      size="small"
      :row-key="(index) => index.name"
      :columns="columns"
      :data="layoutReady ? filteredIndexes : []"
      :max-height="tableBodyHeight"
      :virtual-scroll="true"
      :striped="true"
      :bordered="true"
      :bottom-bordered="true"
      row-class-name="cursor-default"
    />
  </div>
</template>

<script lang="ts" setup>
import type { DataTableColumn } from "naive-ui";
import { NCheckbox, NDataTable } from "naive-ui";
import { computed, h, watch } from "vue";
import { useI18n } from "vue-i18n";
import type { ComposedDatabase } from "@/types";
import type {
  DatabaseMetadata,
  IndexMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto/v1/database_service";
import { getHighlightHTMLByRegExp, useAutoHeightDataTable } from "@/utils";
import { EllipsisCell } from "../../common";
import { useEditorPanelContext } from "../../context";

const props = defineProps<{
  db: ComposedDatabase;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table: TableMetadata;
  keyword?: string;
}>();

const { viewState } = useEditorPanelContext();
const {
  containerElRef,
  dataTableRef,
  virtualListRef,
  tableBodyHeight,
  layoutReady,
} = useAutoHeightDataTable();
const { t } = useI18n();

const filteredIndexes = computed(() => {
  const keyword = props.keyword?.trim().toLowerCase();
  if (!keyword) return props.table.indexes;
  return props.table.indexes.filter(
    (index) =>
      index.name.toLowerCase().includes(keyword) ||
      index.expressions.some((column) => column.toLowerCase().includes(keyword))
  );
});

const columns = computed(() => {
  const downGrade = filteredIndexes.value.length > 50;
  const columns: (DataTableColumn<IndexMetadata> & { hide?: boolean })[] = [
    {
      key: "name",
      title: t("schema-editor.column.name"),
      resizable: true,
      minWidth: 140,
      className: "truncate",
      render: (index) => {
        return h("span", {
          innerHTML: getHighlightHTMLByRegExp(index.name, props.keyword ?? ""),
        });
      },
    },
    {
      key: "columns",
      title: t("schema-editor.columns"),
      resizable: true,
      minWidth: 360,
      render: (index) => {
        const tags = index.expressions.map((column) => {
          return `<span>${getHighlightHTMLByRegExp(column, props.keyword ?? "")}</span>`;
        });
        return h("div", { class: "truncate", innerHTML: tags.join(", ") });
      },
    },
    {
      key: "comment",
      title: t("schema-editor.column.comment"),
      resizable: true,
      minWidth: 140,
      maxWidth: 320,
      className: "overflow-hidden",
      render: (index) => {
        return h(EllipsisCell, {
          content: index.comment,
          downGrade,
        });
      },
    },
    {
      key: "primary",
      title: t("schema-editor.column.primary"),
      resizable: false,
      width: 80,
      className: "checkbox-cell",
      render: (index) => {
        return h(NCheckbox, { checked: index.primary, readonly: true });
      },
    },
    {
      key: "unique",
      title: t("schema-editor.index.unique"),
      resizable: false,
      width: 80,
      className: "checkbox-cell",
      render: (index) => {
        return h(NCheckbox, { checked: index.unique, readonly: true });
      },
    },
  ];
  return columns.filter((header) => !header.hide);
});

watch(
  [() => viewState.value?.detail.index, virtualListRef],
  ([index, vl]) => {
    if (index && vl) {
      requestAnimationFrame(() => {
        vl.scrollTo({ key: index });
      });
    }
  },
  { immediate: true }
);
</script>

<style lang="postcss" scoped>
:deep(.n-data-table-th .n-data-table-resize-button::after) {
  @apply bg-control-bg h-2/3;
}
:deep(.n-data-table-td.input-cell) {
  @apply pl-0.5 pr-1 py-0;
}
:deep(.n-data-table-td.checkbox-cell) {
  @apply pr-1 py-0;
}
</style>
