// frontend/src/react/components/sql-editor/Panels/common/tables/PartitionsTable.tsx
import { ChevronDown } from "lucide-react";
import { useEffect, useMemo, useRef } from "react";
import { useTranslation } from "react-i18next";
import { HighlightLabelText } from "@/react/components/HighlightLabelText";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/react/components/ui/table";
import type {
  TableMetadata,
  TablePartitionMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { useViewStateNav } from "../useViewStateNav";

type PartitionRow = {
  partition: TablePartitionMetadata;
  parent?: TablePartitionMetadata;
};

interface PartitionsTableProps {
  table: TableMetadata;
  keyword?: string;
}

export function PartitionsTable({ table, keyword }: PartitionsTableProps) {
  const { t } = useTranslation();
  const { detail } = useViewStateNav();
  const containerRef = useRef<HTMLDivElement>(null);

  const filtered = useMemo(() => {
    const trimmed = keyword?.trim().toLowerCase();
    if (!trimmed) return table.partitions;
    return table.partitions.filter(
      (partition) =>
        partition.name.toLowerCase().includes(trimmed) ||
        partition.subpartitions.some((sub) =>
          sub.name.toLowerCase().includes(trimmed)
        )
    );
  }, [table.partitions, keyword]);

  const flat = useMemo(() => {
    const out: PartitionRow[] = [];
    const walk = (
      partition: TablePartitionMetadata,
      parent?: TablePartitionMetadata
    ) => {
      out.push({ partition, parent });
      partition.subpartitions?.forEach((child) => walk(child, partition));
    };
    filtered.forEach((partition) => walk(partition));
    return out;
  }, [filtered]);

  const selectedKey = detail?.partition;

  useEffect(() => {
    if (!selectedKey) return;
    const el = containerRef.current?.querySelector<HTMLElement>(
      `[data-key="${CSS.escape(selectedKey)}"]`
    );
    el?.scrollIntoView({ block: "nearest" });
  }, [selectedKey]);

  const rowKey = (item: PartitionRow) => {
    return item.parent
      ? `${item.parent.name}/${item.partition.name}`
      : item.partition.name;
  };

  return (
    <div ref={containerRef} className="w-full h-full overflow-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="w-6" />
            <TableHead>{t("common.name")}</TableHead>
            <TableHead>{t("common.type")}</TableHead>
            <TableHead>
              {t("schema-editor.table-partition.expression")}
            </TableHead>
            <TableHead>{t("schema-editor.table-partition.value")}</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {flat.map((item) => {
            const key = rowKey(item);
            return (
              <TableRow
                key={key}
                data-key={key}
                data-state={selectedKey === key ? "selected" : undefined}
              >
                <TableCell className="w-6">
                  {item.partition.subpartitions?.length > 0 ? (
                    <ChevronDown className="size-4" />
                  ) : null}
                </TableCell>
                <TableCell className="truncate max-w-[320px]">
                  <HighlightLabelText
                    text={item.partition.name}
                    keyword={keyword}
                  />
                </TableCell>
                <TableCell className="truncate">
                  {item.partition.type}
                </TableCell>
                <TableCell className="truncate">
                  {item.partition.expression}
                </TableCell>
                <TableCell className="truncate">
                  {item.partition.value}
                </TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
    </div>
  );
}

// frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/PartitionsTable.vue
<template>
  <div ref="containerElRef" class="w-full h-full overflow-x-auto">
    <NDataTable
      v-bind="$attrs"
      ref="dataTableRef"
      size="small"
      :row-key="partitionKey"
      :columns="columns"
      :data="layoutReady ? flattenItemList : []"
      :max-height="tableBodyHeight"
      :virtual-scroll="true"
      :striped="true"
      :bordered="true"
      :bottom-bordered="true"
    />
  </div>
</template>

<script setup lang="tsx">
import { ChevronDownIcon } from "lucide-vue-next";
import { NDataTable, type DataTableColumn } from "naive-ui";
import { computed, h, watch } from "vue";
import { useI18n } from "vue-i18n";
import type { ComposedDatabase } from "@/types";
import {
  TablePartitionMetadata,
  type DatabaseMetadata,
  type SchemaMetadata,
  type TableMetadata,
} from "@/types/proto/v1/database_service";
import { getHighlightHTMLByRegExp, useAutoHeightDataTable } from "@/utils";
import { useEditorPanelContext } from "../../context";

type FlattenTablePartitionMetadata = {
  partition: TablePartitionMetadata;
  parent?: TablePartitionMetadata;
};

const props = defineProps<{
  db: ComposedDatabase;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table: TableMetadata;
  keyword?: string;
}>();

const { t } = useI18n();
const { viewState } = useEditorPanelContext();
const {
  dataTableRef,
  containerElRef,
  virtualListRef,
  tableBodyHeight,
  layoutReady,
} = useAutoHeightDataTable();

const filteredPartitions = computed(() => {
  const keyword = props.keyword?.trim().toLowerCase();
  if (!keyword) {
    return props.table.partitions;
  }
  return props.table.partitions.filter((partition) => {
    return (
      partition.name.toLowerCase().includes(keyword) ||
      partition.subpartitions.some((sub) =>
        sub.name.toLowerCase().includes(keyword)
      )
    );
  });
});

const flattenItemList = computed(() => {
  const list: FlattenTablePartitionMetadata[] = [];
  const dfsWalk = (
    partition: TablePartitionMetadata,
    parent?: TablePartitionMetadata
  ) => {
    list.push({
      partition,
      parent,
    });
    partition.subpartitions?.forEach((child) => {
      dfsWalk(child, partition);
    });
  };
  filteredPartitions.value.forEach((partition) =>
    dfsWalk(partition, undefined)
  );
  return list;
});

const partitionKey = (item: FlattenTablePartitionMetadata) => {
  const keys: string[] = [];

  if (item.parent) keys.push(item.parent.name);
  keys.push(item.partition.name);
  return keys.join("/");
};

const columns = computed(() => {
  const columns: (DataTableColumn<FlattenTablePartitionMetadata> & {
    hide?: boolean;
  })[] = [
    {
      key: "parent",
      resizable: false,
      width: 24,
      render: (item) => {
        if (item.partition.subpartitions?.length > 0) {
          return <ChevronDownIcon class="w-4 h-4" />;
        }
      },
    },
    {
      key: "name",
      title: t("common.name"),
      resizable: true,
      minWidth: 140,
      maxWidth: 320,
      className: "truncate",
      render: (item) => {
        return h("span", {
          innerHTML: getHighlightHTMLByRegExp(
            item.partition.name,
            props.keyword ?? ""
          ),
        });
      },
    },
    {
      key: "partition.type",
      title: t("common.type"),
      resizable: true,
      minWidth: 140,
      className: "truncate",
    },
    {
      key: "partition.expression",
      title: t("schema-editor.table-partition.expression"),
      resizable: true,
      minWidth: 140,
      className: "truncate",
    },
    {
      key: "partition.value",
      title: t("schema-editor.table-partition.value"),
      resizable: true,
      minWidth: 140,
      className: "truncate",
    },
  ];
  return columns.filter((header) => !header.hide);
});

watch(
  [() => viewState.value?.detail.partition, virtualListRef],
  ([partition, vl]) => {
    if (partition && vl) {
      requestAnimationFrame(() => {
        vl.scrollTo({ key: partition });
      });
    }
  },
  { immediate: true }
);
</script>

<style lang="postcss" scoped>
:deep(.n-data-table-th .n-data-table-resize-button::after) {
  @apply bg-control-bg h-2/3;
}
:deep(.n-data-table-td.input-cell) {
  @apply pl-0.5 pr-1 py-0;
}

:deep(.n-data-table-td.input-cell .n-input__placeholder),
:deep(.n-data-table-td.input-cell .n-base-selection-placeholder) {
  @apply italic;
}
:deep(.n-data-table-td.checkbox-cell) {
  @apply pr-1 py-0;
}
:deep(.n-data-table-td.text-cell) {
  @apply pr-1 py-0;
}
</style>
