// frontend/src/modules/sql-editor/components/Panels/TablesPanel/TablesPanel.tsx
import { useState } from "react";
import { useAppDatabaseMetadata } from "@/hooks/useAppDatabaseMetadata";
import { useConnectionOfCurrentSQLEditorTab } from "@/modules/sql-editor/hooks/useSQLEditorState";
import { PanelSearchBox } from "../common/PanelSearchBox";
import { useViewStateNav } from "../common/useViewStateNav";
import { TableDetail } from "./TableDetail";
import { TablesTable } from "./TablesTable";

export function TablesPanel() {
  const { database } = useConnectionOfCurrentSQLEditorTab();
  const databaseName = database.name;
  const db = database;
  // Parent `Panels.tsx` drives the metadata fetch; we only subscribe.
  const databaseMetadata = useAppDatabaseMetadata(databaseName ?? "", {
    autoFetch: false,
  });

  const { schema: schemaName, detail, setDetail } = useViewStateNav();

  const [keyword, setKeyword] = useState("");

  const schema = databaseMetadata.schemas.find((s) => s.name === schemaName);
  const table = schema?.tables.find((t) => t.name === detail?.table);

  if (!db || !schema) return null;

  if (table) {
    return (
      <TableDetail
        db={db}
        database={databaseMetadata}
        schema={schema}
        table={table}
      />
    );
  }

  return (
    <div className="px-2 py-2 gap-y-2 h-full overflow-hidden flex flex-col">
      <div className="w-full flex flex-row gap-x-2 justify-end items-center">
        <PanelSearchBox value={keyword} onChange={setKeyword} />
      </div>
      <div className="flex-1 min-h-0">
        <TablesTable
          db={db}
          database={databaseMetadata}
          schema={schema}
          tables={schema.tables}
          keyword={keyword}
          onSelect={({ table: target }) => setDetail({ table: target.name })}
        />
      </div>
    </div>
  );
}

// frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesPanel.vue
<template>
  <div
    v-if="metadata?.schema"
    class="px-2 py-2 gap-y-2 h-full overflow-hidden flex flex-col"
  >
    <div
      v-show="!metadata.table"
      class="w-full flex flex-row gap-x-2 justify-between items-center"
    >
      <div class="flex items-center justify-start gap-2">
        <DatabaseChooser />
        <SchemaSelectToolbar simple />
      </div>
      <div class="flex items-center justify-end">
        <SearchBox
          v-model:value="state.keywords.table"
          size="small"
          style="width: 10rem"
        />
      </div>
    </div>
    <TablesTable
      v-show="!metadata.table"
      :db="database"
      :database="metadata.database"
      :schema="metadata.schema"
      :tables="metadata.schema.tables"
      :keyword="state.keywords.table"
      @click="select"
    />

    <TableDetail
      v-if="metadata.table"
      :db="database"
      :database="metadata.database"
      :schema="metadata.schema"
      :table="metadata.table"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, reactive } from "vue";
import { SearchBox } from "@/components/v2";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
} from "@/store";
import {
  DatabaseMetadata,
  SchemaMetadata,
  TableMetadata,
  TablePartitionMetadata,
} from "@/types/proto/v1/database_service";
import DatabaseChooser from "@/views/sql-editor/EditorCommon/DatabaseChooser.vue";
import { useEditorPanelContext } from "../../context";
import { SchemaSelectToolbar } from "../common";
import TableDetail from "./TableDetail.vue";
import TablesTable from "./TablesTable.vue";

const { database } = useConnectionOfCurrentSQLEditorTab();
const { viewState, updateViewState } = useEditorPanelContext();
const databaseMetadata = computed(() => {
  return useDBSchemaV1Store().getDatabaseMetadata(database.value.name);
});
const state = reactive({
  keywords: {
    table: "",
  },
});

const metadata = computed(() => {
  const database = databaseMetadata.value;
  const schema = database.schemas.find(
    (s) => s.name === viewState.value?.schema
  );
  const table = schema?.tables.find(
    (t) => t.name === viewState.value?.detail?.table
  );
  return { database, schema, table };
});

const select = (selected: {
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table?: TableMetadata;
  partition?: TablePartitionMetadata;
}) => {
  updateViewState({
    detail: {
      table: selected.table?.name,
      partition: selected.partition?.name,
    },
  });
};
</script>
