// frontend/src/modules/sql-editor/components/TreeNodePrefix.tsx
import {
  FileCode,
  FolderCode,
  FolderMinus,
  FolderOpen,
  FolderPen,
  FolderSync,
} from "lucide-react";
import type { WorksheetFolderNode } from "@/modules/sql-editor/model/Sheet";
import type { SheetViewMode } from "@/modules/sql-editor/model/Sheet/types";

type Props = {
  readonly node: WorksheetFolderNode;
  readonly isOpen: boolean;
  readonly rootPath: string;
  readonly view: SheetViewMode;
};

export function TreeNodePrefix({ node, isOpen, rootPath, view }: Props) {
  const cls = "size-4 text-control shrink-0";

  if (node.worksheet) {
    return <FileCode className={cls} />;
  }
  if (isOpen) {
    return <FolderOpen className={cls} />;
  }
  if (node.key === rootPath) {
    if (view === "draft") {
      return <FolderPen className={cls} />;
    }
    if (view === "shared") {
      return <FolderSync className={cls} />;
    }
    return <FolderCode className={cls} />;
  }
  if (node.empty) {
    return <FolderMinus className={cls} />;
  }
  return <FolderCode className={cls} />;
}

// frontend/src/views/sql-editor/AsidePanel/WorksheetPane/SheetList/TreeNodePrefix.vue
<template>
  <FileCodeIcon
    v-if="node.worksheet"
    class="w-4 h-auto text-gray-600"
  />
  <FolderOpenIcon
    v-else-if="expandedKeys.has(node.key)"
    class="w-4 h-auto text-gray-600"
  />
  <template v-else-if="node.key === rootPath">
    <FolderPenIcon
      v-if="view === 'draft'"
      class="w-4 h-auto text-gray-600"
    />
    <FolderSyncIcon
      v-else-if="view === 'shared'"
      class="w-4 h-auto text-gray-600"
    />
    <FolderCodeIcon
      v-else
      class="w-4 h-auto text-gray-600"
    />
  </template>
  <FolderMinusIcon
    v-else-if="node.empty"
    class="w-4 h-auto text-gray-600"
  />
  <FolderCodeIcon
    v-else
    class="w-4 h-auto text-gray-600"
  />
</template>

<script setup lang="ts">
import {
  FileCodeIcon,
  FolderCodeIcon,
  FolderMinusIcon,
  FolderOpenIcon,
  FolderPenIcon,
  FolderSyncIcon,
} from "lucide-vue-next";
import type {
  SheetViewMode,
  WorksheetFolderNode,
} from "@/views/sql-editor/Sheet";

defineProps<{
  node: WorksheetFolderNode;
  expandedKeys: Set<string>;
  rootPath: string;
  view: SheetViewMode;
}>();
</script>
