// frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel/PrettyJSON.vue
<template>
  <!-- eslint-disable-next-line vue/no-v-html -->
  <div v-html="state.html" />
</template>

<script setup lang="ts">
import { escape } from "lodash-es";
import { shallowReactive, watch } from "vue";

const props = defineProps<{
  content: string;
}>();

const state = shallowReactive({
  html: "",
  controller: new AbortController(),
});

watch(
  () => props.content,
  async (content) => {
    if (state.controller) {
      state.controller.abort();
      state.controller = new AbortController();
    }
    const controller = state.controller;
    const finish = (html: string) => {
      if (controller.signal.aborted) {
        return;
      }
      state.html = html;
    };

    try {
      const { prettyPrintJson } = await import("pretty-print-json");
      const { parse } = await import("lossless-json");
      const { losslessReviver } = await import("@/composables/utils");
      await import("./pretty-print-json.css");
      // Use lossless-json to preserve precision for large integers (> 2^53-1)
      const obj = parse(content, null, losslessReviver);
      const html = prettyPrintJson.toHtml(obj, {
        quoteKeys: true,
        trailingCommas: false,
      });
      finish(html);
    } catch (err) {
      console.warn("[PrettyJSON]", err);

      finish(escape(props.content));
    }
  },
  {
    immediate: true,
  }
);
</script>

// frontend/src/react/components/sql-editor/ResultView/PrettyJSON.tsx
import { escape } from "lodash-es";
import { useEffect, useState } from "react";

interface PrettyJSONProps {
  content: string;
}

/**
 * Pretty-prints a JSON string. Heavy deps (`pretty-print-json`,
 * `lossless-json`) load lazily so that JSON-cell hover doesn't pay
 * for them eagerly. An AbortController per `content` prevents the
 * older pretty-print result from racing in after a quick switch.
 */
export function PrettyJSON({ content }: PrettyJSONProps) {
  const [html, setHtml] = useState<string>("");

  useEffect(() => {
    const controller = new AbortController();
    (async () => {
      try {
        const [{ prettyPrintJson }, { parse }, { losslessReviver }] =
          await Promise.all([
            import("pretty-print-json"),
            import("lossless-json"),
            import("@/composables/utils"),
          ]);
        await import("./pretty-print-json.css");
        if (controller.signal.aborted) return;
        const obj = parse(content, null, losslessReviver);
        const next = prettyPrintJson.toHtml(obj, {
          quoteKeys: true,
          trailingCommas: false,
        });
        if (!controller.signal.aborted) setHtml(next);
      } catch (err) {
        console.warn("[PrettyJSON]", err);
        if (!controller.signal.aborted) setHtml(escape(content));
      }
    })();
    return () => controller.abort();
  }, [content]);

  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}
