// frontend/src/views/sql-editor/EditorCommon/ResultView/SelectionCopyTooltips.vue
<template>
  <div
    v-if="shouldShow"
    class="w-full absolute h-full bg-white dark:bg-dark-bg flex flex-row justify-start items-center text-control dark:text-control-light"
    @click.prevent.stop
  >
    <InfoIcon :size="16" class="mr-2 text-control" />
    <i18n-t
      keypath="sql-editor.copy-selected-results"
      tag="p"
      class="text-sm flex flex-row justify-start items-center gap-1"
    >
      <template #action>
        <NButton size="tiny" type="primary" secondary>
          <template #icon>
            <span v-if="isMac" class="text-base leading-none">⌘</span>
            <span
              v-else
              class="tracking-tighter text-xs transform scale-x-90 leading-none"
            >
              Ctrl
            </span>
          </template>
          C
        </NButton>
      </template>
      <template #button>
        <NButton size="tiny" @click="copySelectionToClipboard" type="primary" secondary>
          <template #icon>
            <CopyIcon />
          </template>
          {{ $t("common.copy") }}
        </NButton>
      </template>
    </i18n-t>
    <div class="ml-1">
      <NButton size="tiny" quaternary @click="deselect">
        {{ $t("sql-editor.cancel-selection") }}
      </NButton>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { CopyIcon, InfoIcon } from "lucide-vue-next";
import { NButton } from "naive-ui";
import { computed } from "vue";
import { useSelectionContext } from "./DataTable/common/selection-logic";

const { state: selectionState, copySelectionToClipboard, deselect } = useSelectionContext();

const shouldShow = computed(
  () =>
    selectionState.value.rows.length > 0 ||
    selectionState.value.columns.length > 0
);

const isMac = navigator.platform.match(/mac/i);
</script>

// frontend/src/react/components/sql-editor/ResultView/SelectionCopyTooltips.tsx
import { CopyIcon, InfoIcon } from "lucide-react";
import { Trans, useTranslation } from "react-i18next";
import { Button } from "@/react/components/ui/button";
import { useSelectionContext } from "./context";

export function SelectionCopyTooltips() {
  const { t } = useTranslation();
  const {
    state: { rows, columns },
    copySelected,
    deselect,
  } = useSelectionContext();

  if (rows.length === 0 && columns.length === 0) return null;

  const isMac = /mac/i.test(navigator.platform);

  return (
    <div
      className="w-full absolute h-full bg-background flex flex-row justify-start items-center text-control"
      onClick={(e) => {
        e.preventDefault();
        e.stopPropagation();
      }}
    >
      <InfoIcon size={16} className="mr-2 text-control" />
      <p className="text-sm flex flex-row justify-start items-center gap-1">
        <Trans
          i18nKey="sql-editor.copy-selected-results"
          components={{
            action: (
              <Button
                size="sm"
                variant="outline"
                className="h-6 px-2 gap-x-1"
                disabled
              >
                {isMac ? (
                  <span className="text-base leading-none">⌘</span>
                ) : (
                  <span className="tracking-tighter text-xs leading-none">
                    Ctrl
                  </span>
                )}
                C
              </Button>
            ),
            button: (
              <Button
                size="sm"
                variant="default"
                className="h-6 px-2 gap-x-1"
                onClick={copySelected}
              >
                <CopyIcon className="size-3" />
                {t("common.copy")}
              </Button>
            ),
          }}
        />
      </p>
      <div className="ml-1">
        <Button size="sm" variant="ghost" onClick={deselect}>
          {t("sql-editor.cancel-selection")}
        </Button>
      </div>
    </div>
  );
}
