// frontend/src/components/FileContentPreviewModal.vue
<template>
  <BBModal :title="$t('common.preview')" @close="$emit('cancel')">
    <div class="w-144 py-1 flex flex-col justify-start items-start gap-2">
      <div class="w-full flex flex-row justify-between items-center gap-4">
        <p class="font-medium textlabel text-nowrap">
          {{ $t("sql-editor.select-encoding") }}
        </p>
        <NSelect
          v-model:value="state.encoding"
          class="w-auto!"
          filterable
          :options="encodingOptions"
        />
      </div>
      <div class="w-full overflow-hidden relative h-80 shrink-0">
        <MonacoEditor
          class="border w-full h-full"
          :content="decodedText"
          :readonly="true"
        />
        <NSpin v-if="isLoading" class="absolute inset-0" />
      </div>
      <div class="w-full flex justify-end gap-x-2">
        <NButton @click="$emit('cancel')">
          {{ $t("common.cancel") }}
        </NButton>
        <NButton
          type="primary"
          :disabled="!allowConfirm"
          :loading="isLoading"
          @click="$emit('confirm', decodedText)"
        >
          {{ $t("common.confirm") }}
        </NButton>
      </div>
    </div>
  </BBModal>
</template>

<script lang="ts" setup>
import { NSelect, NButton, NSpin } from "naive-ui";
import { computed, reactive, ref, watch } from "vue";
import { BBModal } from "@/bbkit";
import { MonacoEditor } from "@/components/MonacoEditor";
import { pushNotification } from "@/store";
import { ENCODINGS, readFileAsArrayBuffer, type Encoding } from "@/utils";

interface LocalState {
  encoding: Encoding;
}

const props = defineProps<{
  file: File;
}>();

defineEmits<{
  (event: "cancel"): void;
  (event: "confirm", text: string): void;
}>();

const state = reactive<LocalState>({
  encoding: "utf-8",
});
const isLoading = ref(true);
const decodedText = ref<string>("");

const allowConfirm = computed(() => {
  return !isLoading.value;
});

const encodingOptions = computed(() =>
  ENCODINGS.map((encoding) => ({
    label: encoding,
    value: encoding,
  }))
);

watch(
  [() => props.file, state],
  async () => {
    isLoading.value = true;
    try {
      const { arrayBuffer } = await readFileAsArrayBuffer(props.file);
      const text = new TextDecoder(state.encoding).decode(arrayBuffer);
      decodedText.value = text;
    } catch (error) {
      console.error(error);
      pushNotification({
        module: "bytebase",
        style: "CRITICAL",
        title: "Failed to read file",
      });
    }
    isLoading.value = false;
  },
  {
    immediate: true,
  }
);
</script>

// frontend/src/react/components/sql-editor/StandardPanel/FileContentPreviewModal.tsx
import { Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { ReadonlyMonaco } from "@/react/components/monaco/ReadonlyMonaco";
import { Button } from "@/react/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogTitle,
} from "@/react/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/react/components/ui/select";
import { pushNotification } from "@/store";
import { ENCODINGS, type Encoding, readFileAsArrayBuffer } from "@/utils";

interface FileContentPreviewModalProps {
  file: File;
  open: boolean;
  onCancel: () => void;
  onConfirm: (text: string) => void;
}

/**
 * React port of `frontend/src/components/FileContentPreviewModal.vue`.
 * Decodes the file as bytes, exposes an encoding picker, renders the
 * decoded text in a read-only Monaco preview, and emits the chosen
 * statement back to the caller on confirm.
 */
export function FileContentPreviewModal({
  file,
  open,
  onCancel,
  onConfirm,
}: FileContentPreviewModalProps) {
  const { t } = useTranslation();
  const [encoding, setEncoding] = useState<Encoding>("utf-8");
  const [decodedText, setDecodedText] = useState("");
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    void readFileAsArrayBuffer(file)
      .then(({ arrayBuffer }) => {
        if (cancelled) return;
        const text = new TextDecoder(encoding).decode(arrayBuffer);
        setDecodedText(text);
      })
      .catch((error) => {
        if (cancelled) return;
        console.error(error);
        pushNotification({
          module: "bytebase",
          style: "CRITICAL",
          title: "Failed to read file",
        });
      })
      .finally(() => {
        if (cancelled) return;
        setIsLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [file, encoding]);

  return (
    <Dialog open={open} onOpenChange={(next) => !next && onCancel()}>
      <DialogContent className="w-[36rem] max-w-[36rem]">
        <DialogTitle>{t("common.preview")}</DialogTitle>
        <div className="py-1 flex flex-col justify-start items-start gap-2">
          <div className="w-full flex flex-row justify-between items-center gap-4">
            <p className="font-medium textlabel whitespace-nowrap">
              {t("sql-editor.select-encoding")}
            </p>
            <Select
              value={encoding}
              onValueChange={(value) => {
                if (typeof value === "string") setEncoding(value as Encoding);
              }}
            >
              <SelectTrigger size="sm" className="w-auto">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {ENCODINGS.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="w-full overflow-hidden relative h-80 shrink-0 border border-control-border rounded-xs">
            <ReadonlyMonaco content={decodedText} className="w-full h-full" />
            {isLoading ? (
              <div className="absolute inset-0 bg-background/60 flex items-center justify-center">
                <Loader2 className="size-6 animate-spin text-control-light" />
              </div>
            ) : null}
          </div>
          <div className="w-full flex justify-end gap-x-2">
            <Button variant="outline" onClick={onCancel}>
              {t("common.cancel")}
            </Button>
            <Button
              variant="default"
              disabled={isLoading}
              onClick={() => onConfirm(decodedText)}
            >
              {t("common.confirm")}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
