// frontend/src/components/misc/SQLUploadButton.vue
<template>
  <NButton tag="div" v-bind="$attrs" @click="handleClick">
    <template #icon>
      <slot name="icon">
        <UploadIcon class="w-4 h-4" />
      </slot>

      <input
        ref="inputRef"
        type="file"
        accept=".sql,.txt,application/sql,text/plain"
        class="hidden"
        @change="handleUpload"
      />
    </template>

    <span v-if="!iconOnly">
      <slot />
    </span>

    <FileContentPreviewModal
      v-if="selectedFile"
      :file="selectedFile"
      @cancel="cleanup"
      @confirm="handleStatementConfirm"
    />
  </NButton>
</template>

<script lang="ts" setup>
import { UploadIcon } from "lucide-vue-next";
import { NButton } from "naive-ui";
import { ref } from "vue";
import { useI18n } from "vue-i18n";
import FileContentPreviewModal from "@/components/FileContentPreviewModal.vue";
import { pushNotification } from "@/store";
import { MAX_UPLOAD_FILE_SIZE_MB } from "@/utils";

defineProps<{
  iconOnly?: boolean;
}>();

const emit = defineEmits<{
  (event: "update:sql", text: string, filename: string): void;
}>();

const { t } = useI18n();
const inputRef = ref<HTMLInputElement>();
const selectedFile = ref<File | null>(null);

const handleClick = () => {
  inputRef.value?.click();
};

const cleanup = () => {
  selectedFile.value = null;
  if (!inputRef.value) {
    return;
  }
  inputRef.value.files = null;
  inputRef.value.value = "";
};

const handleUpload = async (e: Event) => {
  const target = e.target as HTMLInputElement;
  const file = (target.files || [])[0];
  const cleanup = () => {
    // Note that once selected a file, selecting the same file again will not
    // trigger <input type="file">'s change event.
    // So we need to do some cleanup stuff here.
    target.files = null;
    target.value = "";
  };

  if (!file) {
    return cleanup();
  }
  if (file.size > MAX_UPLOAD_FILE_SIZE_MB * 1024 * 1024) {
    pushNotification({
      module: "bytebase",
      style: "CRITICAL",
      title: t("issue.upload-sql-file-max-size-exceeded", {
        size: `${MAX_UPLOAD_FILE_SIZE_MB}MB`,
      }),
    });
    return cleanup();
  }

  selectedFile.value = file;

  cleanup();
};

const handleStatementConfirm = (statement: string) => {
  emit("update:sql", statement, selectedFile.value!.name);
  cleanup();
};
</script>

// frontend/src/react/components/sql-editor/StandardPanel/SQLUploadButton.tsx
import type { ChangeEvent, ReactNode } from "react";
import { useCallback, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/react/components/ui/button";
import { cn } from "@/react/lib/utils";
import { pushNotification } from "@/store";
import { MAX_UPLOAD_FILE_SIZE_MB } from "@/utils";
import { FileContentPreviewModal } from "./FileContentPreviewModal";

interface SQLUploadButtonProps {
  iconOnly?: boolean;
  className?: string;
  children?: ReactNode;
  onUpdateSql: (text: string, filename: string) => void;
}

/**
 * React port of `frontend/src/components/misc/SQLUploadButton.vue`.
 *
 * Hidden `<input type="file">` triggered by clicking the button. After
 * the user picks a file, mounts a preview modal that decodes + shows
 * the content; the parent receives the final text via `onUpdateSql`.
 */
export function SQLUploadButton({
  iconOnly,
  className,
  children,
  onUpdateSql,
}: SQLUploadButtonProps) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLInputElement>(null);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);

  const cleanup = useCallback(() => {
    setSelectedFile(null);
    if (inputRef.current) {
      inputRef.current.value = "";
    }
  }, []);

  const handleClick = useCallback(() => {
    inputRef.current?.click();
  }, []);

  const handleUpload = useCallback(
    (event: ChangeEvent<HTMLInputElement>) => {
      const file = event.target.files?.[0];
      const cleanupInput = () => {
        // Selecting the same file twice doesn't fire `change` again,
        // so reset the value here too.
        if (inputRef.current) {
          inputRef.current.value = "";
        }
      };
      if (!file) {
        cleanupInput();
        return;
      }
      if (file.size > MAX_UPLOAD_FILE_SIZE_MB * 1024 * 1024) {
        pushNotification({
          module: "bytebase",
          style: "CRITICAL",
          title: t("issue.upload-sql-file-max-size-exceeded", {
            size: `${MAX_UPLOAD_FILE_SIZE_MB}MB`,
          }),
        });
        cleanupInput();
        return;
      }
      setSelectedFile(file);
      cleanupInput();
    },
    [t]
  );

  const handleConfirm = useCallback(
    (statement: string) => {
      if (selectedFile) {
        onUpdateSql(statement, selectedFile.name);
      }
      cleanup();
    },
    [onUpdateSql, selectedFile, cleanup]
  );

  return (
    <>
      <Button
        type="button"
        variant="ghost"
        size="sm"
        className={cn("h-7 px-1", className)}
        onClick={handleClick}
      >
        {children}
        {iconOnly ? null : (
          <span className="ml-1">{t("sql-editor.upload-file")}</span>
        )}
      </Button>
      <input
        ref={inputRef}
        type="file"
        accept=".sql,.txt,application/sql,text/plain"
        className="hidden"
        onChange={handleUpload}
      />
      {selectedFile ? (
        <FileContentPreviewModal
          file={selectedFile}
          open
          onCancel={cleanup}
          onConfirm={handleConfirm}
        />
      ) : null}
    </>
  );
}
