// frontend/src/react/components/sql-editor/SchemaPane/HoverPanel/TableInfo.tsx
import { useTranslation } from "react-i18next";
import { EngineIcon } from "@/react/components/EngineIcon";
import { useDatabaseV1Store, useDBSchemaV1Store } from "@/store";
import { Engine } from "@/types/proto-es/v1/common_pb";
import { bytesToString, getInstanceResource } from "@/utils";
import { engineNameV1 } from "@/utils/v1/instance";
import { InfoItem } from "./InfoItem";

type Props = {
  readonly database: string;
  readonly schema?: string;
  readonly table: string;
};

/**
 * Replaces `HoverPanel/TableInfo.vue`. Index size and collation are
 * hidden for ClickHouse + Snowflake; collation is also hidden for
 * Postgres because the engine reports it at the column level instead of
 * the table level. Comment is shown only when present.
 */
export function TableInfo({ database, schema, table }: Props) {
  const { t } = useTranslation();
  const dbSchema = useDBSchemaV1Store();
  const databaseStore = useDatabaseV1Store();

  const tableMetadata = dbSchema.getTableMetadata({ database, schema, table });
  const instanceEngine = getInstanceResource(
    databaseStore.getDatabaseByName(database)
  ).engine;

  const indexSize =
    instanceEngine === Engine.CLICKHOUSE || instanceEngine === Engine.SNOWFLAKE
      ? ""
      : bytesToString(Number(tableMetadata.indexSize));
  const collation =
    instanceEngine === Engine.CLICKHOUSE ||
    instanceEngine === Engine.SNOWFLAKE ||
    instanceEngine === Engine.POSTGRES
      ? ""
      : tableMetadata.collation;
  const comment = tableMetadata.comment;

  return (
    <div className="min-w-56 max-w-[18rem] gap-y-1">
      <InfoItem title={t("common.name")}>{tableMetadata.name}</InfoItem>
      <InfoItem title={t("database.engine")}>
        <span className="flex items-center gap-x-0.5">
          <EngineIcon engine={instanceEngine} className="size-4" />
          {engineNameV1(instanceEngine)}
        </span>
      </InfoItem>
      <InfoItem title={t("database.row-count-estimate")}>
        {String(tableMetadata.rowCount)}
      </InfoItem>
      <InfoItem title={t("database.data-size")}>
        {bytesToString(Number(tableMetadata.dataSize))}
      </InfoItem>
      {indexSize ? (
        <InfoItem title={t("database.index-size")}>{indexSize}</InfoItem>
      ) : null}
      {collation ? (
        <InfoItem title={t("db.collation")}>{collation}</InfoItem>
      ) : null}
      {comment ? (
        <InfoItem title={t("database.comment")}>{comment}</InfoItem>
      ) : null}
    </div>
  );
}

// frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/TableInfo.vue
<template>
  <div class="min-w-[14rem] max-w-[18rem] gap-y-1">
    <InfoItem :title="$t('common.name')">
      {{ tableMetadata.name }}
    </InfoItem>
    <InfoItem :title="$t('database.engine')">
      <RichEngineName :engine="instanceEngine" />
    </InfoItem>
    <InfoItem :title="$t('database.row-count-estimate')">
      {{ tableMetadata.rowCount }}
    </InfoItem>
    <InfoItem :title="$t('database.data-size')">
      {{ bytesToString(Number(tableMetadata.dataSize)) }}
    </InfoItem>
    <InfoItem v-if="indexSize" :title="$t('database.index-size')">
      {{ indexSize }}
    </InfoItem>
    <InfoItem v-if="collation" :title="$t('db.collation')">
      {{ collation }}
    </InfoItem>
    <InfoItem v-if="comment" :title="$t('database.comment')">
      {{ comment }}
    </InfoItem>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { RichEngineName } from "@/components/v2";
import { useDBSchemaV1Store, useDatabaseV1Store } from "@/store";
import { Engine } from "@/types/proto-es/v1/common_pb";
import { bytesToString } from "@/utils";
import InfoItem from "./InfoItem.vue";

const props = defineProps<{
  database: string;
  schema?: string;
  table: string;
}>();

const dbSchema = useDBSchemaV1Store();
const databaseStore = useDatabaseV1Store();

const instanceEngine = computed(
  () => databaseStore.getDatabaseByName(props.database).instanceResource.engine
);

const tableMetadata = computed(() =>
  dbSchema.getTableMetadata({
    database: props.database,
    schema: props.schema,
    table: props.table,
  })
);

const indexSize = computed(() => {
  if ([Engine.CLICKHOUSE, Engine.SNOWFLAKE].includes(instanceEngine.value)) {
    return "";
  }
  return bytesToString(Number(tableMetadata.value.indexSize));
});

const collation = computed(() => {
  if (
    [Engine.CLICKHOUSE, Engine.SNOWFLAKE, Engine.POSTGRES].includes(
      instanceEngine.value
    )
  ) {
    return "";
  }
  return tableMetadata.value.collation;
});

const comment = computed(() => {
  return tableMetadata.value.userComment;
});
</script>
