// frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ForeignKeysTable.vue
<template>
  <div ref="containerElRef" class="w-full h-full overflow-x-auto">
    <NDataTable
      v-bind="$attrs"
      ref="dataTableRef"
      size="small"
      :row-key="(fk) => fk.name"
      :columns="columns"
      :data="layoutReady ? filteredForeignKeys : []"
      :max-height="tableBodyHeight"
      :virtual-scroll="true"
      :striped="true"
      :bordered="true"
      :bottom-bordered="true"
      row-class-name="cursor-default"
    />
  </div>
</template>

<script lang="ts" setup>
import type { DataTableColumn, DataTableInst } from "naive-ui";
import { NDataTable } from "naive-ui";
import { computed, h, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import type { ComposedDatabase } from "@/types";
import { Engine } from "@/types/proto-es/v1/common_pb";
import type {
  DatabaseMetadata,
  ForeignKeyMetadata,
  SchemaMetadata,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { convertEngineToNew } from "@/utils/v1/common-conversions";
import { getHighlightHTMLByRegExp, useAutoHeightDataTable } from "@/utils";
import { useCurrentTabViewStateContext } from "../../context/viewState";

const props = defineProps<{
  db: ComposedDatabase;
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  table: TableMetadata;
  keyword?: string;
}>();

const { viewState } = useCurrentTabViewStateContext();
const { containerElRef, virtualListRef, tableBodyHeight, layoutReady } =
  useAutoHeightDataTable();
const dataTableRef = ref<DataTableInst>();
const { t } = useI18n();

const filteredForeignKeys = computed(() => {
  const keyword = props.keyword?.trim().toLowerCase();
  if (!keyword) return props.table.foreignKeys;
  return props.table.foreignKeys.filter(
    (fk) =>
      fk.name.toLowerCase().includes(keyword) ||
      fk.columns.some((column) => column.toLowerCase().includes(keyword)) ||
      fk.referencedSchema.toLowerCase().includes(keyword) ||
      fk.referencedTable.toLowerCase().includes(keyword) ||
      fk.referencedColumns.some((column) =>
        column.toLowerCase().includes(keyword)
      )
  );
});

const columns = computed(() => {
  const columns: (DataTableColumn<ForeignKeyMetadata> & { hide?: boolean })[] =
    [
      {
        key: "name",
        title: t("schema-editor.column.name"),
        resizable: true,
        minWidth: 140,
        className: "truncate",
        render: (index) => {
          return h("span", {
            innerHTML: getHighlightHTMLByRegExp(
              index.name,
              props.keyword ?? ""
            ),
          });
        },
      },
      {
        key: "columns",
        title: t("schema-editor.columns"),
        resizable: true,
        minWidth: 140,
        render: (fk) => {
          const keyword = props.keyword ?? "";
          const columns = fk.columns.map((column) => {
            return h("span", {
              innerHTML: getHighlightHTMLByRegExp(column, keyword),
            });
          });
          return h("div", { class: "flex flex-col gap-1" }, columns);
        },
      },
      {
        key: "referencedColumns",
        title: t("database.foreign-key.reference"),
        resizable: true,
        minWidth: 140,
        render: (fk) => {
          const keyword = props.keyword ?? "";
          const columns = fk.referencedColumns.map((column) => {
            const parts: string[] = [];
            if (fk.referencedSchema) parts.push(fk.referencedSchema);
            parts.push(fk.referencedTable);
            parts.push(column);
            return h("span", {
              innerHTML: getHighlightHTMLByRegExp(parts.join("."), keyword),
            });
          });
          return h("div", { class: "flex flex-col gap-1" }, columns);
        },
      },
      {
        key: "onDelete",
        title: "ON DELETE",
        resizable: true,
        minWidth: 140,
        hide: props.table.foreignKeys.every((fk) => !fk.onDelete),
      },
      {
        key: "onUpdate",
        title: "ON UPDATE",
        resizable: true,
        minWidth: 140,
        hide: props.table.foreignKeys.every((fk) => !fk.onUpdate),
      },
      {
        key: "matchType",
        title: "Match type",
        resizable: true,
        minWidth: 140,
        hide: convertEngineToNew(props.db.instanceResource.engine) !== Engine.POSTGRES,
      },
    ];
  return columns.filter((header) => !header.hide);
});

watch(
  [() => viewState.value?.detail.foreignKey, virtualListRef],
  ([fk, vl]) => {
    if (fk && vl) {
      requestAnimationFrame(() => {
        vl.scrollTo({ key: fk });
      });
    }
  },
  { immediate: true }
);
</script>

<style lang="postcss" scoped>
:deep(.n-data-table-th .n-data-table-resize-button::after) {
  @apply bg-control-bg h-2/3;
}
:deep(.n-data-table-td.input-cell) {
  @apply pl-0.5 pr-1 py-0;
}
:deep(.n-data-table-td.checkbox-cell) {
  @apply pr-1 py-0;
}
</style>

// frontend/src/react/components/sql-editor/Panels/common/tables/ForeignKeysTable.tsx
import { useEffect, useMemo, useRef } from "react";
import { useTranslation } from "react-i18next";
import { HighlightLabelText } from "@/react/components/HighlightLabelText";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/react/components/ui/table";
import { Engine } from "@/types/proto-es/v1/common_pb";
import type {
  Database,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import { getInstanceResource } from "@/utils";
import { useViewStateNav } from "../useViewStateNav";

interface ForeignKeysTableProps {
  db: Database;
  table: TableMetadata;
  keyword?: string;
}

export function ForeignKeysTable({
  db,
  table,
  keyword,
}: ForeignKeysTableProps) {
  const { t } = useTranslation();
  const { detail } = useViewStateNav();
  const containerRef = useRef<HTMLDivElement>(null);

  const filtered = useMemo(() => {
    const trimmed = keyword?.trim().toLowerCase();
    if (!trimmed) return table.foreignKeys;
    return table.foreignKeys.filter(
      (fk) =>
        fk.name.toLowerCase().includes(trimmed) ||
        fk.columns.some((c) => c.toLowerCase().includes(trimmed)) ||
        fk.referencedSchema.toLowerCase().includes(trimmed) ||
        fk.referencedTable.toLowerCase().includes(trimmed) ||
        fk.referencedColumns.some((c) => c.toLowerCase().includes(trimmed))
    );
  }, [table.foreignKeys, keyword]);

  const showOnDelete = table.foreignKeys.some((fk) => fk.onDelete);
  const showOnUpdate = table.foreignKeys.some((fk) => fk.onUpdate);
  const showMatchType = getInstanceResource(db).engine === Engine.POSTGRES;

  const selectedKey = detail?.foreignKey;

  useEffect(() => {
    if (!selectedKey) return;
    const el = containerRef.current?.querySelector<HTMLElement>(
      `[data-key="${CSS.escape(selectedKey)}"]`
    );
    el?.scrollIntoView({ block: "nearest" });
  }, [selectedKey]);

  return (
    <div ref={containerRef} className="w-full h-full overflow-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{t("schema-editor.column.name")}</TableHead>
            <TableHead>{t("schema-editor.columns")}</TableHead>
            <TableHead>{t("database.foreign-key.reference")}</TableHead>
            {showOnDelete ? <TableHead>ON DELETE</TableHead> : null}
            {showOnUpdate ? <TableHead>ON UPDATE</TableHead> : null}
            {showMatchType ? <TableHead>Match type</TableHead> : null}
          </TableRow>
        </TableHeader>
        <TableBody>
          {filtered.map((fk) => (
            <TableRow
              key={fk.name}
              data-key={fk.name}
              data-state={selectedKey === fk.name ? "selected" : undefined}
            >
              <TableCell className="truncate max-w-[200px]">
                <HighlightLabelText text={fk.name} keyword={keyword} />
              </TableCell>
              <TableCell>
                <div className="flex flex-col gap-1">
                  {fk.columns.map((column, i) => (
                    <span key={`${column}-${i}`}>
                      <HighlightLabelText text={column} keyword={keyword} />
                    </span>
                  ))}
                </div>
              </TableCell>
              <TableCell>
                <div className="flex flex-col gap-1">
                  {fk.referencedColumns.map((column, i) => {
                    const parts: string[] = [];
                    if (fk.referencedSchema) parts.push(fk.referencedSchema);
                    parts.push(fk.referencedTable);
                    parts.push(column);
                    return (
                      <span key={`${column}-${i}`}>
                        <HighlightLabelText
                          text={parts.join(".")}
                          keyword={keyword}
                        />
                      </span>
                    );
                  })}
                </div>
              </TableCell>
              {showOnDelete ? <TableCell>{fk.onDelete}</TableCell> : null}
              {showOnUpdate ? <TableCell>{fk.onUpdate}</TableCell> : null}
              {showMatchType ? <TableCell>{fk.matchType}</TableCell> : null}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
