// frontend/src/react/components/sql-editor/AdminModeButton.tsx
import { Wrench } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Button } from "@/react/components/ui/button";
import { Tooltip } from "@/react/components/ui/tooltip";
import { useVueState } from "@/react/hooks/useVueState";
import { cn } from "@/react/lib/utils";
import { useSQLEditorStore, useSQLEditorTabStore } from "@/store";

type AdminModeButtonProps = {
  readonly size?: "sm" | "default";
  readonly hideText?: boolean;
};

/**
 * Replaces frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue.
 * Visible only when the user has admin permission AND the current tab is
 * in WORKSHEET mode. Clicking switches the tab to ADMIN mode.
 */
export function AdminModeButton({
  size = "default",
  hideText = false,
}: AdminModeButtonProps) {
  const { t } = useTranslation();
  const editorStore = useSQLEditorStore();
  const tabStore = useSQLEditorTabStore();

  const allowAdmin = useVueState(() => editorStore.allowAdmin);
  const currentTabMode = useVueState(() => tabStore.currentTab?.mode);
  const isDisconnected = useVueState(() => tabStore.isDisconnected);

  if (!allowAdmin || currentTabMode !== "WORKSHEET") {
    return null;
  }

  const label = t("sql-editor.admin-mode.self");

  const handleClick = () => {
    tabStore.updateCurrentTab({ mode: "ADMIN" });
  };

  return (
    <Tooltip content={label} side="bottom">
      <Button
        variant="outline"
        size={size}
        disabled={isDisconnected}
        onClick={handleClick}
        className={cn(
          "h-7 px-1.5 gap-1",
          "border-warning text-warning hover:bg-warning/5 hover:text-warning"
        )}
      >
        <Wrench className="size-4" />
        {!hideText && <span>{label}</span>}
      </Button>
    </Tooltip>
  );
}

// frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
<template>
  <NButton
    v-if="showButton"
    :size="props.size"
    type="warning"
    :ghost="true"
    :disabled="isDisconnected"
    @click.stop="enterAdminMode"
  >
    <template #icon>
      <WrenchIcon class="w-4 h-4" />
    </template>
    <span v-if="!hideText">{{ $t("sql-editor.admin-mode.self") }}</span>
  </NButton>
</template>

<script lang="ts" setup>
import { WrenchIcon } from "lucide-vue-next";
import { type ButtonProps, NButton } from "naive-ui";
import { storeToRefs } from "pinia";
import type { PropType } from "vue";
import { computed } from "vue";
import { useSQLEditorStore, useSQLEditorTabStore } from "@/store";

const emit = defineEmits<{
  (e: "enter"): void;
}>();

const props = defineProps({
  size: {
    type: String as PropType<ButtonProps["size"]>,
    default: "medium",
  },
  hideText: {
    type: Boolean,
    default: false,
  },
});

const tabStore = useSQLEditorTabStore();
const editorStore = useSQLEditorStore();

const { currentTab, isDisconnected } = storeToRefs(tabStore);

const showButton = computed(() => {
  if (!editorStore.allowAdmin) return false;
  const mode = currentTab.value?.mode;
  return mode === "WORKSHEET";
});

const enterAdminMode = async () => {
  const tab = currentTab.value;
  if (!tab) {
    return;
  }

  tabStore.updateCurrentTab({
    mode: "ADMIN",
  });

  emit("enter");
};
</script>
