// frontend/src/react/components/sql-editor/DatabaseChooser.tsx
import { ChevronRight, Database, SquareStack } from "lucide-react";
import { useTranslation } from "react-i18next";
import { EngineIconPath } from "@/components/InstanceForm/constants";
import { EnvironmentLabel } from "@/react/components/EnvironmentLabel";
import { Tooltip } from "@/react/components/ui/tooltip";
import { useVueState } from "@/react/hooks/useVueState";
import { cn } from "@/react/lib/utils";
import {
  useConnectionOfCurrentSQLEditorTab,
  useSQLEditorStore,
  useSQLEditorTabStore,
  useSQLEditorUIStore,
} from "@/store";
import { isValidDatabaseName, isValidInstanceName } from "@/types";
import {
  extractDatabaseResourceName,
  getDatabaseEnvironment,
  getInstanceResource,
} from "@/utils";

type DatabaseChooserProps = {
  readonly disabled?: boolean;
};

/**
 * Replaces frontend/src/views/sql-editor/EditorCommon/DatabaseChooser.vue.
 * Breadcrumb-style chooser showing the current connection
 * (Environment > Instance > Database). Click opens the connection panel.
 */
export function DatabaseChooser({ disabled = false }: DatabaseChooserProps) {
  const { t } = useTranslation();
  const tabStore = useSQLEditorTabStore();
  const editorStore = useSQLEditorStore();
  const uiStore = useSQLEditorUIStore();
  const connection = useConnectionOfCurrentSQLEditorTab();

  const currentTab = useVueState(() => tabStore.currentTab);
  const isInBatchMode = useVueState(() => tabStore.isInBatchMode);
  const projectContextReady = useVueState(
    () => editorStore.projectContextReady
  );
  const database = useVueState(() => connection.database.value);

  const instance = getInstanceResource(database);
  const environment = getDatabaseEnvironment(database);
  const databaseName = extractDatabaseResourceName(database.name).databaseName;

  const isConnected =
    !!currentTab &&
    isValidInstanceName(instance.name) &&
    isValidDatabaseName(database.name);

  const handleClick = () => {
    uiStore.showConnectionPanel = true;
  };

  return (
    <button
      type="button"
      disabled={disabled || !projectContextReady}
      onClick={handleClick}
      className={cn(
        "inline-flex items-center justify-end gap-1 px-2 h-8 text-sm",
        "border border-accent text-accent",
        "hover:bg-accent/5 focus:bg-accent/5",
        "rounded-none first:rounded-l-xs last:rounded-r-xs",
        "[&:not(:last-child)]:border-r-0",
        "disabled:opacity-50 disabled:cursor-not-allowed",
        "transition-colors overflow-hidden"
      )}
    >
      {isConnected ? (
        <div className="flex flex-row items-center text-control truncate">
          {isInBatchMode && (
            <Tooltip content={t("sql-editor.batch-query.batch")}>
              <SquareStack className="size-4 mr-1 text-accent" />
            </Tooltip>
          )}
          <EnvironmentLabel environmentName={environment.name} />
          <ChevronRight className="size-4 shrink-0 text-control-light" />
          <div className="flex items-center gap-1">
            <img
              className="size-4 shrink-0"
              src={EngineIconPath[instance.engine]}
              alt=""
            />
            <span className="truncate">{instance.title}</span>
          </div>
          <ChevronRight className="size-4 shrink-0 text-control-light" />
          <div className="flex items-center gap-1 truncate">
            <Database className="size-4 shrink-0" />
            <span className="truncate">{databaseName}</span>
          </div>
        </div>
      ) : (
        <span>{t("sql-editor.select-a-database-to-start")}</span>
      )}
    </button>
  );
}

// frontend/src/views/sql-editor/EditorCommon/DatabaseChooser.vue
<template>
  <NButton
    :disabled="disabled || !projectContextReady"
    type="primary"
    size="small"
    ghost
    style="
      justify-content: end;
      --n-padding: 0 8px;
      --n-color-hover: rgb(var(--color-accent) / 0.05);
      --n-color-pressed: rgb(var(--color-accent) / 0.05);
      --n-color-focus: rgb(var(--color-accent) / 0.05);
    "
    @click="changeConnection"
  >
    <div
      v-if="
        currentTab &&
        isValidInstanceName(instance.name) &&
        isValidDatabaseName(database.name)
      "
      class="flex flex-row items-center text-main"
    >
      <NPopover v-if="isInBatchMode" placement="bottom">
        <template #trigger>
          <SquareStackIcon class="w-4 h-4 mr-1 text-accent" />
        </template>
        <template #default>
          {{ $t("sql-editor.batch-query.batch") }}
        </template>
      </NPopover>
      <EnvironmentV1Name
        :environment="database.effectiveEnvironmentEntity"
        :link="false"
      />
      <ChevronRightIcon class="shrink-0 h-4 w-4 text-control-light" />
      <div class="flex items-center gap-1">
        <InstanceV1EngineIcon
          :instance="instance"
          show-status
          class="shrink-0"
        />
        <span>{{ instance.title }}</span>
      </div>
      <ChevronRightIcon class="shrink-0 h-4 w-4 text-control-light" />
      <div class="flex items-center gap-1">
        <DatabaseIcon class="shrink-0" />
        <span>{{ database.databaseName }}</span>
      </div>
    </div>
    <template v-else>
      {{ $t("sql-editor.select-a-database-to-start") }}
    </template>
  </NButton>
</template>

<script lang="ts" setup>
import { ChevronRightIcon, SquareStackIcon } from "lucide-vue-next";
import { NButton, NPopover } from "naive-ui";
import { storeToRefs } from "pinia";
import { DatabaseIcon } from "@/components/Icon";
import { EnvironmentV1Name, InstanceV1EngineIcon } from "@/components/v2";
import {
  useConnectionOfCurrentSQLEditorTab,
  useSQLEditorStore,
  useSQLEditorTabStore,
} from "@/store";
import { isValidDatabaseName, isValidInstanceName } from "@/types";
import { useSQLEditorContext } from "../context";

const { currentTab, isInBatchMode } = storeToRefs(useSQLEditorTabStore());
const { showConnectionPanel } = useSQLEditorContext();
const { projectContextReady } = storeToRefs(useSQLEditorStore());

const { instance, database } = useConnectionOfCurrentSQLEditorTab();

const changeConnection = () => {
  showConnectionPanel.value = true;
};

defineProps<{
  disabled?: boolean;
}>();
</script>

<style lang="postcss" scoped>
:deep(.n-button__content) {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
