// frontend/src/react/components/sql-editor/SaveSheetModal.tsx
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/react/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogTitle,
} from "@/react/components/ui/dialog";
import { Input } from "@/react/components/ui/input";
import { useSQLEditorEvent } from "@/react/hooks/useSQLEditorEvent";
import { useSQLEditorWorksheetStore, useWorkSheetStore } from "@/store";
import type { SQLEditorTab } from "@/types";
import { UNKNOWN_ID } from "@/types";
import { extractWorksheetID } from "@/utils";
import { useSheetContextByView } from "@/views/sql-editor/Sheet";
import { FolderForm } from "./FolderForm";

export function SaveSheetModal() {
  const { t } = useTranslation();
  const worksheetStore = useWorkSheetStore();
  const editorWorksheetStore = useSQLEditorWorksheetStore();
  const sheetContext = useSheetContextByView("my");

  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [folder, setFolder] = useState("");
  const [rawTab, setRawTab] = useState<SQLEditorTab | undefined>(undefined);

  const needShowModal = (tab: SQLEditorTab) => !tab.worksheet;

  const doSaveSheet = async (tab?: SQLEditorTab, tabTitle?: string) => {
    const effectiveTab = tab ?? rawTab;
    if (!effectiveTab) {
      setOpen(false);
      return;
    }
    // Use the passed title (silent path) or the current state title (modal path)
    const effectiveTitle = tabTitle ?? title;
    if (effectiveTitle === "") {
      return;
    }

    editorWorksheetStore.abortAutoSave();

    const { worksheet, connection, statement, id: tabId } = effectiveTab;
    const folders = sheetContext.getFoldersForWorksheet(folder);

    const sheetId = extractWorksheetID(worksheet ?? "");
    if (sheetId !== String(UNKNOWN_ID)) {
      await editorWorksheetStore.maybeUpdateWorksheet({
        tabId,
        worksheet,
        title: effectiveTitle,
        database: connection.database,
        statement,
        folders,
      });
    } else {
      await editorWorksheetStore.createWorksheet({
        tabId,
        title: effectiveTitle,
        statement,
        database: connection.database,
        folders,
      });
    }

    setOpen(false);
  };

  useSQLEditorEvent("save-sheet", ({ tab, editTitle }) => {
    setTitle(tab.title);
    setFolder("");
    setRawTab(tab);

    if (needShowModal(tab) || editTitle) {
      if (tab.worksheet) {
        const worksheet = worksheetStore.getWorksheetByName(tab.worksheet);
        if (worksheet) {
          setFolder(sheetContext.getPwdForWorksheet(worksheet));
        }
      }
      setOpen(true);
    } else {
      void doSaveSheet(tab, tab.title);
    }
  });

  const close = () => setOpen(false);

  return (
    <Dialog open={open} onOpenChange={(next) => !next && close()}>
      <DialogContent className="w-[32rem] max-w-[calc(100vw-8rem)] 2xl:max-w-[calc(100vw-8rem)] p-4">
        <DialogTitle>{t("sql-editor.save-sheet")}</DialogTitle>
        <div className="flex flex-col gap-y-3">
          <div className="flex flex-col gap-y-1">
            <p>
              {t("common.title")}
              <span className="text-error ml-0.5">*</span>
            </p>
            <Input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder={t("sql-editor.save-sheet-input-placeholder")}
              maxLength={200}
            />
          </div>
          <FolderForm folder={folder} onFolderChange={setFolder} />
          <div className="flex justify-end gap-x-2 mt-4">
            <Button variant="outline" onClick={close}>
              {t("common.close")}
            </Button>
            <Button disabled={!title} onClick={() => void doSaveSheet()}>
              {t("common.save")}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/views/sql-editor/EditorCommon/SaveSheetModal.vue
<template>
  <BBModal v-if="showModal" :title="$t('sql-editor.save-sheet')" @close="close">
    <div
      class="save-sheet-modal flex flex-col gap-y-3 w-lg max-w-[calc(100vw-8rem)]"
    >
      <div class="flex flex-col gap-y-1">
        <p>
          {{ $t("common.title") }}
          <RequiredStar />
        </p>
        <NInput
          ref="sheetTitleInputRef"
          v-model:value="pendingEdit.title"
          :placeholder="$t('sql-editor.save-sheet-input-placeholder')"
          :maxlength="200"
        />
      </div>
      <FolderForm ref="folderFormRef" :folder="pendingEdit.folder" />
      <div class="flex justify-end gap-x-2 mt-4">
        <NButton @click="close">{{ $t("common.close") }}</NButton>
        <NButton
          :disabled="!pendingEdit.title"
          type="primary"
          @click="doSaveSheet"
        >
          {{ $t("common.save") }}
        </NButton>
      </div>
    </div>
  </BBModal>
</template>

<script lang="tsx" setup>
import { NButton, NInput } from "naive-ui";
import { ref } from "vue";
import { BBModal } from "@/bbkit";
import RequiredStar from "@/components/RequiredStar.vue";
import { useEmitteryEventListener } from "@/composables/useEmitteryEventListener";
import { useWorkSheetStore } from "@/store";
import type { SQLEditorTab } from "@/types";
import { UNKNOWN_ID } from "@/types";
import { extractWorksheetUID } from "@/utils";
import FolderForm from "@/views/sql-editor/AsidePanel/WorksheetPane/SheetList/FolderForm.vue";
import { useSheetContextByView } from "@/views/sql-editor/Sheet";
import { useSQLEditorContext } from "../context";

const worksheetV1Store = useWorkSheetStore();
const editorContext = useSQLEditorContext();
const { abortAutoSave } = editorContext;
const { getPwdForWorksheet } = useSheetContextByView("my");
const folderFormRef = ref<InstanceType<typeof FolderForm>>();

const pendingEdit = ref<{
  title: string;
  folder: string;
  rawTab?: SQLEditorTab;
}>({
  title: "",
  folder: "",
});
const showModal = ref(false);

const doSaveSheet = async () => {
  if (!pendingEdit.value.rawTab) {
    return close();
  }
  if (pendingEdit.value.title === "") {
    return;
  }

  // Abort any in-progress auto-save - manual save takes priority
  abortAutoSave();

  const {
    worksheet,
    connection,
    statement,
    id: tabId,
  } = pendingEdit.value.rawTab;
  const folders = folderFormRef.value?.folders ?? [];

  const sheetId = Number(extractWorksheetUID(worksheet ?? ""));
  if (sheetId !== UNKNOWN_ID) {
    await editorContext.maybeUpdateWorksheet({
      tabId,
      worksheet,
      title: pendingEdit.value.title,
      database: connection.database,
      statement,
      folders,
    });
  } else {
    await editorContext.createWorksheet({
      tabId,
      title: pendingEdit.value.title,
      statement: pendingEdit.value.rawTab.statement,
      database: connection.database,
      folders,
    });
  }

  showModal.value = false;
};

const needShowModal = (tab: SQLEditorTab) => {
  // If the sheet is saved, we don't need to show the name popup.
  return !tab.worksheet;
};

const close = () => {
  showModal.value = false;
};

useEmitteryEventListener(
  editorContext.events,
  "save-sheet",
  ({ tab, editTitle }) => {
    pendingEdit.value = {
      title: tab.title,
      folder: "",
      rawTab: tab,
    };

    if (needShowModal(tab) || editTitle) {
      const worksheet = worksheetV1Store.getWorksheetByName(tab.worksheet);
      if (worksheet) {
        pendingEdit.value.folder = getPwdForWorksheet(worksheet);
      }
      showModal.value = true;
      return;
    }
    doSaveSheet();
  }
);
</script>
