// frontend/src/modules/sql-editor/components/SaveSheetModal.tsx
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useSQLEditorEvent } from "@/hooks/useSQLEditorEvent";
import { useSheetContextByView } from "@/modules/sql-editor/model/Sheet";
import { useSQLEditorStore } from "@/modules/sql-editor/store";
import { useAppStore } from "@/stores/app";
import type { SQLEditorTab } from "@/types";
import { UNKNOWN_ID } from "@/types";
import { extractWorksheetID } from "@/utils";
import { FolderForm } from "./FolderForm";

export function SaveSheetModal() {
  const { t } = useTranslation();
  const abortAutoSave = useSQLEditorStore((s) => s.abortAutoSave);
  const maybeUpdateWorksheet = useSQLEditorStore((s) => s.maybeUpdateWorksheet);
  const createWorksheet = useSQLEditorStore((s) => s.createWorksheet);
  const sheetContext = useSheetContextByView("my");

  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [folder, setFolder] = useState("");
  const [rawTab, setRawTab] = useState<SQLEditorTab | undefined>(undefined);

  // A manual save opens the modal when the worksheet has never been saved
  // OR is still untitled, so the user can give it a title rather than
  // silently persisting an "Untitled" worksheet. Auto-save never reaches
  // here (it calls `maybeUpdateWorksheet` directly).
  const needShowModal = (tab: SQLEditorTab) =>
    !tab.worksheet || !tab.title.trim();

  const doSaveSheet = async (
    tab?: SQLEditorTab,
    tabTitle?: string,
    tabFolder?: string
  ) => {
    const effectiveTab = tab ?? rawTab;
    if (!effectiveTab) {
      setOpen(false);
      return;
    }
    // Silent path passes title + folder explicitly because React state setters
    // are async — reading state here would observe the prior modal's values.
    // Empty titles are allowed; surfaces render an "Untitled" placeholder.
    const effectiveTitle = tabTitle ?? title;
    const effectiveFolder = tabFolder ?? folder;

    abortAutoSave();

    const { worksheet, connection, statement, id: tabId } = effectiveTab;
    const folders = sheetContext.getFoldersForWorksheet(effectiveFolder);

    const sheetId = extractWorksheetID(worksheet ?? "");
    if (sheetId !== String(UNKNOWN_ID)) {
      await maybeUpdateWorksheet({
        tabId,
        worksheet,
        title: effectiveTitle,
        database: connection.database,
        statement,
        folders,
      });
    } else {
      await createWorksheet({
        tabId,
        title: effectiveTitle,
        statement,
        database: connection.database,
        folders,
      });
    }

    setOpen(false);
  };

  useSQLEditorEvent("save-sheet", ({ tab, editTitle }) => {
    setTitle(tab.title);
    setRawTab(tab);

    // Compute the folder synchronously: for an already-saved worksheet, use
    // its current pwd; otherwise reset. We then both reflect this in state
    // (for the modal-open path) AND pass it explicitly into doSaveSheet
    // (for the silent path) — bypassing React's async setState batching.
    let nextFolder = "";
    if (tab.worksheet) {
      const worksheet = useAppStore
        .getState()
        .getWorksheetByName(tab.worksheet);
      if (worksheet) {
        nextFolder = sheetContext.getPwdForWorksheet(worksheet);
      }
    }
    setFolder(nextFolder);

    if (needShowModal(tab) || editTitle) {
      setOpen(true);
    } else {
      void doSaveSheet(tab, tab.title, nextFolder);
    }
  });

  const close = () => setOpen(false);

  return (
    <Dialog open={open} onOpenChange={(next) => !next && close()}>
      <DialogContent className="w-[32rem] max-w-[calc(100vw-8rem)] 2xl:max-w-[calc(100vw-8rem)] p-4">
        <DialogTitle>{t("sql-editor.save-sheet")}</DialogTitle>
        <div className="flex flex-col gap-y-3">
          <div className="flex flex-col gap-y-1">
            <p>{t("common.title")}</p>
            <Input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder={t("common.untitled")}
              maxLength={200}
            />
          </div>
          <FolderForm folder={folder} onFolderChange={setFolder} />
          <div className="flex justify-end gap-x-2 mt-4">
            <Button appearance="outline" onClick={close}>
              {t("common.close")}
            </Button>
            <Button onClick={() => void doSaveSheet()}>
              {t("common.save")}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/views/sql-editor/EditorCommon/SaveSheetModal.vue
<template>
  <BBModal v-if="showModal" :title="$t('sql-editor.save-sheet')" @close="close">
    <div
      class="save-sheet-modal flex flex-col gap-y-3 w-lg max-w-[calc(100vw-8rem)]"
    >
      <div class="flex flex-col gap-y-1">
        <p>
          {{ $t("common.title") }}
          <RequiredStar />
        </p>
        <NInput
          ref="sheetTitleInputRef"
          v-model:value="pendingEdit.title"
          :placeholder="$t('sql-editor.save-sheet-input-placeholder')"
          :maxlength="200"
        />
      </div>
      <FolderForm ref="folderFormRef" :folder="pendingEdit.folder" />
      <div class="flex justify-end gap-x-2 mt-4">
        <NButton @click="close">{{ $t("common.close") }}</NButton>
        <NButton
          :disabled="!pendingEdit.title"
          type="primary"
          @click="doSaveSheet"
        >
          {{ $t("common.save") }}
        </NButton>
      </div>
    </div>
  </BBModal>
</template>

<script lang="tsx" setup>
import { NButton, NInput } from "naive-ui";
import { ref } from "vue";
import { BBModal } from "@/bbkit";
import RequiredStar from "@/components/RequiredStar.vue";
import { useEmitteryEventListener } from "@/composables/useEmitteryEventListener";
import { useWorkSheetStore } from "@/store";
import type { SQLEditorTab } from "@/types";
import { UNKNOWN_ID } from "@/types";
import { extractWorksheetUID } from "@/utils";
import FolderForm from "@/views/sql-editor/AsidePanel/WorksheetPane/SheetList/FolderForm.vue";
import { useSheetContextByView } from "@/views/sql-editor/Sheet";
import { useSQLEditorContext } from "../context";

const worksheetV1Store = useWorkSheetStore();
const editorContext = useSQLEditorContext();
const { abortAutoSave } = editorContext;
const { getPwdForWorksheet } = useSheetContextByView("my");
const folderFormRef = ref<InstanceType<typeof FolderForm>>();

const pendingEdit = ref<{
  title: string;
  folder: string;
  rawTab?: SQLEditorTab;
}>({
  title: "",
  folder: "",
});
const showModal = ref(false);

const doSaveSheet = async () => {
  if (!pendingEdit.value.rawTab) {
    return close();
  }
  if (pendingEdit.value.title === "") {
    return;
  }

  // Abort any in-progress auto-save - manual save takes priority
  abortAutoSave();

  const {
    worksheet,
    connection,
    statement,
    id: tabId,
  } = pendingEdit.value.rawTab;
  const folders = folderFormRef.value?.folders ?? [];

  const sheetId = Number(extractWorksheetUID(worksheet ?? ""));
  if (sheetId !== UNKNOWN_ID) {
    await editorContext.maybeUpdateWorksheet({
      tabId,
      worksheet,
      title: pendingEdit.value.title,
      database: connection.database,
      statement,
      folders,
    });
  } else {
    await editorContext.createWorksheet({
      tabId,
      title: pendingEdit.value.title,
      statement: pendingEdit.value.rawTab.statement,
      database: connection.database,
      folders,
    });
  }

  showModal.value = false;
};

const needShowModal = (tab: SQLEditorTab) => {
  // If the sheet is saved, we don't need to show the name popup.
  return !tab.worksheet;
};

const close = () => {
  showModal.value = false;
};

useEmitteryEventListener(
  editorContext.events,
  "save-sheet",
  ({ tab, editTitle }) => {
    pendingEdit.value = {
      title: tab.title,
      folder: "",
      rawTab: tab,
    };

    if (needShowModal(tab) || editTitle) {
      const worksheet = worksheetV1Store.getWorksheetByName(tab.worksheet);
      if (worksheet) {
        pendingEdit.value.folder = getPwdForWorksheet(worksheet);
      }
      showModal.value = true;
      return;
    }
    doSaveSheet();
  }
);
</script>
