// frontend/src/plugins/ai/react/HistoryPanel/ConversationRenameDialog.tsx
import { head } from "lodash-es";
import { Loader2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/react/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogTitle,
} from "@/react/components/ui/dialog";
import { Input } from "@/react/components/ui/input";
import { useConversationStore } from "../../store";
import type { Conversation } from "../../types";

type Props = {
  readonly conversation: Conversation;
  readonly onCancel: () => void;
  readonly onUpdated: () => void;
};

/**
 * React port of `plugins/ai/components/HistoryPanel/ConversationRenameDialog.vue`.
 *
 * Single-field rename modal. The name initializes to:
 *   1. The current conversation name, or
 *   2. The first message's content (often the user's seed prompt), or
 *   3. The localized "Untitled conversation" placeholder.
 *
 * Mirrors the Vue version exactly. Auto-focuses the input on mount via
 * a ref + rAF so the input is interactive immediately when the dialog
 * portal mounts.
 */
export function ConversationRenameDialog({
  conversation,
  onCancel,
  onUpdated,
}: Props) {
  const { t } = useTranslation();
  const store = useConversationStore();

  const [name, setName] = useState(
    conversation.name ||
      head(conversation.messageList)?.content ||
      t("plugin.ai.conversation.untitled")
  );
  const [loading, setLoading] = useState(false);

  const inputRef = useRef<HTMLInputElement | null>(null);
  useEffect(() => {
    const raf = requestAnimationFrame(() => {
      inputRef.current?.focus();
    });
    return () => cancelAnimationFrame(raf);
  }, []);

  const handleRename = async () => {
    setLoading(true);
    conversation.name = name;
    await store.updateConversation(conversation);
    onUpdated();
  };

  return (
    <Dialog open onOpenChange={(open) => !open && onCancel()}>
      <DialogContent className="w-[18rem] p-6">
        <DialogTitle>{t("plugin.ai.conversation.rename")}</DialogTitle>
        <div className="relative flex flex-col items-start gap-y-2 mt-3">
          <div className="text-sm text-control">{t("common.name")}</div>
          <div className="w-full">
            <Input
              ref={inputRef}
              value={name}
              onChange={(e) => setName(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  e.preventDefault();
                  void handleRename();
                }
              }}
              className="w-full"
            />
          </div>
          <div className="w-full flex items-center justify-end gap-x-2 mt-4 pt-2 border-t">
            <Button variant="outline" onClick={onCancel}>
              {t("common.cancel")}
            </Button>
            <Button onClick={() => void handleRename()} disabled={loading}>
              {t("common.update")}
            </Button>
          </div>
          {loading && (
            <div className="absolute inset-0 bg-background/50 flex items-center justify-center rounded-sm">
              <Loader2 className="size-5 animate-spin" />
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/plugins/ai/components/HistoryPanel/ConversationRenameDialog.vue
<template>
  <BBModal
    :title="$t('plugin.ai.conversation.rename')"
    @close="$emit('cancel')"
  >
    <div class="w-[18rem] flex flex-col items-start gap-y-2">
      <div class="textlabel">{{ $t("common.name") }}</div>
      <div class="w-full">
        <NInput
          v-model:value="state.name"
          class="bb-ai-conversation-rename-input w-full"
          @keypress.enter="handleRename"
        />
      </div>
      <div
        class="w-full flex items-center justify-end gap-x-2 mt-4 pt-2 border-t"
      >
        <NButton @click="$emit('cancel')">
          {{ $t("common.cancel") }}
        </NButton>
        <NButton type="primary" @click="handleRename">
          {{ $t("common.update") }}
        </NButton>
      </div>
      <div
        v-if="state.loading"
        class="absolute inset-0 bg-white/50 flex flex-col items-center justify-center rounded-lg"
      >
        <BBSpin />
      </div>
    </div>
  </BBModal>
</template>

<script lang="ts" setup>
import { head } from "lodash-es";
import { NButton, NInput } from "naive-ui";
import { onMounted, reactive } from "vue";
import { useI18n } from "vue-i18n";
import { BBModal } from "@/bbkit";
import { useConversationStore } from "../../store";
import type { Conversation } from "../../types";

type LocalState = {
  name: string;
  loading: boolean;
};

const props = defineProps<{
  conversation: Conversation;
}>();

const emit = defineEmits<{
  (event: "cancel"): void;
  (event: "updated"): void;
}>();

const { t } = useI18n();

const state = reactive<LocalState>({
  name:
    props.conversation.name ||
    head(props.conversation.messageList)?.content ||
    t("plugin.ai.conversation.untitled"),
  loading: false,
});
const store = useConversationStore();

const handleRename = async () => {
  const { conversation } = props;
  const { name } = state;
  conversation.name = name;
  state.loading = true;
  await store.updateConversation(conversation);
  emit("updated");
};

onMounted(() => {
  requestAnimationFrame(() => {
    const input = document.querySelector(
      ".bb-ai-conversation-rename-input input[type=text]"
    ) as HTMLInputElement;
    if (input) {
      input.focus();
    }
  });
});
</script>
