// frontend/src/components/FeatureGuard/FeatureModal.vue
<template>
  <BBModal v-if="open && feature" :title="title" @close="$emit('cancel')">
    <div class="min-w-0 md:min-w-[400px] max-w-4xl mb-2">
      <div class="flex items-start gap-x-2 mt-3">
        <div class="flex items-center">
          <heroicons-solid:lock-closed
            v-if="instanceMissingLicense"
            class="text-accent w-6 h-6"
          />
          <SparklesIcon v-else class="h-6 w-6 text-accent" />
        </div>
        <h3
          id="modal-headline"
          class="flex self-center text-lg leading-6 font-medium text-gray-900"
        >
          {{ $t(`dynamic.subscription.features.${featureKey}.title`) }}
        </h3>
      </div>
      <div class="mt-4">
        <p class="whitespace-pre-wrap">
          {{ $t(`dynamic.subscription.features.${featureKey}.desc`) }}
        </p>
      </div>
      <div class="mt-3">
        <p class="whitespace-pre-wrap">
          <i18n-t
            v-if="instanceMissingLicense"
            keypath="subscription.instance-assignment.missing-license-attention"
          />
          <i18n-t
            v-else-if="requiredPlan !== PlanType.FREE"
            keypath="subscription.required-plan-with-trial"
          >
            <template #requiredPlan>
              <span class="font-bold text-accent">
                {{
                  $t(
                    `subscription.plan.${PlanType[requiredPlan].toLowerCase()}.title`
                  )
                }}
              </span>
            </template>
            <template v-if="!hasPermission" #startTrial>
              {{ $t("subscription.contact-to-upgrade") }}
            </template>
            <template v-else #startTrial>
              {{
                $t("subscription.trial-for-days", {
                  days: subscriptionStore.trialingDays,
                })
              }}
            </template>
          </i18n-t>
          <i18n-t v-else keypath="subscription.trial-for-days">
            <template #days>
              {{ subscriptionStore.trialingDays }}
            </template>
          </i18n-t>
        </p>
      </div>
      <div class="mt-7 flex justify-end gap-x-2">
        <NButton
          v-if="!hasPermission"
          type="primary"
          @click.prevent="$emit('cancel')"
        >
          {{ $t("common.ok") }}
        </NButton>
        <template v-else-if="subscriptionStore.showTrial">
          <NButton type="primary" @click.prevent="trialSubscription">
            {{
              $t("subscription.request-n-days-trial", {
                days: subscriptionStore.trialingDays,
              })
            }}
          </NButton>
        </template>
        <NButton v-else type="primary" @click.prevent="ok">
          {{
            instanceMissingLicense
              ? $t("subscription.instance-assignment.assign-license")
              : $t("common.learn-more")
          }}
        </NButton>
      </div>
    </div>
  </BBModal>
  <WeChatQRModal
    v-if="state.showQRCodeModal"
    :title="$t('subscription.request-with-qr')"
    @close="state.showQRCodeModal = false"
  />
  <InstanceAssignment
    :show="state.showInstanceAssignmentDrawer"
    @dismiss="state.showInstanceAssignmentDrawer = false"
  />
</template>

<script lang="ts" setup>
import { SparklesIcon } from "lucide-vue-next";
import { NButton } from "naive-ui";
import { computed, reactive } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { BBModal } from "@/bbkit";
import { useLanguage } from "@/composables/useLanguage";
import { useSubscriptionV1Store } from "@/store";
import { ENTERPRISE_INQUIRE_LINK } from "@/types";
import type {
  Instance,
  InstanceResource,
} from "@/types/proto-es/v1/instance_service_pb";
import {
  PlanFeature,
  PlanType,
} from "@/types/proto-es/v1/subscription_service_pb";
import { autoSubscriptionRoute, hasWorkspacePermissionV2 } from "@/utils";
import InstanceAssignment from "../InstanceAssignment.vue";
import WeChatQRModal from "../WeChatQRModal.vue";

interface LocalState {
  showInstanceAssignmentDrawer: boolean;
  showQRCodeModal: boolean;
}

const props = withDefaults(
  defineProps<{
    open: boolean;
    feature?: PlanFeature;
    instance?: Instance | InstanceResource;
  }>(),
  {
    feature: PlanFeature.FEATURE_UNSPECIFIED,
    instance: undefined,
  }
);

const state = reactive<LocalState>({
  showInstanceAssignmentDrawer: false,
  showQRCodeModal: false,
});

const emit = defineEmits(["cancel"]);
const { t } = useI18n();
const router = useRouter();
const { locale } = useLanguage();

const subscriptionStore = useSubscriptionV1Store();
const hasPermission = hasWorkspacePermissionV2("bb.settings.set");

const instanceMissingLicense = computed(() => {
  return subscriptionStore.instanceMissingLicense(
    props.feature,
    props.instance
  );
});

const title = computed(() => {
  if (instanceMissingLicense.value) {
    return t("subscription.instance-assignment.require-license");
  }
  return t("subscription.disabled-feature");
});

const ok = () => {
  if (instanceMissingLicense.value) {
    state.showInstanceAssignmentDrawer = true;
  } else {
    router.push(autoSubscriptionRoute(router));
  }
  emit("cancel");
};

const requiredPlan = computed(() =>
  subscriptionStore.getMinimumRequiredPlan(props.feature)
);

const featureKey = computed(() => {
  return PlanFeature[props.feature].split(".").join("-");
});

const trialSubscription = () => {
  if (locale.value === "zh-CN") {
    state.showQRCodeModal = true;
  } else {
    window.open(ENTERPRISE_INQUIRE_LINK, "_blank");
  }
};
</script>

<style scoped>
@media (min-width: 768px) {
  .md\:min-w-400 {
    min-width: 400px;
  }
}
</style>

// frontend/src/components/ui/feature-modal.tsx
import { Lock, Sparkles, X } from "lucide-react";
import { useTranslation } from "react-i18next";
import { router } from "@/app/router";
import { INSTANCE_ROUTE_DASHBOARD } from "@/app/router/handles";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogTitle,
} from "@/components/ui/dialog";
import { useSubscriptionState } from "@/hooks/useAppState";
import { useAppStore } from "@/stores/app";
import { ENTERPRISE_INQUIRE_LINK } from "@/types";
import type {
  Instance,
  InstanceResource,
} from "@/types/proto-es/v1/instance_service_pb";
import {
  PlanFeature,
  PlanType,
} from "@/types/proto-es/v1/subscription_service_pb";
import { autoSubscriptionRoute, hasWorkspacePermissionV2 } from "@/utils";

type Props = {
  readonly open: boolean;
  readonly feature: PlanFeature | undefined;
  readonly instance?: Instance | InstanceResource;
  readonly onOpenChange: (open: boolean) => void;
};

const planLabel: Record<number, string> = {
  [PlanType.FREE]: "free",
  [PlanType.TEAM]: "team",
  [PlanType.ENTERPRISE]: "enterprise",
};

/**
 * Subscription paywall dialog shown when the current plan doesn't include
 * a requested feature. Three copy variants:
 *  - Instance missing license → lock icon, "assign license" CTA.
 *  - Required plan above FREE → plan name + trial or contact-admin line.
 *  - Required plan equals FREE → trial-for-days line.
 */
export function FeatureModal({ open, feature, instance, onOpenChange }: Props) {
  const { t } = useTranslation();
  const { showTrial, trialingDays } = useSubscriptionState();
  const hasPermission = hasWorkspacePermissionV2("bb.settings.set");

  const resolvedFeature = feature ?? PlanFeature.FEATURE_UNSPECIFIED;
  const instanceMissingLicense = useAppStore((state) =>
    state.instanceMissingLicense(resolvedFeature, instance)
  );
  const requiredPlan = useAppStore((state) =>
    state.getMinimumRequiredPlan(resolvedFeature)
  );

  if (!feature) {
    return null;
  }

  const featureKey = PlanFeature[feature].split(".").join("-");
  const title = instanceMissingLicense
    ? t("subscription.instance-assignment.require-license")
    : t("subscription.disabled-feature");

  const close = () => onOpenChange(false);

  const confirmLabel = instanceMissingLicense
    ? t("subscription.instance-assignment.assign-license")
    : t("common.learn-more");

  const handleConfirm = () => {
    if (instanceMissingLicense) {
      void router.push({
        name: INSTANCE_ROUTE_DASHBOARD,
        query: {
          assignLicense: "1",
          instances: instance?.name,
        },
      });
    } else {
      void router.push(autoSubscriptionRoute());
    }
    close();
  };

  const requiredPlanLabel = t(
    `subscription.plan.${planLabel[requiredPlan] ?? "enterprise"}.title`
  );
  const startTrialLabel = hasPermission
    ? t("subscription.trial-for-days", { days: trialingDays })
    : t("subscription.contact-to-upgrade");

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <div>
          <div className="flex items-center justify-between border-b pb-2 mb-4">
            <DialogTitle className="text-base font-medium">{title}</DialogTitle>
            {/* Vue's BBModal had a built-in X close affordance; the React
                Dialog primitive does not, so render one explicitly so
                users can dismiss the paywall regardless of which CTA path
                renders below. */}
            <DialogClose
              aria-label={t("common.close")}
              className="rounded-xs p-1 text-control hover:bg-control-bg focus:outline-hidden focus-visible:ring-2 focus-visible:ring-accent cursor-pointer"
            >
              <X className="size-4" />
            </DialogClose>
          </div>
          <div className="flex items-start gap-x-2">
            <div className="flex items-center">
              {instanceMissingLicense ? (
                <Lock className="size-6 text-accent" />
              ) : (
                <Sparkles className="size-6 text-accent" />
              )}
            </div>
            <h3 className="flex self-center text-lg leading-6 font-medium">
              {t(`dynamic.subscription.features.${featureKey}.title`)}
            </h3>
          </div>

          <div className="mt-4">
            <p className="whitespace-pre-wrap">
              {t(`dynamic.subscription.features.${featureKey}.desc`)}
            </p>
          </div>

          <div className="mt-3">
            <p className="whitespace-pre-wrap">
              {instanceMissingLicense
                ? t(
                    "subscription.instance-assignment.missing-license-attention"
                  )
                : requiredPlan !== PlanType.FREE
                  ? t("subscription.required-plan-with-trial", {
                      requiredPlan: requiredPlanLabel,
                      startTrial: startTrialLabel,
                    })
                  : t("subscription.trial-for-days", {
                      days: trialingDays,
                    })}
            </p>
          </div>

          <div className="mt-7 flex justify-end gap-x-2">
            {!hasPermission ? (
              <Button variant="default" onClick={close}>
                {t("common.ok")}
              </Button>
            ) : showTrial && !instanceMissingLicense ? (
              <Button
                variant="default"
                onClick={() => {
                  window.open(ENTERPRISE_INQUIRE_LINK, "_blank");
                  // Vue's BBModal default-closes after a CTA click; mirror
                  // that so the paywall doesn't linger after the inquiry
                  // tab opens.
                  close();
                }}
              >
                {t("subscription.request-n-days-trial", {
                  days: trialingDays,
                })}
              </Button>
            ) : (
              <Button variant="default" onClick={handleConfirm}>
                {confirmLabel}
              </Button>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
