// frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTablesPanel.vue
<template>
  <div
    v-if="metadata?.schema"
    class="px-2 py-2 gap-y-2 h-full overflow-hidden flex flex-col"
  >
    <div
      v-show="!metadata.externalTable"
      class="w-full flex flex-row gap-x-2 justify-between items-center"
    >
      <div class="flex items-center justify-start">
        <SchemaSelectToolbar />
      </div>
      <div class="flex items-center justify-end">
        <DatabaseChooser />
      </div>
    </div>
    <ExternalTablesTable
      v-show="!metadata.externalTable"
      :db="database"
      :database="metadata.database"
      :schema="metadata.schema"
      :external-tables="metadata.schema.externalTables"
      @click="select"
    />

    <template v-if="metadata.externalTable">
      <div
        class="w-full h-[28px] flex flex-row gap-x-2 justify-start items-center"
      >
        <NButton text @click="deselect">
          <ChevronLeftIcon class="w-5 h-5" />
          <div class="flex items-center gap-1">
            <TableIcon class="w-4 h-4" />
            <span>{{ metadata.externalTable.name }}</span>
          </div>
        </NButton>
      </div>
      <ExternalTableColumnsTable
        :db="database"
        :database="metadata.database"
        :schema="metadata.schema"
        :external-table="metadata.externalTable"
      />
    </template>
  </div>
</template>

<script setup lang="ts">
import { ChevronLeftIcon } from "lucide-vue-next";
import { NButton } from "naive-ui";
import { computed } from "vue";
import { TableIcon } from "@/components/Icon";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
} from "@/store";
import {
  DatabaseMetadata,
  DatabaseMetadataView,
  SchemaMetadata,
  ExternalTableMetadata,
} from "@/types/proto/v1/database_service";
import DatabaseChooser from "@/views/sql-editor/EditorCommon/DatabaseChooser.vue";
import { useEditorPanelContext } from "../../context";
import { SchemaSelectToolbar } from "../common";
import ExternalTableColumnsTable from "./ExternalTableColumnsTable.vue";
import ExternalTablesTable from "./ExternalTablesTable.vue";

const { database } = useConnectionOfCurrentSQLEditorTab();
const { viewState, updateViewState } = useEditorPanelContext();
const databaseMetadata = computed(() => {
  return useDBSchemaV1Store().getDatabaseMetadata(
    database.value.name,
    DatabaseMetadataView.DATABASE_METADATA_VIEW_FULL
  );
});

const metadata = computed(() => {
  const database = databaseMetadata.value;
  const schema = database.schemas.find(
    (s) => s.name === viewState.value?.schema
  );
  const externalTable = schema?.externalTables.find(
    (t) => t.name === viewState.value?.detail?.externalTable
  );
  return { database, schema, externalTable };
});

const select = (selected: {
  database: DatabaseMetadata;
  schema: SchemaMetadata;
  externalTable: ExternalTableMetadata;
}) => {
  updateViewState({
    detail: { externalTable: selected.externalTable.name },
  });
};

const deselect = () => {
  updateViewState({
    detail: {},
  });
};
</script>

// frontend/src/modules/sql-editor/components/Panels/ExternalTablesPanel/ExternalTablesPanel.tsx
import { ChevronLeft, Table as TableIcon } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { useAppDatabaseMetadata } from "@/hooks/useAppDatabaseMetadata";
import { useConnectionOfCurrentSQLEditorTab } from "@/modules/sql-editor/hooks/useSQLEditorState";
import { PanelSearchBox } from "../common/PanelSearchBox";
import { ColumnsTable } from "../common/tables/ColumnsTable";
import { useViewStateNav } from "../common/useViewStateNav";
import { ExternalTablesTable } from "./ExternalTablesTable";

/**
 * Single Columns detail tab — no viewer needed.
 */
export function ExternalTablesPanel() {
  const { database } = useConnectionOfCurrentSQLEditorTab();
  const databaseName = database.name;
  const db = database;
  const databaseMetadata = useAppDatabaseMetadata(databaseName ?? "", {
    autoFetch: false,
  });

  const {
    schema: schemaName,
    detail,
    setDetail,
    clearDetail,
  } = useViewStateNav();

  const [tableKeyword, setTableKeyword] = useState("");
  const [columnKeyword, setColumnKeyword] = useState("");

  const schema = databaseMetadata.schemas.find((s) => s.name === schemaName);
  const externalTable = schema?.externalTables.find(
    (t) => t.name === detail?.externalTable
  );

  if (!db || !schema) return null;

  return (
    <div className="px-2 py-2 gap-y-2 h-full overflow-hidden flex flex-col">
      {!externalTable ? (
        <>
          <div className="w-full flex flex-row gap-x-2 justify-end items-center">
            <PanelSearchBox value={tableKeyword} onChange={setTableKeyword} />
          </div>
          <div className="flex-1 min-h-0">
            <ExternalTablesTable
              database={databaseMetadata}
              schema={schema}
              externalTables={schema.externalTables}
              keyword={tableKeyword}
              onSelect={({ externalTable: target }) =>
                setDetail({ externalTable: target.name })
              }
            />
          </div>
        </>
      ) : (
        <>
          <div className="w-full h-9 flex flex-row gap-x-2 justify-between items-center">
            <Button
              appearance="secondary"
              size="md"
              className="px-1"
              onClick={() => clearDetail()}
            >
              <ChevronLeft className="size-5" />
              <TableIcon className="size-4 text-control" />
              <span className="truncate">{externalTable.name}</span>
            </Button>
            <PanelSearchBox value={columnKeyword} onChange={setColumnKeyword} />
          </div>
          <div className="flex-1 min-h-0">
            <ColumnsTable
              db={db}
              database={databaseMetadata}
              schema={schema}
              columns={externalTable.columns}
              flavor="external-table"
              keyword={columnKeyword}
            />
          </div>
        </>
      )}
    </div>
  );
}
