// frontend/src/modules/sql-editor/components/ResultView/BinaryFormatButton.tsx
import { CodeIcon } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { cn } from "@/lib/utils";
import type { BinaryFormat } from "./binary-format";

interface BinaryFormatButtonProps {
  format: BinaryFormat | undefined;
  onFormatChange: (format: BinaryFormat) => void;
}

export function BinaryFormatButton({
  format,
  onFormatChange,
}: BinaryFormatButtonProps) {
  const { t } = useTranslation();
  const current: BinaryFormat = format ?? "DEFAULT";
  const hasOverride = current !== "DEFAULT";

  const options: { value: BinaryFormat; label: string }[] = [
    { value: "DEFAULT", label: t("sql-editor.format-default") },
    { value: "BINARY", label: t("sql-editor.binary-format") },
    { value: "HEX", label: t("sql-editor.hex-format") },
    { value: "TEXT", label: t("sql-editor.text-format") },
    { value: "BOOLEAN", label: t("sql-editor.boolean-format") },
  ];

  return (
    <Popover>
      <PopoverTrigger
        render={
          <Button
            appearance={hasOverride ? "solid" : "outline"}
            size="xs"
            className={cn("ml-1 w-6 rounded-full p-0")}
            onClick={(e) => e.stopPropagation()}
          />
        }
      >
        <CodeIcon className="size-3" />
      </PopoverTrigger>
      <PopoverContent align="start" className="w-52 p-2">
        <div className="text-xs font-semibold mb-2">
          {t("sql-editor.column-display-format")}
        </div>
        <RadioGroup
          value={current}
          onValueChange={(next) => onFormatChange(next as BinaryFormat)}
          className="flex flex-col gap-2"
        >
          {options.map((option) => (
            <RadioGroupItem key={option.value} value={option.value}>
              {option.label}
            </RadioGroupItem>
          ))}
        </RadioGroup>
      </PopoverContent>
    </Popover>
  );
}

// frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/BinaryFormatButton.vue
<!-- Button to change binary data format for an entire column -->
<template>
  <div>
    <NPopover trigger="click" placement="bottom">
      <template #trigger>
        <NButton
          size="tiny"
          circle
          class="ml-1 dark:bg-dark-bg!"
          @click.stop
          :type="hasColumnOverride ? 'primary' : 'default'"
          :secondary="hasColumnOverride"
        >
          <template #icon>
            <CodeIcon class="w-3 h-3" />
          </template>
        </NButton>
      </template>
      <template #default>
        <div class="p-2 w-52">
          <div class="text-xs font-semibold mb-2">
            {{ $t("sql-editor.column-display-format") }}
          </div>
          <NRadioGroup
            :value="currentColumnFormat"
            class="flex flex-col gap-2"
            @update:value="emit('update:format', $event as BinaryFormat)"
          >
            <NRadio value="DEFAULT">
              {{ $t("sql-editor.format-default") }}
            </NRadio>
            <NRadio value="BINARY">
              {{ $t("sql-editor.binary-format") }}
            </NRadio>
            <NRadio value="HEX">
              {{ $t("sql-editor.hex-format") }}
            </NRadio>
            <NRadio value="TEXT">
              {{ $t("sql-editor.text-format") }}
            </NRadio>
            <NRadio value="BOOLEAN">
              {{ $t("sql-editor.boolean-format") }}
            </NRadio>
          </NRadioGroup>
        </div>
      </template>
    </NPopover>
  </div>
</template>

<script setup lang="ts">
import { CodeIcon } from "lucide-vue-next";
import { NButton, NPopover, NRadio, NRadioGroup } from "naive-ui";
import { computed } from "vue";
import { type BinaryFormat } from "../binary-format-store";

const emit = defineEmits<{
  (e: "update:format", format: BinaryFormat): void;
}>();

const props = defineProps<{
  format: BinaryFormat | undefined;
}>();

const currentColumnFormat = computed(() => {
  return props.format || "DEFAULT";
});

const hasColumnOverride = computed(() => {
  return currentColumnFormat.value !== "DEFAULT";
});
</script>
