// frontend/src/react/components/sql-editor/SchemaPane/TreeNode/DatabaseNode.tsx
import { EngineIcon } from "@/react/components/EngineIcon";
import { useDatabaseV1Store } from "@/store";
import { extractDatabaseResourceName, getInstanceResource } from "@/utils";
import type { TreeNode } from "../schemaTree";
import { CommonNode } from "./CommonNode";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

/**
 * Replaces `TreeNode/DatabaseNode.vue`. The schema tree's root node:
 * engine icon + database display name (highlight-aware).
 */
export function DatabaseNode({ node, keyword }: Props) {
  const databaseStore = useDatabaseV1Store();
  const target = (node as TreeNode<"database">).meta.target;

  const database = databaseStore.getDatabaseByName(target.database);

  const databaseName = extractDatabaseResourceName(database.name).databaseName;
  const instance = getInstanceResource(database);

  return (
    <CommonNode
      text={databaseName}
      keyword={keyword}
      highlight={true}
      icon={<EngineIcon engine={instance.engine} className="size-4" />}
    />
  );
}

// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DatabaseNode.vue
<template>
  <CommonNode
    :text="databaseName"
    :keyword="keyword"
    :highlight="true"
  >
    <template #icon>
      <InstanceV1EngineIcon :instance="instanceResource" />
    </template>
  </CommonNode>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { InstanceV1EngineIcon } from "@/components/v2";
import { useDatabaseV1Store } from "@/store";
import { extractDatabaseResourceName, getInstanceResource } from "@/utils";
import type { TreeNode } from "../tree";
import CommonNode from "./CommonNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const databaseStore = useDatabaseV1Store();

const database = computed(() =>
  databaseStore.getDatabaseByName(
    (props.node as TreeNode<"database">).meta.target.database
  )
);

const databaseName = computed(
  () => extractDatabaseResourceName(database.value.name).databaseName
);

const instanceResource = computed(() => getInstanceResource(database.value));
</script>
