// frontend/src/modules/sql-editor/components/SchemaPane/TreeNode/ExternalTableNode.tsx
import type { TreeNode } from "../schemaTree";
import { CommonNode } from "./CommonNode";
import { ExternalTableIcon } from "./icons";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

export function ExternalTableNode({ node, keyword }: Props) {
  const target = (node as TreeNode<"external-table">).meta.target;
  return (
    <CommonNode
      text={target.externalTable}
      keyword={keyword}
      highlight={true}
      icon={<ExternalTableIcon />}
    />
  );
}

// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ExternalTableNode.vue
<template>
  <CommonNode :text="target.externalTable" :keyword="keyword" :highlight="true">
    <template #icon>
      <ExternalTableIcon class="w-4 h-4" />
    </template>
  </CommonNode>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { ExternalTableIcon } from "@/components/Icon";
import type { TreeNode } from "../tree";
import CommonNode from "./CommonNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const target = computed(
  () => (props.node as TreeNode<"external-table">).meta.target
);
</script>
