// frontend/src/modules/sql-editor/components/SchemaPane/TreeNode/SchemaNode.tsx
import { Box } from "lucide-react";
import { useTranslation } from "react-i18next";
import type { TreeNode } from "../schemaTree";
import { CommonNode } from "./CommonNode";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

/**
 * Schema namespace node — falls back to the i18n "default" label when the
 * schema name is empty.
 */
export function SchemaNode({ node, keyword }: Props) {
  const { t } = useTranslation();
  const target = (node as TreeNode<"schema">).meta.target;

  return (
    <CommonNode
      text={target.schema}
      keyword={keyword}
      highlight={true}
      icon={<Box className="size-4" />}
      fallbackText={<>{t("db.schema.default")}</>}
    />
  );
}

// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SchemaNode.vue
<template>
  <CommonNode :text="target.schema.name" :keyword="keyword" :highlight="true">
    <template #icon>
      <SchemaIcon class="w-4 h-4" />
    </template>
  </CommonNode>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { SchemaIcon } from "@/components/Icon";
import type { TreeNode } from "../common";
import CommonNode from "./CommonNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const target = computed(() => (props.node as TreeNode<"schema">).meta.target);
</script>
