// frontend/src/react/components/sql-editor/SchemaPane/TreeNode/SequenceNode.tsx
import type { TreeNode } from "../schemaTree";
import { CommonNode } from "./CommonNode";
import { SequenceIcon } from "./icons";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

export function SequenceNode({ node, keyword }: Props) {
  const target = (node as TreeNode<"sequence">).meta.target;
  return (
    <CommonNode
      text={target.sequence}
      keyword={keyword}
      highlight={true}
      indent={0}
      icon={<SequenceIcon />}
    />
  );
}

// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SequenceNode.vue
<template>
  <CommonNode
    :text="target.sequence"
    :keyword="keyword"
    :highlight="true"
    :indent="0"
  >
    <template #icon>
      <SequenceIcon class="w-4 h-4 text-gray-500" />
    </template>
  </CommonNode>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { SequenceIcon } from "@/components/Icon";
import type { TreeNode } from "../tree";
import CommonNode from "./CommonNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const target = computed(() => (props.node as TreeNode<"sequence">).meta.target);
</script>
