// frontend/src/components/FeatureGuard/FeatureBadge.vue
<!-- This component is used when uses don't have available plan to access the feature, or the instance is missing required license. -->
<!-- Normally this should be a blocker to use the feature -->
<template>
  <div
    v-if="instanceMissingLicense"
    class="text-accent cursor-pointer"
    v-bind="$attrs"
    @click="
      (e: MouseEvent) => {
        e.stopPropagation();
        e.preventDefault();
        state.showInstanceAssignmentDrawer = true;
      }
    "
  >
    <NTooltip :show-arrow="true">
      <template #trigger>
        <heroicons-solid:lock-closed class="w-5 h-5" />
      </template>
      <span class="w-56 text-sm">
        {{ $t("subscription.instance-assignment.missing-license-attention") }}
      </span>
    </NTooltip>
  </div>
  <div v-else-if="!hasFeature" class="text-accent" v-bind="$attrs">
    <NTooltip :show-arrow="true">
      <template #trigger>
        <router-link
          v-if="clickable"
          :to="autoSubscriptionRoute($router)"
          exact-active-class=""
        >
          <heroicons-solid:sparkles class="w-5 h-5" />
        </router-link>
        <span v-else>
          <heroicons-solid:sparkles class="w-5 h-5" />
        </span>
      </template>
      <span class="w-56 text-sm">
        {{
          $t("subscription.require-subscription", {
            requiredPlan: $t(
              `subscription.plan.${PlanType[
                subscriptionStore.getMinimumRequiredPlan(feature)
              ].toLowerCase()}.title`
            ),
          })
        }}
      </span>
    </NTooltip>
  </div>
  <InstanceAssignment
    v-if="instanceMissingLicense && canManageSubscription"
    :show="state.showInstanceAssignmentDrawer"
    @dismiss="state.showInstanceAssignmentDrawer = false"
  />
</template>

<script lang="ts" setup>
import { NTooltip } from "naive-ui";
import { reactive, computed } from "vue";
import { useSubscriptionV1Store } from "@/store";
import type {
  Instance,
  InstanceResource,
} from "@/types/proto-es/v1/instance_service_pb";
import {
  PlanFeature,
  PlanType,
} from "@/types/proto-es/v1/subscription_service_pb";
import { autoSubscriptionRoute, hasWorkspacePermissionV2 } from "@/utils";
import InstanceAssignment from "../InstanceAssignment.vue";

interface LocalState {
  showInstanceAssignmentDrawer: boolean;
}

const props = withDefaults(
  defineProps<{
    feature: PlanFeature;
    instance?: Instance | InstanceResource;
    showInstanceMissingLicense?: boolean;
    clickable?: boolean;
  }>(),
  {
    instance: undefined,
    clickable: false,
    showInstanceMissingLicense: false,
  }
);

const state = reactive<LocalState>({
  showInstanceAssignmentDrawer: false,
});

const subscriptionStore = useSubscriptionV1Store();

const hasFeature = computed(() => {
  return subscriptionStore.hasInstanceFeature(props.feature);
});

const instanceMissingLicense = computed(() => {
  return (
    props.showInstanceMissingLicense ||
    subscriptionStore.instanceMissingLicense(props.feature, props.instance)
  );
});

const canManageSubscription = computed((): boolean => {
  return hasWorkspacePermissionV2("bb.instances.update");
});
</script>

// frontend/src/react/components/FeatureBadge.tsx
import { Lock, Sparkles } from "lucide-react";
import { useTranslation } from "react-i18next";
import { useVueState } from "@/react/hooks/useVueState";
import { useSubscriptionV1Store } from "@/store";
import type {
  Instance,
  InstanceResource,
} from "@/types/proto-es/v1/instance_service_pb";
import {
  PlanFeature,
  PlanType,
} from "@/types/proto-es/v1/subscription_service_pb";
import { Tooltip } from "./ui/tooltip";

interface FeatureBadgeProps {
  readonly feature: PlanFeature;
  readonly instance?: Instance | InstanceResource;
  readonly clickable?: boolean;
}

const planLabel: Record<number, string> = {
  [PlanType.FREE]: "free",
  [PlanType.TEAM]: "team",
  [PlanType.ENTERPRISE]: "enterprise",
};

/**
 * FeatureBadge shows a sparkles icon with tooltip when the user's plan
 * doesn't include the required feature, or a lock icon when the instance
 * is missing a license assignment.
 *
 * Renders nothing if the feature is available.
 */
export function FeatureBadge({
  feature,
  instance,
  clickable = true,
}: FeatureBadgeProps) {
  const { t } = useTranslation();
  const subscriptionStore = useSubscriptionV1Store();

  const hasFeature = useVueState(() =>
    subscriptionStore.hasInstanceFeature(feature, instance)
  );
  const instanceMissingLicense = useVueState(() =>
    subscriptionStore.instanceMissingLicense(feature, instance)
  );
  const minimumPlan = useVueState(() =>
    subscriptionStore.getMinimumRequiredPlan(feature)
  );

  if (instanceMissingLicense) {
    return (
      <Tooltip
        content={t(
          "subscription.instance-assignment.missing-license-attention"
        )}
      >
        <span className="text-accent inline-flex">
          <Lock className="w-5 h-5" />
        </span>
      </Tooltip>
    );
  }

  if (hasFeature) {
    return null;
  }

  const requiredPlanLabel = t(
    `subscription.plan.${planLabel[minimumPlan] ?? "enterprise"}.title`
  );
  const tooltip = t("subscription.require-subscription", {
    requiredPlan: requiredPlanLabel,
  });

  if (clickable) {
    return (
      <Tooltip content={tooltip}>
        <a href="/setting/subscription" className="text-accent inline-flex">
          <Sparkles className="w-5 h-5" />
        </a>
      </Tooltip>
    );
  }

  return (
    <Tooltip content={tooltip}>
      <span className="text-accent inline-flex">
        <Sparkles className="w-5 h-5" />
      </span>
    </Tooltip>
  );
}
