// frontend/src/components/Label/LabelListEditor.vue
<template>
  <div class="flex flex-col gap-y-2">
    <div
      class="grid gap-x-1 gap-y-2"
      style="grid-template-columns: 1fr 1fr auto"
    >
      <LabelEditorRow
        v-for="(kv, i) in kvList"
        :key="i"
        :kv="kv"
        :index="i"
        :readonly="readonly"
        :errors="errorsForKV(i)"
        @update-key="updateKey(i, $event)"
        @update-value="updateValue(i, $event)"
        @remove="handleRemove(i)"
      />
    </div>

    <div v-if="!readonly">
      <NButton size="small" :disabled="!allowAddLabel" @click="handleAdd">
        <template #icon>
          <heroicons:plus />
        </template>
        {{ $t("label.add-label") }}
      </NButton>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { cloneDeep } from "lodash-es";
import { NButton } from "naive-ui";
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { MAX_LABEL_VALUE_LENGTH } from "@/utils";
import LabelEditorRow from "./LabelEditorRow.vue";
import type { Label } from "./types";

const props = defineProps<{
  kvList: Label[];
  readonly: boolean;
  showErrors: boolean;
}>();

const emit = defineEmits<{
  (event: "update:kvList", kvList: Label[]): void;
}>();

const { t } = useI18n();

const errorList = computed(() => {
  const { kvList } = props;
  const list: { key: string[]; value: string[] }[] = [];
  for (let i = 0; i < kvList.length; i++) {
    const kv = kvList[i];

    const { key, value } = kv;
    const errors = {
      key: [] as string[],
      value: [] as string[],
    };
    if (!key) {
      errors.key.push(t("label.error.key-necessary"));
    } else {
      if (kvList.filter((kv) => kv.key === key).length > 1) {
        errors.key.push(t("label.error.key-duplicated"));
      }
    }
    if (!value) {
      if (!kv.allowEmpty) {
        errors.value.push(t("label.error.value-necessary"));
      }
    } else if (value.length > MAX_LABEL_VALUE_LENGTH) {
      errors.value.push(
        t("label.error.max-value-length-exceeded", {
          length: MAX_LABEL_VALUE_LENGTH,
        })
      );
    }
    list.push(errors);
  }

  return list;
});

const errorsForKV = (index: number) => {
  if (!props.showErrors) {
    return { key: [], value: [] };
  }
  return errorList.value[index] ?? { key: [], value: [] };
};

const flattenErrorsForKV = (index: number) => {
  const errors = errorsForKV(index);
  return [...errors.key, ...errors.value];
};

const flattenErrors = computed(() => {
  const flattenErrors: { key: string; errors: string[] }[] = [];
  props.kvList.forEach((kv, i) => {
    const { key } = kv;
    const errors = flattenErrorsForKV(i);
    if (errors.length > 0) {
      flattenErrors.push({ key, errors });
    }
  });
  return flattenErrors;
});

const allowAddLabel = computed(() => {
  return flattenErrors.value.length === 0;
});

const updateKey = (index: number, key: string) => {
  const list = cloneDeep(props.kvList);
  const kv = list[index];
  if (!kv) return;
  kv.key = key;
  emit("update:kvList", list);
};

const updateValue = (index: number, value: string) => {
  const list = cloneDeep(props.kvList);
  const kv = list[index];
  if (!kv) return;
  kv.value = value;
  emit("update:kvList", list);
};

const handleRemove = (index: number) => {
  const list = cloneDeep(props.kvList);
  list.splice(index, 1);
  emit("update:kvList", list);
};

const handleAdd = () => {
  const list = cloneDeep(props.kvList);
  emit("update:kvList", [...list, { key: "", value: "" }]);
};

defineExpose({
  errorList,
  flattenErrors,
});
</script>

// frontend/src/react/components/LabelListEditor.tsx
import { Plus, Trash2 } from "lucide-react";
import { useEffect, useMemo } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/react/components/ui/button";
import { Input } from "@/react/components/ui/input";

const MAX_LABEL_VALUE_LENGTH = 256;

export function LabelListEditor({
  kvList,
  onChange,
  readonly,
  showErrors = true,
  onErrorsChange,
}: {
  kvList: { key: string; value: string }[];
  onChange: (list: { key: string; value: string }[]) => void;
  readonly: boolean;
  showErrors?: boolean;
  onErrorsChange?: (errors: string[]) => void;
}) {
  const { t } = useTranslation();

  const errorList = useMemo(() => {
    return kvList.map((kv) => {
      const errors = { key: [] as string[], value: [] as string[] };
      if (!kv.key) {
        errors.key.push(t("label.error.key-necessary"));
      } else if (kvList.filter((k) => k.key === kv.key).length > 1) {
        errors.key.push(t("label.error.key-duplicated"));
      }
      if (!kv.value) {
        errors.value.push(t("label.error.value-necessary"));
      } else if (kv.value.length > MAX_LABEL_VALUE_LENGTH) {
        errors.value.push(
          t("label.error.max-value-length-exceeded", {
            length: MAX_LABEL_VALUE_LENGTH,
          })
        );
      }
      return errors;
    });
  }, [kvList, t]);

  const flatErrors = useMemo(() => {
    return errorList.flatMap((e) => [...e.key, ...e.value]);
  }, [errorList]);

  const hasErrors = flatErrors.length > 0;

  useEffect(() => {
    onErrorsChange?.(flatErrors);
  }, [flatErrors, onErrorsChange]);

  const updateKey = (index: number, key: string) => {
    onChange(kvList.map((kv, i) => (i === index ? { ...kv, key } : kv)));
  };
  const updateValue = (index: number, value: string) => {
    onChange(kvList.map((kv, i) => (i === index ? { ...kv, value } : kv)));
  };
  const handleRemove = (index: number) => {
    onChange(kvList.filter((_, i) => i !== index));
  };
  const handleAdd = () => {
    onChange([...kvList, { key: "", value: "" }]);
  };

  return (
    <div className="flex flex-col gap-y-2">
      {kvList.map((kv, index) => {
        const errors = showErrors
          ? (errorList[index] ?? { key: [], value: [] })
          : { key: [], value: [] };
        const combinedErrors = [...errors.key, ...errors.value];
        return (
          <div key={index} className="flex flex-col gap-y-1">
            <div className="flex items-center gap-x-2">
              {readonly ? (
                <span className="flex-1 text-sm">{kv.key}</span>
              ) : (
                <Input
                  className={`flex-1 ${errors.key.length > 0 ? "border-error" : ""}`}
                  value={kv.key}
                  placeholder={t("setting.label.key-placeholder")}
                  onChange={(e) => updateKey(index, e.target.value)}
                />
              )}
              {readonly ? (
                <span className="flex-1 text-sm">
                  {kv.value || (
                    <span className="text-control-placeholder">
                      {t("label.empty-label-value")}
                    </span>
                  )}
                </span>
              ) : (
                <Input
                  className={`flex-1 ${errors.value.length > 0 ? "border-error" : ""}`}
                  value={kv.value}
                  placeholder={t("setting.label.value-placeholder")}
                  onChange={(e) => updateValue(index, e.target.value)}
                />
              )}
              {!readonly && (
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => handleRemove(index)}
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
              )}
            </div>
            {combinedErrors.length > 0 && (
              <ul className="text-xs text-error list-disc list-outside pl-4">
                {combinedErrors.map((err) => (
                  <li key={err}>{err}</li>
                ))}
              </ul>
            )}
          </div>
        );
      })}
      {!readonly && (
        <Button
          variant="outline"
          size="sm"
          className="self-start"
          disabled={!kvList.length ? false : hasErrors}
          onClick={handleAdd}
        >
          <Plus className="w-4 h-4 mr-1" />
          {t("label.add-label")}
        </Button>
      )}
    </div>
  );
}
