// frontend/src/components/LearnMoreLink.vue
<template>
  <a
    class="inline-flex items-center"
    :class="[color === 'normal' ? 'normal-link' : 'light-link']"
    :href="url"
    :target="external ? '__BLANK' : ''"
  >
    {{ $t("common.learn-more") }}
    <ExternalLinkIcon v-if="external" class="w-4 h-4 ml-1" />
  </a>
</template>

<script lang="ts" setup>
import { ExternalLinkIcon } from "lucide-vue-next";

withDefaults(
  defineProps<{
    url: string;
    external?: boolean;
    color?: "normal" | "light";
  }>(),
  {
    color: "normal",
    external: true,
  }
);
</script>

// frontend/src/react/components/LearnMoreLink.tsx
import { ExternalLink } from "lucide-react";
import { useTranslation } from "react-i18next";
import { cn } from "@/react/lib/utils";

interface LearnMoreLinkProps {
  href: string;
  className?: string;
}

export function LearnMoreLink({ href, className }: LearnMoreLinkProps) {
  const { t } = useTranslation();
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className={cn(
        "inline-flex items-center gap-x-0.5 hover:underline",
        className
      )}
    >
      {t("common.learn-more")}
      <ExternalLink className="w-3 h-3" />
    </a>
  );
}
