// frontend/src/components/ResourceIdField.vue
<template>
  <div
    v-bind="$attrs"
    class="w-full max-w-full"
    :class="[shouldShowResourceIdField ? 'mt-4' : '']"
  >
    <template v-if="!shouldShowResourceIdField">
      <p v-if="state.resourceId" class="w-full text-gray-500 text-sm pt-2">
        {{ $t("resource-id.self", { resource: resourceName }) }}:
        <span class="text-gray-600 font-medium mr-1">{{
          state.resourceId
        }}</span>
        <template v-if="!readonly">
          {{ $t("resource-id.cannot-be-changed-later") }}
          <span
            class="text-accent font-medium cursor-pointer hover:opacity-80"
            @click="state.isResourceIdChanged = true"
          >
            {{ $t("common.edit") }}
          </span>
        </template>
      </p>
    </template>
    <template v-else>
      <label for="name" class="textlabel">
        {{ $t("resource-id.self", { resource: resourceName }) }}
        <span class="text-red-600">*</span>
      </label>
      <div class="mt-1 textinfolabel">
        {{ $t("resource-id.description", { resource: resourceName }) }}
      </div>
      <BBTextField
        class="mt-2 w-full"
        :value="state.resourceId"
        @input="
          handleResourceIdInput(($event.target as HTMLInputElement).value)
        "
      />
    </template>
    <ul
      v-if="state.validatedMessages.length > 0"
      class="w-full my-2 space-y-2 list-disc list-outside pl-4"
    >
      <li
        v-for="validateMessage in state.validatedMessages"
        :key="validateMessage.message"
        class="break-words w-full text-xs"
        :class="[
          validateMessage.type === 'warning' && 'text-yellow-600',
          validateMessage.type === 'error' && 'text-red-600',
        ]"
      >
        {{ validateMessage.message }}
      </li>
    </ul>
  </div>
</template>

<script lang="ts" setup>
import { computed, reactive, watch } from "vue";
import { useI18n } from "vue-i18n";
import { useDebounceFn } from "@vueuse/core";
import { randomString } from "@/utils";
import { ResourceId } from "@/types";

// characters is the validated characters for resource id.
const characters = "abcdefghijklmnopqrstuvwxyz1234567890-";

// randomCharacter returns a random character from the english alphabet.
const randomCharacter = (): string => {
  const characters = "abcdefghijklmnopqrstuvwxyz";
  return characters.charAt(Math.floor(Math.random() * characters.length));
};

const resourceIdPattern = /^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$/;

interface ValidatedMessage {
  type: "warning" | "error";
  message: string;
}

interface LocalState {
  resourceId: string;
  isResourceIdChanged: boolean;
  validatedMessages: ValidatedMessage[];
}

type ResourceType = "environment" | "instance" | "project" | "idp";

const props = withDefaults(
  defineProps<{
    resource: ResourceType;
    value: string;
    resourceTitle: string;
    readonly: boolean;
    randomString: boolean;
    validator: (resourceId: ResourceId) => Promise<string | undefined>;
  }>(),
  {
    value: "",
    resourceTitle: "",
    randomString: false,
    readonly: false,
    validator: () => Promise.resolve(undefined),
  }
);

const { t } = useI18n();
const state = reactive<LocalState>({
  resourceId: props.value,
  isResourceIdChanged: false,
  validatedMessages: [],
});

const resourceName = computed(() => {
  return t(`resource.${props.resource}`);
});

const getPrefix = (resource: string) => {
  switch (resource) {
    case "environment":
      return "env";
    case "instance":
      return "ins";
    case "project":
      return "proj";
    case "idp":
      return "idp";
    default:
      return "";
  }
};
const randomSuffix = randomString(4).toLowerCase();

const shouldShowResourceIdField = computed(() => {
  return !props.readonly && state.isResourceIdChanged;
});

const handleResourceIdInput = (newValue: string) => {
  if (!state.isResourceIdChanged) {
    return;
  }

  state.validatedMessages = [];
  debounceHandleResourceIdChange(newValue);
};

const debounceHandleResourceIdChange = useDebounceFn(
  async (newValue: string) => {
    state.resourceId = newValue;
    state.validatedMessages = [];

    // if the resource id is empty, do not validate.
    if (newValue === "" && !state.isResourceIdChanged) {
      return;
    }

    // common validation for resource id (min length, max length, pattern).
    if (state.resourceId.length < 1) {
      state.validatedMessages.push({
        type: "error",
        message: t("resource-id.validation.minlength", {
          resource: resourceName.value,
        }),
      });
    } else if (state.resourceId.length > 64) {
      state.validatedMessages.push({
        type: "error",
        message: t("resource-id.validation.overflow", {
          resource: resourceName.value,
        }),
      });
    } else if (!resourceIdPattern.test(state.resourceId)) {
      state.validatedMessages.push({
        type: "error",
        message: t("resource-id.validation.pattern", {
          resource: resourceName.value,
        }),
      });
    }

    // custom validation for resource id. (e.g. check if the resource id is already used)
    if (props.validator) {
      const message = await props.validator(state.resourceId);
      if (message) {
        state.validatedMessages.push({
          type: "error",
          message,
        });
      }
    }
  },
  200
);

watch(
  () => props.value,
  (newValue) => {
    state.resourceId = newValue;
  }
);

watch(
  () => props.resourceTitle,
  (resourceTitle) => {
    if (props.readonly) {
      return;
    }

    if (!state.isResourceIdChanged) {
      let name = "";
      if (resourceTitle) {
        const formatedTitle = resourceTitle
          .toLowerCase()
          .split("")
          .map((char) => {
            if (char === " ") {
              return "";
            }
            if (characters.includes(char)) {
              return char;
            }
            return randomCharacter();
          })
          .join("")
          .toLowerCase();

        if (props.randomString) {
          name = `${getPrefix(
            props.resource
          )}-${formatedTitle}-${randomSuffix}`;
        } else {
          name = `${formatedTitle || randomString(4).toLowerCase()}`;
        }
      }
      debounceHandleResourceIdChange(name);
    }
  },
  {
    immediate: true,
  }
);

defineExpose({
  resourceId: computed(() => state.resourceId),
  isValidated: computed(() => {
    return state.validatedMessages.length === 0;
  }),
});
</script>

// frontend/src/react/components/ResourceIdField.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from "react";
import { useTranslation } from "react-i18next";
import { Input } from "@/react/components/ui/input";
import type { ValidatedMessage } from "@/types";
import { randomString } from "@/utils";

const VALID_CHARS = "abcdefghijklmnopqrstuvwxyz1234567890-";
const RESOURCE_ID_PATTERN = /^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$/;

export interface ResourceIdFieldRef {
  resourceId: string;
  isValidated: boolean;
  addValidationError: (message: string) => void;
}

interface ResourceIdFieldProps {
  value: string;
  // Localized resource-type label (e.g. "Project", "Environment").
  // Used in the field label, description, placeholder, and validation
  // messages — NOT the user-entered title/name of the resource.
  resourceName: string;
  resourceTitle?: string;
  suffix?: boolean;
  readonly?: boolean;
  validate?: (resourceId: string) => Promise<ValidatedMessage[]>;
  onChange?: (value: string) => void;
  onValidationChange?: (isValid: boolean) => void;
}

function randomCharacter(ch?: string): string {
  const letters = "abcdefghijklmnopqrstuvwxyz";
  const index = ch
    ? ch.charCodeAt(0) % letters.length
    : Math.floor(Math.random() * letters.length);
  return letters.charAt(index);
}

function escapeTitle(str: string): string {
  return str
    .toLowerCase()
    .split("")
    .map((char) => {
      if (char === " ") return "-";
      if (char.match(/\s/)) return "";
      if (VALID_CHARS.includes(char)) return char;
      return randomCharacter(char);
    })
    .join("");
}

export const ResourceIdField = forwardRef<
  ResourceIdFieldRef,
  ResourceIdFieldProps
>(function ResourceIdField(
  {
    value,
    resourceName,
    resourceTitle,
    suffix = false,
    readonly = false,
    validate,
    onChange,
    onValidationChange,
  },
  ref
) {
  const { t } = useTranslation();
  const [manualEdit, setManualEdit] = useState(false);
  const [messages, setMessages] = useState<ValidatedMessage[]>([]);
  const randomSuffixRef = useRef(randomString(4).toLowerCase());
  const initializedRef = useRef(false);
  // Use refs for callbacks to avoid re-triggering the auto-generate effect
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;
  const validateRef = useRef(validate);
  validateRef.current = validate;
  const onValidationChangeRef = useRef(onValidationChange);
  onValidationChangeRef.current = onValidationChange;

  const updateMessages = useCallback((msgs: ValidatedMessage[]) => {
    setMessages(msgs);
    onValidationChangeRef.current?.(msgs.length === 0);
  }, []);

  const validateId = useCallback(
    async (id: string): Promise<ValidatedMessage[]> => {
      const result: ValidatedMessage[] = [];

      if (id === "") {
        result.push({
          type: "error",
          message: t("resource-id.validation.empty", {
            resource: resourceName,
          }),
        });
      } else if (id.length > 64) {
        result.push({
          type: "error",
          message: t("resource-id.validation.overflow", {
            resource: resourceName,
          }),
        });
      } else if (!RESOURCE_ID_PATTERN.test(id)) {
        result.push({
          type: "error",
          message: t("resource-id.validation.pattern", {
            resource: resourceName,
          }),
        });
      }

      if (validateRef.current && result.length === 0) {
        const custom = await validateRef.current(id);
        if (Array.isArray(custom)) {
          result.push(...custom);
        }
      }

      return result;
    },
    [resourceName, t]
  );

  // Auto-generate from title
  useEffect(() => {
    if (readonly || manualEdit) return;

    const parts: string[] = [];
    if (resourceTitle) {
      const escaped = escapeTitle(resourceTitle);
      if (suffix) {
        parts.push(escaped, randomSuffixRef.current);
      } else if (escaped) {
        parts.push(escaped);
      } else {
        parts.push(randomString(4).toLowerCase());
      }
    }
    const name = parts.join("-");

    onChangeRef.current?.(name);
    validateId(name).then((msgs) => {
      if (!initializedRef.current && msgs.length > 0) {
        const fallback = name + "-" + randomString(4).toLowerCase();
        onChangeRef.current?.(fallback);
        validateId(fallback).then(updateMessages);
      } else {
        updateMessages(msgs);
      }
      initializedRef.current = true;
    });
  }, [resourceTitle, readonly, manualEdit, suffix, validateId, updateMessages]);

  const handleManualInput = (newValue: string) => {
    onChange?.(newValue);
    setMessages([]);
    validateId(newValue).then(updateMessages);
  };

  useImperativeHandle(
    ref,
    () => ({
      get resourceId() {
        return value;
      },
      get isValidated() {
        return messages.length === 0;
      },
      addValidationError(message: string) {
        const newMessages: ValidatedMessage[] = [
          ...messages,
          { type: "error", message },
        ];
        setMessages(newMessages);
        onValidationChangeRef.current?.(false);
      },
    }),
    [value, messages]
  );

  const visible = readonly ? !!value : true;
  if (!visible) return null;

  return (
    <div>
      {readonly || !manualEdit ? (
        <div className="textinfolabel text-sm flex items-start flex-wrap gap-x-1">
          <div className="flex items-center gap-x-1">
            {t("resource-id.self", { resource: resourceName })}:
            {value ? (
              <span className="text-gray-600 font-medium mr-1">{value}</span>
            ) : (
              <span className="text-control-placeholder italic">-</span>
            )}
          </div>
          {!readonly && (
            <div>
              <span>{t("resource-id.cannot-be-changed-later")}</span>
              <button
                type="button"
                className="text-accent font-medium cursor-pointer hover:opacity-80 ml-1"
                onClick={() => setManualEdit(true)}
              >
                {t("common.edit")}
              </button>
            </div>
          )}
        </div>
      ) : (
        <div className="mt-3">
          <label className="textlabel flex items-center">
            {t("resource-id.self", { resource: resourceName })}
            <span className="ml-0.5 text-error">*</span>
          </label>
          <p className="textinfolabel mb-2 mt-1">
            {t("resource-id.description", { resource: resourceName })}
          </p>
          <Input
            value={value}
            onChange={(e) => handleManualInput(e.target.value)}
            placeholder={t("resource-id.self", { resource: resourceName })}
            className={
              messages.some((m) => m.type === "error") ? "border-error" : ""
            }
          />
        </div>
      )}
      {messages.length > 0 && (
        <ul className="w-full my-2 flex flex-col gap-y-2 list-disc list-outside pl-4">
          {messages.map((msg) => (
            <li
              key={msg.message}
              className={`break-words w-full text-xs ${
                msg.type === "warning" ? "text-yellow-600" : "text-red-600"
              }`}
            >
              {msg.message}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
});
