// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/FunctionNode.vue
<template>
  <CommonNode
    :text="(functionMetadata?.signature || functionMetadata?.name) ?? ''"
    :keyword="keyword"
    :highlight="true"
    :indent="0"
  >
    <template #icon>
      <FunctionIcon class="w-4 h-4" />
    </template>
  </CommonNode>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { FunctionIcon } from "@/components/Icon";
import { useDBSchemaV1Store } from "@/store";
import type { TreeNode } from "../tree";
import CommonNode from "./CommonNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const dbSchema = useDBSchemaV1Store();

const target = computed(() => (props.node as TreeNode<"function">).meta.target);

const functionMetadata = computed(
  () =>
    dbSchema.getSchemaMetadata({
      database: target.value.database,
      schema: target.value.schema,
    })?.functions[target.value.position]
);
</script>

// frontend/src/react/components/sql-editor/SchemaPane/TreeNode/FunctionNode.tsx
import { useDBSchemaV1Store } from "@/store";
import type { TreeNode } from "../schemaTree";
import { CommonNode } from "./CommonNode";
import { FunctionIcon } from "./icons";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

/** Replaces `TreeNode/FunctionNode.vue`. Same signature-vs-name fallback
 *  as ProcedureNode. */
export function FunctionNode({ node, keyword }: Props) {
  const dbSchema = useDBSchemaV1Store();
  const target = (node as TreeNode<"function">).meta.target;

  const functionMetadata = dbSchema.getSchemaMetadata({
    database: target.database,
    schema: target.schema,
  })?.functions[target.position];

  return (
    <CommonNode
      text={(functionMetadata?.signature || functionMetadata?.name) ?? ""}
      keyword={keyword}
      highlight={true}
      indent={0}
      icon={<FunctionIcon />}
    />
  );
}
