// frontend/src/views/auth/InactiveRemindModal.vue
<template>
  <BBModal
    :show="shouldShow"
    :trap-focus="true"
    :show-close="false"
    :mask-closable="false"
    :header-class="'hidden!'"
  >
    <div class="flex items-center w-auto md:min-w-96 max-w-full h-auto md:py-4">
      <div class="flex flex-col justify-center items-start flex-1 gap-y-4">
        <div>
          <p class="font-medium text-lg">
            {{ $t("auth.inactive-modal.title") }}
          </p>
          <span class="textinfo">
            {{
              $t("auth.inactive-modal.description", {
                minutes: showModalThresholdInMins,
              })
            }}
          </span>
        </div>
        <div class="w-full flex items-center justify-end gap-x-2">
          <NButton quaternary @click="logout">
            {{ $t("common.logout") }}
          </NButton>
          <NButton type="primary" @click="staySignedIn">
            {{ $t("auth.inactive-modal.stay-signed-in") }}
          </NButton>
        </div>
      </div>
    </div>
  </BBModal>
</template>

<script lang="tsx" setup>
import { NButton } from "naive-ui";
import { computed, onUnmounted, ref, watch } from "vue";
import { BBModal } from "@/bbkit";
import { useCurrentTimestamp } from "@/composables/useCurrentTimestamp";
import { useLastActivity } from "@/composables/useLastActivity";
import { useAuthStore, useSettingV1Store } from "@/store";

const authStore = useAuthStore();
const settingV1Store = useSettingV1Store();
const timer = ref<NodeJS.Timeout | undefined>();

// Show the modal 3min before the inactiveTimeout threshold.
const showModalThresholdInMins = 3;

const logout = () => {
  authStore.logout();
};

const inactiveTimeoutInSeconds = computed(() =>
  Number(settingV1Store.workspaceProfile.inactiveSessionTimeout?.seconds ?? 0)
);

const { lastActivityTs } = useLastActivity();

const staySignedIn = () => (lastActivityTs.value = Date.now());

const { currentTsInMS } = useCurrentTimestamp();

const shouldShow = computed(() => {
  if (inactiveTimeoutInSeconds.value <= 0) {
    return false;
  }

  const inactiveInSeconds = (currentTsInMS.value - lastActivityTs.value) / 1000;
  // Show the modal 3min before the inactiveTimeout threshold.
  return (
    inactiveInSeconds >
    inactiveTimeoutInSeconds.value - showModalThresholdInMins * 60
  );
});

const resetTimeout = () => {
  if (timer.value) {
    clearTimeout(timer.value);
    timer.value = undefined;
  }
};

watch(
  () => shouldShow.value,
  (show) => {
    resetTimeout();

    if (show) {
      timer.value = setTimeout(
        () => {
          logout();
        },
        showModalThresholdInMins * 60 * 1000
      );
    }
  }
);

onUnmounted(() => {
  resetTimeout();
});
</script>

// frontend/src/react/components/auth/InactiveRemindModal.tsx
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/react/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/react/components/ui/dialog";
import { useVueState } from "@/react/hooks/useVueState";
import { useAuthStore, useCurrentUserV1, useSettingV1Store } from "@/store";
import { storageKeyLastActivity } from "@/utils/storage-keys";

const SHOW_THRESHOLD_MIN = 3;

export function InactiveRemindModal() {
  const { t } = useTranslation();
  const currentUserEmail = useVueState(() => useCurrentUserV1().value.email);
  const inactiveTimeoutInSeconds = useVueState(() =>
    Number(
      useSettingV1Store().workspaceProfile.inactiveSessionTimeout?.seconds ?? 0
    )
  );

  const storageKey = storageKeyLastActivity(currentUserEmail);
  const [nowMS, setNowMS] = useState(() => Date.now());
  const [lastActivityTs, setLastActivityTs] = useState(() => Date.now());
  const logoutTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    const read = () => {
      const raw = localStorage.getItem(storageKey);
      if (raw !== null) {
        const parsed = Number(raw);
        if (!Number.isNaN(parsed)) setLastActivityTs(parsed);
      }
    };
    read();
    // Poll for same-tab updates (VueUse writes aren't broadcast as `storage`
    // events in the same tab).
    const pollId = setInterval(read, 1000);
    const onStorage = (e: StorageEvent) => {
      if (e.key === storageKey) read();
    };
    window.addEventListener("storage", onStorage);
    return () => {
      clearInterval(pollId);
      window.removeEventListener("storage", onStorage);
    };
  }, [storageKey]);

  useEffect(() => {
    const id = setInterval(() => setNowMS(Date.now()), 1000);
    return () => clearInterval(id);
  }, []);

  const shouldShow = (() => {
    if (inactiveTimeoutInSeconds <= 0) return false;
    const inactiveSeconds = (nowMS - lastActivityTs) / 1000;
    return inactiveSeconds > inactiveTimeoutInSeconds - SHOW_THRESHOLD_MIN * 60;
  })();

  useEffect(() => {
    if (!shouldShow) {
      if (logoutTimerRef.current) {
        clearTimeout(logoutTimerRef.current);
        logoutTimerRef.current = null;
      }
      return;
    }
    logoutTimerRef.current = setTimeout(
      () => {
        useAuthStore().logout();
      },
      SHOW_THRESHOLD_MIN * 60 * 1000
    );
    return () => {
      if (logoutTimerRef.current) {
        clearTimeout(logoutTimerRef.current);
        logoutTimerRef.current = null;
      }
    };
  }, [shouldShow]);

  const staySignedIn = () => {
    const now = Date.now();
    localStorage.setItem(storageKey, String(now));
    setLastActivityTs(now);
  };

  const logout = () => useAuthStore().logout();

  if (!shouldShow) return null;

  return (
    <Dialog open>
      <DialogContent className="p-4 md:min-w-96 max-w-full">
        <DialogTitle className="font-medium text-lg">
          {t("auth.inactive-modal.title")}
        </DialogTitle>
        <DialogDescription className="textinfo mt-1">
          {t("auth.inactive-modal.description", {
            minutes: SHOW_THRESHOLD_MIN,
          })}
        </DialogDescription>
        <div className="w-full flex items-center justify-end gap-x-2 mt-4">
          <Button variant="ghost" onClick={logout}>
            {t("common.logout")}
          </Button>
          <Button onClick={staySignedIn}>
            {t("auth.inactive-modal.stay-signed-in")}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
