// frontend/src/modules/schema-diagram/Navigator/TreeNode/Label.tsx
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { HighlightLabelText } from "@/components/HighlightLabelText";
import type { NavigatorTreeNode } from "../types";
import { isTypedNode } from "../utils";

interface LabelProps {
  node: NavigatorTreeNode;
  keyword: string;
}

/**
 * React port of `Navigator/TreeNode/Label.vue`. Uses the shared
 * `HighlightLabelText` for keyword highlighting (per the
 * use-highlightlabeltext memory rule — never inline highlight HTML).
 */
export function Label({ node, keyword }: LabelProps) {
  const { t } = useTranslation();
  const text = useMemo(() => {
    return node.data.name || t("db.schema.default");
  }, [node, t]);

  const id = `tree-node-label-${node.type}-${node.id}`;

  return (
    <div
      className="flex items-center gap-x-1 max-w-full"
      data-schema-editor-nav-tree-node-id={id}
    >
      <HighlightLabelText text={text} keyword={keyword} className="truncate" />
      {isTypedNode(node, "schema") && (
        <span className="shrink-0 text-control-light">
          ({node.data.tables.length})
        </span>
      )}
    </div>
  );
}

// frontend/src/components/SchemaDiagram/Navigator/TreeNode/Label.vue
<template>
  <!-- eslint-disable vue/no-v-html -->
  <div class="flex items-center gap-x-1 max-w-full">
    <span
      class="truncate"
      :data-schema-editor-nav-tree-node-id="id"
      v-html="html"
    />
    <span v-if="isTypedNode(node, 'schema')" class="shrink-0 text-gray-500">
      ({{ node.data.tables.length }})
    </span>
  </div>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { getHighlightHTMLByKeyWords } from "@/utils";
import type { TreeNode } from "../types";
import { isTypedNode } from "../utils";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const { t } = useI18n();

// render an unique id for every node
// for auto scroll to the node when tab switches
const id = computed(() => {
  const { node } = props;
  return `tree-node-label-${node.type}-${node.id}`;
});

const text = computed(() => {
  const { node } = props;
  return node.data.name || t("db.schema.default");
});

const html = computed(() => {
  return getHighlightHTMLByKeyWords(text.value, props.keyword);
});
</script>
