// frontend/src/modules/schema-diagram/Navigator/TreeNode/Prefix.tsx
import { Layers, Table2 } from "lucide-react";
import type { NavigatorTreeNode } from "../types";

interface PrefixProps {
  node: NavigatorTreeNode;
}

export function Prefix({ node }: PrefixProps) {
  if (node.type === "schema") return <Layers className="size-4" />;
  if (node.type === "table") return <Table2 className="size-4" />;
  return null;
}

// frontend/src/components/SchemaDiagram/Navigator/TreeNode/Prefix.vue
<template>
  <template v-if="node.type === 'schema'">
    <Layers class="w-4 h-4" />
  </template>
  <template v-if="node.type === 'table'">
    <Table2 class="w-4 h-4" />
  </template>
</template>

<script lang="ts" setup>
import { Layers, Table2 } from "lucide-vue-next";
import type { TreeNode } from "../types";

defineProps<{
  node: TreeNode;
}>();
</script>
