// frontend/src/views/Page404.vue
<template>
  <div class="w-full px-4 grid place-items-center py-24">
    <img
      class="w-16 h-auto opacity-80"
      src="@/assets/logo-icon.svg"
      alt="Bytebase"
    />
    <p class="mt-4 text-balance text-center">
      {{ $t("common.resource-not-found") }}
    </p>
    <div class="mt-12">
      <NButton size="small" @click.prevent="goHome">
        <template #icon><ChevronLeftIcon /></template>
        {{ $t("error-page.go-back-home") }}
      </NButton>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ChevronLeftIcon } from "lucide-vue-next";
import { NButton } from "naive-ui";
import { useRouter } from "vue-router";
import { WORKSPACE_ROOT_MODULE } from "@/router/dashboard/workspaceRoutes";

const router = useRouter();

const goHome = () => {
  router.push({ name: WORKSPACE_ROOT_MODULE });
};
</script>

// frontend/src/react/pages/workspace/Page404.tsx
import { ChevronLeft } from "lucide-react";
import { useTranslation } from "react-i18next";
import logoIcon from "@/assets/logo-icon.svg";
import { Button } from "@/react/components/ui/button";
import { router } from "@/router";
import { WORKSPACE_ROOT_MODULE } from "@/router/dashboard/workspaceRoutes";

export function Page404() {
  const { t } = useTranslation();

  const goHome = () => {
    router.push({ name: WORKSPACE_ROOT_MODULE });
  };

  return (
    <div className="w-full px-4 grid place-items-center py-24">
      <img className="w-16 h-auto opacity-80" src={logoIcon} alt="Bytebase" />
      <p className="mt-4 text-balance text-center">
        {t("common.resource-not-found")}
      </p>
      <div className="mt-12">
        <Button variant="outline" size="sm" onClick={goHome}>
          <ChevronLeft className="h-4 w-4" />
          {t("error-page.go-back-home")}
        </Button>
      </div>
    </div>
  );
}
