// frontend/src/plugins/agent/components/ToolCallCard.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type {
  AgentAskUserOption,
  AgentAskUserResponse,
  ToolCall,
} from "../logic/types";

const props = defineProps<{
  toolCall: ToolCall;
  result?: string;
}>();

const expanded = ref(false);

const parseJson = (value?: string): unknown => {
  if (!value) {
    return undefined;
  }
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
};

const formatJson = (value?: string): string => {
  if (!value) {
    return "";
  }
  try {
    return JSON.stringify(JSON.parse(value), null, 2);
  } catch {
    return value;
  }
};

const parseAskUserOption = (value: unknown): AgentAskUserOption | null => {
  if (!value || typeof value !== "object") {
    return null;
  }

  const option = value as Record<string, unknown>;
  const label =
    typeof option.label === "string"
      ? option.label.trim()
      : typeof option.value === "string"
        ? option.value.trim()
        : "";
  const optionValue =
    typeof option.value === "string" ? option.value.trim() : "";

  if (!label || !optionValue) {
    return null;
  }

  return {
    label,
    value: optionValue,
    description:
      typeof option.description === "string" && option.description.trim()
        ? option.description.trim()
        : undefined,
  };
};

const resultText = computed(() => props.result ?? "");
const parsedArguments = computed(() => parseJson(props.toolCall.arguments));
const parsedResult = computed(() => parseJson(resultText.value));
const isAskUser = computed(() => props.toolCall.name === "ask_user");
const isDone = computed(() => props.toolCall.name === "done");
const askPrompt = computed(() => {
  if (
    typeof parsedArguments.value === "object" &&
    parsedArguments.value &&
    "prompt" in parsedArguments.value &&
    typeof parsedArguments.value.prompt === "string"
  ) {
    return parsedArguments.value.prompt;
  }
  return "";
});
const askKind = computed(() => {
  if (
    typeof parsedArguments.value === "object" &&
    parsedArguments.value &&
    "kind" in parsedArguments.value
  ) {
    if (parsedArguments.value.kind === "confirm") {
      return "confirm";
    }
    if (parsedArguments.value.kind === "choose") {
      return "choose";
    }
  }
  return "input";
});
const askDefaultValue = computed(() => {
  if (
    typeof parsedArguments.value === "object" &&
    parsedArguments.value &&
    "defaultValue" in parsedArguments.value &&
    typeof parsedArguments.value.defaultValue === "string"
  ) {
    return parsedArguments.value.defaultValue;
  }
  return "";
});
const askOptions = computed<AgentAskUserOption[]>(() => {
  if (
    typeof parsedArguments.value !== "object" ||
    !parsedArguments.value ||
    !("options" in parsedArguments.value) ||
    !Array.isArray(parsedArguments.value.options)
  ) {
    return [];
  }

  return parsedArguments.value.options
    .map((option) => parseAskUserOption(option))
    .filter((option): option is AgentAskUserOption => !!option);
});
const askResponse = computed<AgentAskUserResponse | null>(() => {
  if (
    typeof parsedResult.value !== "object" ||
    !parsedResult.value ||
    !("kind" in parsedResult.value) ||
    typeof parsedResult.value.kind !== "string" ||
    !("answer" in parsedResult.value) ||
    typeof parsedResult.value.answer !== "string"
  ) {
    return null;
  }

  const response = parsedResult.value as Record<string, unknown>;

  if (response.kind === "confirm") {
    if (typeof response.confirmed !== "boolean") {
      return null;
    }
    return response as AgentAskUserResponse;
  }

  if (response.kind === "choose") {
    if (typeof response.value !== "string") {
      return null;
    }
    return response as AgentAskUserResponse;
  }

  if (response.kind === "input") {
    return response as AgentAskUserResponse;
  }

  return null;
});
const doneText = computed(() => {
  if (
    typeof parsedArguments.value === "object" &&
    parsedArguments.value &&
    "text" in parsedArguments.value &&
    typeof parsedArguments.value.text === "string"
  ) {
    return parsedArguments.value.text;
  }
  return "";
});
const doneSuccess = computed(() => {
  if (
    typeof parsedArguments.value === "object" &&
    parsedArguments.value &&
    "success" in parsedArguments.value
  ) {
    return parsedArguments.value.success !== false;
  }
  return true;
});
</script>

<template>
  <div class="rounded border bg-gray-50 text-xs">
    <div
      class="flex cursor-pointer items-center gap-x-2 px-2 py-1.5"
      @click="expanded = !expanded"
    >
      <span class="font-mono text-gray-600">{{ toolCall.name }}</span>
      <template v-if="isAskUser">
        <span v-if="resultText" class="text-green-500">
          {{ $t("agent.tool-response-submitted") }}
        </span>
        <span v-else class="text-amber-600">{{ $t("agent.tool-ask-user") }}</span>
      </template>
      <template v-else-if="isDone">
        <span :class="doneSuccess ? 'text-green-500' : 'text-red-500'">
          {{ doneSuccess ? $t("agent.tool-completed") : $t("agent.tool-failed") }}
        </span>
      </template>
      <template v-else>
        <span v-if="resultText" class="text-green-500">&#10003;</span>
        <span v-else class="animate-pulse text-gray-400">&#9679;</span>
      </template>
      <span class="ml-auto text-gray-400">{{ expanded ? "\u25BE" : "\u25B8" }}</span>
    </div>

    <div v-if="expanded" class="space-y-1 border-t px-2 py-1.5">
      <template v-if="isAskUser">
        <div class="text-gray-500">
          {{
            askKind === "confirm"
              ? $t("agent.tool-ask-user-confirm")
              : askKind === "choose"
                ? $t("agent.tool-ask-user-choose")
                : $t("agent.tool-ask-user-input")
          }}
        </div>
        <div class="text-gray-500">{{ $t("agent.tool-prompt") }}</div>
        <pre class="whitespace-pre-wrap break-all text-gray-700">{{ askPrompt }}</pre>
        <template v-if="askDefaultValue">
          <div class="text-gray-500">{{ $t("agent.tool-default-value") }}</div>
          <pre class="whitespace-pre-wrap break-all text-gray-700">{{
            askDefaultValue
          }}</pre>
        </template>
        <template v-if="askKind === 'choose' && askOptions.length > 0">
          <div class="text-gray-500">{{ $t("agent.tool-options") }}</div>
          <div class="space-y-1">
            <div
              v-for="option in askOptions"
              :key="option.value"
              class="rounded border border-gray-200 bg-white px-2 py-1"
            >
              <div class="font-medium text-gray-700">{{ option.label }}</div>
              <div class="text-gray-500">{{ option.value }}</div>
              <div v-if="option.description" class="text-gray-500">
                {{ option.description }}
              </div>
            </div>
          </div>
        </template>
        <template v-if="askResponse">
          <div class="text-gray-500">{{ $t("agent.tool-answer") }}</div>
          <pre class="whitespace-pre-wrap break-all text-gray-700">{{
            askResponse.answer
          }}</pre>
          <template v-if="askResponse.kind === 'choose'">
            <div class="text-gray-500">{{ $t("agent.tool-value") }}</div>
            <pre class="whitespace-pre-wrap break-all text-gray-700">{{
              askResponse.value
            }}</pre>
          </template>
        </template>
      </template>

      <template v-else-if="isDone">
        <div class="text-gray-500">{{ $t("agent.result") }}</div>
        <pre class="whitespace-pre-wrap break-all text-gray-700">{{ doneText }}</pre>
      </template>

      <template v-else>
        <div class="text-gray-500">{{ $t("agent.args") }}</div>
        <pre class="whitespace-pre-wrap break-all text-gray-700">{{
          formatJson(toolCall.arguments)
        }}</pre>
        <template v-if="resultText">
          <div class="text-gray-500">{{ $t("agent.result") }}</div>
          <pre
            class="max-h-32 overflow-y-auto whitespace-pre-wrap break-all text-gray-700"
            >{{ formatJson(resultText) }}</pre
          >
        </template>
      </template>
    </div>
  </div>
</template>

// frontend/src/react/plugins/agent/components/ToolCallCard.tsx
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import type {
  AgentAskUserOption,
  AgentAskUserResponse,
  ToolCall,
} from "../logic/types";

interface Props {
  toolCall: ToolCall;
  result?: string;
}

const parseJson = (value?: string): unknown => {
  if (!value) return undefined;
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
};

const formatJson = (value?: string): string => {
  if (!value) return "";
  try {
    return JSON.stringify(JSON.parse(value), null, 2);
  } catch {
    return value;
  }
};

const parseAskUserOption = (value: unknown): AgentAskUserOption | null => {
  if (!value || typeof value !== "object") return null;

  const option = value as Record<string, unknown>;
  const label =
    typeof option.label === "string"
      ? option.label.trim()
      : typeof option.value === "string"
        ? option.value.trim()
        : "";
  const optionValue =
    typeof option.value === "string" ? option.value.trim() : "";

  if (!label || !optionValue) return null;

  return {
    label,
    value: optionValue,
    description:
      typeof option.description === "string" && option.description.trim()
        ? option.description.trim()
        : undefined,
  };
};

export function ToolCallCard({ toolCall, result }: Props) {
  const { t } = useTranslation();
  const [expanded, setExpanded] = useState(false);

  const resultText = result ?? "";
  const parsedArguments = useMemo(
    () => parseJson(toolCall.arguments),
    [toolCall.arguments]
  );
  const parsedResult = useMemo(() => parseJson(resultText), [resultText]);
  const isAskUser = toolCall.name === "ask_user";
  const isDone = toolCall.name === "done";

  const askPrompt = useMemo(() => {
    if (
      typeof parsedArguments === "object" &&
      parsedArguments &&
      "prompt" in parsedArguments &&
      typeof (parsedArguments as Record<string, unknown>).prompt === "string"
    ) {
      return (parsedArguments as Record<string, unknown>).prompt as string;
    }
    return "";
  }, [parsedArguments]);

  const askKind = useMemo(() => {
    if (
      typeof parsedArguments === "object" &&
      parsedArguments &&
      "kind" in parsedArguments
    ) {
      const kind = (parsedArguments as Record<string, unknown>).kind;
      if (kind === "confirm") return "confirm" as const;
      if (kind === "choose") return "choose" as const;
    }
    return "input" as const;
  }, [parsedArguments]);

  const askDefaultValue = useMemo(() => {
    if (
      typeof parsedArguments === "object" &&
      parsedArguments &&
      "defaultValue" in parsedArguments &&
      typeof (parsedArguments as Record<string, unknown>).defaultValue ===
        "string"
    ) {
      return (parsedArguments as Record<string, unknown>)
        .defaultValue as string;
    }
    return "";
  }, [parsedArguments]);

  const askOptions = useMemo<AgentAskUserOption[]>(() => {
    if (
      typeof parsedArguments !== "object" ||
      !parsedArguments ||
      !("options" in parsedArguments) ||
      !Array.isArray((parsedArguments as Record<string, unknown>).options)
    ) {
      return [];
    }
    return ((parsedArguments as Record<string, unknown>).options as unknown[])
      .map((option) => parseAskUserOption(option))
      .filter((option): option is AgentAskUserOption => !!option);
  }, [parsedArguments]);

  const askResponse = useMemo<AgentAskUserResponse | null>(() => {
    if (
      typeof parsedResult !== "object" ||
      !parsedResult ||
      !("kind" in parsedResult) ||
      typeof (parsedResult as Record<string, unknown>).kind !== "string" ||
      !("answer" in parsedResult) ||
      typeof (parsedResult as Record<string, unknown>).answer !== "string"
    ) {
      return null;
    }

    const response = parsedResult as Record<string, unknown>;
    if (response.kind === "confirm") {
      if (typeof response.confirmed !== "boolean") return null;
      return response as unknown as AgentAskUserResponse;
    }
    if (response.kind === "choose") {
      if (typeof response.value !== "string") return null;
      return response as unknown as AgentAskUserResponse;
    }
    if (response.kind === "input") {
      return response as unknown as AgentAskUserResponse;
    }
    return null;
  }, [parsedResult]);

  const doneText = useMemo(() => {
    if (
      typeof parsedArguments === "object" &&
      parsedArguments &&
      "text" in parsedArguments &&
      typeof (parsedArguments as Record<string, unknown>).text === "string"
    ) {
      return (parsedArguments as Record<string, unknown>).text as string;
    }
    return "";
  }, [parsedArguments]);

  const doneSuccess = useMemo(() => {
    if (
      typeof parsedArguments === "object" &&
      parsedArguments &&
      "success" in parsedArguments
    ) {
      return (parsedArguments as Record<string, unknown>).success !== false;
    }
    return true;
  }, [parsedArguments]);

  const renderStatus = () => {
    if (isAskUser) {
      return resultText ? (
        <span className="text-green-500">
          {t("agent.tool-response-submitted")}
        </span>
      ) : (
        <span className="text-amber-600">{t("agent.tool-ask-user")}</span>
      );
    }
    if (isDone) {
      return (
        <span className={doneSuccess ? "text-green-500" : "text-red-500"}>
          {doneSuccess ? t("agent.tool-completed") : t("agent.tool-failed")}
        </span>
      );
    }
    return resultText ? (
      <span className="text-green-500">&#10003;</span>
    ) : (
      <span className="animate-pulse text-gray-400">&#9679;</span>
    );
  };

  const renderExpandedContent = () => {
    if (isAskUser) {
      return (
        <>
          <div className="text-gray-500">
            {askKind === "confirm"
              ? t("agent.tool-ask-user-confirm")
              : askKind === "choose"
                ? t("agent.tool-ask-user-choose")
                : t("agent.tool-ask-user-input")}
          </div>
          <div className="text-gray-500">{t("agent.tool-prompt")}</div>
          <pre className="whitespace-pre-wrap break-all text-gray-700">
            {askPrompt}
          </pre>
          {askDefaultValue && (
            <>
              <div className="text-gray-500">
                {t("agent.tool-default-value")}
              </div>
              <pre className="whitespace-pre-wrap break-all text-gray-700">
                {askDefaultValue}
              </pre>
            </>
          )}
          {askKind === "choose" && askOptions.length > 0 && (
            <>
              <div className="text-gray-500">{t("agent.tool-options")}</div>
              <div className="space-y-1">
                {askOptions.map((option) => (
                  <div
                    key={option.value}
                    className="rounded border border-gray-200 bg-white px-2 py-1"
                  >
                    <div className="font-medium text-gray-700">
                      {option.label}
                    </div>
                    <div className="text-gray-500">{option.value}</div>
                    {option.description && (
                      <div className="text-gray-500">{option.description}</div>
                    )}
                  </div>
                ))}
              </div>
            </>
          )}
          {askResponse && (
            <>
              <div className="text-gray-500">{t("agent.tool-answer")}</div>
              <pre className="whitespace-pre-wrap break-all text-gray-700">
                {askResponse.answer}
              </pre>
              {askResponse.kind === "choose" && (
                <>
                  <div className="text-gray-500">{t("agent.tool-value")}</div>
                  <pre className="whitespace-pre-wrap break-all text-gray-700">
                    {askResponse.value}
                  </pre>
                </>
              )}
            </>
          )}
        </>
      );
    }

    if (isDone) {
      return (
        <>
          <div className="text-gray-500">{t("agent.result")}</div>
          <pre className="whitespace-pre-wrap break-all text-gray-700">
            {doneText}
          </pre>
        </>
      );
    }

    return (
      <>
        <div className="text-gray-500">{t("agent.args")}</div>
        <pre className="whitespace-pre-wrap break-all text-gray-700">
          {formatJson(toolCall.arguments)}
        </pre>
        {resultText && (
          <>
            <div className="text-gray-500">{t("agent.result")}</div>
            <pre className="max-h-32 overflow-y-auto whitespace-pre-wrap break-all text-gray-700">
              {formatJson(resultText)}
            </pre>
          </>
        )}
      </>
    );
  };

  return (
    <div className="rounded border bg-gray-50 text-xs">
      <div
        className="flex cursor-pointer items-center gap-x-2 px-2 py-1.5"
        onClick={() => setExpanded(!expanded)}
      >
        <span className="font-mono text-gray-600">{toolCall.name}</span>
        {renderStatus()}
        <span className="ml-auto text-gray-400">
          {expanded ? "\u25BE" : "\u25B8"}
        </span>
      </div>

      {expanded && (
        <div className="space-y-1 border-t px-2 py-1.5">
          {renderExpandedContent()}
        </div>
      )}
    </div>
  );
}
