// frontend/src/react/components/instance/InstanceSyncButton.tsx
import { ChevronDown } from "lucide-react";
import { useCallback, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/react/components/ui/button";
import { pushNotification, useDatabaseV1Store } from "@/store";
import { SyncStatus } from "@/types/proto-es/v1/database_service_pb";
import { hasWorkspacePermissionV2 } from "@/utils";

interface InstanceSyncButtonProps {
  type?: "default" | "primary";
  size?: "small" | "medium";
  disabled?: boolean;
  instanceName?: string;
  instanceTitle?: string;
  onSyncSchema: (enableFullSync: boolean) => void;
}

export function InstanceSyncButton({
  disabled = false,
  instanceName = "",
  instanceTitle = "",
  onSyncSchema,
}: InstanceSyncButtonProps) {
  const { t } = useTranslation();
  const [syncing, setSyncing] = useState(false);
  const [open, setOpen] = useState(false);

  const hasPermission = hasWorkspacePermissionV2("bb.instances.sync");

  const syncSchema = useCallback(
    async (option: "sync-all" | "sync-new") => {
      setOpen(false);
      try {
        setSyncing(true);
        const displayName = instanceTitle || instanceName || "";
        if (displayName) {
          pushNotification({
            module: "bytebase",
            style: "INFO",
            title: t("db.syncing-databases-for-instance", { 0: displayName }),
          });
        } else {
          pushNotification({
            module: "bytebase",
            style: "INFO",
            title: t("db.start-to-sync-schema"),
          });
        }

        onSyncSchema(option === "sync-all");

        if (instanceName) {
          const displayName = instanceTitle || instanceName;
          let notificationShown = false;

          const checkSyncStatus = async () => {
            const databaseStore = useDatabaseV1Store();
            const { databases } = await databaseStore.fetchDatabases({
              parent: instanceName,
              pageSize: 1000,
              silent: true,
            });
            const stillSyncing = databases.filter(
              (db) => db.syncStatus === SyncStatus.SYNC_STATUS_UNSPECIFIED
            );
            const failed = databases.filter(
              (db) => db.syncStatus === SyncStatus.FAILED
            );
            if (stillSyncing.length > 0) return "syncing";
            if (failed.length > 0) {
              pushNotification({
                module: "bytebase",
                style: "WARN",
                title: t("db.n-databases-had-sync-errors", {
                  0: failed.length,
                }),
              });
            } else {
              pushNotification({
                module: "bytebase",
                style: "SUCCESS",
                title: t("database.sync-complete-for-instance", {
                  0: displayName,
                }),
              });
            }
            notificationShown = true;
            return "complete";
          };

          setTimeout(async () => {
            try {
              await checkSyncStatus();
            } catch {
              /* retry at 30s */
            }
          }, 15000);

          setTimeout(async () => {
            if (notificationShown) return;
            try {
              await checkSyncStatus();
            } catch {
              /* user can check database list */
            }
          }, 30000);
        }
      } catch (error) {
        pushNotification({
          module: "bytebase",
          style: "CRITICAL",
          title: t("db.failed-to-sync-schema"),
          description: (error as Error).message,
        });
      } finally {
        setSyncing(false);
      }
    },
    [instanceName, instanceTitle, onSyncSchema, t]
  );

  return (
    <div className="relative">
      <Button
        variant="outline"
        disabled={!hasPermission || disabled || syncing}
        onClick={() => setOpen(!open)}
      >
        {syncing ? t("instance.syncing") : t("instance.sync.self")}
        <ChevronDown className="ml-1 size-4" />
      </Button>
      {open && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} />
          <div className="absolute left-0 top-full mt-1 z-50 min-w-[140px] rounded-sm border bg-background shadow-md py-1">
            <button
              type="button"
              className="w-full text-left px-3 py-1.5 text-sm hover:bg-control-bg"
              title={t("instance.sync.sync-all-tip")}
              onClick={() => syncSchema("sync-all")}
            >
              {t("instance.sync.sync-all")}
            </button>
            <button
              type="button"
              className="w-full text-left px-3 py-1.5 text-sm hover:bg-control-bg"
              onClick={() => syncSchema("sync-new")}
            >
              {t("instance.sync.sync-new")}
            </button>
          </div>
        </>
      )}
    </div>
  );
}

// frontend/src/components/Instance/InstanceSyncButton.vue
<template>
  <NDropdown
    :trigger="'click'"
    :options="syncInstnceOptions"
    :render-label="renderDropdownLabel"
    :disabled="disabled || syncingSchema"
    @select="syncSchema"
  >
    <PermissionGuardWrapper
      v-slot="slotProps"
      :permissions="['bb.instances.sync']"
    >
      <NButton
        icon-placement="right"
        :loading="syncingSchema"
        :quaternary="quaternary"
        :disabled="slotProps.disabled || disabled"
        :size="size"
        :type="type"
      >
        <template #icon>
          <ChevronDownIcon class="w-4" />
        </template>
        <template v-if="syncingSchema">
          {{ $t("instance.syncing") }}
        </template>
        <template v-else>
          {{ $t("instance.sync.self") }}
        </template>
      </NButton>
    </PermissionGuardWrapper>
  </NDropdown>
</template>

<script lang="tsx" setup>
import type { ConnectError } from "@connectrpc/connect";
import { ChevronDownIcon } from "lucide-vue-next";
import type { DropdownOption } from "naive-ui";
import { NButton, NDropdown, NTooltip } from "naive-ui";
import { computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import PermissionGuardWrapper from "@/components/Permission/PermissionGuardWrapper.vue";
import { pushNotification, useDatabaseV1Store } from "@/store";
import { SyncStatus } from "@/types/proto-es/v1/database_service_pb";

const props = withDefaults(
  defineProps<{
    type?: "default" | "primary";
    size?: "small" | "medium";
    disabled?: boolean;
    quaternary?: boolean;
    instanceName?: string;
    instanceTitle?: string;
  }>(),
  {
    type: "default",
    size: "medium",
    disabled: false,
    quaternary: false,
    instanceName: "",
    instanceTitle: "",
  }
);

const emit = defineEmits<{
  (name: "sync-schema", enableFullSync: boolean): void;
}>();

const { t } = useI18n();
const syncingSchema = ref<boolean>(false);

type SyncInstanceOption = "sync-all" | "sync-new";

const renderDropdownLabel = (option: DropdownOption) => {
  if (option.key === "sync-new") {
    return <span>{option.label}</span>;
  }
  return (
    <NTooltip placement="top-start">
      {{
        trigger: () => option.label,
        default: () => (
          <span class="text-sm text-nowrap">
            {t("instance.sync.sync-all-tip")}
          </span>
        ),
      }}
    </NTooltip>
  );
};

const syncInstnceOptions = computed((): DropdownOption[] => {
  return [
    {
      key: "sync-all",
      label: t("instance.sync.sync-all"),
    },
    {
      key: "sync-new",
      label: t("instance.sync.sync-new"),
    },
  ];
});

const syncSchema = async (option: SyncInstanceOption) => {
  try {
    syncingSchema.value = true;

    // Show immediate "syncing" notification (honest - not claiming success yet)
    const displayName = props.instanceTitle || props.instanceName || "";
    if (displayName) {
      pushNotification({
        module: "bytebase",
        style: "INFO",
        title: t("db.syncing-databases-for-instance", [displayName]),
      });
    } else {
      // Fallback for batch sync or when instance info not provided
      pushNotification({
        module: "bytebase",
        style: "INFO",
        title: t("db.start-to-sync-schema"),
      });
    }

    emit("sync-schema", option === "sync-all" /* enable full sync */);

    // Two-phase delayed check for sync status
    if (props.instanceName) {
      const displayName = props.instanceTitle || props.instanceName;
      let notificationShown = false;

      const checkSyncStatus = async (): Promise<"complete" | "syncing"> => {
        const databaseStore = useDatabaseV1Store();
        const { databases } = await databaseStore.fetchDatabases({
          parent: props.instanceName,
          pageSize: 1000,
          silent: true,
        });

        const stillSyncing = databases.filter(
          (db) => db.syncStatus === SyncStatus.SYNC_STATUS_UNSPECIFIED
        );
        const failed = databases.filter(
          (db) => db.syncStatus === SyncStatus.FAILED
        );

        // If any databases still syncing, don't notify yet
        if (stillSyncing.length > 0) {
          return "syncing";
        }

        // All syncs complete - show appropriate notification
        if (failed.length > 0) {
          pushNotification({
            module: "bytebase",
            style: "WARN",
            title: t("db.n-databases-had-sync-errors", [failed.length]),
          });
        } else {
          pushNotification({
            module: "bytebase",
            style: "SUCCESS",
            title: t("database.sync-complete-for-instance", [displayName]),
          });
        }
        notificationShown = true;
        return "complete";
      };

      // First check at 15 seconds (fast feedback for small instances)
      setTimeout(async () => {
        try {
          await checkSyncStatus();
        } catch {
          // Silently ignore - will retry at 30s
        }
      }, 15000);

      // Second check at 30 seconds (for larger instances)
      setTimeout(async () => {
        if (notificationShown) return;
        try {
          await checkSyncStatus();
          // If still syncing at 30s, don't notify - user can check database list
        } catch {
          // Silently ignore - user can check database list
        }
      }, 30000);
    }
  } catch (error) {
    pushNotification({
      module: "bytebase",
      style: "CRITICAL",
      title: t("db.failed-to-sync-schema"),
      description: (error as ConnectError).message,
    });
  } finally {
    syncingSchema.value = false;
  }
};
</script>
