// frontend/src/components/InstanceForm/DataSourceSection/SshConnectionForm.vue
<template>
  <div class="flex flex-row items-center gap-x-4 mt-2">
    <NRadio
      v-for="sshType in SshTypes"
      :key="sshType"
      :value="sshType"
      :disabled="disabled"
      :checked="state.type === sshType"
      @update:checked="handleSelectType(sshType, $event)"
    >
      {{ getSshTypeLabel(sshType) }}
    </NRadio>
  </div>

  <template v-if="state.type !== 'NONE'">
    <div
      class="sm:col-span-1 sm:col-start-1 mt-4 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-4"
    >
      <div class="sm:col-span-3 sm:col-start-1">
        <label for="sshHost" class="textlabel block">
          {{ $t("data-source.ssh.host") }}
        </label>
        <NInput
          v-model:value="state.value.sshHost"
          class="mt-2 w-full"
          :placeholder="''"
          :disabled="disabled"
        />
      </div>

      <div class="sm:col-span-1">
        <label for="sshPort" class="textlabel block">
          {{ $t("data-source.ssh.port") }}
        </label>
        <NInput
          v-model:value="state.value.sshPort"
          class="mt-2 w-full"
          :placeholder="''"
          :disabled="disabled"
          :allow-input="onlyAllowNumber"
        />
      </div>
    </div>

    <div
      class="mt-2 grid grid-cols-1 gap-y-2 gap-x-4 border-none sm:grid-cols-3"
    >
      <div class="mt-2 sm:col-span-3 sm:col-start-1">
        <label for="sshUser" class="textlabel block">
          {{ $t("data-source.ssh.user") }}
        </label>
        <NInput
          v-model:value="state.value.sshUser"
          class="mt-2 w-full"
          :placeholder="''"
          :disabled="disabled"
        />
      </div>
      <div class="mt-2 sm:col-span-3 sm:col-start-1">
        <label for="sshPassword" class="textlabel block">
          {{ $t("data-source.ssh.password") }}
        </label>
        <NInput
          v-model:value="state.value.sshPassword"
          class="mt-2 w-full"
          :placeholder="$t('instance.password-write-only')"
          :disabled="disabled"
        />
      </div>
    </div>
    <div class="mt-4 sm:col-span-3 sm:col-start-1">
      <div class="mt-2 sm:col-span-1 sm:col-start-1 flex flex-col">
        <label for="sshPrivateKey" class="textlabel block">
          {{ $t("data-source.ssh.ssh-key") }}
          ({{ t("common.optional") }})
        </label>
        <DroppableTextarea
          v-model:value="state.value.sshPrivateKey"
          :resizable="false"
          :disabled="disabled"
          :placeholder="$t('common.write-only')"
          class="w-full h-24 mt-2 whitespace-pre-wrap"
        />
      </div>
    </div>
  </template>

  <FeatureModal
    feature="bb.feature.instance-ssh-connection"
    :open="state.showFeatureModal"
    :instance="instance"
    @cancel="state.showFeatureModal = false"
  />
</template>

<script lang="ts" setup>
import { NInput, NRadio } from "naive-ui";
import { reactive, computed, watch } from "vue";
import { useI18n } from "vue-i18n";
import { FeatureModal } from "@/components/FeatureGuard";
import DroppableTextarea from "@/components/misc/DroppableTextarea.vue";
import { useSubscriptionV1Store } from "@/store";
import type { Instance } from "@/types/proto/v1/instance_service";
import { onlyAllowNumber } from "@/utils";

const SshTypes = ["NONE", "TUNNEL+PK"] as const;

type SshType = (typeof SshTypes)[number];

type WithSshOptions = {
  sshHost?: string;
  sshPort?: string;
  sshUser?: string;
  sshPassword?: string;
  sshPrivateKey?: string;
};

type LocalState = {
  type: SshType;
  value: WithSshOptions;
  showFeatureModal: boolean;
};

const props = defineProps<{
  value: WithSshOptions;
  instance?: Instance;
  disabled: boolean;
}>();

const emit = defineEmits<{
  (e: "change", value: WithSshOptions): void;
}>();

const { t } = useI18n();

const state = reactive<LocalState>({
  type: guessSshType(props.value),
  value: {},
  showFeatureModal: false,
});

const hasSSHConnectionFeature = computed(() => {
  return useSubscriptionV1Store().hasInstanceFeature(
    "bb.feature.instance-ssh-connection",
    props.instance
  );
});

const handleSelectType = (type: SshType, checked: boolean) => {
  if (!checked) return;

  if (!hasSSHConnectionFeature.value) {
    if (type !== "NONE") {
      state.type = "NONE";
      state.showFeatureModal = true;
      return;
    }
  }

  state.type = type;
};

// Sync the latest version to local state when props.value changed.
watch(
  () => props.value,
  (newValue) => {
    state.type = guessSshType(newValue);
    state.value = {
      sshHost: props.value.sshHost,
      sshPort: props.value.sshPort,
      sshUser: props.value.sshUser,
      sshPassword: props.value.sshPassword,
      sshPrivateKey: props.value.sshPrivateKey,
    };
  },
  {
    immediate: true,
  }
);

// Emit the latest lo the parent when local value has been edited.
watch(
  () => state.value,
  (localValue) => {
    emit("change", { ...localValue });
  },
  { deep: true }
);

watch(
  () => state.type,
  (type) => {
    if (type === "NONE") {
      state.value.sshHost = "";
      state.value.sshPort = "";
      state.value.sshUser = "";
      state.value.sshPassword = "";
      state.value.sshPrivateKey = "";
    }
  }
);

function getSshTypeLabel(type: SshType): string {
  if (type === "TUNNEL+PK") {
    return t("data-source.ssh-type.tunnel-and-private-key");
  }
  return t("data-source.ssh-type.none");
}

function guessSshType(value: WithSshOptions): SshType {
  if (value.sshPort) {
    return "TUNNEL+PK";
  }
  return "NONE";
}
</script>

// frontend/src/components/instance/SshConnectionForm.tsx
import {
  type DragEvent,
  type ReactNode,
  useCallback,
  useEffect,
  useState,
} from "react";
import { useTranslation } from "react-i18next";
import {
  FormField,
  FormLabel,
  ResponsiveFormLayout,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Textarea } from "@/components/ui/textarea";
import type { Instance } from "@/types/proto-es/v1/instance_service_pb";

const SSH_TYPES = ["NONE", "TUNNEL+PK"] as const;
type SshType = (typeof SSH_TYPES)[number];

interface SshValue {
  sshHost: string;
  sshPort: string;
  sshUser: string;
  sshPassword: string;
  sshPrivateKey: string;
}

interface SshConnectionFormProps {
  title?: ReactNode;
  value: SshValue;
  instance?: Instance;
  disabled?: boolean;
  onChange: (value: Partial<SshValue>) => void;
}

function guessSshType(value: Partial<SshValue>): SshType {
  if (
    value.sshHost ||
    value.sshPort ||
    value.sshUser ||
    value.sshPassword ||
    value.sshPrivateKey
  ) {
    return "TUNNEL+PK";
  }
  return "NONE";
}

export function SshConnectionForm({
  value,
  title,
  instance: _instance,
  disabled = false,
  onChange,
}: SshConnectionFormProps) {
  const { t } = useTranslation();
  const [sshType, setSshType] = useState<SshType>(() => guessSshType(value));

  // Sync type from props when value changes externally.
  useEffect(() => {
    setSshType(guessSshType(value));
  }, [value]);

  const handleSelectType = useCallback(
    (type: SshType) => {
      setSshType(type);
      if (type === "NONE") {
        onChange({
          sshHost: "",
          sshPort: "",
          sshUser: "",
          sshPassword: "",
          sshPrivateKey: "",
        });
      }
    },
    [onChange]
  );

  const getSshTypeLabel = (type: SshType): string => {
    if (type === "TUNNEL+PK") {
      return t("data-source.ssh-type.tunnel-and-private-key");
    }
    return t("data-source.ssh-type.none");
  };

  const handleDrop = useCallback(
    (e: DragEvent<HTMLTextAreaElement>) => {
      e.preventDefault();
      const file = e.dataTransfer.files[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = () => {
        if (typeof reader.result === "string") {
          onChange({ sshPrivateKey: reader.result });
        }
      };
      reader.readAsText(file);
    },
    [onChange]
  );

  const handleDragOver = useCallback((e: DragEvent<HTMLTextAreaElement>) => {
    e.preventDefault();
  }, []);

  return (
    <div className="flex flex-col gap-4">
      <FormField title={title ?? t("data-source.ssh-connection")}>
        <div className="flex flex-col gap-4">
          <RadioGroup
            value={sshType}
            onValueChange={(value) => handleSelectType(value as SshType)}
            aria-label={t("data-source.ssh-connection")}
            disabled={disabled}
            className="flex-col items-start self-start gap-y-2"
          >
            {SSH_TYPES.map((type) => (
              <RadioGroupItem key={type} value={type} disabled={disabled}>
                {getSshTypeLabel(type)}
              </RadioGroupItem>
            ))}
          </RadioGroup>
          {sshType !== "NONE" && (
            <ResponsiveFormLayout>
              <fieldset className="flex flex-col gap-4 rounded-xs border border-control-border px-3 py-2">
                <legend className="px-1 textlabel">
                  {t("data-source.ssh-connection")}
                </legend>
                <FormField>
                  <FormLabel htmlFor="sshHost">
                    {t("data-source.ssh.host")}
                  </FormLabel>
                  <div className="flex flex-wrap items-center gap-2">
                    <Input
                      id="sshHost"
                      className="min-w-0 flex-1"
                      value={value.sshHost}
                      disabled={disabled}
                      onChange={(e) => onChange({ sshHost: e.target.value })}
                    />
                    <FormLabel htmlFor="sshPort">
                      {t("data-source.ssh.port")}
                    </FormLabel>
                    <Input
                      id="sshPort"
                      className="w-20 shrink-0"
                      value={value.sshPort}
                      disabled={disabled}
                      onChange={(e) => {
                        const val = e.target.value;
                        if (val === "" || /^\d+$/.test(val))
                          onChange({ sshPort: val });
                      }}
                    />
                  </div>
                </FormField>
                <FormField>
                  <FormLabel htmlFor="sshUser">
                    {t("data-source.ssh.user")}
                  </FormLabel>
                  <Input
                    id="sshUser"
                    value={value.sshUser}
                    disabled={disabled}
                    onChange={(e) => onChange({ sshUser: e.target.value })}
                  />
                </FormField>
                <FormField>
                  <FormLabel htmlFor="sshPassword">
                    {t("data-source.ssh.password")}
                  </FormLabel>
                  <Input
                    id="sshPassword"
                    placeholder={t("instance.password-write-only")}
                    value={value.sshPassword}
                    disabled={disabled}
                    onChange={(e) => onChange({ sshPassword: e.target.value })}
                  />
                </FormField>
                <FormField>
                  <FormLabel htmlFor="sshPrivateKey">
                    {t("data-source.ssh.ssh-key")} ({t("common.optional")})
                  </FormLabel>
                  <Textarea
                    id="sshPrivateKey"
                    className="w-full h-24 whitespace-pre-wrap resize-none"
                    value={value.sshPrivateKey}
                    disabled={disabled}
                    placeholder={t("common.sensitive-placeholder")}
                    onDrop={handleDrop}
                    onDragOver={handleDragOver}
                    onChange={(e) =>
                      onChange({ sshPrivateKey: e.target.value })
                    }
                  />
                </FormField>
              </fieldset>
            </ResponsiveFormLayout>
          )}
        </div>
      </FormField>
    </div>
  );
}
