// frontend/src/react/components/sql-editor/AccessGrantRequestDrawer.tsx
import { create } from "@bufbuild/protobuf";
import { DurationSchema, TimestampSchema } from "@bufbuild/protobuf/wkt";
import { Loader2 } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { accessGrantServiceClientConnect } from "@/connect";
import { MonacoEditor } from "@/react/components/monaco/MonacoEditor";
import { Alert } from "@/react/components/ui/alert";
import { Button } from "@/react/components/ui/button";
import { Checkbox } from "@/react/components/ui/checkbox";
import { Combobox } from "@/react/components/ui/combobox";
import { ExpirationPicker } from "@/react/components/ui/expiration-picker";
import {
  Sheet,
  SheetBody,
  SheetContent,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "@/react/components/ui/sheet";
import { Textarea } from "@/react/components/ui/textarea";
import { useVueState } from "@/react/hooks/useVueState";
import { useSQLEditorStore } from "@/react/stores/sqlEditor";
import { router } from "@/router";
import { PROJECT_V1_ROUTE_ISSUE_DETAIL } from "@/router/dashboard/projectV1";
import {
  pushNotification,
  useCurrentUserV1,
  useDatabaseV1Store,
  useSQLEditorStore as useSQLEditorPiniaStore,
  useSQLEditorTabStore,
} from "@/store";
import {
  AccessGrant_Status,
  AccessGrantSchema,
  CreateAccessGrantRequestSchema,
} from "@/types/proto-es/v1/access_grant_service_pb";
import {
  extractDatabaseResourceName,
  extractIssueUID,
  extractProjectResourceName,
} from "@/utils";

// Multi-select database combobox
function MultiDatabaseSelect({
  value,
  projectName,
  onChange,
}: {
  value: string[];
  projectName: string;
  onChange: (val: string[]) => void;
}) {
  const { t } = useTranslation();
  const [databases, setDatabases] = useState<
    { name: string; displayName: string }[]
  >([]);

  const databaseStore = useDatabaseV1Store();

  useEffect(() => {
    databaseStore
      .fetchDatabases({
        parent: projectName,
        filter: { query: "" },
        pageSize: 100,
        silent: true,
      })
      .then((result) => {
        setDatabases(
          result.databases.map((db) => {
            const { databaseName } = extractDatabaseResourceName(db.name);
            return { name: db.name, displayName: databaseName };
          })
        );
      })
      .catch(() => {
        /* ignore */
      });
  }, [databaseStore, projectName]);

  return (
    <Combobox
      multiple={true}
      value={value}
      onChange={onChange}
      placeholder={t("database.select")}
      noResultsText={t("common.no-data")}
      options={databases.map((db) => ({
        value: db.name,
        label: db.displayName,
      }))}
    />
  );
}

interface Props {
  readonly targets?: string[];
  readonly query?: string;
  readonly unmask?: boolean;
  readonly onClose: () => void;
}

interface AccessGrantRequestDrawerInnerProps extends Props {
  readonly stableProps: Props;
}

function AccessGrantRequestDrawerInner({
  stableProps,
  onClose,
}: AccessGrantRequestDrawerInnerProps) {
  const { t } = useTranslation();
  const currentUser = useCurrentUserV1();
  const editorStore = useSQLEditorPiniaStore();
  const tabStore = useSQLEditorTabStore();
  const setAsidePanelTab = useSQLEditorStore((s) => s.setAsidePanelTab);
  const setHighlightAccessGrantName = useSQLEditorStore(
    (s) => s.setHighlightAccessGrantName
  );

  const currentUserEmail = useVueState(() => currentUser.value.email);
  const project = useVueState(() => editorStore.project);

  const defaultTargets = useMemo(() => {
    if (stableProps.targets && stableProps.targets.length > 0) {
      return stableProps.targets;
    }
    const database = tabStore.currentTab?.connection?.database;
    return database ? [database] : [];
  }, [stableProps.targets, tabStore]);

  const [targets, setTargets] = useState<string[]>(defaultTargets);
  const [query, setQuery] = useState(stableProps.query ?? "");
  const [unmask, setUnmask] = useState(stableProps.unmask ?? false);
  const [duration, setDuration] = useState<number>(4);
  const [customExpireTime, setCustomExpireTime] = useState<string | undefined>(
    undefined
  );
  const [reason, setReason] = useState("");
  const [isRequesting, setIsRequesting] = useState(false);

  const autoCompleteContext = useMemo(() => {
    const db = targets[0];
    if (!db) return undefined;
    const { instance } = extractDatabaseResourceName(db);
    return { instance, database: db };
  }, [targets]);

  const durationOptions = useMemo(
    () => [
      { value: "1", label: t("sql-editor.duration-hour", { hours: 1 }) },
      { value: "4", label: t("sql-editor.duration-hours", { hours: 4 }) },
      { value: "24", label: t("sql-editor.duration-day", { days: 1 }) },
      { value: "168", label: t("sql-editor.duration-days", { days: 7 }) },
      { value: "-1", label: t("common.custom") },
    ],
    [t]
  );

  const today = new Date();
  const minDate = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-${String(today.getDate()).padStart(2, "0")}T00:00`;

  const allowSubmit = useMemo(() => {
    if (targets.length === 0) return false;
    if (!query.trim()) return false;
    if (!reason.trim()) return false;
    if (duration === -1 && !customExpireTime) return false;
    return true;
  }, [targets, query, reason, duration, customExpireTime]);

  const handleSubmit = async () => {
    if (isRequesting || !allowSubmit) return;
    setIsRequesting(true);
    try {
      const expiration =
        duration === -1 && customExpireTime
          ? (() => {
              const ms = new Date(customExpireTime).getTime();
              return {
                case: "expireTime" as const,
                value: create(TimestampSchema, {
                  seconds: BigInt(Math.floor(ms / 1000)),
                  nanos: (ms % 1000) * 1000000,
                }),
              };
            })()
          : {
              case: "ttl" as const,
              value: create(DurationSchema, {
                seconds: BigInt(duration * 3600),
              }),
            };

      const accessGrant = create(AccessGrantSchema, {
        creator: `users/${currentUserEmail}`,
        targets,
        query,
        unmask,
        reason,
        expiration,
      });

      const response = await accessGrantServiceClientConnect.createAccessGrant(
        create(CreateAccessGrantRequestSchema, {
          parent: project as string,
          accessGrant,
        })
      );

      pushNotification({
        module: "bytebase",
        style: "SUCCESS",
        title: t("common.created"),
      });

      if (response.status === AccessGrant_Status.PENDING && response.issue) {
        const route = router.resolve({
          name: PROJECT_V1_ROUTE_ISSUE_DETAIL,
          params: {
            projectId: extractProjectResourceName(response.issue),
            issueId: extractIssueUID(response.issue),
          },
        });
        window.open(route.fullPath, "_blank");
      } else {
        setAsidePanelTab("ACCESS");
        setHighlightAccessGrantName(response.name);
      }
      onClose();
    } finally {
      setIsRequesting(false);
    }
  };

  return (
    <>
      <SheetHeader>
        <SheetTitle>{t("sql-editor.request-data-access")}</SheetTitle>
      </SheetHeader>
      <SheetBody>
        <div className="flex flex-col gap-y-6">
          {/* Databases */}
          <div className="flex flex-col gap-y-2">
            <div className="text-sm font-medium text-control">
              {t("common.databases")}
              <span className="text-error ml-0.5">*</span>
            </div>
            <MultiDatabaseSelect
              value={targets}
              projectName={project as string}
              onChange={setTargets}
            />
          </div>

          {/* Statement */}
          <div className="flex flex-col gap-y-2">
            <div className="text-sm font-medium text-control">
              {t("common.statement")}
              <span className="text-error ml-0.5">*</span>
            </div>
            <Alert
              variant="info"
              description={t("sql-editor.only-select-allowed")}
            />
            <MonacoEditor
              className="border rounded-[3px] h-40"
              content={query}
              language="sql"
              autoCompleteContext={autoCompleteContext}
              onChange={setQuery}
            />
          </div>

          {/* Unmask */}
          <div className="flex flex-col gap-y-2">
            <div className="text-sm font-medium text-control">
              {t("sql-editor.grant-type-unmask")}
            </div>
            <label className="flex items-center gap-2 cursor-pointer">
              <Checkbox
                checked={unmask}
                onCheckedChange={(checked) => setUnmask(checked)}
              />
              <span>{t("sql-editor.access-type-unmask")}</span>
            </label>
          </div>

          {/* Expiration */}
          <div className="flex flex-col gap-y-2">
            <div className="text-sm font-medium text-control">
              {t("common.expiration")}
              <span className="text-error ml-0.5">*</span>
            </div>
            <Combobox
              value={String(duration)}
              onChange={(val) => setDuration(Number(val))}
              options={durationOptions}
            />
            {duration === -1 && (
              <ExpirationPicker
                value={customExpireTime}
                onChange={setCustomExpireTime}
                minDate={minDate}
              />
            )}
          </div>

          {/* Reason */}
          <div className="flex flex-col gap-y-2">
            <div className="text-sm font-medium text-control">
              {t("common.reason")}
              <span className="text-error ml-0.5">*</span>
            </div>
            <Textarea
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              rows={3}
              placeholder=""
            />
          </div>
        </div>
      </SheetBody>
      <SheetFooter>
        <Button variant="outline" onClick={onClose} disabled={isRequesting}>
          {t("common.cancel")}
        </Button>
        <Button
          variant="default"
          disabled={!allowSubmit || isRequesting}
          onClick={() => void handleSubmit()}
          data-submit-btn
        >
          {isRequesting && <Loader2 className="size-4 mr-1 animate-spin" />}
          {t("common.submit")}
        </Button>
      </SheetFooter>
    </>
  );
}

export function AccessGrantRequestDrawer({
  targets,
  query,
  unmask,
  onClose,
}: Props) {
  const propsRef = useRef({ targets, query, unmask, onClose });
  // Freeze props while drawer is open so inner form stays stable during close animation
  const stableProps = propsRef.current;

  return (
    <Sheet open={true} onOpenChange={(next) => !next && onClose()}>
      <SheetContent width="standard">
        <AccessGrantRequestDrawerInner
          key={`${targets?.join(",")}-${query}-${unmask}`}
          stableProps={stableProps}
          onClose={onClose}
        />
      </SheetContent>
    </Sheet>
  );
}

// frontend/src/views/sql-editor/AsidePanel/AccessPane/AccessGrantRequestDrawer.vue
<template>
  <Drawer
    :show="true"
    width="auto"
    @update:show="(show: boolean) => !show && $emit('close')"
  >
    <DrawerContent
      :title="$t('sql-editor.request-data-access')"
      :closable="true"
      class="w-[40rem] max-w-[100vw]"
    >
      <div class="flex flex-col gap-y-6">
        <div class="flex flex-col gap-y-2">
          <div class="text-sm font-medium text-control">
            {{ $t("common.databases") }}
            <RequiredStar class="ml-0.5" />
          </div>
          <DatabaseSelect
            :value="form.targets"
            :project-name="editorStore.project"
            :multiple="true"
            @update:value="
              (val) => (form.targets = (val as string[] | undefined) ?? [])
            "
          />
        </div>

        <div class="flex flex-col gap-y-2">
          <div class="text-sm font-medium text-control">
            {{ $t("common.statement") }}
            <RequiredStar class="ml-0.5" />
          </div>
          <BBAttention type="info">
            {{ $t("sql-editor.only-select-allowed") }}
          </BBAttention>
          <MonacoEditor
            class="border rounded-[3px] h-40"
            :content="form.query"
            language="sql"
            :auto-complete-context="autoCompleteContext"
            @update:content="form.query = $event"
          />
        </div>

        <div class="flex flex-col gap-y-2">
          <div class="text-sm font-medium text-control">
            {{ $t("sql-editor.grant-type-unmask") }}
          </div>
          <div class="flex flex-col gap-y-1">
            <NCheckbox v-model:checked="form.unmask">
              {{ $t("sql-editor.access-type-unmask") }}
            </NCheckbox>
          </div>
        </div>

        <div class="flex flex-col gap-y-2">
          <div class="text-sm font-medium text-control">
            {{ $t("common.expiration") }}
            <RequiredStar class="ml-0.5" />
          </div>
          <NSelect
            v-model:value="form.duration"
            :options="durationOptions"
          />
          <NDatePicker
            v-if="form.duration === -1"
            v-model:value="form.customExpireTime"
            type="datetime"
            :is-date-disabled="isDateDisabled"
            clearable
            :actions="null"
            :update-value-on-close="true"
          />
        </div>

        <div class="flex flex-col gap-y-2">
          <div class="text-sm font-medium text-control">
            {{ $t("common.reason") }}
            <RequiredStar class="ml-0.5" />
          </div>
          <NInput
            v-model:value="form.reason"
            type="textarea"
            :rows="3"
            :placeholder="$t('common.optional')"
          />
        </div>
      </div>

      <template #footer>
        <div class="flex items-center justify-end gap-x-2">
          <NButton @click="$emit('close')">
            {{ $t("common.cancel") }}
          </NButton>
          <NButton
            type="primary"
            :disabled="!allowSubmit"
            :loading="isRequesting"
            @click="handleSubmit"
          >
            {{ $t("common.submit") }}
          </NButton>
        </div>
      </template>
    </DrawerContent>
  </Drawer>
</template>

<script lang="ts" setup>
import { create } from "@bufbuild/protobuf";
import { DurationSchema, TimestampSchema } from "@bufbuild/protobuf/wkt";
import dayjs from "dayjs";
import { NButton, NCheckbox, NDatePicker, NInput, NSelect } from "naive-ui";
import { computed, reactive, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { BBAttention } from "@/bbkit";
import { MonacoEditor } from "@/components/MonacoEditor";
import RequiredStar from "@/components/RequiredStar.vue";
import { DatabaseSelect, Drawer, DrawerContent } from "@/components/v2";
import { accessGrantServiceClientConnect } from "@/connect";
import { PROJECT_V1_ROUTE_ISSUE_DETAIL } from "@/router/dashboard/projectV1";
import {
  pushNotification,
  useCurrentUserV1,
  useSQLEditorStore,
  useSQLEditorTabStore,
} from "@/store";
import {
  AccessGrant_Status,
  AccessGrantSchema,
  CreateAccessGrantRequestSchema,
} from "@/types/proto-es/v1/access_grant_service_pb";
import {
  extractDatabaseResourceName,
  extractIssueUID,
  extractProjectResourceName,
} from "@/utils";
import { useSQLEditorContext } from "../../context";

const props = withDefaults(
  defineProps<{
    // Pre-selected database resource names.
    // Format: "instances/{instance}/databases/{database}"
    targets?: string[];
    // Pre-filled SQL statement.
    query?: string;
    // Pre-check the "Unmask" access type checkbox.
    unmask?: boolean;
  }>(),
  {
    targets: undefined,
    query: "",
    unmask: false,
  }
);

const emit = defineEmits<{
  (event: "close"): void;
}>();

const { t } = useI18n();
const router = useRouter();
const currentUser = useCurrentUserV1();
const editorStore = useSQLEditorStore();
const tabStore = useSQLEditorTabStore();
const isRequesting = ref(false);
const { asidePanelTab, highlightAccessGrantName } = useSQLEditorContext();

// Default to the currently connected database if no targets provided.
const defaultTargets = computed(() => {
  if (props.targets) return props.targets;
  const database = tabStore.currentTab?.connection?.database;
  return database ? [database] : [];
});

const form = reactive({
  targets: [...defaultTargets.value],
  query: props.query,
  unmask: props.unmask,
  duration: 4,
  customExpireTime: undefined as number | undefined,
  reason: "",
});

const autoCompleteContext = computed(() => {
  const db = form.targets[0];
  if (!db) return undefined;
  const { instance } = extractDatabaseResourceName(db);
  return { instance, database: db };
});

const durationOptions = computed(() => [
  { label: t("sql-editor.duration-hours", { hours: 1 }), value: 1 },
  { label: t("sql-editor.duration-hours", { hours: 4 }), value: 4 },
  { label: t("sql-editor.duration-day", { days: 1 }), value: 24 },
  { label: t("sql-editor.duration-days", { days: 7 }), value: 168 },
  { label: t("common.custom"), value: -1 },
]);

const isDateDisabled = (date: number) => {
  if (date < dayjs().startOf("day").valueOf()) {
    return true;
  }
  return false;
};

const allowSubmit = computed(() => {
  if (form.targets.length === 0) return false;
  if (!form.query.trim()) return false;
  if (!form.reason) return false;
  if (form.duration === -1 && !form.customExpireTime) return false;
  return true;
});

const handleSubmit = async () => {
  if (isRequesting.value) return;
  isRequesting.value = true;
  try {
    const accessGrant = create(AccessGrantSchema, {
      creator: `users/${currentUser.value.email}`,
      targets: form.targets,
      query: form.query,
      unmask: form.unmask,
      reason: form.reason,
      expiration:
        form.duration === -1
          ? {
              case: "expireTime" as const,
              value: create(TimestampSchema, {
                seconds: BigInt(Math.floor(form.customExpireTime! / 1000)),
                nanos: (form.customExpireTime! % 1000) * 1000000,
              }),
            }
          : {
              case: "ttl" as const,
              value: create(DurationSchema, {
                seconds: BigInt(form.duration * 3600),
              }),
            },
    });

    const response = await accessGrantServiceClientConnect.createAccessGrant(
      create(CreateAccessGrantRequestSchema, {
        parent: editorStore.project,
        accessGrant,
      })
    );

    pushNotification({
      module: "bytebase",
      style: "SUCCESS",
      title: t("common.created"),
    });

    if (response.status === AccessGrant_Status.PENDING && response.issue) {
      const route = router.resolve({
        name: PROJECT_V1_ROUTE_ISSUE_DETAIL,
        params: {
          projectId: extractProjectResourceName(response.issue),
          issueId: extractIssueUID(response.issue),
        },
      });
      window.open(route.fullPath, "_blank");
    } else {
      asidePanelTab.value = "ACCESS";
      highlightAccessGrantName.value = response.name;
    }
    emit("close");
  } finally {
    isRequesting.value = false;
  }
};
</script>
