// frontend/src/modules/sql-editor/components/ConnectionPane/TreeNode/InstanceNode.tsx
import { EngineIcon } from "@/components/EngineIcon";
import { HighlightLabelText } from "@/components/HighlightLabelText";
import type { SQLEditorTreeNode } from "@/types";
import { instanceV1Name } from "@/utils";

type Props = {
  readonly node: SQLEditorTreeNode;
  readonly keyword: string;
};

export function InstanceNode({ node, keyword }: Props) {
  const target = (node as SQLEditorTreeNode<"instance">).meta.target;
  const instance = {
    ...target,
    $typeName: "bytebase.v1.InstanceResource" as const,
  };
  return (
    <div className="flex items-center max-w-full overflow-hidden gap-x-1">
      <span className="inline-flex items-center gap-x-1">
        <EngineIcon engine={instance.engine} className="size-4" />
        <span className="truncate">
          <HighlightLabelText
            text={instanceV1Name(instance)}
            keyword={keyword}
          />
        </span>
      </span>
    </div>
  );
}

// frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/InstanceNode.vue
<template>
  <div class="flex items-center max-w-full overflow-hidden gap-x-1">
    <EnvironmentV1Name
      v-if="!hasEnvironmentContext"
      :environment="environment"
      :link="false"
      class="text-control-light"
    />
    <InstanceV1Name :link="false" :instance="instance" :keyword="keyword" />
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { EnvironmentV1Name, InstanceV1Name } from "@/components/v2";
import { useEnvironmentV1Store } from "@/store";
import type { SQLEditorTreeNode as TreeNode } from "@/types";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const instance = computed(() => {
  const target = (props.node as TreeNode<"instance">).meta.target;
  // Add $typeName to match InstanceResource type expected by InstanceV1Name
  return {
    ...target,
    $typeName: "bytebase.v1.InstanceResource" as const,
  };
});

const environment = computed(() =>
  useEnvironmentV1Store().getEnvironmentByName(instance.value.environment)
);

const hasEnvironmentContext = computed(() => {
  return true;
});
</script>
