// frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
<template>
  <div
    class="gap-y-1 h-full flex flex-col items-stretch relative overflow-hidden"
  >
    <div class="px-1 flex flex-row gap-1">
      <div class="flex-1 overflow-hidden">
        <SearchBox
          ref="searchBoxRef"
          v-model:value="searchPattern"
          :disabled="!currentTab"
          size="small"
          style="width: 100%; max-width: 100%"
        />
      </div>
      <div class="shrink-0 flex items-center">
        <SyncSchemaButton size="small" />
      </div>
    </div>

    <div
      ref="treeContainerElRef"
      class="schema-tree flex-1 px-1 pb-1 text-sm overflow-hidden select-none"
      :data-height="treeContainerHeight"
    >
      <MaskSpinner v-if="isFetchingMetadata" />

      <!-- Adaptive UI: Use tree for small DBs, flat list for large DBs -->
      <template v-else-if="metadata">
        <!-- For large databases (>1000 tables): Use flat list -->
        <FlatTableList
          v-if="totalTableCount > 1000"
          :metadata="metadata"
          :search="searchPattern"
          :database="database.name"
          @select="handleFlatListSelect"
          @select-all="handleFlatListSelectAll"
          @contextmenu="handleFlatListContextMenu"
        />

        <!-- For small databases: Use tree view -->
        <NTree
          v-else-if="tree"
          ref="treeRef"
          v-model:expanded-keys="expandedKeys"
          :selected-keys="selectedKeys"
          :block-line="true"
          :data="tree"
          :show-irrelevant-nodes="false"
          :pattern="mounted ? debouncedSearchPattern : ''"
          :virtual-scroll="true"
          :node-props="nodeProps"
          :theme-overrides="{ nodeHeight: '21px' }"
          :render-label="renderLabel"
        />
        <NEmpty v-else class="mt-16" />
      </template>
      <NEmpty v-else class="mt-16" />
    </div>

    <NDropdown
      v-if="!isFetchingMetadata"
      placement="bottom-start"
      trigger="manual"
      :x="dropdownPosition.x"
      :y="dropdownPosition.y"
      :options="dropdownOptions"
      :show="showDropdown"
      :on-clickoutside="handleDropdownClickoutside"
      @select="handleDropdownSelect"
    />

    <MaskSpinner v-if="isFetchingMetadata" class="bg-white/75!" />

    <BBModal :show="!!schemaViewer" @close="schemaViewer = undefined">
      <template v-if="schemaViewer" #title>
        <RichDatabaseName :database="database" />
      </template>
      <TableSchemaViewer
        v-if="schemaViewer"
        style="width: calc(100vw - 12rem); height: calc(100vh - 12rem)"
        v-bind="schemaViewer"
        :database="database"
      />
    </BBModal>

    <HoverPanel :offset-x="8" :offset-y="0" :margin="4" />
  </div>
</template>

<script setup lang="ts">
import {
  computedAsync,
  refDebounced,
  useElementSize,
  useEventListener,
  useMounted,
} from "@vueuse/core";
import { head, uniq, without } from "lodash-es";
import {
  NDropdown,
  NEmpty,
  NTree,
  type TreeInst,
  type TreeOption,
} from "naive-ui";
import { storeToRefs } from "pinia";
import { computed, h, nextTick, ref, watch, watchEffect } from "vue";
import { BBModal } from "@/bbkit";
import MaskSpinner from "@/components/misc/MaskSpinner.vue";
import TableSchemaViewer from "@/components/TableSchemaViewer.vue";
import { RichDatabaseName, SearchBox } from "@/components/v2";
import { useEmitteryEventListener } from "@/composables/useEmitteryEventListener";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
  useSQLEditorTabStore,
} from "@/store";
import { isValidDatabaseName } from "@/types";
import type { TableMetadata } from "@/types/proto-es/v1/database_service_pb";
import {
  allEqual,
  extractDatabaseResourceName,
  findAncestor,
  isDescendantOf,
} from "@/utils";
import { useSQLEditorContext } from "../../context";
import { useCurrentTabViewStateContext } from "../../EditorPanel";
import { useActions, useDropdown } from "./actions";
import { useClickEvents } from "./click";
import FlatTableList from "./FlatTableList.vue";
import HoverPanel, { provideHoverStateContext } from "./HoverPanel";
import SyncSchemaButton from "./SyncSchemaButton.vue";
import { Label } from "./TreeNode";
import {
  buildDatabaseSchemaTree,
  ExpandableNodeTypes,
  type NodeTarget,
  type TreeNode,
} from "./tree";

const mounted = useMounted();
const searchBoxRef = ref<InstanceType<typeof SearchBox>>();
const treeRef = ref<TreeInst>();
const treeContainerElRef = ref<HTMLElement>();
const { height: treeContainerHeight } = useElementSize(
  treeContainerElRef,
  undefined,
  {
    box: "content-box",
  }
);

const { viewState: panelViewState } = useCurrentTabViewStateContext();
const { schemaViewer } = useSQLEditorContext();
const {
  show: showDropdown,
  context: dropdownContext,
  position: dropdownPosition,
  options: dropdownOptions,
  handleSelect: handleDropdownSelect,
  handleClickoutside: handleDropdownClickoutside,
} = useDropdown();
const { selectAllFromTableOrView } = useActions();
const { currentTab } = storeToRefs(useSQLEditorTabStore());
const { database } = useConnectionOfCurrentSQLEditorTab();

// Simple search pattern that resets when tab changes
const searchPattern = ref("");
const debouncedSearchPattern = refDebounced(searchPattern, 200);

// Reset search when tab changes
watch(
  () => currentTab.value?.id,
  () => {
    searchPattern.value = "";
  }
);
const isFetchingMetadata = ref(false);
const totalTableCount = ref(0);
const metadata = computedAsync(
  async () => {
    const db = database.value;
    if (!isValidDatabaseName(db.name)) return null;
    const metadata = await useDBSchemaV1Store().getOrFetchDatabaseMetadata({
      database: db.name,
    });
    totalTableCount.value = metadata.schemas.reduce(
      (sum, schema) => sum + (schema.tables?.length || 0),
      0
    );
    return metadata;
  },
  /* default */ null,
  {
    evaluating: isFetchingMetadata,
  }
);
const { events: nodeClickEvents, handleClick: handleNodeClick } =
  useClickEvents();
const {
  state: hoverState,
  position: hoverPosition,
  update: updateHoverState,
} = provideHoverStateContext();
const tree = ref<TreeNode[]>();

const expandedKeys = computed({
  get() {
    const treeState = currentTab.value?.treeState;
    if (!treeState) return [];
    if (treeState.database !== database.value.name) return [];
    return treeState.keys;
  },
  set(keys) {
    if (!currentTab.value) return;
    const treeState = currentTab.value.treeState;
    if (treeState.database !== database.value.name) return;
    treeState.keys = keys;
  },
});

const upsertExpandedKeys = (keys: string[]) => {
  const curr = expandedKeys.value;
  if (!curr) return;
  expandedKeys.value = uniq([...curr, ...keys]);
};
const removeExpandedKeys = (keys: string[]) => {
  const curr = expandedKeys.value;
  if (!curr) return;
  expandedKeys.value = without(curr, ...keys);
};

const defaultExpandedKeys = () => {
  if (!tree.value) return [];
  const keys: string[] = [];
  const collect = (node: TreeNode) => {
    keys.push(node.key);
    node.children?.forEach((child) => walk(child as TreeNode));
  };
  const walk = (node: TreeNode) => {
    const { type } = node.meta;
    if (type === "database" || type === "schema") {
      collect(node);
    } else if (type === "expandable-text") {
      const { mockType } = node.meta.target as NodeTarget<"expandable-text">;
      if (mockType === "table" || mockType === "view") {
        collect(node);
      }
    }
  };
  walk(tree.value[0]);
  return keys;
};
const nodeProps = ({ option }: { option: TreeOption }) => {
  const node = option as any as TreeNode;
  return {
    onclick(e: MouseEvent) {
      if (node.disabled) return;

      if (isDescendantOf(e.target as Element, ".n-tree-node-content")) {
        handleNodeClick(node);
      }
    },
    oncontextmenu(e: MouseEvent) {
      e.preventDefault();
      showDropdown.value = false;
      if (node && node.key) {
        dropdownContext.value = node;
      }

      nextTick().then(() => {
        showDropdown.value = true;
        dropdownPosition.value.x = e.clientX;
        dropdownPosition.value.y = e.clientY;
      });
    },

    onmouseenter(e: MouseEvent) {
      const { type } = node.meta;
      if (
        type === "table" ||
        type === "external-table" ||
        type === "column" ||
        type === "view" ||
        type === "partition-table"
      ) {
        const target = node.meta.target as NodeTarget<
          "table" | "external-table" | "column" | "view"
        >;
        // Use a small delay even when transitioning between nodes
        // to prevent excessive re-renders when moving quickly
        const delay = hoverState.value ? 150 : undefined;
        updateHoverState(target, "before", delay);

        nextTick().then(() => {
          // Find the node element and put the database panel to the bottom
          // of the node, near the cursor
          const wrapper = findAncestor(e.target as HTMLElement, ".n-tree-node");
          if (!wrapper) {
            // Clear hover state if we can't find the wrapper
            updateHoverState(undefined, "after", 150);
            return;
          }
          const bounding = wrapper.getBoundingClientRect();
          hoverPosition.value.x = e.clientX;
          hoverPosition.value.y = bounding.bottom;
        });
      }
    },
    onmouseleave() {
      updateHoverState(undefined, "after");
    },
    // attrs below for trouble-shooting
    "data-node-meta-type": node.meta.type,
    "data-node-key": node.key,
  };
};

// dynamic render the highlight keywords
const renderLabel = ({ option }: { option: TreeOption }) => {
  const node = option as any as TreeNode;
  const keyword = searchPattern.value;
  return h(Label, { node, keyword });
};

const selectedKeys = computed(() => {
  const db = database.value;
  if (!isValidDatabaseName(db.name)) return [];
  const keys: string[] = [];
  const tab = currentTab.value;
  if (tab && tab.connection.schema !== undefined) {
    keys.push(`${db.name}/schemas/${tab.connection.schema}`);
  }
  if (!panelViewState.value || panelViewState.value.view === "CODE") {
    return keys;
  }
  const {
    schema,
    detail: {
      table,
      column,
      view,
      procedure,
      func,
      sequence,
      trigger,
      externalTable,
      package: pack,
      partition,
      index,
      foreignKey,
    },
  } = panelViewState.value;

  const parts = [db.name, `schemas/${schema}`];
  if (table) {
    parts.push(`tables/${table}`);
    if (column) {
      parts.push(`columns/${column}`);
    } else if (index) {
      parts.push(`indexes/${index}`);
    } else if (partition) {
      parts.push(`partitionTables/${partition}`);
    } else if (trigger) {
      parts.push(`triggers/${trigger}`);
    } else if (foreignKey) {
      parts.push(`foreignKeys/${foreignKey}`);
    }
  } else if (view) {
    parts.push(`views/${view}`);
    if (column) {
      parts.push(`columns/${column}`);
    }
  } else if (procedure) {
    parts.push(`procedures/${procedure}`);
  } else if (func) {
    parts.push(`functions/${func}`);
  } else if (sequence) {
    parts.push(`sequences/${sequence}`);
  } else if (externalTable) {
    parts.push(`externalTables/${externalTable}`);
  } else if (pack) {
    parts.push(`packages/${pack}`);
  }

  return [parts.join("/")];
});
watchEffect(() => {
  const key = head(selectedKeys.value);
  if (key) {
    treeRef.value?.scrollTo({ key });
  }
});

// bottom-up recursively
const expandNode = (node: TreeNode) => {
  const keysToExpand: string[] = [];
  if (ExpandableNodeTypes.includes(node.meta.type)) {
    keysToExpand.push(node.key);
  }
  upsertExpandedKeys(keysToExpand);
};
const collapseNode = (node: TreeNode) => {
  removeExpandedKeys([node.key]);
};
const toggleNode = (node: TreeNode) => {
  if (expandedKeys.value.includes(node.key)) {
    collapseNode(node);
  } else {
    expandNode(node);
  }
};

const singleClick = (node: TreeNode) => {
  toggleNode(node);
  if (node.meta.type === "schema") {
    const tab = currentTab.value;
    if (tab) {
      tab.connection.schema = (node.meta.target as NodeTarget<"schema">).schema;
      return;
    }
  }
};
useEmitteryEventListener(nodeClickEvents, "single-click", ({ node }) => {
  singleClick(node);
});
useEmitteryEventListener(nodeClickEvents, "double-click", ({ node }) => {
  if (node.meta.type === "table" || node.meta.type === "view") {
    selectAllFromTableOrView(node);
  } else if (
    node.meta.type === "expandable-text" ||
    node.meta.type === "schema"
  ) {
    toggleNode(node);
  } else {
    singleClick(node);
  }
});

// Watch only the properties we actually need, not the entire tab object
// This prevents re-renders on every keystroke in the editor
watch(
  [
    isFetchingMetadata,
    metadata,
    () => currentTab.value?.id,
    () => currentTab.value?.connection.database,
    () => currentTab.value?.treeState.database,
  ],
  ([isFetchingMetadata, metadata, _, connectionDb, treeStateDb]) => {
    const cleanup = () => {
      tree.value = undefined;
    };

    const tab = currentTab.value;
    if (isFetchingMetadata || !metadata || !tab) {
      return cleanup();
    }
    if (
      !allEqual(
        extractDatabaseResourceName(metadata.name).database,
        connectionDb,
        database.value.name
      )
    ) {
      return cleanup();
    }

    if (totalTableCount.value <= 1000) {
      requestAnimationFrame(() => {
        tree.value = buildDatabaseSchemaTree(database.value, metadata);
        if (treeStateDb !== connectionDb && connectionDb) {
          // Set initial tree state for the tab when it firstly opens or its
          // connection has been changed
          tab.treeState.database = connectionDb;
          tab.treeState.keys = defaultExpandedKeys();
        }
      });
    }
  },
  {
    immediate: true,
  }
);

// Handlers for flat list events
const handleFlatListSelect = (table: any) => {
  // Update connection schema if needed
  const tab = currentTab.value;
  if (tab && table.schema) {
    tab.connection.schema = table.schema;
  }
};

const handleFlatListSelectAll = (table: {
  key: string;
  schema: string;
  metadata: TableMetadata;
}) => {
  // Execute SELECT * for the table
  if (table.metadata) {
    selectAllFromTableOrView({
      key: table.key,
      meta: {
        type: "table",
        target: {
          database: database.value.name,
          schema: table.schema,
          table: table.metadata.name,
        },
      },
    });
  }
};

const handleFlatListContextMenu = (
  event: MouseEvent,
  table: {
    key: string;
    schema: string;
    metadata: TableMetadata;
  }
) => {
  dropdownContext.value = {
    key: table.key,
    meta: {
      type: "table",
      target: {
        database: database.value.name,
        schema: table.schema,
        table: table.metadata.name,
      },
    },
  };

  nextTick().then(() => {
    showDropdown.value = true;
    dropdownPosition.value.x = event.clientX;
    dropdownPosition.value.y = event.clientY;
  });
};

useEventListener(treeContainerElRef, "keydown", () => {
  searchBoxRef.value?.inputRef?.focus();
});
</script>

<style lang="postcss" scoped>
.schema-tree :deep(.n-tree .v-vl) {
  --n-node-content-height: 21px !important;
}
.schema-tree :deep(.n-tree-node-content) {
  padding-left: 0 !important;
  padding-right: 0 !important;
  font-size: 0.875rem;
  line-height: 1.25rem;
}
.schema-tree :deep(.n-tree-node-wrapper) {
  padding: 0;
}
.schema-tree :deep(.n-tree-node-indent) {
  width: 10px;
  height: 10px;
}
.schema-tree :deep(.n-tree-node-switcher) {
  width: 20px !important;
  height: 20px !important;
  align-self: center;
}
.schema-tree :deep(.n-tree-node-switcher--hide) {
  width: 0 !important;
}
.schema-tree :deep(.n-tree-node-content__prefix) {
  flex-shrink: 0;
  margin-right: 0.25rem !important;
}
.schema-tree.project
  :deep(.n-tree-node[data-node-type="project"] .n-tree-node-content__prefix) {
  display: none;
}
.schema-tree :deep(.n-tree-node-content__text) {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin-right: 0.25rem;
}
.schema-tree :deep(.n-tree-node--pending) {
  background-color: transparent !important;
}
.schema-tree :deep(.n-tree-node--pending:hover) {
  background-color: var(--n-node-color-hover) !important;
}
.schema-tree :deep(.n-tree-node--selected),
.schema-tree :deep(.n-tree-node--selected:hover) {
  background-color: var(--n-node-color-active) !important;
  font-weight: 500;
}
</style>

// frontend/src/react/components/sql-editor/SchemaPane/SchemaPane.tsx
import { uniq, without } from "lodash-es";
import { ChevronDown, ChevronRight, Loader2 } from "lucide-react";
import {
  type CSSProperties,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { useTranslation } from "react-i18next";
import { EngineIconPath } from "@/components/InstanceForm/constants";
import { TableSchemaViewer } from "@/react/components/TableSchemaViewer";
import {
  Dialog,
  DialogContent,
  DialogTitle,
} from "@/react/components/ui/dialog";
import { Input } from "@/react/components/ui/input";
import { Tree, type TreeDataNode } from "@/react/components/ui/tree";
import { countVisibleRows } from "@/react/components/ui/tree-utils";
import { useVueState } from "@/react/hooks/useVueState";
import { cn } from "@/react/lib/utils";
import {
  useConnectionOfCurrentSQLEditorTab,
  useDBSchemaV1Store,
  useSQLEditorTabStore,
} from "@/store";
import { isValidDatabaseName } from "@/types";
import type {
  DatabaseMetadata,
  GetSchemaStringRequest_ObjectType,
  TableMetadata,
} from "@/types/proto-es/v1/database_service_pb";
import {
  extractDatabaseResourceName,
  getInstanceResource,
  instanceV1Name,
} from "@/utils";
import { findAncestor } from "@/utils/dom";
import { useSchemaPaneActions } from "./actions";
import { useAvailableActions } from "./availableActions";
import { useClickEvents } from "./click";
import { FlatTableList } from "./FlatTableList";
import { HoverPanel } from "./HoverPanel/HoverPanel";
import { HoverStateProvider, useHoverState } from "./hover-state";
import {
  SchemaContextMenu,
  type SchemaContextMenuHandle,
} from "./SchemaContextMenu";
import { SyncSchemaButton } from "./SyncSchemaButton";
import {
  buildDatabaseSchemaTree,
  ExpandableNodeTypes,
  type NodeTarget,
  type TreeNode as SchemaTreeNode,
} from "./schemaTree";
import { Label } from "./TreeNode/Label";

const ROW_HEIGHT = 21;
const TREE_FALLBACK_HEIGHT = 360;
const FLAT_TABLE_THRESHOLD = 1000;
const SEARCH_DEBOUNCE_MS = 200;

/**
 * React port of `frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue`.
 *
 * Wires together every Phase 1–4 artifact:
 *   - schemaTree.ts builder              (Phase 1)
 *   - useDelayedValue / useHoverState    (Phase 1)
 *   - leaf TreeNode/*.tsx                (Phase 1)
 *   - heavy nodes + Label dispatcher     (Phase 2)
 *   - HoverPanel + *Info cards           (Phase 3)
 *   - useSchemaPaneActions / ContextMenu (Phase 4a/4b)
 *   - SyncSchemaButton                   (Phase 4c)
 *   - FlatTableList                      (Phase 4d)
 *
 * The schema-viewer modal lives in the Vue parent (`AsidePanel.vue`)
 * since it embeds Vue-only `BBModal` + `TableSchemaViewer`. The menu's
 * "View schema text" action emits a `show-schema-viewer` event on
 * `sqlEditorEvents` which the Vue context provider listens for and
 * mirrors onto its inject ref.
 */
export function SchemaPane() {
  return (
    <HoverStateProvider>
      <SchemaPaneInner />
      <HoverPanel offsetX={8} offsetY={0} margin={4} />
    </HoverStateProvider>
  );
}

function SchemaPaneInner() {
  const { t } = useTranslation();
  const tabStore = useSQLEditorTabStore();
  const dbSchemaStore = useDBSchemaV1Store();
  const connection = useConnectionOfCurrentSQLEditorTab();
  const hoverState = useHoverState();

  const database = useVueState(() => connection.database.value);
  const currentTabId = useVueState(() => tabStore.currentTab?.id);
  // `connection` is mutated in place via `Object.assign`-style updates,
  // so depth is required to catch nested-field changes (schema, database,
  // instance) without a fresh reference.
  const tabConnection = useVueState(() => tabStore.currentTab?.connection, {
    deep: true,
  });
  const tabConnectionSchema = tabConnection?.schema;
  // tab.viewState shapes the selectedKeys highlight when the editor
  // panel is on a non-CODE view (e.g. TABLES drill-down).
  const panelViewState = useVueState(() => tabStore.currentTab?.viewState, {
    deep: true,
  });

  const [searchPattern, setSearchPattern] = useState("");
  const debouncedSearch = useDebouncedValue(searchPattern, SEARCH_DEBOUNCE_MS);

  // Reset the search box on every tab switch — matches Vue's
  // `watch(() => currentTab.value?.id, ...)`.
  useEffect(() => {
    setSearchPattern("");
  }, [currentTabId]);

  const [metadata, setMetadata] = useState<DatabaseMetadata | null>(null);
  const [isFetching, setIsFetching] = useState(false);

  // Fetch metadata on database change. The store de-duplicates so this
  // is safe to fire on every render where the name flips.
  useEffect(() => {
    if (!isValidDatabaseName(database.name)) {
      setMetadata(null);
      setIsFetching(false);
      return;
    }
    setIsFetching(true);
    let cancelled = false;
    void dbSchemaStore
      .getOrFetchDatabaseMetadata({ database: database.name })
      .then((md) => {
        if (cancelled) return;
        setMetadata(md);
      })
      .finally(() => {
        if (cancelled) return;
        setIsFetching(false);
      });
    return () => {
      cancelled = true;
    };
  }, [database.name, dbSchemaStore]);

  const totalTableCount = useMemo(() => {
    if (!metadata) return 0;
    return metadata.schemas.reduce(
      (sum, schema) => sum + (schema.tables?.length ?? 0),
      0
    );
  }, [metadata]);

  // Build the tree via requestAnimationFrame so the heavy walk doesn't
  // block the metadata-fetch teardown's transition. Mirrors Vue's
  // `requestAnimationFrame(() => { tree.value = buildDatabaseSchemaTree(...) })`.
  const [tree, setTree] = useState<SchemaTreeNode[] | undefined>(undefined);
  useEffect(() => {
    if (isFetching || !metadata) {
      setTree(undefined);
      return;
    }
    if (totalTableCount > FLAT_TABLE_THRESHOLD) {
      setTree(undefined);
      return;
    }
    let raf = 0;
    raf = requestAnimationFrame(() => {
      const built = buildDatabaseSchemaTree(database, metadata);
      setTree(built);
      // First-mount default expand: seed treeState.keys so the user
      // sees database/schema/Tables/Views opened by default. The Vue
      // version seeds when `treeStateDb !== connectionDb && connectionDb`.
      const tab = tabStore.currentTab;
      const connectionDb = tab?.connection.database;
      if (tab && connectionDb && tab.treeState.database !== connectionDb) {
        tab.treeState.database = connectionDb;
        tab.treeState.keys = defaultExpandedKeys(built);
      }
    });
    return () => cancelAnimationFrame(raf);
  }, [isFetching, metadata, totalTableCount, database, tabStore]);

  // Reactive proxy for `tab.treeState.keys`. Reads via useVueState +
  // deep watch (Pinia mutates in place); writes go through a thin
  // setter so the store mutation triggers the watch.
  const expandedKeys = useVueState<string[]>(
    () => {
      const tab = tabStore.currentTab;
      if (!tab) return [];
      if (tab.treeState.database !== database.name) return [];
      return tab.treeState.keys ?? [];
    },
    { deep: true }
  );

  const setExpandedKeys = useCallback(
    (keys: string[]) => {
      const tab = tabStore.currentTab;
      if (!tab) return;
      if (tab.treeState.database !== database.name) return;
      tab.treeState.keys = keys;
    },
    [tabStore, database.name]
  );

  const upsertExpandedKeys = useCallback(
    (keys: string[]) => {
      setExpandedKeys(uniq([...expandedKeys, ...keys]));
    },
    [expandedKeys, setExpandedKeys]
  );
  const removeExpandedKeys = useCallback(
    (keys: string[]) => {
      setExpandedKeys(without(expandedKeys, ...keys));
    },
    [expandedKeys, setExpandedKeys]
  );

  // ---- Selected-key highlight (current connection / detail view) ---------
  const selectedKeys = useMemo(() => {
    if (!isValidDatabaseName(database.name)) return [];
    const keys: string[] = [];
    if (tabConnectionSchema !== undefined) {
      keys.push(`${database.name}/schemas/${tabConnectionSchema}`);
    }
    if (!panelViewState || panelViewState.view === "CODE") return keys;

    const detail = panelViewState.detail ?? {};
    const parts = [database.name, `schemas/${panelViewState.schema ?? ""}`];
    if (detail.table) {
      parts.push(`tables/${detail.table}`);
      if (detail.column) parts.push(`columns/${detail.column}`);
      else if (detail.index) parts.push(`indexes/${detail.index}`);
      else if (detail.partition)
        parts.push(`partitionTables/${detail.partition}`);
      else if (detail.trigger) parts.push(`triggers/${detail.trigger}`);
      else if (detail.foreignKey)
        parts.push(`foreignKeys/${detail.foreignKey}`);
    } else if (detail.view) {
      parts.push(`views/${detail.view}`);
      if (detail.column) parts.push(`columns/${detail.column}`);
    } else if (detail.procedure) {
      parts.push(`procedures/${detail.procedure}`);
    } else if (detail.func) {
      parts.push(`functions/${detail.func}`);
    } else if (detail.sequence) {
      parts.push(`sequences/${detail.sequence}`);
    } else if (detail.externalTable) {
      parts.push(`externalTables/${detail.externalTable}`);
    } else if (detail.package) {
      parts.push(`packages/${detail.package}`);
    }
    return [parts.join("/")];
  }, [database.name, tabConnectionSchema, panelViewState]);

  // ---- Adaptive flat / tree -----------------------------------------------
  const treeData = useMemo<TreeDataNode<SchemaTreeNode>[]>(() => {
    if (!tree) return [];
    return tree.map(toTreeData);
  }, [tree]);

  const expandedKeySet = useMemo(() => new Set(expandedKeys), [expandedKeys]);
  const searchKeyword = debouncedSearch.trim();
  const visibleRowCount = useMemo(() => {
    if (!tree) return 0;
    return tree.reduce(
      (sum, root) =>
        sum +
        countVisibleRows(root, expandedKeySet, searchKeyword, schemaNodeMatch),
      0
    );
  }, [tree, expandedKeySet, searchKeyword]);

  // ---- Click discriminator (single vs double) -----------------------------
  const { events: clickEvents, handleClick } = useClickEvents();
  const { selectAllFromTableOrView } = useSchemaActionsForClick();

  const toggleNode = useCallback(
    (node: SchemaTreeNode) => {
      if (expandedKeys.includes(node.key)) {
        removeExpandedKeys([node.key]);
      } else if (ExpandableNodeTypes.includes(node.meta.type)) {
        upsertExpandedKeys([node.key]);
      }
    },
    [expandedKeys, removeExpandedKeys, upsertExpandedKeys]
  );

  useEffect(() => {
    const offSingle = clickEvents.on("single-click", ({ node }) => {
      // Toggle expand for non-leaf rows. For schema, also push the
      // selected schema into the tab's connection.
      if (node.meta.type === "schema") {
        const tab = tabStore.currentTab;
        if (tab) {
          tab.connection.schema = (
            node.meta.target as NodeTarget<"schema">
          ).schema;
        }
      }
      toggleNode(node);
    });
    const offDouble = clickEvents.on("double-click", ({ node }) => {
      const type = node.meta.type;
      if (type === "table" || type === "view") {
        void selectAllFromTableOrView(node);
      } else if (type === "schema" || type === "expandable-text") {
        toggleNode(node);
      } else {
        // Leaf nodes: mirror single-click toggle behavior so the tree
        // state matches what the user expects after a fast double-tap.
        toggleNode(node);
      }
    });
    return () => {
      offSingle();
      offDouble();
    };
  }, [clickEvents, selectAllFromTableOrView, tabStore, toggleNode]);

  // ---- Context menu (right-click) -----------------------------------------
  const contextMenuRef = useRef<SchemaContextMenuHandle>(null);
  // Schema-viewer modal lives here now (was bridged through Vue parent
  // until the React TableSchemaViewer landed). Local state because the
  // SchemaPane right-click menu is the only trigger.
  const [schemaViewer, setSchemaViewerState] = useState<
    | {
        schema?: string;
        object?: string;
        type?: GetSchemaStringRequest_ObjectType;
      }
    | undefined
  >(undefined);
  const setSchemaViewer = useCallback(
    (
      viewer:
        | {
            schema?: string;
            object?: string;
            type?: GetSchemaStringRequest_ObjectType;
          }
        | undefined
    ) => {
      setSchemaViewerState(viewer);
    },
    []
  );
  const availableActions = useAvailableActions();

  // ---- Flat list handlers (when totalTableCount > 1000) -------------------
  const onFlatSelect = useCallback(
    (item: { schema?: string }) => {
      const tab = tabStore.currentTab;
      if (tab && item.schema) {
        tab.connection.schema = item.schema;
      }
    },
    [tabStore]
  );
  const onFlatSelectAll = useCallback(
    (item: { key: string; schema: string; metadata: TableMetadata }) => {
      const synthetic: SchemaTreeNode = {
        key: item.key,
        meta: {
          type: "table",
          target: {
            database: database.name,
            schema: item.schema,
            table: item.metadata.name,
          },
        },
      };
      void selectAllFromTableOrView(synthetic);
    },
    [database.name, selectAllFromTableOrView]
  );
  const onFlatContextMenu = useCallback(
    (
      e: React.MouseEvent,
      item: { key: string; schema: string; metadata: TableMetadata }
    ) => {
      const synthetic: SchemaTreeNode = {
        key: item.key,
        meta: {
          type: "table",
          target: {
            database: database.name,
            schema: item.schema,
            table: item.metadata.name,
          },
        },
      };
      contextMenuRef.current?.show(synthetic, e);
    },
    [database.name]
  );

  return (
    <div className="gap-y-1 h-full flex flex-col items-stretch relative overflow-hidden">
      <div className="px-1 flex flex-row gap-1">
        <div className="flex-1 overflow-hidden">
          <Input
            value={searchPattern}
            placeholder={t("common.search")}
            disabled={!tabStore.currentTab}
            onChange={(e) => setSearchPattern(e.target.value)}
            className="h-8 text-sm w-full"
          />
        </div>
        <div className="shrink-0 flex items-center">
          <SyncSchemaButton />
        </div>
      </div>

      <div className="schema-tree flex-1 px-1 pb-1 text-sm overflow-auto select-none">
        {isFetching ? (
          <div className="flex items-center justify-center mt-16 text-control-light">
            <Loader2 className="size-5 animate-spin" />
          </div>
        ) : metadata ? (
          totalTableCount > FLAT_TABLE_THRESHOLD ? (
            <FlatTableList
              metadata={metadata}
              search={debouncedSearch}
              database={database.name}
              onSelect={onFlatSelect}
              onSelectAll={onFlatSelectAll}
              onContextMenu={onFlatContextMenu}
            />
          ) : tree && tree.length > 0 ? (
            <Tree<SchemaTreeNode>
              data={treeData}
              selectedIds={selectedKeys}
              expandedIds={expandedKeys}
              searchTerm={searchKeyword || undefined}
              searchMatch={searchMatch}
              onToggle={(id) => {
                const next = new Set(expandedKeys);
                if (next.has(id)) next.delete(id);
                else next.add(id);
                setExpandedKeys([...next]);
              }}
              height={
                Math.max(visibleRowCount, 1) * ROW_HEIGHT ||
                TREE_FALLBACK_HEIGHT
              }
              rowHeight={ROW_HEIGHT}
              indent={10}
              renderNode={({ node, style }) => (
                <SchemaTreeRow
                  style={style}
                  node={node.data.data}
                  isOpen={!!node.isOpen}
                  hasChildren={
                    !!node.data.data.children &&
                    node.data.data.children.length > 0
                  }
                  keyword={searchKeyword}
                  selected={selectedKeys.includes(node.data.data.key)}
                  hoverUpdate={hoverState.update}
                  hoverHasState={hoverState.state !== undefined}
                  hoverSetPosition={hoverState.setPosition}
                  databaseName={database.name}
                  onClickNode={handleClick}
                  onContextMenu={(n, e) => contextMenuRef.current?.show(n, e)}
                />
              )}
            />
          ) : (
            <EmptyHint label={t("common.empty")} />
          )
        ) : (
          <EmptyHint label={t("common.empty")} />
        )}
      </div>

      <SchemaContextMenu
        ref={contextMenuRef}
        availableActions={availableActions}
        setSchemaViewer={setSchemaViewer}
      />

      {/* Schema-viewer modal — Vue's BBModal+TableSchemaViewer used to
          live in the parent (`SQLEditorHomePage.vue`) bridged via the
          `show-schema-viewer` event because TableSchemaViewer was Vue.
          Now the React TableSchemaViewer ships, so the trigger and its
          modal home in the same place. */}
      <Dialog
        open={!!schemaViewer}
        onOpenChange={(open) => {
          if (!open) setSchemaViewerState(undefined);
        }}
      >
        <DialogContent
          className="p-4"
          style={{
            width: "calc(100vw - 12rem)",
            height: "calc(100vh - 12rem)",
            maxWidth: "calc(100vw - 12rem)",
          }}
        >
          <DialogTitle className="text-base font-medium flex items-center gap-x-1">
            <DatabaseTitle database={database} />
          </DialogTitle>
          {schemaViewer ? (
            <TableSchemaViewer
              database={database}
              schema={schemaViewer.schema}
              object={schemaViewer.object}
              type={schemaViewer.type}
              className="flex-1"
            />
          ) : null}
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ---- Helpers / sub-components ----------------------------------------------

function toTreeData(node: SchemaTreeNode): TreeDataNode<SchemaTreeNode> {
  return {
    id: node.key,
    data: node,
    children: node.children?.map(toTreeData),
  };
}

const searchMatch = (
  node: TreeDataNode<SchemaTreeNode>,
  term: string
): boolean => {
  // Mirror Vue's NTree default: case-insensitive substring match against
  // the node's display label.
  const label = node.data.label ?? "";
  return label.toLowerCase().includes(term.toLowerCase());
};

const schemaNodeMatch = (node: SchemaTreeNode, term: string): boolean => {
  const label = node.label ?? "";
  return label.toLowerCase().includes(term.toLowerCase());
};

function defaultExpandedKeys(tree: SchemaTreeNode[]): string[] {
  if (tree.length === 0) return [];
  const keys: string[] = [];
  const collect = (n: SchemaTreeNode) => {
    keys.push(n.key);
    n.children?.forEach(walk);
  };
  const walk = (n: SchemaTreeNode) => {
    const t = n.meta.type;
    if (t === "database" || t === "schema") {
      collect(n);
    } else if (t === "expandable-text") {
      const mockType = (n.meta.target as NodeTarget<"expandable-text">)
        .mockType;
      if (mockType === "table" || mockType === "view") collect(n);
    }
  };
  walk(tree[0]);
  return keys;
}

function useDebouncedValue<T>(value: T, delayMs: number): T {
  const [debounced, setDebounced] = useState(value);
  useEffect(() => {
    const id = setTimeout(() => setDebounced(value), delayMs);
    return () => clearTimeout(id);
  }, [value, delayMs]);
  return debounced;
}

/**
 * Direct re-export of `useSchemaPaneActions` so SchemaPaneInner can
 * grab `selectAllFromTableOrView` for the double-click handler. The
 * full menu-action surface lives inside `useSchemaPaneContextMenu`
 * (consumed by SchemaContextMenu).
 */
function useSchemaActionsForClick() {
  return useSchemaPaneActions();
}

/**
 * Minimal database breadcrumb for the schema-viewer modal title:
 * engine icon + instance name + chevron + database name. Replaces
 * Vue's `<RichDatabaseName>` for this single use site — full port
 * of `RichDatabaseName.vue` is deferred until another React surface
 * needs it.
 */
function DatabaseTitle({
  database,
}: {
  database: { name: string; project: string } & Record<string, unknown>;
}) {
  const instance = getInstanceResource(database as never);
  const iconPath = EngineIconPath[instance.engine];
  const databaseName = extractDatabaseResourceName(database.name).databaseName;
  return (
    <span className="inline-flex items-center gap-x-1">
      {iconPath ? (
        <img src={iconPath} alt="" className="size-4 shrink-0" />
      ) : null}
      <span className="truncate">{instanceV1Name(instance)}</span>
      <ChevronRight className="size-3 shrink-0" />
      <span className="truncate">{databaseName}</span>
    </span>
  );
}

function EmptyHint({ label }: { label: string }) {
  return (
    <div className="flex items-center justify-center mt-16 text-control-light text-sm">
      {label}
    </div>
  );
}

function SchemaTreeRow({
  style,
  node,
  isOpen,
  hasChildren,
  keyword,
  selected,
  hoverUpdate,
  hoverHasState,
  hoverSetPosition,
  databaseName,
  onClickNode,
  onContextMenu,
}: {
  style: CSSProperties;
  node: SchemaTreeNode;
  isOpen: boolean;
  hasChildren: boolean;
  keyword: string;
  selected: boolean;
  hoverUpdate: ReturnType<typeof useHoverState>["update"];
  hoverHasState: boolean;
  hoverSetPosition: ReturnType<typeof useHoverState>["setPosition"];
  databaseName: string;
  onClickNode: (node: SchemaTreeNode) => void;
  onContextMenu: (node: SchemaTreeNode, e: React.MouseEvent) => void;
}) {
  const rowRef = useRef<HTMLDivElement | null>(null);

  const handleMouseEnter = (e: React.MouseEvent<HTMLDivElement>) => {
    const type = node.meta.type;
    if (
      type !== "table" &&
      type !== "external-table" &&
      type !== "column" &&
      type !== "view" &&
      type !== "partition-table"
    ) {
      return;
    }
    const target = node.meta.target as
      | NodeTarget<"table">
      | NodeTarget<"external-table">
      | NodeTarget<"column">
      | NodeTarget<"view">
      | NodeTarget<"partition-table">;
    // Build the sparse hover state shape from the current target.
    const state: {
      database: string;
      schema?: string;
      table?: string;
      externalTable?: string;
      view?: string;
      column?: string;
      partition?: string;
    } = { database: databaseName };
    if ("schema" in target) state.schema = target.schema as string;
    if ("table" in target) state.table = target.table as string;
    if ("externalTable" in target)
      state.externalTable = target.externalTable as string;
    if ("view" in target) state.view = target.view as string;
    if ("column" in target) state.column = target.column as string;
    if ("partition" in target) state.partition = target.partition as string;

    const delay = hoverHasState ? 150 : undefined;
    hoverUpdate(state, "before", delay);

    // Compute position from the row's bounding rect, like Vue's
    // `findAncestor(.n-tree-node)` → getBoundingClientRect.
    const wrapper = findAncestor(
      e.target as HTMLElement,
      ".bb-schema-tree-row"
    );
    if (!wrapper) {
      hoverUpdate(undefined, "after", 150);
      return;
    }
    const rect = wrapper.getBoundingClientRect();
    hoverSetPosition({ x: e.clientX, y: rect.bottom });
  };

  const handleMouseLeave = () => {
    hoverUpdate(undefined, "after");
  };

  return (
    <div
      ref={rowRef}
      style={style}
      className={cn(
        "bb-schema-tree-row flex items-center w-full pr-2 cursor-pointer rounded-sm h-full",
        "hover:bg-control-bg/70",
        selected && "bg-accent/10 font-medium",
        node.disabled && "cursor-default opacity-70"
      )}
      data-node-key={node.key}
      data-node-meta-type={node.meta.type}
      onClick={() => {
        if (node.disabled) return;
        onClickNode(node);
      }}
      onContextMenu={(e) => {
        e.preventDefault();
        onContextMenu(node, e);
      }}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      <span className="shrink-0 inline-flex size-5 items-center justify-center text-control-light">
        {hasChildren ? (
          isOpen ? (
            <ChevronDown className="size-3.5" />
          ) : (
            <ChevronRight className="size-3.5" />
          )
        ) : null}
      </span>
      <Label node={node} keyword={keyword} />
    </div>
  );
}
