// frontend/src/react/components/SchemaDiagram/Navigator/Tree.tsx
import { useMemo } from "react";
import {
  Tree as ArboristTree,
  type TreeDataNode,
} from "@/react/components/ui/tree";
import { cn } from "@/react/lib/utils";
import { getInstanceResource, hasSchemaProperty } from "@/utils";
import { DEFAULT_PADDINGS } from "../common/const";
import { useSchemaDiagramContext } from "../common/context";
import { Label, Prefix, Suffix } from "./TreeNode";
import type { NavigatorTreeNode } from "./types";
import { isTypedNode } from "./utils";

interface NavigatorTreeProps {
  keyword?: string;
  /** Outer height of the virtualized tree viewport. */
  height?: number;
}

/**
 * React port of `Navigator/Tree.vue`. Reuses the shared `Tree` primitive
 * (react-arborist) and renders schema → table levels with prefix /
 * suffix slots. Clicking a table emits `set-center` so the canvas
 * recenters on it.
 */
export function NavigatorTree({
  keyword = "",
  height = 480,
}: NavigatorTreeProps) {
  const ctx = useSchemaDiagramContext();
  const { selectedSchemas, events, database } = ctx;

  const isFlatTree = useMemo(
    () => hasSchemaProperty(getInstanceResource(database).engine),
    [database]
  );

  const data = useMemo<readonly TreeDataNode<NavigatorTreeNode>[]>(() => {
    const schemaNodes = selectedSchemas.map((schema) => {
      const tableChildren: TreeDataNode<NavigatorTreeNode>[] =
        schema.tables.map((table) => ({
          id: `table-${schema.name}-${table.name}`,
          data: {
            id: `table-${schema.name}-${table.name}`,
            type: "table" as const,
            data: table,
          },
        }));
      const node: TreeDataNode<NavigatorTreeNode> = {
        id: `schema-${schema.name}`,
        children: tableChildren,
        data: {
          id: `schema-${schema.name}`,
          type: "schema" as const,
          data: schema,
          children: tableChildren.map((c) => c.data),
        },
      };
      return node;
    });
    // Mirror Vue: collapse the tree when there's a single, unnamed schema
    // (e.g. MySQL's default schema) — show only the table children.
    if (schemaNodes.length === 1 && selectedSchemas[0].name === "") {
      return schemaNodes[0].children ?? [];
    }
    return schemaNodes;
  }, [selectedSchemas]);

  return (
    <ArboristTree<NavigatorTreeNode>
      className={cn(
        "bb-schema-diagram-nav-tree select-none",
        isFlatTree && "flat"
      )}
      data={data}
      height={height}
      searchTerm={keyword}
      searchMatch={(node, term) =>
        (node.data.data.name ?? "").toLowerCase().includes(term.toLowerCase())
      }
      renderNode={({ node, style, dragHandle }) => {
        const treeNode = node.data.data;
        return (
          <div
            ref={dragHandle}
            style={style}
            className={cn(
              "flex items-center gap-x-1 px-1 cursor-pointer hover:bg-control-bg"
            )}
            onClick={() => {
              if (isTypedNode(treeNode, "schema")) {
                node.toggle();
                return;
              }
              if (isTypedNode(treeNode, "table")) {
                void events.emit("set-center", {
                  type: "table",
                  target: treeNode.data,
                  padding: DEFAULT_PADDINGS,
                });
              }
            }}
            data-node-type={treeNode.type}
          >
            <Prefix node={treeNode} />
            <div className="flex-1 min-w-0">
              <Label node={treeNode} keyword={keyword} />
            </div>
            <Suffix node={treeNode} />
          </div>
        );
      }}
    />
  );
}

// frontend/src/components/SchemaDiagram/Navigator/Tree.vue
<template>
  <NTree
    class="bb-schema-diagram-nav-tree select-none"
    :class="[isFlatTree && 'flat']"
    :data="treeData"
    :block-line="true"
    :pattern="keyword"
    :show-irrelevant-nodes="false"
    :default-expand-all="true"
    :selected-keys="[]"
    :expand-on-click="true"
    :render-label="renderLabel"
    :render-prefix="renderPrefix"
    :render-suffix="renderSuffix"
    :node-props="nodeProps"
  />
</template>

<script lang="ts" setup>
import { NTree, type TreeOption } from "naive-ui";
import { computed, h } from "vue";
import { isDescendantOf, hasSchemaProperty } from "@/utils";
import { useSchemaDiagramContext } from "../common";
import { DEFAULT_PADDINGS } from "../common/const";
import { Label, Prefix, Suffix } from "./TreeNode";
import type { TreeNode } from "./types";
import { isTypedNode } from "./utils";

const props = withDefaults(
  defineProps<{
    keyword?: string;
  }>(),
  {
    keyword: "",
  }
);

const context = useSchemaDiagramContext();
const { selectedSchemas, events, database } = context;

const isFlatTree = computed(() => {
  return hasSchemaProperty(database.value.instanceResource.engine);
});

const treeData = computed(() => {
  const schemaNodeList = selectedSchemas.value.map<TreeNode<"schema">>(
    (schema) => {
      const children = schema.tables.map<TreeNode<"table">>((table) => {
        return {
          key: table.name,
          label: table.name,
          type: "table",
          data: table,
          isLeaf: true,
          children: [],
        };
      });
      return {
        key: schema.name,
        label: schema.name,
        type: "schema",
        data: schema,
        isLeaf: children.length === 0,
        children,
      };
    }
  );
  if (schemaNodeList.length === 1 && schemaNodeList[0].data.name === "") {
    return schemaNodeList[0].children;
  }
  return schemaNodeList;
});

// dynamic render the highlight keywords
const renderLabel = ({ option }: { option: TreeOption }) => {
  const node = option as any as TreeNode;
  return h(Label, { node, keyword: props.keyword });
};

// Render icons before nodes.
const renderPrefix = ({ option }: { option: TreeOption }) => {
  const node = option as any as TreeNode;
  return h(Prefix, { node });
};

// Render icons after nodes.
const renderSuffix = ({ option }: { option: TreeOption }) => {
  const node = option as any as TreeNode;
  return h(Suffix, { node });
};

const nodeProps = ({ option }: { option: TreeOption }) => {
  const node = option as TreeNode;
  return {
    onClick(e: MouseEvent) {
      if (node.disabled) return;

      if (isDescendantOf(e.target as Element, ".n-tree-node-content")) {
        // Check if clicked on the content part.
        // And ignore the fold/unfold arrow.
        if (isTypedNode(node, "table")) {
          events.emit("set-center", {
            type: "table",
            target: node.data,
            padding: DEFAULT_PADDINGS,
          });
        }
      }
    },
    "data-node-type": node.type,
  };
};
</script>

<style lang="postcss">
.bb-schema-diagram-nav-tree.flat .n-tree-node-switcher {
  @apply !hidden;
}
.bb-schema-diagram-nav-tree .n-tree-node-content {
  @apply !pl-0;
}
.bb-schema-diagram-nav-tree .n-tree-node-content__prefix {
  @apply shrink-0 !mr-1;
}
.bb-schema-diagram-nav-tree .n-tree-node-content__text {
  @apply truncate mr-1;
}
.bb-schema-diagram-nav-tree .n-tree-node--pending {
  background-color: transparent !important;
}
.bb-schema-diagram-nav-tree .n-tree-node--pending:hover {
  background-color: var(--n-node-color-hover) !important;
}
.bb-schema-diagram-nav-tree .n-tree-node--selected,
.bb-schema-diagram-nav-tree .n-tree-node--selected:hover {
  background-color: var(--n-node-color-active) !important;
}
</style>
