// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DummyNode.vue
<template>
  <NPopover :disabled="!error">
    <template #trigger>
      <span class="text-control-placeholder ml-[2px]">{{ text }}</span>
    </template>
    <template #default>
      <div class="text-error max-w-[20rem] wrap-break-word break-all">
        {{ error }}
      </div>
    </template>
  </NPopover>
</template>

<script setup lang="ts">
import { NPopover } from "naive-ui";
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import type { TreeNode } from "../tree";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const { t } = useI18n();

const error = computed(() => {
  return (props.node as TreeNode<"error">).meta.target.error;
});

const text = computed(() => {
  return `<${error.value ? t("common.error") : t("common.empty")}>`;
});
</script>

// frontend/src/modules/sql-editor/components/SchemaPane/TreeNode/DummyNode.tsx
import { useTranslation } from "react-i18next";
import { Tooltip } from "@/components/ui/tooltip";
import type { TreeNode } from "../schemaTree";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

/**
 * Renders an "<Empty>" / "<Error>" placeholder span; if the underlying
 * target carries an `error`, the span exposes that message via Tooltip on
 * hover.
 */
export function DummyNode({ node }: Props) {
  const { t } = useTranslation();
  const error = (node as TreeNode<"error">).meta.target.error;
  const text = `<${error ? t("common.error") : t("common.empty")}>`;
  const span = (
    <span className="text-control-placeholder ml-[2px]">{text}</span>
  );

  if (!error) return span;

  return (
    <Tooltip
      content={
        <div className="text-error wrap-break-word break-all">
          {String(error)}
        </div>
      }
    >
      {span}
    </Tooltip>
  );
}
