// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/IndexNode.vue
<template>
  <CommonNode
    :text="target.index"
    :keyword="keyword"
    :highlight="true"
    :indent="0"
  >
    <template #icon>
      <PrimaryKeyIcon v-if="isPrimaryKey" class="w-4 h-4" />
      <IndexIcon v-else class="!w-4 !h-4 text-accent/80" />
    </template>
  </CommonNode>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { IndexIcon, PrimaryKeyIcon } from "@/components/Icon";
import { useDBSchemaV1Store } from "@/store";
import type { TreeNode } from "../tree";
import CommonNode from "./CommonNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const dbSchema = useDBSchemaV1Store();

const target = computed(() => (props.node as TreeNode<"index">).meta.target);

const indexMetadata = computed(() => {
  const { database, schema, table, index } = target.value;
  const tableMetadata = dbSchema.getTableMetadata({
    database,
    schema,
    table,
  });
  return tableMetadata.indexes.find((i) => i.name === index);
});

const isPrimaryKey = computed(() => {
  return indexMetadata.value?.primary;
});
</script>

// frontend/src/modules/sql-editor/components/SchemaPane/TreeNode/IndexNode.tsx
import { useAppStore } from "@/stores/app";
import type { TreeNode } from "../schemaTree";
import { CommonNode } from "./CommonNode";
import { IndexIcon, PrimaryKeyIcon } from "./icons";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

/**
 * PrimaryKeyIcon when the index is marked `primary`, IndexIcon otherwise.
 */
export function IndexNode({ node, keyword }: Props) {
  const target = (node as TreeNode<"index">).meta.target;
  const tableMetadata = useAppStore((s) =>
    s.getTableMetadata({
      database: target.database,
      schema: target.schema,
      table: target.table,
    })
  );
  const isPrimaryKey = !!tableMetadata.indexes.find(
    (i) => i.name === target.index
  )?.primary;

  return (
    <CommonNode
      text={target.index}
      keyword={keyword}
      highlight={true}
      indent={0}
      icon={
        isPrimaryKey ? (
          <PrimaryKeyIcon />
        ) : (
          <IndexIcon className="size-4! text-accent/80" />
        )
      }
    />
  );
}
