// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ProcedureNode.vue
<template>
  <CommonNode
    :text="(procedureMetadata?.signature || procedureMetadata?.name) ?? ''"
    :keyword="keyword"
    :highlight="true"
    :indent="0"
  >
    <template #icon>
      <ProcedureIcon class="w-4 h-4" />
    </template>
  </CommonNode>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { ProcedureIcon } from "@/components/Icon";
import { useDBSchemaV1Store } from "@/store";
import type { TreeNode } from "../tree";
import CommonNode from "./CommonNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const dbSchema = useDBSchemaV1Store();

const target = computed(
  () => (props.node as TreeNode<"procedure">).meta.target
);

const procedureMetadata = computed(
  () =>
    dbSchema.getSchemaMetadata({
      database: target.value.database,
      schema: target.value.schema,
    })?.procedures[target.value.position]
);
</script>

// frontend/src/modules/sql-editor/components/SchemaPane/TreeNode/ProcedureNode.tsx
import { useAppStore } from "@/stores/app";
import type { TreeNode } from "../schemaTree";
import { CommonNode } from "./CommonNode";
import { ProcedureIcon } from "./icons";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

/**
 * Reads procedure metadata to prefer the resolved `signature` over the
 * bare `name` (engines like Oracle expose overloads where signature is the
 * disambiguator).
 */
export function ProcedureNode({ node, keyword }: Props) {
  const target = (node as TreeNode<"procedure">).meta.target;
  const schemaMetadata = useAppStore((s) =>
    s.getSchemaMetadata({ database: target.database, schema: target.schema })
  );
  const procedureMetadata = schemaMetadata?.procedures[target.position];

  return (
    <CommonNode
      text={(procedureMetadata?.signature || procedureMetadata?.name) ?? ""}
      keyword={keyword}
      highlight={true}
      indent={0}
      icon={<ProcedureIcon />}
    />
  );
}
