// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/TableNode.vue
<template>
  <CommonNode :text="target.table" :keyword="keyword" :highlight="true">
    <template #icon>
      <TableIcon class="w-4 h-4" />
    </template>
  </CommonNode>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { TableIcon } from "@/components/Icon";
import type { TreeNode } from "../tree";
import CommonNode from "./CommonNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const target = computed(() => (props.node as TreeNode<"table">).meta.target);
</script>

// frontend/src/modules/sql-editor/components/SchemaPane/TreeNode/TableNode.tsx
import type { TreeNode } from "../schemaTree";
import { CommonNode } from "./CommonNode";
import { TableLeafIcon } from "./icons";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

export function TableNode({ node, keyword }: Props) {
  const target = (node as TreeNode<"table">).meta.target;
  return (
    <CommonNode
      text={target.table}
      keyword={keyword}
      highlight={true}
      icon={<TableLeafIcon />}
    />
  );
}
