// frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/TextNode.vue
<template>
  <CommonNode :text="text" :highlight="false" :data-mock-type="type">
    <template v-if="render" #default>
      <component :is="render" />
    </template>

    <template #icon>
      <FolderIcon class="w-4 h-4 stroke-accent fill-accent/10" />
    </template>
  </CommonNode>
</template>

<script setup lang="ts">
import { isFunction } from "lodash-es";
import { FolderIcon } from "lucide-vue-next";
import { computed } from "vue";
import type { TreeNode } from "../tree";
import CommonNode from "./CommonNode.vue";

const props = defineProps<{
  node: TreeNode;
  keyword: string;
}>();

const target = computed(() => {
  return (props.node as TreeNode<"expandable-text">).meta.target;
});

const type = computed(() => {
  return target.value.mockType;
});

const text = computed(() => {
  const { text } = target.value;
  return isFunction(text) ? text() : text;
});
const render = computed(() => {
  return target.value.render;
});
</script>

// frontend/src/modules/sql-editor/components/SchemaPane/TreeNode/TextNode.tsx
import { Folder } from "lucide-react";
import type { TreeNode } from "../schemaTree";
import { CommonNode } from "./CommonNode";

type Props = {
  readonly node: TreeNode;
  readonly keyword: string;
};

/**
 * Folder-style row used for "Tables / Views / Indexes / …" headers. If the
 * target sets a `render` ReactNode, we pass it through CommonNode's
 * `children` to override the default text+icon layout entirely.
 */
export function TextNode({ node }: Props) {
  const target = (node as TreeNode<"expandable-text">).meta.target;
  const text = typeof target.text === "function" ? target.text() : target.text;

  if (target.render) {
    return <CommonNode text={text}>{target.render}</CommonNode>;
  }

  return (
    <CommonNode
      text={text}
      highlight={false}
      data-mock-type={target.mockType}
      icon={<Folder className="size-4 stroke-accent fill-accent/10" />}
    />
  );
}
